### ISSUE TITLE
Add SPH fluid interaction with rigid body / cloth simulation (was googlecode Issue 296)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#100]
See https://code.google.com/p/bullet/issues/detail?id=296&colspec=Modified%20ID%20Type%20Stars%20Status%20Owner%20Summary

**Comment by erwincoumans** [comment]
This is likely not going to happen, unless a volunteer shows up to work on SPH for Bullet. Until such volunteer shows up, let's close the issue.

**Comment by juancarlosgzrz** [comment]
Any news?
