### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by tdeprelle** [bulletphysics/bullet3#1004]
Hi everyone,

I'm struggling with a problem of rendering...

Does anyone know why some part of an urdf file don't show up when I do the rendering via getCameraImage ?

![image](https://cloud.githubusercontent.com/assets/18024358/23758879/653b0504-04eb-11e7-85ae-e20ee263ae5b.png)

Thanks for your help

**Comment by erwincoumans** [comment]
The tinyrenderer doesn't clip triangles at the moment. Until that is implemented, it is best to split large triangles into smaller ones.

**Comment by erwincoumans** [comment]
I created an issue to track clipping of tinyrenderer: 
https://github.com/bulletphysics/bullet3/issues/1006

**Comment by erwincoumans** [comment]
See https://github.com/bulletphysics/bullet3/pull/1063
