### ISSUE TITLE
Example Browser missing "Physics Server"

### ISSUE THREAD

**Issue by shazoom** [bulletphysics/bullet3#1014]
I was trying to follow the pybullet introduction [article](http://bulletphysics.org/mediawiki-1.5.8/index.php/Using_pybullet)  but when I run App_ExampleBrowser I don't have the option in the left pane for Physics Server under Experiments. It's built on Mint 18.

Sorry it seems like I'm short on details but I really haven't a clue what I'm doing wrong.

**Comment by erwincoumans** [comment]
It is moved out of Experiments into its own section, 3rd category from the top: Physics Server-Client. See screenshot.
<img width="667" alt="physics_server" src="https://cloud.githubusercontent.com/assets/725468/23885062/0a32b8d2-082e-11e7-97c1-106d77a33f59.png">

**Comment by benelot** [comment]
I will update the article soon, mistake of mine! In the article it refers
to the most recent version of it being in the google docs.

**Comment by shazoom** [comment]
Thanks. I should have spotted that...but I didn't 😁

**Comment by benelot** [comment]
I will add a last updated tag, so that people see how old it is. Also I
think the article becomes more stable now as the feature is no longer very
new and experimental.
