### ISSUE TITLE
Direct snprintf usage causes issues with Visual Studio 2013 (Windows 7)

### ISSUE THREAD

**Issue by simo-11** [bulletphysics/bullet3#1037]
Error	48	error C3861: 'snprintf': identifier not found	bullet3\examples\Importers\ImportMJCFDemo\BulletMJCFImporter.cpp	177		bullet3\examples\Importers\ImportURDFDemo\UrdfParser.cpp	1683

prefixing with _ allows compile but some  portable change should probably be done

**Comment by olegklimov** [comment]
```cpp
#ifdef _MSC_VER
#  define snprintf _snprintf
#endif
```
is the fix.

**Comment by olegklimov** [comment]
Can you please put it into `UrdfParser.h` included by both `UrdfParser.cpp` and `BulletMJCFImporter.cpp` and see if it works for you?

**Comment by erwincoumans** [comment]
Thanks, but I already fixed it here:
https://github.com/bulletphysics/bullet3/pull/1039

**Comment by simo-11** [comment]
Thanks for quick fix
