### ISSUE TITLE
Soft btPoint2PointConstraint

### ISSUE THREAD

**Issue by sabotage3d** [bulletphysics/bullet3#1042]
I am trying to modify btPoint2PointConstraint to make it soft, but instead of using CFM and ERP. I am looking into using frequency and damping ratio. Would it be easy to implement or it would require changes to the constraint solver?

**Comment by xissburg** [comment]
I believe you could achieve that using a `btGeneric6DofSpringConstraint` instead.

**Comment by erwincoumans** [comment]
closing out-of-date issues.
