### ISSUE TITLE
error <110> to run SharedMemory_VR

### ISSUE THREAD

**Issue by Poorasadion** [bulletphysics/bullet3#1051]
Hi.

When I ran App_PhysicsServer_SharedMemory_VR on windows 7, I received a error:

b3warning[..\..\eamples\StandaloneMain\hellovr_opengl_main,cpp,385]:
VR_init failed unable to init VR run time: installation path could not be located <110>

Any thoughts about these issues?

Thanks.

**Comment by erwincoumans** [comment]
Do other Valve Steam and OpenVR apps work? Is this for HTC Vive or Oculus Rift/Touch?

**Comment by Poorasadion** [comment]
How can understand OpenVR apps worked?
I used Oculus DK22.

**Comment by erwincoumans** [comment]
You need to install the Valve Steam SDK first. Not sure if OpenVR supports DK2 works, just google around.
We only test/support Oculus Rift CV1/final and Vive.
