### ISSUE TITLE
btCollisionWorldImporter::getNumConstraints is not implemented

### ISSUE THREAD

**Issue by helgemathee** [bulletphysics/bullet3#1077]
Tested on 2.86.1

**Comment by erwincoumans** [comment]
This is on purpose, since the btCollisionWorld doesn't have constraints, only collision object information. If you want to serialize constraints, use the btBulletWorldImporter (in Extras/Serialize)

**Comment by helgemathee** [comment]
Sure - sorry if there was a confusion. I can see it was removed in the master branch. The issue with 2.68.1 was that it is a missing symbol in our wrapping - since we wrap all methods.
