### ISSUE TITLE
Merge blender and PyBullet for blender 2.8?

### ISSUE THREAD

**Issue by BluePrintRandom** [bulletphysics/bullet3#1081]
would it be possible to couple pyBullet to blender like the bge is now?

From what I understand pyBullet is render agnostic, and the 2.8 project promises a much better render/viewport for blender.

Thank You @erwincoumans - your work is amazing.

**Comment by benelot** [comment]
pybullet can currently only load models from urdf, sdf and mjcf files. No customly created models. I think that makes it a no-go for you until now, right?

**Comment by erwincoumans** [comment]
No, let's close this issue. If volunteers want to merge PyBullet and Blender, welcome.
