### ISSUE TITLE
Assert in btSequentialImpulseConstraintSolver::solveGroupCacheFriendlySetup. btAssert(fsum > SIMD_EPSILON); (was googlecode  Issue 666)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#109]
See https://code.google.com/p/bullet/issues/detail?id=666&colspec=Modified%20ID%20Type%20Stars%20Status%20Owner%20Summary

**Comment by erwincoumans** [comment]
closing out-of-date issues.

**Comment by markusstephanides** [comment]
I still have this issue, occurs only in debug mode. Is there any solution for this yet?
