### ISSUE TITLE
Please add fluid dynamics and fracture

### ISSUE THREAD

**Issue by ghost** [bulletphysics/bullet3#1113]
Please, add fluid dynamics to Bullet physics, as seen on nVidia PhysX.
Please, also add breakable objects (fractures).

**Comment by berserk82** [comment]
For fracture, please have a look at this code: https://github.com/mrdoob/three.js/blob/master/examples/js/ConvexObjectBreaker.js

**Comment by ahundt** [comment]
did you run the demos? looks like fractures are there

**Comment by berserk82** [comment]
I'm sorry, in truth I didn't. 
I wouldn't have to compile.

**Comment by ahundt** [comment]
you wouldn't have to compile?

**Comment by berserk82** [comment]
Sorry, I meant: if I can, I generally avoid to compile code.
This is because in the past I got errors due to missing dependencies or so and no one told anything

**Comment by erwincoumans** [comment]
Let's close this issue. For chat use forums.
