### ISSUE TITLE
OpenGL rendering in headless mode is broken

### ISSUE THREAD

**Issue by jaredweiss** [bulletphysics/bullet3#1157]
Using the rendering option `ER_BULLET_HARDWARE_OPENGL` in `getCameraImage` while using a  `DIRECT` pybullet server (i.e. no GUI) will render/return blank canvases. If headless rendering shouldn't be possible with the opengl renderer an error should be thrown instead of just returning an empty image.

**Comment by erwincoumans** [comment]
well, DIRECT mode implies no GUI and no OpenGL, so you can obviously not use OpenGL to render images. Use ER_TINY_RENDERER instead. pybullet doesn't have verbose error messages indeed.

**Comment by jaredweiss** [comment]
got it. thanks

**Comment by joemathai** [comment]
I am facing a similar issue, ER_TINY_RENDERER is returning a blank canvas in DIRECT mode. But using the same setup with ER_BULLET_HARDWARE_OPENGL in GUI mode returns the correct image. Am I missing something?

**Comment by erwincoumans** [comment]
It works just fine with out scenes, it is likely due to your URDF files.
Did you try running the Bullet/examples/pybullet/examples/testrender.py script? It uses TinyRenderer by default.

**Comment by carismoses** [comment]
I think that there is a bug in rendering option ER_TINY_RENDERER. To properly render in DIRECT mode, you have to use the viewMatrix and projectionMatrix options when you call getCameraImage. In the Bullet/examples/pybullet/examples/testrender.py script, if you remove either of these options from the getCameraImage call (line 49), the images don't render properly.
