### ISSUE TITLE
resetSimulation or disconnect do not reset loaded textures

### ISSUE THREAD

**Issue by olimastro** [bulletphysics/bullet3#1172]
Hello,

I have installed pybullet through pip and I am trying to automatically create very simple videos. So far, I want to randomize the textures on a plane and I have been massively struggling. I do something like this:

```python
for v in videos:
  p.connect(p.DIRECT)
  p.resetSimulation()
  write_new_mtlfile()
  plane = p.loadURDF('plane.urdf')
  # do things
  p.removeBody(plane)
  p.resetSimulation()
  p.disconnect
```

In the same folder as `plane.urdf` there is a `plane.obj` which loads a `plane.mtl` that gets written by `write_new_mtlfile()` (it was the only way I thought of randomizing textures). 

When I run this, it only loads the first ever texture and every subsequent simulation will have the same texture as the first one. Only when I reload the program does the texture change (still according to the first randomly written `plane.mtl`). I even insterted an `ipdb` to stop the execution after one run. On the second run, I deleted manually the `plane.mtl` right before the `loadURDF` and nothing complained! It did the plane, with the same texture as on the first run, again.

Sorry if this is not the right place to post this problem.
Thank you.

**Comment by erwincoumans** [comment]
pybullet should be an enjoyable experience, not suffering. You need to disable file caching using 
pybullet.setPhysicsEngineParameter(enableFileCaching=0)
