### ISSUE TITLE
warning building with g++

### ISSUE THREAD

**Issue by consultit** [bulletphysics/bullet3#1173]
bullet3/src/LinearMath/btThreads.cpp:453:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
 #endif #else // #if BT_THREADSAFE

**Comment by erwincoumans** [comment]
Thanks for the report, is fixed here: https://github.com/bulletphysics/bullet3/pull/1174

**Comment by consultit** [comment]
that's all right.
