### ISSUE TITLE
Why human robot flying in tensorflow/humanoid_running.py ?

### ISSUE THREAD

**Issue by foolyc** [bulletphysics/bullet3#1188]
the original py file ensorflow/humanoid_running.py:
![index](https://user-images.githubusercontent.com/7566074/27182859-48b90c20-520f-11e7-8a4d-a73d93844c02.gif)
even when i set all the joint force to 0
`
		forces = [0.] * len(motors)
		for m in range(len(motors)):
			forces[m] = 0#motor_power[m]*actions[m]*0.082
		p.setJointMotorControlArray(human, motors,controlMode=p.TORQUE_CONTROL, forces=forces)
`
the human robot still flies.
so whats the problem?

**Comment by erwincoumans** [comment]
What operating system (version etc) and Python version and pybullet version are you using? Does the unmodified humanoid_running.py have the issue?

**Comment by erwincoumans** [comment]
Should work better in latest version. Closing issue.
