### ISSUE TITLE
Can't move kinematic object using setLinearVelocity

### ISSUE THREAD

**Issue by AndreaCatania** [bulletphysics/bullet3#1204]
As mentioned in this post of 2011 I can't use setLinearVelocity to move a kinematic object http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=4&t=6186

This is a Bug or this is normal behaviour?

This is how I setup my kinematic box: 

     boxRb = createRigidBody(0, startTransform, colShape);
     boxRb->setFlags(boxRb->getFlags() | btCollisionObject::CollisionFlags::CF_KINEMATIC_OBJECT);
     boxRb->setActivationState(DISABLE_DEACTIVATION);

Here how I move each tick:

    btTransform t( boxRb->getWorldTransform() );
    t.setOrigin(t.getOrigin() + btVector3(10, 0, 0) * deltaTime);
    boxRb->setWorldTransform(t);
    boxRb->getMotionState()->setWorldTransform(t);
    cout << "Current velocity: " << boxRb->getLinearVelocity().length() << endl;

The linear velocity is always 0, is it a bug?

**Comment by xissburg** [comment]
Kinematic objects are not controlled by Bullet thus setting their velocity won't make them move. Anyway, what are you trying to achieve? A moving platform? You might consider creating a dynamic body and keeping it fixed in space via constraints as well.
