### ISSUE TITLE
Teleop Compatibility

### ISSUE THREAD

**Issue by alee156** [bulletphysics/bullet3#1205]
Is there any support for keyboard control of robots currently for pybullet?
If not do you have any advice on how to implement something like this.
I was thinking something similar to Teleop control in Gazebo.

Thanks!
Albert

**Comment by erwincoumans** [comment]
Did you mean keyboard control of simulated robots?

Otherwise, how do you exactly interface with controls of real robots?

**Comment by alee156** [comment]
Keyboard control of simulated robots

**Comment by erwincoumans** [comment]
That should be easy to do: pybullet has a getKeyboardEvents and you simply use that to control the robot using setJointMotorControl2(...).
