### ISSUE TITLE
Premake5 executable need to be updated

### ISSUE THREAD

**Issue by BillelAdam** [bulletphysics/bullet3#1222]
the provided Premake5 executable need to be updated for it to support generating Visual Studio 2017 directly without the need to upgrade Visual Studio 2015 projects.

**Comment by BillelAdam** [comment]
i've made a pull request with the required change.

**Comment by erwincoumans** [comment]
Fixed here:
https://github.com/bulletphysics/bullet3/pull/2034/commits/21d9465d94eb20c1bf7e7ca458b5e6b644dd4d12
