### ISSUE TITLE
No files installed when Ninja CMake backend is used

### ISSUE THREAD

**Issue by tpetazzoni** [bulletphysics/bullet3#1225]
Due to the following logic in ```CMakeLists.txt```:

```
IF("${CMAKE_GENERATOR}" MATCHES "Unix Makefiles")
        OPTION(INSTALL_LIBS "Set when you want to install libraries" ON)
ELSE()
        IF(APPLE AND FRAMEWORK)
                OPTION(INSTALL_LIBS "Set when you want to install libraries" ON)
        ELSE()
#by default, don't enable the 'INSTALL' option for Xcode and MSVC projectfiles
                OPTION(INSTALL_LIBS "Set when you want to install libraries" OFF)
        ENDIF()
ENDIF()
```

when the Ninja generator of CMake is used, nothing gets installed, because INSTALL_LIBS is set to OFF by default. So shouldn't the case of Xcode/MSVC be handled specifically, in order to keep INSTALL_LIBS=ON by default in all other cases ?

**Comment by erwincoumans** [comment]
We don't support all possible combinations of platforms, build systems etc. If someone wants to add Ninja INSTALL support we welcome a simple patch. Otherwise, let's just close the issue.
