### ISSUE TITLE
Linux: ExampleBrowser runs at 25% and uses 100% of GPU power

### ISSUE THREAD

**Issue by benelot** [bulletphysics/bullet3#1277]
Even if I nothing is loaded and nothing is connected to the example browser, it is pretty processor and GPU intensive. Is there a reason for it? Is/was there some work on that (I am not sure if I have the latest version)? It seems to run at full power all the time...To me that sounds like it has no FPS cap, so it runs at 10^4 FPS when nothing is running.

**Comment by Paul17041993** [comment]
Yes, it runs at max speed, doesn't use vsync at all, so what you're seeing is expected. I don't think it'd really be a good idea to change this in the demo explorer, but a checkbox on the window to enable vsync might be useful...

Sometimes vsync or fps limits can be a bad thing, it can reflect poorer than usual performance and in some cases may not work properly at all (eg; mesa drivers).

**Comment by benelot** [comment]
Well ok, that sounds like a good reasoning for the current situation.
Thanks for the headsup!
