### ISSUE TITLE
Cannot access pybullet env states from another thread in GUI mode

### ISSUE THREAD

**Issue by JulianYG** [bulletphysics/bullet3#1294]
If I want to read some bullet states from another thread/process asynchronously, bullet gives segfault with GUI mode, but works in DIRECT mode. I think this is due to OpenGL.

**Comment by erwincoumans** [comment]
First of all, you can only have 1 GUI connection per process. If you like to connect to an existing GUI connection from a different thread/process you can use the following:

start process/thread A using p.connect(p.GUI_SERVER) 
start process/thread B using p.connect(p.SHARED_MEMORY, key=12348)

If you use DIRECT mode, each thread and process has its own private data, so there is no reading state from another thread/process possible.
