### ISSUE TITLE
broken examples

### ISSUE THREAD

**Issue by jtoy** [bulletphysics/bullet3#1310]
* on mac  "python getAABB.py"  just starts  using all CPU and stops responding on startup.

*  humanoid_benchmark.py doesn't run, there is only 1 object loaded.
```
python humanoid_benchmark.py
pybullet build time: Sep  7 2017 14:59:36
Traceback (most recent call last):
  File "humanoid_benchmark.py", line 12, in <module>
    ob = objects[1]
IndexError: tuple index out of range
```

**Comment by erwincoumans** [comment]
Fixed here, also explained how to use the json benchmark file:
https://github.com/bulletphysics/bullet3/pull/1307/commits/ec25f663c22339d07a4b4d6be56d9a19a98147ce
will be in bullet3 soon.
