### ISSUE TITLE
Best constraint for pulling object.

### ISSUE THREAD

**Issue by ongamex** [bulletphysics/bullet3#1312]
I want an object to be pulled after a point(for example, minimal distance between the object and the point to be 10.f). I'm not sure which constraint I should use.
In general I'm having a really hard time understanding the docs about constraint. For example:

http://bulletphysics.org/mediawiki-1.5.8/index.php/Constraints 

"The slider constraint allows the body to rotate around one axis and translate along this axis. 
The slider twist uses the following constructor: "

And later the constructor: btSliderConstraint(btRigidBody& rbA, btRigidBody& rbB, ...);
Now, how do I specify the "axis"? Why there are two objects?
There is a constructor. that takes one objects and two transform? How can I describe the target axis with these?

**Comment by erwincoumans** [comment]
I suggest looking at the constraint demo in the Example Browser, the source code is at bullet3\examples\Constraints\ConstraintDemo.cpp.
For other questions, please use the Bullet forums at http://bulletphysics.org
