### ISSUE TITLE
How to show depth and segmentation images?

### ISSUE THREAD

**Issue by ahundt** [bulletphysics/bullet3#1316]
How do I enable the segmentation and depth cameras in the GUI? Is this currently possible via something like [configureDebugVisualizer()](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.twmfawqnrl8k)?

I've searched the issues, examples, and pybullet docs, for "segmentation" and "depth", plus manually read through quite a few files with no luck. I'm able to turn on the rgb camera GUI rendering from python, but I haven't figured out how to display the segmentation and depth outside of the ExampleBrowser we've previously discussed.

I'm trying to see something like synthetic camera image, depth, and segmentation below, following from [our earlier discussion](https://github.com/bulletphysics/bullet3/issues/1136#issuecomment-302985681) in my own pybullet simulation, rather than the ExampleBrowser:

![Example Browser Kuka Segmentation Depth](https://cloud.githubusercontent.com/assets/725468/26290486/b6423cb0-3e5c-11e7-97a3-cba8139cdaf8.png)

**Comment by erwincoumans** [comment]
This hasn't been exposed. You could use MatplotLib, or do you prefer to have the option in the GUI?

**Comment by ahundt** [comment]
I'd appreciate an option in the gui! It would be helpful for ease of use and performance reasons.

**Comment by ahundt** [comment]
Can details on how the segmentation mask is defined also be added to the quickstart guide? 

I don't see any information on the encoding of the segmentation mask, particularly details regarding how ids are assigned and what values will be contained in the mask. For example:

- Is there a way I can determine which joint of the arm is present, or will it only be the bodyUniqueId?
- How do I get an enumeration of all possible numerical ids that could be in the segmentation image?
- Do single object models get single ids, or does it go by parts?
- Can the granularity of ids be changed?

**Comment by erwincoumans** [comment]
The segmentation mask is only the object unique id, if any, per pixel, no further details are in there.

**Comment by erwincoumans** [comment]
Latest revision of getCameraImage has the option to also add the link index, next to the object unique id, for each pixel in the segmentation mask buffer. Also the quickstart guide has info about it, and example here:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/segmask_linkindex.py

Any object and link in the scene that is visible can be in the segmentation mask buffer.
