### ISSUE TITLE
If that's worth to update the SSE code to AVX (was googlecode Issue 474)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#135]
See https://code.google.com/p/bullet/issues/detail?id=474&colspec=Modified%20ID%20Type%20Stars%20Status%20Owner%20Summary

**Comment by devshgraphicsprogramming** [comment]
Its good to replace SEE with AVX intrnsics (AVX instrinsics that still operate on __m128) to ensure no expensive SSE/AVX context switch happens on the CPU (CPU has to save all SSE registers before it does AVX ops and vice versa), which can be a problem when Bullet is compiled with mixed SSE and AVX intrinsics.

Another way to alleviate this potential problem is to compile everything with the `-mavx` flag
https://software.intel.com/sites/default/files/m/d/4/1/d/8/11MC12_Avoiding_2BAVX-SSE_2BTransition_2BPenalties_2Brh_2Bfinal.pdf

But not sure if GCC and MSVC behave the same (upgrade SSE intrinsics to VEX coded equivalents).

**Comment by erwincoumans** [comment]
We are not going to refactor Bullet 2.x anymore. Perhaps a future new physics engine.
