### ISSUE TITLE
stepUntilRest() feature?

### ISSUE THREAD

**Issue by srajangarg** [bulletphysics/bullet3#1355]
Does bullet have something along the lines of "step simulate until all objects are at rest"? In my specific case, I have an object (which maybe unstable) placed on the ground. I need it's initial and final positions. What would be the best way to go about it?

**Comment by srajangarg** [comment]
@erwincoumans ping. Sorry for multiple doubts. Last one!

**Comment by erwincoumans** [comment]
You can stepSimulation and check if objects are 'asleep', using the C++ API. Otherwise, you can create your own "is at rest" check, by keeping track of the linear and angular velocity for say 100 steps, and if they stay below some chosen threshold they are "at rest".
