### ISSUE TITLE
collision detection: btConeShape behaves like cylinder shape. 

### ISSUE THREAD

**Issue by EastskyKang** [bulletphysics/bullet3#1375]
I am using bullet collision for collision detection. 

As I define cone object as follows:

  btCollisionShape* coneCollisionShape = new btConeShapeZ(radius, height);
  btCollisionObject* coneCollisionObject = new btCollisionObject();
  coneCollisionObject->setCollisionShape(coneCollisionShape);

object occupies cylindrical space, not cone shape. Am I missing something here?

**Comment by erwincoumans** [comment]
The RollingFrictionDemo uses cone shapes and they work fine.
https://github.com/bulletphysics/bullet3/blob/master/examples/RollingFrictionDemo/RollingFrictionDemo.cpp
Can you create a btRigidBody instead of btCollisionObject?

**Comment by erwincoumans** [comment]
How do you determine what space is occupied?

**Comment by EastskyKang** [comment]
Thank you so much for your response. 

As I put an unit sphere to certain position (which is not supposed to be occupied), collision was detected. 

By the way, I only want to use collision detection feature, since I have my own dynamics engine. Is using btRigidBody proper way to do it?

**Comment by erwincoumans** [comment]
Why using your own dynamics engine, since it obviously works well with btRigidBody, LOL?
Now seriously, it should work just fine. How do you perform the query? Do you set the world transforms for the query properly? What is the contact point information (closest distance, contact normal etc)? Note that a positive distance means no collision.

**Comment by EastskyKang** [comment]
@erwincoumans Thank you for comment. I am actually building a dynamics simulator for robotics (for some special purposes). That's why I am using bullet for just for collision detection. 

And I realized I was detecting collision by using collision between manifolds. As I changed my implementation it seems works fine. 

Anyway, thank you so much for your quick and kind response. I will close the issue.

**Comment by erwincoumans** [comment]
Robotics is the main focus of Bullet nowadays, please check http://pybullet.org There is URDF  and SDF loading, Inverse Dynamics, Inverse Kinematics, motor control etc. We simulate KUKA arm grasping, quadruped/biped robot locomotion etc.

**Comment by erwincoumans** [comment]
See some new paper using pybullet:https://stanfordvl.github.io/ntp/?utm_content=buffer8b1fc
Also our researchers at Google Brain and X use this simulator in both C++ and Python.

**Comment by EastskyKang** [comment]
@erwincoumans Great! thank you so much for your suggestion. I will take a look and consider use bullet dynamics engines.
