### ISSUE TITLE
Inverse Dynamics has problems with fixed joints

### ISSUE THREAD

**Issue by MichaelLutter** [bulletphysics/bullet3#1379]
I tried simple inverse dynamics control with two two-joint-robots. The first robot contains fixed joints between both revolute joints while the second does not contain fixed joints between the revolute joints. 

- For the robot **without fixed joints**, inverse dynamics control **works fine**. The joint position & velocities behave as the desired positions and velocities. 
![invdynamics_wo_fixed_joints](https://user-images.githubusercontent.com/10160295/31538902-4e1eabf6-b007-11e7-84ec-78d5fd7e0c42.png)

- For the robot **with fixed joints** only the first/base joint yields the desired behavior. The second joint **does not track the desired position/velocity**. If the second joint is actuated by a constant the coupling of the first/base joint is not compensated and hence does not behave as expected. 
![invdynamics_w_fixed_joints](https://user-images.githubusercontent.com/10160295/31538901-4e07fa00-b007-11e7-8fe6-47790c1685a0.png)

For recreation purposes I attached both urdf files as well as the python script for a simple inverse dynamics control example. The figures were created using Pybullet 1.5.6 installed via pip. 

[InvDynamicsTest.tar.gz](https://github.com/bulletphysics/bullet3/files/1382099/InvDynamicsTest.tar.gz)

**Comment by erwincoumans** [comment]
Thanks for the reproduction case, it must be some indexing problem between Python and the inverse kinematics (which handles fixed joints just fine). I'll look into it right now.
Once I fixed it, can we add your reproduction case as an example for pybullet?

**Comment by MichaelLutter** [comment]
Thanks for the fast response. 

Yes, you can add the my code as pybullet example. 

Side Remark: 
Can you make the disabling of the motors for torque control in the [Quick Start Guide page 17](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#) more explicit? It took me quite a while to figure out what it really meant.

**Comment by erwincoumans** [comment]
It was indeed a mismatch, the inverse dynamics excepts input arrays size of #dofs, but pybullet checks for #joints. It is fixed in this CL: https://github.com/bulletphysics/bullet3/pull/1381
Please run "pip install -U pybullet" to update to pybullet version 1.5.8 for the fix.
The updated script is here:
https://github.com/erwincoumans/bullet3/blob/master/examples/pybullet/examples/inverse_dynamics.py#L79
Thanks for the report!

**Comment by erwincoumans** [comment]
While looking into this, we are currently using DLS instead of SDLS. SDLS has better behaviour in case the target is out-of-reach (DLS oscillates, SDLS doesn't).
