### ISSUE TITLE
Support for <equality> <connect> constraints?

### ISSUE THREAD

**Issue by bchasnov** [bulletphysics/bullet3#1395]
Is there support for the equality constraint similar to the element in Mujoco[1]?

[1] http://www.mujoco.org/book/modeling.html#equality-connect

**Comment by erwincoumans** [comment]
pybullet allows to create constraints between bodies, at arbitrary locations on the base or at child links.
See createConstraint in the quickstart guide. You can connect two links by another multibody, attached with point to point constraint on both end for a distance constraint. You can use changeConstraint to configure some parameters.

Please re-open with more details, if you need other/new functionality exposed in pybullet.
