### ISSUE TITLE
ModuleNotFoundError: No module named 'pybullet_envs.bullet.cartpole_bullet'

### ISSUE THREAD

**Issue by jgresham** [bulletphysics/bullet3#1403]
**Steps to reproduce**
Fresh pip install of pybullet with python3.6, then run
`python3 -m pybullet_envs.baselines.train_kuka_grasping`

Removing
`from pybullet_envs.bullet.cartpole_bullet import CartPoleBulletEnv`
in /pybullet_envs/baselines/enjoy_pybullet_cartpole.py and /pybullet_envs/baselines/train_pybullet_cartpole.py fixed the issue.

Please let me know if I didn't install properly or if I should continue to look into fixing this

**Comment by benelot** [comment]
Thanks for the input, it is great that somebody starts to use the envs! I
will check if I can reproduce that problem. Weird is that you get problems
during kuka training with the cartpole training/running scripts.

**Comment by erwincoumans** [comment]
importing some of the modules (pybullet_envs etc) will import various packages. It should be fixed in latest release (this commit: https://github.com/bulletphysics/bullet3/pull/1405/commits/9385f36505a37f99e6d2c92bd2c052d25305ea2a) I'll update the pypi pybullet package now.

**Comment by jgresham** [comment]
Thank you for the prompt reply and fix.

**Comment by erwincoumans** [comment]
The train_kuka_grasping and some other environments are still work-in-progress by the way, we'll make them train using DQN (discrete) and PPO (continuous), same for racecar and minitaur.
