### ISSUE TITLE
Unable to install on Win10: pip install pybullet 

### ISSUE THREAD

**Issue by bingjeff** [bulletphysics/bullet3#1411]
Python 2.7 installed using Anaconda 5.0.

Also unable to install pybullet using the python setup.py install unless I comment out the numpy option.

Is it possible that there is just a mismatch on the numpy version? The compiler was very unhappy with the numpy specific c-types.

Everything works just fine if I install with numpy flag removed.

**Comment by erwincoumans** [comment]
Thanks for the report. Did you try to install numpy first (pip install numpy)?

**Comment by bingjeff** [comment]
Yeah. Numpy was installed. Presumably the wrong version. There were a bunch
of warnings about using a deprecated numpy API.

I'm not super familiar with this, but if it's helpful I can try and figure
out how to compile on my system.

Alternatively, if I know the approved method of installation I can do that.

**Comment by erwincoumans** [comment]
No, it was a C99 issue, variables need to be declared at the beginning of a block. Fixed now, please update.
Thanks for the report!

**Comment by bingjeff** [comment]
Awesome! Thanks Erwin.
