### ISSUE TITLE
Version Mismatch Pip & Source Code

### ISSUE THREAD

**Issue by MichaelLutter** [bulletphysics/bullet3#1415]
Pip installs Version 1.6.2 while the Source Code of the Master Branch installs [1.5.8](https://github.com/bulletphysics/bullet3/blob/master/setup.py#L444) 

```
pip show pybullet
Name: pybullet
Version: 1.6.2
Summary: Official Python Interface for the Bullet Physics SDK specialized for Robotics Simulation and Reinforcement Learning
Home-page: https://github.com/bulletphysics/bullet3
Author: Erwin Coumans, Yunfei Bai, Jasmine Hsu
Author-email: erwincoumans@google.com
```

**Comment by erwincoumans** [comment]
Yes, I haven't always committed the version in setup.py, but it is very up-to-date. I'll make a bit more effort to keep those numbers in sync.
