### ISSUE TITLE
wrong m_shapeType in btMinkowskiSumShape

### ISSUE THREAD

**Issue by cprogrammer1994** [bulletphysics/bullet3#1423]
I think wrong `m_shapeType` is used in `btMinkowskiSumShape`.

[btMinkowskiSumShape.cpp:25](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp#L25)

```c++
btMinkowskiSumShape::btMinkowskiSumShape(const btConvexShape* shapeA,const btConvexShape* shapeB)
: btConvexInternalShape (),
m_shapeA(shapeA),
m_shapeB(shapeB)
{
	m_shapeType = MINKOWSKI_DIFFERENCE_SHAPE_PROXYTYPE;
	m_transA.setIdentity();
	m_transB.setIdentity();
}
```

`m_shapeType` should be `MINKOWSKI_SUM_SHAPE_PROXYTYPE` not `MINKOWSKI_DIFFERENCE_SHAPE_PROXYTYPE`

- Should I raise a PR with a fix?
- Is this kept for backward compatibility reasons?

My renderer is using `MINKOWSKI_DIFFERENCE_SHAPE_PROXYTYPE` to detect this kind of shape. I think others could adapt easily too.

**Comment by erwincoumans** [comment]
They were mixed up indeed (and there is only a single implementation with wrong names). Please modify your renderer, it is not worth breaking the API for this seldomly used shape.
