### ISSUE TITLE
Something wrong when visualizing GEOM_BOX shape using pybullet

### ISSUE THREAD

**Issue by MuhongGuo** [bulletphysics/bullet3#1427]
When I try to create a box with the following code, I found the size of the visual box is wrong. And no matter how I change the _halfExtents_ argument in createVisualShape, the box in Example Browser always looked the same. 

```
test_visual = p.createVisualShape(p.GEOM_BOX, halfExtents=[1,1,1])
test_collision = p.createCollisionShape(p.GEOM_BOX, halfExtents=[1,1,1])
test_body = p.createMultiBody(baseMass=0, baseCollisionShapeIndex=test_collision, \
baseVisualShapeIndex=test_visual, basePosition = [0, 0, 1])
```

**Comment by erwincoumans** [comment]
createVisualShape is pretty rudumentary, main workflow is loadURDF etc. Still, it will be fixed here:
https://github.com/bulletphysics/bullet3/commit/9c55b613155cb6d868c27289397f66188b01d240
Thanks for the report!
