### ISSUE TITLE
Simulated multi body only move with very large simulation step

### ISSUE THREAD

**Issue by XB32Z** [bulletphysics/bullet3#1433]
Hi all, 

I have been trying to create my own multi body getting inspired by the programmatically made pendulum example. However my multi body only moves when the time step is larger than 60. 

It is either because the integration is unstable or because there is some internal time checking that I did not see. 

Here is my world initialisation: 
```
btMultiBodyDynamicsWorld* m_dynamicsWorld;

  m_collisionConfiguration = new btDefaultCollisionConfiguration();

  m_filterCallback = new MyOverlapFilterCallback2();
  m_filterCallback->m_filterMode = MyFilterModes::FILTER_GROUPAMASKB_OR_GROUPBMASKA2;

  ///use the default collision dispatcher. For parallel processing you can use a diffent dispatcher (see Extras/BulletMultiThreaded)
  m_dispatcher = new	btCollisionDispatcher(m_collisionConfiguration);

  m_pairCache = new btHashedOverlappingPairCache();

  m_pairCache->setOverlapFilterCallback(m_filterCallback);

  m_broadphase = new btDbvtBroadphase(m_pairCache);

  m_solver = new btMultiBodyConstraintSolver();

  m_dynamicsWorld = new btMultiBodyDynamicsWorld(m_dispatcher, m_broadphase, m_solver, m_collisionConfiguration);
  m_dynamicsWorld->getCollisionObjectArray().reserve(32768);
  m_dynamicsWorld->getSolverInfo().m_erp2 = 0.08;

  m_dynamicsWorld->getSolverInfo().m_frictionERP = 0.2;
  m_dynamicsWorld->getSolverInfo().m_linearSlop = 0.00001;
  m_dynamicsWorld->getSolverInfo().m_numIterations = 50;
  m_dynamicsWorld->getSolverInfo().m_leastSquaresResidualThreshold = 1e-7;

  m_dynamicsWorld->setGravity(btVector3(0, -9.81, 0));
```
Here is the simulation step 
`m_dynamicsWorld->stepSimulation(1/60., 0);`

Or could there be a mistake in my multiBody structure? What element could make it not move at all? Do I need for example jointMotors?

Thx for you help :D

**Comment by erwincoumans** [comment]
If you can modify an existing multibody demo in the examplr browser and it doesn't work, file  an issue. Otherwise compare your code with the examples. You can also use http://pybullet.org and try to reproduce it.
