### ISSUE TITLE
How to contact bullet forum administrator?

### ISSUE THREAD

**Issue by spencerkohan** [bulletphysics/bullet3#1436]
Apologies if this is the wrong place for a question like this, but I don't know any other way to get in touch with the bullet community.

I'm trying to make an account on the forum at bulletphysics.org, but I never get a registration confirmation email, and the page tells me to "contact a board administrator" in this case to sort out the problem, but it seems to require a registered account to even go to the list of admins.  How can I get in touch with an administrator to get a forum account?

**Comment by benelot** [comment]
So you received a registration confirmation after all?
