### ISSUE TITLE
Resolving Collision Objects

### ISSUE THREAD

**Issue by abishekh** [bulletphysics/bullet3#1442]
I'm trying to find a good way to identify collision objects in the world using some sort of ID or name. Looking through the API the only thing I see that might be able to achieve this is the userID. The problem being : Suppose I have 5 spheres in my world and they move around randomly - when and if they collide, I want to know which two spheres collided and be able to print some sort of message like - "Sphere AAA and Sphere BBB collided! "

What would be a good way to achieve this?

**Comment by erwincoumans** [comment]
Are you using pybullet / Python bindings? If so, each object has a unique id, and the collision results will provide the body unique ids (and link indices). See http://pybullet.org
The underlying C++ implementation is here: https://github.com/erwincoumans/bullet3/blob/master/examples/SharedMemory/PhysicsServerCommandProcessor.cpp#L5305
There is a collision query for existing contact points (after step Simulation) and a query to compute closest points between arbitrary object(s). The object unique id can be stored in the btCollisionObject/btMultiBody/btRigidBody user info (for example getUserIndex2), or you can store the mapping between rigid body and unique id explicitly in some custom efficient data structure (hash map etc).
