### ISSUE TITLE
How to disable movement of axis in PhysicsClientC_API

### ISSUE THREAD

**Issue by skylian** [bulletphysics/bullet3#1448]
Not sure if this is the right place to ask such question. 

I want to implement sliding movement on models loaded from URDF using PyBullet. Is it possible to use methods like "setAngularFactor" and "setLinearFactor" to disable movements of some axis in PhysicsClientC_API?

**Comment by erwincoumans** [comment]
No, setAngularFactor/setLinearFactor works on rigid body.
You can use fixed joints and add revolute joints instead. See this example:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/biped2d_pybullet.py

**Comment by ffranchina** [comment]
@erwincoumans Is using `createConstraint` wrong for achieving the aimed purpose?
