### ISSUE TITLE
m_interpolationWorldTransform ignored when used to predict transform (was googlecode Issue 467)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#146]
https://code.google.com/p/bullet/issues/detail?id=467&colspec=Modified%20ID%20Type%20Stars%20Status%20Owner%20Summary

**Comment by BulletMan** [comment]
m_interpolationWorldTransform
m_interpolationLinearVelocity
m_interpolationAngularVelocity

always given the values of

m_worldTransform
m_linearVelocity
m_angularVelocity

consecutively, when btRigidBody::setCenterOfMassTransform is called.
I find no use for them. Even when m_interpolationWorldTransform is set by calling btRigidBody::predictIntegratedTransform it is never made use of. Interpolation works fine though.

**Comment by erwincoumans** [comment]
Closing out-of-date issues.
