### ISSUE TITLE
Implementing closed-loop gaits for Minitaur

### ISSUE THREAD

**Issue by anirudhamajumdar** [bulletphysics/bullet3#1466]
It would be great if we can provide high-level (i.e., heading and speed) commands to the Minitaur and have the robot track these. This would be very useful in testing out higher level planning and obstacle avoidance algorithms. Thank you!

**Comment by erwincoumans** [comment]
The raibert controller is close to this.
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_envs/minitaur/envs/minitaur_raibert_controller_example.py

In the future we open source envs_v2, this will add more capabilities.
