### ISSUE TITLE
Cannot load Universal Robot UR3 urdf

### ISSUE THREAD

**Issue by IlyaBoyur** [bulletphysics/bullet3#1468]
Hello everyone,
I know that the [similar](https://github.com/bulletphysics/bullet3/issues/1109)  issue closed, but that topic actually do not cover **the way to work around for others.**

My issue is:
I have ur3 parts wrongly oriented in pybullet GUI.
What I do:
1. Generate ur3_robot.urdf from ur3_robot.urdf.xacro
2.  Transform base.dae,...,wrist3.dae to base.obj,..,wrist3.obj with [this converter](http://www.greentoken.de/onlineconv/) or [that one](http://www.meshconvert.com/)

3. Edit ur3_robot.urdf to use new meshes files and open it with `pybullet.loadURDF(/path/to/urdf,position,orientation)`

4. What I have in attached image. So, what am I doing wrong?
And where are any colours?)

![ur3_pybullet](https://user-images.githubusercontent.com/22999968/33667691-9900f788-daae-11e7-88b2-d52ff9e52aa3.png)

**Comment by erwincoumans** [comment]
Please file your issue in the Bullet / PyBullet forums here:
https://pybullet.org/Bullet/phpBB3/viewforum.php?f=24
