### ISSUE TITLE
testing if there a connected gui

### ISSUE THREAD

**Issue by cedspam** [bulletphysics/bullet3#1533]
I had the problem in pybullet, there isn't an easy way to test if a gui is already connected, tryng to gonnect generaes an error which is not of a specific type. there are no function to list active connections or to test specifically this error

**Comment by erwincoumans** [comment]
There is a PyBullet.getConnectionInfo for that, see [PyBullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3), it also provides the connection type.
