### ISSUE TITLE
Bullet3 and x64

### ISSUE THREAD

**Issue by Krakean** [bulletphysics/bullet3#1539]
Hello
Is bullet 2.87 support x64? Just when I generated solutions for vs2015, it shows only Win32. Is x64 supported?

**Comment by iSLC** [comment]
Yes it does. Just the build systems is a little behind.

**Comment by erwincoumans** [comment]
Yes, and the build system is not behind at all.
Using premake, you can switch between 32bit and 64bit in Visual Studio, which is recommended.
Using cmake, you can pick 64bit when creating the visual studio project.
The build_visual_studio_vr_pybullet_double_cmake.bat batch file creates 64bit project.
