### ISSUE TITLE
Tutorials are broken

### ISSUE THREAD

**Issue by elect86** [bulletphysics/bullet3#1580]
Every sample I try to run under `Tutorials` in the Example Browser throw this:

![Imgur](https://i.imgur.com/GwwzRSP.png)

**Comment by erwincoumans** [comment]
It works just fine here. Did you change your current working directory? The tutorial load a texture file checker_huge.gif, in a data directory in one of the parent directories of the current working directory.

**Comment by elect86** [comment]
I just cloned the project and generated using `cmake` for VS 2017 Win64, am I not supposed to do like this?

**Comment by erwincoumans** [comment]
It all depends from what directory you run cmake. If things don't work, first check if the provided script don't work either. If they work fine, compare what is different from your approach.
