### ISSUE TITLE
elaborated explanation?

### ISSUE THREAD

**Issue by neurochen** [bulletphysics/bullet3#1584]
Hello, I am very much interested in your projects published in https://www.youtube.com/watch?v=YR-9IZ65YP8. What I want to achieve is essentially as what you did there: let python control unity using shared memory, minimizing the communication delay. Could you please elaborate how you implement this amazing demo? If you could see more words about the memory assignment, that's even cooler. Did you first create a shared memory region using python and then map it to c#? Do you still need to have a loop in C# side to update the new value? Thanks!

**Comment by erwincoumans** [comment]
We just use the Unity wrapper, start a shared memory server outside of Unity and then connect over shared memory to that server. Note that we haven't updated that wrapper, no time for this.
https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/unity3d
