### ISSUE TITLE
b3RobotSimulatorClientAPI_NoGUI does not implement getCameraImage.

### ISSUE THREAD

**Issue by lshamis** [bulletphysics/bullet3#1602]
`b3RobotSimulatorClientAPI_NoGUI` declares a method `getCameraImage`, but has no implementation.

**Comment by erwincoumans** [comment]
It was a contribution and somehow this method got missing in action.
This pull request adds it: https://github.com/bulletphysics/bullet3/pull/1603
We primarily use PyBullet and the C-API, but it is good to keep the C++ binding up-to-date too.
Thanks for the report!

**Comment by erwincoumans** [comment]
fixed now,
