### ISSUE TITLE
Slight inconsistency in one of the ObsoleteDemos

### ISSUE THREAD

**Issue by vif** [bulletphysics/bullet3#163]
I was searching the source code (using githubs search) for getFlags(), and noticed that ObsoleteDemos / OpenGL / GL_DialogDynamicsWorld.cpp has an inconsistency in that line  243 and 323 do 

```
body->setCollisionFlags(body->getFlags()|btCollisionObject::CF_NO_CONTACT_RESPONSE);
```

instead of

```
body->setCollisionFlags(body->getCollisionFlags()|btCollisionObject::CF_NO_CONTACT_RESPONSE);
```

i.e. using getFlags() instead of getCollisionFlags().

Not that it really changes anything.

**Comment by erwincoumans** [comment]
closing out-of-date issues.
