### ISSUE TITLE
calculateJacobian doesn't returns Jacobian with #dof when robot loaded with useFixedBase=False

### ISSUE THREAD

**Issue by k-maheshkumar** [bulletphysics/bullet3#1641]
Hi,
I can see from pybullet documentation that, the calculateJacobian returns:
linearJacobian: mat3x ((dof), (dof), (dof))
angularJacobian: mat3x ((dof), (dof), (dof))
For example, husky/husky.urdf, which has numDoF: 4 and numJoints: 10), is loaded using loadURDF with useFixedBase=True. Everything works as expected and calculateJacobian returns 3x4 matrix. But, when same urdf loaded with useFixedBase=false, calculateJacobian returns 3x10 matrix. 

The above example can be seen in the file attached.

Also, I can see from issue [#1615](https://github.com/bulletphysics/bullet3/pull/1615) that the inputs now takes numDoF instead of numJoints. So, I expect the output also need to match the numDoF and not numJoints. But I wonder, how it works with useFixedBase=True and not with useFixedBase=False.

Can you please explain if my expectation is right?.

[jacobian.py.zip](https://github.com/bulletphysics/bullet3/files/1921760/jacobian.py.zip)

**Comment by erwincoumans** [comment]
For a floating base, the base will add 6 degrees of freedom (3 linear and 3 angular) so the total is 4+6=10 dofs,
hence the jacobian becomes 3x10
