### ISSUE TITLE
Unknown geometry type: polyline

### ISSUE THREAD

**Issue by rstrudel** [bulletphysics/bullet3#1645]
Hello,

I am trying to load a SDF file I built through Gazebo following this tutorial to extrude shapes from SVG (http://gazebosim.org/tutorials?tut=extrude_svg). The SDF file contains polyline to define visual and collision shape of the mesh. However pybullet does not seem to support this feature as I get the error : 
"Unknown geometry type: polyline" when I try to load it.

Is there a workaround to this problem ?

Best,

Robin

**Comment by erwincoumans** [comment]
No, we don't fully support all COLLADA features. Just convert the asset to Wavefront obj and triangulate them.
