### ISSUE TITLE
Speed up the simulation

### ISSUE THREAD

**Issue by pyni** [bulletphysics/bullet3#1649]
I wonder whether pybullet has the function  to speed up the simulation? Thanks

**Comment by erwincoumans** [comment]
Yes, there are many ways, and it all depends on the particular scenario how to achieve faster speeds. It helps starting to profile your simulation, using the startStateLogging command:

~~~~~~
logId = p.startStateLogging(p.STATE_LOGGING_PROFILE_TIMINGS, "timings.json")
~~~~~~
You can open such timings in Google Chrome, visit the about://tracing (as URL) and load that timings.json file.

Also, try out the examples that come with PyBullet and look at the Bullet Quickstart Guide for performance related APIs (numSolverIterations, timeStep), simplify collision and visual geometries in the URDF file, etc.
