### ISSUE TITLE
memory leak in getJointStates

### ISSUE THREAD

**Issue by lukashermann** [bulletphysics/bullet3#1661]
Apparently there is a memory leak in the **p.getJointStates** method which doesn't occur for the **p.getJointState** method. Especially when using pybullet for reinforcement learning this can cause problems. 

Here is a little test script to reproduce the error: 
[bullet_mem_leak.tar.gz](https://github.com/bulletphysics/bullet3/files/1967018/bullet_mem_leak.tar.gz)

In line 39 the getJointStates method is called, which increases the memory usage gradually. Every 1000 iterations the memory information is printed. If in contrast getJointState is used, there is no memory leak. Additionally by uncommenting line 49 one can see the cause of the leak, a list is created every call of the method which isn't freed afterwards anymore.

**Comment by erwincoumans** [comment]
Thanks for the report and repro case, it is fixed now.
