### ISSUE TITLE
btKinematicCharacterController setWalkDirection issue

### ISSUE THREAD

**Issue by dmaluev** [bulletphysics/bullet3#167]
This code does not allow me to set zero vector for walkDirection:

```
m_normalizedDirection = getNormalizedVector(m_walkDirection);
```

How to stop the moving controller?

And this code is totally wacky:

```
static btVector3
getNormalizedVector(const btVector3& v)
{
    btVector3 n = v.normalized();
    if (n.length() < SIMD_EPSILON) {
        n.setValue(0, 0, 0);
    }
    return n;
}
```

how can the length of a normalized vector be less than epsilon?

**Comment by erwincoumans** [comment]
closing out-of-date issues. btKinematicCharacterController  is not supported.

**Comment by robindegen** [comment]
> closing out-of-date issues. btKinematicCharacterController is not supported.

Is it still not supported or was it added back? Because I still see it in the codebase and there is no comment indicating it's not supported? Could you confirm if it indeed should not be used or if it is okay to use now?
