### ISSUE TITLE
pybullet visualization with baselines or tensorforce

### ISSUE THREAD

**Issue by benelot** [bulletphysics/bullet3#1696]
I am trying to make the pybullet gym environments work with baselines or tensorforce, which works fine so far except for the visualization. In pybullet, visualization can only be enabled very early on, so that it is initialized together with the physics server, whereas in baselines or tensorforce, you only know that the user wants visualization at the time the library calls render() on the environment.

Is it very hard to make pybullet initialize rendering after initialization of the physics world? In fact it should not be so hard to just read out all physics objects and add visualizations to them. 

For now, the sub-optimal solution to this is just to make pybullet try to connect to a running instance of the GUI and if there is none running, just run headless. However, this makes the visualize flag quite useless in both libraries.

**Comment by erwincoumans** [comment]
Indeed, the design of PyBullet and Gym is not compatible for this flag, and the only real solution is your suggestion:

>> pybullet try to connect to a running instance of the GUI and 
>> if there is none running, just run headless
