### ISSUE TITLE
Error on Box to Box GJK algorithm

### ISSUE THREAD

**Issue by AndreaCatania** [bulletphysics/bullet3#1703]
This is a bug that I found on Godot: https://github.com/godotengine/godot/issues/18794
This is the reproducible demo [BasicExample.zip](https://github.com/bulletphysics/bullet3/files/2030925/BasicExample.zip)

This problem is similar to the issue #1623 where the returned penetration is positive.
I've noticed that by setting static body extension from `128, 1, 128` to `1,1,1` the problem disappear.
Also the problem doesn't show up if I remove the line with `kinShape->setMargin(0);` 

This seems to happen only with Box to Box algorithm, Also is mandatory for me set a margin of 0.

Thanks you in advance

**Comment by AndreaCatania** [comment]
Erwin thanks you! it fix the problem!! If you merge it I will import the new version of bullet in godot

**Comment by erwincoumans** [comment]
I need to sort out a few more things related to this collision detection and get back to you when it is done.

**Comment by AndreaCatania** [comment]
Ok let me know thanks you

**Comment by AndreaCatania** [comment]
Hi Erwin, any advance on this?

**Comment by AndreaCatania** [comment]
Hi Erwin, probably you are really busy, I want just remember you this issue. Let me know thanks you!!

**Comment by erwincoumans** [comment]
Yes, it is on my todo, once returned feom vacation.

**Comment by AndreaCatania** [comment]
Ok thanks you, have nice vacation

**Comment by erwincoumans** [comment]
I've been looking into the problem, it is a mix of issues. Need a bit more time, working on it. In the meanwhile, avoid 0 margin, use smaller shape size differences, use double precision, strict float (instead of fast).

**Comment by AndreaCatania** [comment]
In this moment I can't apply any of these, except for 0 margin. But I think that I can wait the fix, so Thanks you for looking on it

**Comment by erwincoumans** [comment]
Can you please check the attached file and see if that fixes the issue(s)?

+ Please never set the collision margin to zero (preferably leave it default). 
+ Don't make it easy for the user to set the margin to zero, since it will lead to incorrect collisions and slow performance.
+ Don't set this setEqualVertexThreshold to zero, please remove the line:
~~~~~~~~~~
gjk_simplex_solver->setEqualVertexThreshold(0.f);
~~~~~~~~~~
[btGjkPairDetector.zip](https://github.com/bulletphysics/bullet3/files/2292248/btGjkPairDetector.zip)

Thanks for the report and testing!

**Comment by erwincoumans** [comment]
Some improvements are checked in now. Please provide some feedback.
https://github.com/bulletphysics/bullet3/pull/1850/commits/ee9fca8c29149a28769d1128a22155ed30ad7826

**Comment by AndreaCatania** [comment]
Sorry if I didn't answer yet, but was a busy period.

**Comment by AndreaCatania** [comment]
It works Thanks you!
