### ISSUE TITLE
"pip install pybullet" fails on Windows 10 due to missing stdint.h

### ISSUE THREAD

**Issue by vpradeep07** [bulletphysics/bullet3#1708]
I'm trying to install pybullet on Windows using pip.  Here's my current workflow:

* Install Python 2.7.15 for windows from https://www.python.org/downloads/windows/
* Install "Microsoft Visual C++ Compiler for Python 2.7" http://aka.ms/vcpython27
  * Running`C:\Users\Vijay Pradeep\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe` gives the following version info: `Microsoft (R) C/C++ Optimizing Compiler Version 15.00.30729.01 for x64`
* Set up a virtualenv (probably not relevant to the error, but mentioning for completeness)
  * Create a virtual env called pybullet-test.  `virtualenv pybullet-env`
  * `cd pybullet-env/Scripts/`, and then `activate.bat`
* `pip install numpy`  (this installed successfully)
* `pip install pybullet==1.9.9` (this installation failed)

There's a lot of warnings along the way, but the relevant error is the following:
`c:\users\vijay pradeep\appdata\local\temp\pip-install-zfcav8\pybullet\examples\thirdpartylibs\tinyxml2\tinyxml2.h(43) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory`
`error: command 'C:\\Users\\Vijay Pradeep\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2`

There seems to be a similar issue occurring with scikit-image:  [StackOverflow: Python-scikit-image-install-failing-using-pip](https://stackoverflow.com/questions/44865576/python-scikit-image-install-failing-using-pip)

Attempting the same workaround mentioned there works for me: I copied the following file (https://raw.githubusercontent.com/mattn/gntp-send/master/include/msinttypes/stdint.h) into my compiler include directory: `C:\Users\Vijay Pradeep\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include`

Suggested fix: Modify bullet's local copy of tinyxml to no longer have a `stdint.h` dependency.  Or include a copy of stdint.h as part of pybullet, and explicitly add it to the include path when compiling for Windows.

Happy to submit a PR/bugfix if this is useful.

**Comment by erwincoumans** [comment]
OK, I got around removing that include stdint.h. Should be fixed now.
