### ISSUE TITLE
`calculateInverseKinematics` return dimension does not match `getNumJoints`

### ISSUE THREAD

**Issue by tomsilver** [bulletphysics/bullet3#1711]
Hi there,

Thanks for all your work on pybullet. I am a very new user, so this issue is likely a misunderstanding on my part -- thanks for your patience.

From the inverse kinematics examples and the quickstart guide, my understanding is that the output of `calculateInverseKinematics` should have length equal to the value of `getNumJoints`, so that one can do something like

    numJoints = p.getNumJoints(kukaId)
    jointPoses = p.calculateInverseKinematics(kukaId,kukaEndEffectorIndex,pos)
    for i in range (numJoints):
        p.setJointMotorControl2(bodyIndex=kukaId,jointIndex=i,targetPosition=jointPoses[i], ... [etc])

I am working with a Baxter robot model and I am finding a consistent dimension mismatch when I do the following:

    baxterEndEffectorId = 48
    currentPos = p.getLinkState(baxterId, baxterEndEffectorId)[0]
    jointPoses = p.calculateInverseKinematics(baxterId, baxterEndEffectorId, currentPos)
    numJoints = p.getNumJoints(baxterId)

    # Will fail now because numJoints == 56 but len(jointPoses) == 19
    assert numJoints == jointPoses

The length of the `jointPoses` is consistently 19 for different values of `baxterEndEffectorId` and target positions, but the baxter model has 56 joints.

I can share a full example if that would be helpful but maybe there is something obvious. Thanks for any insights you can offer!

**Comment by erwincoumans** [comment]
THere are no target positions for fixed joints, so the numJoints != jointPoses if there are fixed joints.
See th inverse_kinematics_sawyer.py example how to deal with it:
https://github.com/erwincoumans/pybullet_robots

**Comment by tomsilver** [comment]
Perfect, thanks very much for the prompt reply @erwincoumans !
