### ISSUE TITLE
collision callback

### ISSUE THREAD

**Issue by blitz-research** [bulletphysics/bullet3#1745]
Hi,

I am trying to write a collision callback function and it currently looks like this:

```
void collisionCallback( btDynamicsWorld *world,btScalar timeStep ){

	int numManifolds=world->getDispatcher()->getNumManifolds();
	
	for( int i=0;i<numManifolds;++i ){

		btPersistentManifold *contactManifold=world->getDispatcher()->getManifoldByIndexInternal( i ); 

		int numContacts=contactManifold->getNumContacts();
		if( !numContacts ) continue;
		
	        for( int j=0;j<numContacts;++j ){
        
			btManifoldPoint &pt=contactManifold->getContactPoint( j );
			
			printf( "pt.distance %f \n",pt.getDistance() );fflush( stdout );
	            
			if( pt.getDistance()<0.0f ){
	            
				const btCollisionObject *body0=contactManifold->getBody0();
				const btCollisionObject *body1=contactManifold->getBody1();
		
				*_collp++=body0->getUserPointer(); //nasty global somewhere
				*_collp++=body1->getUserPointer();
				
				break;
			}
		}
	}
}
```

I am using `world->setInternalTickCallback( &collisionCallback,0,false );` to 'register' the callback.

For now, I'm just trying to establish which pairs of collision objects are colliding, and it sort of works, but it seems to miss some collisions now and then. Worse case, I can land my spaceship/cone on it's side and no collisions register at all!

Oddly, if I skip the getDistance()<0 step entirely so it registers a collision if numContacts!=0, it seems to work, but I thought getDistance()>0 indicated non-penetrating contacts? I am definitely getting penetration values >0, sometimes before I even get any <0 which seemed odd?

The objects being collided are a cone vs box and cone vs terrain.

What am I doing wrong?!?

Also, gContactAddedCallback doesn't seem to ever be called. gContactProcessedCallback is though, so I assume I'm doing something right?

Bye,
Mark

**Comment by erwincoumans** [comment]
Bullet also reports contact with small positive distance. Just ignore them.
