### ISSUE TITLE
SEGFAULT when SoftBody->m_worldInfo->m_broadphase = 0

### ISSUE THREAD

**Issue by dunnousername** [bulletphysics/bullet3#1791]
I have a gist here:
[https://gist.github.com/dunnousername/40798a1c74e9f06ddf52c54f7da44022](https://gist.github.com/dunnousername/40798a1c74e9f06ddf52c54f7da44022)

Here's a copy of the #bulletphysics IRC channel:
> <dunnousernamefn> Huh, I get different errors depending on the order I put source code and libraries on the compiler
> <dunnousernamefn> Hey, on btSoftBody.cpp::2330, there is a check "if(0!=getBroadphaseHandle())". If that is true, then "m_worldInfo->m_broadphase->setAabb(...)". However, m_worldInfo->m_broadphase is 0; this causes a segfault
> <dunnousernamefn> even though 0!=getBroadphaseHandle()
> <dunnousernamefn> which indicates that getBroadphaseHandle() and m_worldINfo->m_broadphase are different things
> <dunnousernamefn> this can be solved by manually setting m_worldInfo->m_broadphase to a pointer to an actual broadphase

**Comment by erwincoumans** [comment]
You should use the world info from the softbody dynamics world (using the getWorldInfo API) and not create a separate one.
