### ISSUE TITLE
Normalizing zero vector

### ISSUE THREAD

**Issue by Jirka1** [bulletphysics/bullet3#180]
In
void btConeTwistConstraint::computeTwistLimitInfo
there is condition
    if (twistAngle > SIMD_EPSILON)
        vTwistAxis.normalize();
If the two constrained bodies have the same initial orientation, I get vTwistAxis as zero vector, condition twistAngle > SIMD_EPSILON holds and it tries to normalize zero vector. I use double precision, but I don't think it's relevant.
twistAngle should be compared to something larger (of order sqrt(SIMD_EPSILON)), since twistAngle is calculated using acos.
Small error in quaternion's w thus causes large error in twistAngle.

**Comment by erwincoumans** [comment]
closing out-of-date issues.
