### ISSUE TITLE
Memory leak in getClosestPoints?

### ISSUE THREAD

**Issue by haudren** [bulletphysics/bullet3#1800]
I am using pybullet to compute distances between a bunch of objects in a scene, but my RAM gets full very quickly... I tried to profile using `memory_profiler` and it seems that the memory allocated by `getClosestPoints` is never freed.

I wrote the following repro program:
```python
import pybullet as p
import pybullet_data
import os
import numpy as np

nr_ducks = 100
nr_steps = 1000

p.connect(p.DIRECT)

root = pybullet_data.getDataPath()

ducks = [p.loadURDF(os.path.join(root, 'duck_vhacd.urdf')) for i in range(nr_ducks)]

for duck in ducks:
    p.resetBasePositionAndOrientation(duck, 0.05*np.random.rand(3), [0, 0, 0, 1])

for i in range(nr_steps):
    distances = [p.getClosestPoints(ducks[0], duck, 0.01) for duck in ducks[1:]]
    del distances  # Should not even be needed

p.disconnect()
```
The resulting memory usage (`mprof run leak_pybullet.py`):
![leak_pybullet](https://user-images.githubusercontent.com/4352562/43060933-017bec26-8e8e-11e8-9827-8a0e09d75c0b.png)

**Comment by erwincoumans** [comment]
Thanks for the report, we'll check it out.

**Comment by erwincoumans** [comment]
Thanks for the report, should be fixed here: https://github.com/bulletphysics/bullet3/pull/1804
