### ISSUE TITLE
Is it possible to get Normal and Tangential forces?

### ISSUE THREAD

**Issue by Amir-Arsalan** [bulletphysics/bullet3#1809]
Hi. I wonder, is it possible to get Normal and Tangential forces of softbody objects in Bullet/PyBullet? If so, how fine-grained are they? Can I get the forces applied to each face/vertex of a mesh?

**Comment by Amir-Arsalan** [comment]
@erwincoumans

**Comment by erwincoumans** [comment]
You can get normal contact forces and tangential friction forces. They are accurate up to each contact point. See PyBullet.getContactPoints in the [PyBullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#).
