### ISSUE TITLE
Incorrect texture rendering for 3D meshes from .obj file

### ISSUE THREAD

**Issue by anoopsonar30** [bulletphysics/bullet3#1813]
I've been trying to render 3D meshes from the S3DIS database which can be found at - http://buildingparser.stanford.edu/dataset.html

The render for area_3 in pybullet looks like this - 
![pybulletrender1](https://user-images.githubusercontent.com/8993026/43559066-5d18e34c-95da-11e8-9a77-0eee5f9b3184.png)

where the textures are all messed up and in the incorrect places. Moreover the roof isn't rendered at all. 
On importing the same .obj file into a software like 3DS Max I got the following perfect renders - 

![3dsmaxrender](https://user-images.githubusercontent.com/8993026/43559118-9778fdf6-95da-11e8-98f6-7a4455de78e4.PNG)
![3dsmaxrender2](https://user-images.githubusercontent.com/8993026/43559120-9ae25b36-95da-11e8-89aa-4c4a17be3624.PNG)

Moreover, I've been trying to render a husky robot on the floor of this 3D environment. However, pybullet renders both area_3 and husky for a split second after which area_3 disappears and only the husky is left. Could someone look into this? The 3D environment above is rendered using the createMultiBody() function using the .obj file and the husky is rendered from it's URDF.

**Comment by erwincoumans** [comment]
PyBullet (and the underlying Bullet Robotics APIs) rendering has some limitations:

1) wavefront obj files can have at most 1 texture
2) there is a limited pre-allocated memory for visual meshes

You can use obj2sdf utility to get around (1), it creates additional obj files for each material/texture

You can try increasing the default memory allocation to get around (2), or reduce/simplify the mesh/obj file.


Can you share the full reproduction case, including PyBullet python file and the actual obj file and textures in some github repo?
