### ISSUE TITLE
Pybullet - request feature: rescale mesh once loaded

### ISSUE THREAD

**Issue by bdelhaisse** [bulletphysics/bullet3#1816]
Hi,

Is there a way to rescale a (visual) mesh once it has been loaded? The documentation in the "Pybullet Quickstart Guide" mentions `changeVisualShape` however there are no parameters to change the scale. Currently,  when I want to change the dimensions of a visual shape (for instance a sphere), I removed it from pybullet and then reload it with a different scale. This is not really practical, and it would probably be better to expose this feature from the `changeVisualShape` method.

Thanks.

**Comment by erwincoumans** [comment]
This is not supported at the moment. If there is a voluteer wanting to implemented it, please re-open and file a pull request. Need to clean the tracker, there are too many requests and no voluteers.
