### ISSUE TITLE
A number of URDFs specify an invalid XML "0.0" version

### ISSUE THREAD

**Issue by gkjohnson** [bulletphysics/bullet3#1821]
A number of the URDF files in the `/data` folder declare the XML version to be `0.0`. See here:

https://github.com/bulletphysics/bullet3/blob/master/data/cube_concave.urdf#L1

There are quite a few others, too. I was trying to parse the xml in Javascript and got the following errors when using [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser):

```xml
<h3>This page contains the following errors:</h3>
<div style="font-family:monospace;font-size:12px">
  error on line 1 at column 20: Unsupported version '0.0'
</div>
```

The ones I tested seem to parse just fine if the version is changed to `1.0`.

Thanks!

**Comment by erwincoumans** [comment]
PyBullet should handle those xml files anyway. If you use a program that doesn't handle them and want to fix the URDF files, feel free to submit a pull request.

**Comment by gkjohnson** [comment]
I am using them in a different application -- I'll make a PR. Thanks!
