### ISSUE TITLE
The number of joint poses calculated by calculateInverseKinematics() is not consistent with getNumJoints()

### ISSUE THREAD

**Issue by shinshiner** [bulletphysics/bullet3#1823]
Hi, I try to run the example code in `examples/pybullet/examples/ik_end_effector_orientation.py` with [this urdf file](https://github.com/corlab/cogimon-gazebo-models/blob/master/universal-robot-ur5/ur5robot.urdf). However, the joint poses returned by `calculateInverseKinematics()` just have 7 values and I got 8 when running `getNumJoints()`. And the robot cannot move to the right position. I feel relatively strange about this. Could you look into it ?

**Comment by erwincoumans** [comment]
The number of joint poses is equal to the number of degrees of freedom, so it skips the fixed joints.
