### ISSUE TITLE
Destruct object mesh at runtime

### ISSUE THREAD

**Issue by fadavi** [bulletphysics/bullet3#1824]
Hey there.
I'm working on a surgery simulation project, needs that to desctruct (cut) softbodies at runtime. (e.g. user should be able to cut a part of a biological organ at runtime)
Is this possible/implementable in bullet?
Please guide me.

thanks.

**Comment by erwincoumans** [comment]
We used to have a demo that shows how to cut soft bodies at run-time, the feature is still there but the demo doesn't enable it. Search the code in SoftBody demo.

**Comment by fadavi** [comment]
thank you so much. i'll close this issue.
