### ISSUE TITLE
pip3 fails to install pybullet on macOS High Sierra 10.13.5

### ISSUE THREAD

**Issue by MatchesMalonee** [bulletphysics/bullet3#1837]
I get this error when I try to install the pybullet library via `pip3` on macOS HS.
```
src/LinearMath/btQuickprof.cpp:713:10: error: thread-local storage is not supported for the current target
    static __thread unsigned int sThreadIndex = kNullIndex;
           ^
  5 warnings and 1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pybullet
  Running setup.py clean for pybullet
Failed to build pybullet
Installing collected packages: pybullet
  Running setup.py install for pybullet ... /
```
The setup tries to install, but since the proper wheels aren't there, that process fails as well.
I'm running Python 3.6.4, no Anaconda, and clang version `Apple LLVM version 9.0.0 (clang-900.0.39.2)`

`xcodebuiild -version` gives me `Xcode 9.2 Build version 9C40b`

I also ran the `xcode.command` file, and experienced no errors during build time.

**Comment by MatchesMalonee** [comment]
I also noticed that most of the files in `src/LinearMath/` directory are at least 7-8 months old, except for three files that were 16 days old as of writing this comment. `btQuickprof.cpp` is one of those files.

**Comment by erwincoumans** [comment]
pip3 install pybullet works fine here for all platforms, including Mac OSX High Sierra 10.13.5. If you figure out what the problem is, please let us know.

**Comment by MatchesMalonee** [comment]
Is the standalone python 3.6 environment not supported by default?

**Comment by erwincoumans** [comment]
There is no support, volunteers help make things work. pybullet compiles and runs for the platforms and configurations , I've not run into those Mac/Python issues myself, and don't have time tracking down everyones issues. If you find a solution, please consider sharing a PR.

**Comment by erwincoumans** [comment]
It must be some clang/Xcode/compiler issue.

Xcode 9.4.1, Build version 9F2000, can you try updating to a newer Xcode / clang version?

**Comment by erwincoumans** [comment]
Some others had similar issues, it is not clear what is causing it and we have no bandwidth on solving it for you.
https://github.com/bulletphysics/bullet3/issues/830
https://github.com/bulletphysics/bullet3/issues/1207
