### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by SuperAwesomePlayer** [bulletphysics/bullet3#1839]
A license like the CC0 or the Unlicense should be added.
Links:
CC0: https://creativecommons.org/share-your-work/public-domain/cc0/
Unlicense: http://unlicense.org/

**Comment by MajesticMack** [comment]
Bullet is actually licensed under the zlib license.  Look at [LICENSE.txt](https://github.com/bulletphysics/bullet3/blob/master/LICENSE.txt)
