### ISSUE TITLE
Feature Request: JS API

### ISSUE THREAD

**Issue by artificial-lshamis** [bulletphysics/bullet3#1840]
AmmoJS (https://github.com/kripken/ammo.js) uses Emscripten to cross-compile cpp to js, allowing webgl to provide in-browser visualization. Unfortunately, AmmoJS hasn't updated its version of Bullet in 2 years and is providing a very outdated version of Bullet2, missing extras, such as b3RobotSimulatorClientAPI.

It would be great if an Emscripten build was provided here. Hopefully it's just a flag switching g++ -> em++ and gcc -> emcc.

**Comment by erwincoumans** [comment]
Happy to accept a contribution, if it doesn't add much maintenance. No cycles to work on this though. Please re-open if someone wants to contribute it.
