### ISSUE TITLE
pybullet set initial velocity of urdf object

### ISSUE THREAD

**Issue by aznshodan** [bulletphysics/bullet3#1845]
is there a way I can set initial velocity of a urdf object?
For instance, I have a sphere2.urdf. I'd like to set some initial velocity to this so that when the simulator starts, it is already moving at the velocity I defined.

**Comment by erwincoumans** [comment]
You can use resetBaseVelocity for that. See the PyBullet quickstart guide:
https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#

**Comment by arpastrana** [comment]
Hi @erwincoumans. Does using `p.resetBaseVelocity()` have a similar impact as p.resetBasePositionAndOrientation() in that, if applied during a running simulation, it will override the effect of all physics simulation?

**Comment by erwincoumans** [comment]
Yes, it will override the physics calculation, so those reset* functions are best used before stepping the simulation.

**Comment by arpastrana** [comment]
👍
