### ISSUE TITLE
hitting assert when creating a BvhTriangleMeshShape

### ISSUE THREAD

**Issue by gjaegy** [bulletphysics/bullet3#185]
Hi,

using the latest trunk, I am hitting an assert when trying to normalize a zero-length vector.

this happens when creating a BvhTriangleMeshShape.

The problem can be seen in the screenshot below. Basically, the "edge" vector is the issue, or rather, the fact that it's built using the difference between two instances of the same vertex (i.e. m_triangleVerticesA[1]-m_triangleVerticesA[1] => 0).

Now, I wonder why I get sharedVertsA[0] == sharedVertsA[1] == 1.

Is that possible? Please note that I am removing all degenerated triangles before creating the shape.

Any help would be appreciated. Thanks a lot !

PS: below the triangle being processed (first and third vertex are close to each other, but not equal (delta(Y) == 1.81e-005):
-       triangle,3  0x0869f180 {mVec128={...} m_floats=0x0869f180 } btVector3 *
-       [0] {mVec128={...} m_floats=0x0869f180 }    btVector3
-       mVec128 {0, -13768.4, 13.0551, -24642.2}    __m128
-       m_floats    0x0869f180  float [4]
      [0] -24642.1563 float
      [1] 13.0550518  float
      [2] -13768.4336 float
      [3] 0.000000000 float
-       [1] {mVec128={...} m_floats=0x0869f190 }    btVector3
-       mVec128 {0, -13700.7, 13.055, -24647.8} __m128
-       m_floats    0x0869f190  float [4]
      [0] -24647.7695 float
      [1] 13.0550337  float
      [2] -13700.6875 float
      [3] 0.000000000 float
-       [2] {mVec128={...} m_floats=0x0869f1a0 }    btVector3
-       mVec128 {0, -13768.4, 13.055, -24642.2} __m128
-       m_floats    0x0869f1a0  float [4]
      [0] -24642.1563 float
      [1] 13.0550337  float
      [2] -13768.4336 float
      [3] 0.000000000 float

![image](https://cloud.githubusercontent.com/assets/900305/3243946/68bb092c-f161-11e3-9ab4-93fad195a976.png)

**Comment by erwincoumans** [comment]
closing out-of-date issues.
