### ISSUE TITLE
How to obtain image coordinates of world object

### ISSUE THREAD

**Issue by msieb1** [bulletphysics/bullet3#1856]
Hello,

Firstly, I wanted to ask why the projection matrix is 4x4 and not 3x4 as one would expect from a projection matrix.

Secondly, I wanted to ask what the quickest way is to obtain the corresponding 2D-image coordinates of an object with 3D-coordinates given in the world frame.

**Comment by erwincoumans** [comment]
Standard OpenGL view and projection matrices are 4x4, so one wouldn't expect a 3x4 matrix. https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glMultMatrix.xml

~~~~~~~
Secondly, I wanted to ask what the quickest way is to obtain the corresponding 2D-image coordinates of an object with 3D-coordinates given in the world frame.
~~~~~~~
We don't provide an API to do such conversion.
