### ISSUE TITLE
Pusher, Striker and Thrower classes seems to have a bug

### ISSUE THREAD

**Issue by jna29** [bulletphysics/bullet3#1861]
It looks like `self.forearm_roll_joint` is mistaken for `self.upper_arm_roll_joint` in the `Pusher`, `Striker` and `Thrower` classes in `pybullet_envs.robot_manipulators`. The mistakes are on lines 108, 118, 168, 208, 257 and 297 in `pybullet_envs/robot_manipulators.py`.

**Comment by erwincoumans** [comment]
There is noone working on it, do you care submitting a patch/pull request?

**Comment by jna29** [comment]
Sure

**Comment by erwincoumans** [comment]
Thanks for your PR, let's close this issue.
