### ISSUE TITLE
Invalid dimensions for image data

### ISSUE THREAD

**Issue by JobSmith** [bulletphysics/bullet3#1871]
When run the file: examples/pybullet/examples/testrender.py, An error occurs:

![image](https://user-images.githubusercontent.com/15700681/45350664-ed1ce700-b5e6-11e8-973f-53ab9be98673.png)

**Comment by erwincoumans** [comment]
Fixed in a commit/PR. Thanks for the report!

**Comment by JobSmith** [comment]
Great job!
