### ISSUE TITLE
Cannot open source file: 'examples/pybullet/pybullet.c': No such file or directory

### ISSUE THREAD

**Issue by Count-Badgerston** [bulletphysics/bullet3#1880]
### Works now !
<strike>not yet available!
I've downloaded the source code and when I navigate to it's directory and run  `python setup.py build` I get the following message: 

> c1: fatal error C1083: Cannot open source file: 'examples/pybullet/pybullet.c': No such file or directory
> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

But when I go to examples/pybullet directory the file pybullet.c is there ! Can't figure out the issue.

I'm using python 3.6 standalone, not in anaconda distro.
Visual studio community edition 2017.

When I try `pip install pybullet` I get a different error:

> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

</strike>

**Comment by Count-Badgerston** [comment]
No problem, things got fixed somehow.

**Comment by ABHIINAV12** [comment]
How ? I am also having the same problem

**Comment by ABHIINAV12** [comment]
> No problem, things got fixed somehow.

how ?

**Comment by ABHIINAV12** [comment]
> ### Works now !
> not yet available!
> I've downloaded the source code and when I navigate to it's directory and run `python setup.py build` I get the following message:
> 
> > c1: fatal error C1083: Cannot open source file: 'examples/pybullet/pybullet.c': No such file or directory
> > error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe' failed with exit status 2
> 
> But when I go to examples/pybullet directory the file pybullet.c is there ! Can't figure out the issue.
> 
> I'm using python 3.6 standalone, not in anaconda distro.
> Visual studio community edition 2017.
> 
> When I try `pip install pybullet` I get a different error:
> 
> > error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\link.exe' failed with exit status 1120

how ?

**Comment by VallesMarinerisExplorer** [comment]
I am having the same issue, I will let you know if I figure it out.

**Comment by VallesMarinerisExplorer** [comment]
Looks like it works if you make sure to cd into the directory with setup.py in it first and not try to put a long path before setup.py when you call it.
