### ISSUE TITLE
Calling `glGenerateMipmap` in OpenGL2 path

### ISSUE THREAD

**Issue by apoms** [bulletphysics/bullet3#1883]
The ExampleBrowser app invokes `glGenerateMipmap` when the OpenGL2 flag is passed, which causes a segfault since `glGenerateMipmap` is not supported for OpenGL < 3 (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGenerateMipmap.xhtml). This can be reproduced by running the following on an OpenGL2 only system:

```
./build_cmake/examples/ExampleBrowser/App_ExampleBrowser --opengl2
```

The offending line is:
https://github.com/bulletphysics/bullet3/blob/master/examples/OpenGLWindow/SimpleOpenGL2Renderer.cpp#L458

**Comment by erwincoumans** [comment]
Let's remove the line. Note that the OpenGL2.x backend is deprecated/unsupported, best to get a newer graphics card/driver.
Fixed here:
https://github.com/bulletphysics/bullet3/pull/2030/commits/5e08808e69ee596b9f42a1f1b1578aaaa8e4edf8
