### ISSUE TITLE
Cassie robot model not fully loading when using URDF

### ISSUE THREAD

**Issue by jmichaux** [bulletphysics/bullet3#1887]
I've been trying to load Cassie using [this](https://github.com/UMich-BipedLab/cassie_description), but for some reason one of the legs isn't loading.  Do I need to modify the URDF somehome?

**Comment by erwincoumans** [comment]
Somehow missed this issue report. The 'package://' prefix needs to be removed. Also, simplified the STL meshes (Blender decimation at 0.1) and added PyBullet script:

See cassie.py at https://github.com/erwincoumans/pybullet_robots

<img width="1016" alt="cassie" src="https://user-images.githubusercontent.com/725468/47884757-489d7100-ddef-11e8-9ed8-16c73583911d.png">

**Comment by jmichaux** [comment]
Thanks @erwincoumans!
