### ISSUE TITLE
How to calculate the distance of the object?

### ISSUE THREAD

**Issue by JobSmith** [bulletphysics/bullet3#1901]
I want  to calculate the distance of each object appearing in the camera image.
Should I add a binocular camera or just create two cameras?

**Comment by erwincoumans** [comment]
You would create two cameras indeed, each with their own view matrix (likely same projection matrix).
We don't have an implementation to compute the distance/depth from a stereo image, do you have that?

**Comment by erwincoumans** [comment]
This is not a Bullet feature, let's close it.
