### ISSUE TITLE
how does pybullet compute lateral friction of spheres?

### ISSUE THREAD

**Issue by aznshodan** [bulletphysics/bullet3#1908]
I have two spheres. One has (mass, radius) of (2.0kg, 0.1m), and the other is (1.0kg, 0.1m).
I ran p.getDynamicsInfo and turns out they both have the same lateral friction coefficient of 0.5. 
I can go and modify the urdf files of both spheres to some values but I want to know if those coefficients are in fact correct coefficients computed by pybullet internally. 

Thanks in advance.

**Comment by underactuated** [comment]
I do not know how friction is implemented in pybullet, by usually the _friction coefficient_ does not depend on mass (do not confuse it with the _friction force_).

**Comment by erwincoumans** [comment]
The friction coefficient is combined between two objects. If you want to know the lateral friction force for a certain contact point, see getContactPoints in the [PyBullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.cb0co8y2vuvc).

**Comment by LFGfg** [comment]
> The friction coefficient is combined between two objects. If you want to know the lateral friction force for a certain contact point, see getContactPoints in the [PyBullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.cb0co8y2vuvc).

How to understand lateralFrictionDir1 and lateralFrictionDir2, and how are they defined?
