### ISSUE TITLE
env.render() doesn't work

### ISSUE THREAD

**Issue by Rendok** [bulletphysics/bullet3#1920]
Hi,

If I create
`env = gym.make("AntBulletEnv-v0")`
`env.render()`
or
`env = gym.make("KukaBulletEnv-v0")`
`env.render()`

Then render doesn't work regardles it is in a loop or not.
How can I fix it?

**Comment by erwincoumans** [comment]
If you want a visual GUI window, you need to call env.render(mode="human") before calling init:
~~~~~~
import gym
import pybullet_envs
env = gym.make("AntBulletEnv-v0")
env.render(mode="human")
env.reset()
while (1):
	observations,reward,done,_=env.step([0,0,0,0,0,0,0,0])
~~~~~~~
