### ISSUE TITLE
eglPlugin not rendering transparent objects in depth map

### ISSUE THREAD

**Issue by rstrudel** [bulletphysics/bullet3#1923]
In the file:
`bullet3/examples/pybullet/examples/testrender_egl.py`

If you modify the visual shape of r2d2 to get a transparent body by adding the lines : 
`robot_id = pybullet.loadURDF("r2d2.urdf")`
`pybullet.changeVisualShape(robot_id, -1, rgbaColor=(1, 0, 0, 0.5))`

Then the transparent part does not appear any more on the depth map.
I have attached two images where you can see the transparent body not appearing in the depth map.
Is there any way to fix or tune this ?

![r2d2_plain](https://user-images.githubusercontent.com/35014917/46670922-c8ab2f00-cbd3-11e8-9515-7f9a2e0cabd0.png)
![r2d2_transparent](https://user-images.githubusercontent.com/35014917/46670923-c8ab2f00-cbd3-11e8-806b-bda8975f66d5.png)

**Comment by erwincoumans** [comment]
You will have to set the alpha to 1 to render into the depth map, so you may want to render twice:
Render with alpha for RGB, and then set the alpha to 1 for the transparent objects that you want to show up in the depth map and render again.
