### ISSUE TITLE
How to remove the coordinate line in the environment?

### ISSUE THREAD

**Issue by JobSmith** [bulletphysics/bullet3#1931]
![image](https://user-images.githubusercontent.com/15700681/46873670-bea25e00-ce69-11e8-9566-f689d7f47e15.png)
You can see the lines around the coordinate.
Now I want to remove it.
How to do it?
What's more, I even did not want the coordinate axis appearing.

**Comment by erwincoumans** [comment]
Those axis are part of the default GUI. You can disable it using 'configureDebugVisualizer', see the [PyBullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#):
~~~~~~~~~
import pybullet as p
p.connect(p.GUI)
p.configureDebugVisualizer(p.COV_ENABLE_GUI,enable=0)
while (1):
        p.stepSimulation()
~~~~~~~~~
