### ISSUE TITLE
Can I change the state of the object in the simulation environment?

### ISSUE THREAD

**Issue by JobSmith** [bulletphysics/bullet3#1938]
Just consider the following interesting situation.
I drive a car in the simulation environment.
The car may crash into a tree or a yellow dark.
Now I want to change the color of the tree or dark when the collision happens.
How could I do?

**Comment by erwincoumans** [comment]
p.changeVisualShape(objectUniqueId, linkIndex, rgbaColor=newColor]
See the [PyBullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA).
