### ISSUE TITLE
BT_USE_SSE_IN_API

### ISSUE THREAD

**Issue by Th0r3k** [bulletphysics/bullet3#194]
I have uncommented this define in the btScalar.h archive because I need to use SSE vectors in my solution, but it becomes totally unstable. Then I realized that it even happen in the basic example provided by your demo solution. It only happens in release, I am using x64 compilation and I have the same results that the basic demo has, boxes falling from the floor.
I have modified a little bit the demo adding __declspec(align(16)) just in case to the classes used for the demo, and in my solution I have this alignment specification in all my physics classes. I am doing something wrong or is still not solved?

**Comment by erwincoumans** [comment]
closing out-of-date issues.
