### ISSUE TITLE
Undefined behavior - accesses outside of array bounds in example

### ISSUE THREAD

**Issue by ShFil119** [bulletphysics/bullet3#1940]
In `bullet3/examples/Evolution/NN3DWalkersTimeWarpBase.h`, function `clampToCustomSpeedNotches`, line:
`		double speedDist = (speeds[i] - speed >= 0) ? speeds[i] - speed : speed - speeds[i];  // float absolute`
Size of array `speeds` is 10, but loop iterate also on `i = 10`.

**Comment by erwincoumans** [comment]
Thanks for the report. Should be fixed in this commit: https://github.com/bulletphysics/bullet3/commit/63784dab5fdf7fe84fd93f2caeef43b8524f7389
