### ISSUE TITLE
How to project 3D point onto image plane?

### ISSUE THREAD

**Issue by msieb1** [bulletphysics/bullet3#1952]
I am multiplying P*V*p3d where P and V are the 4x4-reshaped projection and view matrix, respectively. However, this does not yield the corresponding pixel location of the used 3D point when checking with image obtained with p.getCameraImage.

What is the correct way to compute the 2D projection by hand?

**Comment by msieb1** [comment]
Thanks for the answer. I tried exactly that, but the xy values are out of the [-1,1] range after normalizing. We do not have to take into account the Model matrix, right?

**Comment by daxum** [comment]
It depends on if the point you're using is in world space or model space. From what you've said, it seems that it is in world space, so that shouldn't be a problem. X and y being outside [-1, 1] means that the point's offscreen, so are you sure it's visible?

**Comment by erwincoumans** [comment]
You may want to ask such question in an OpenGL forum or learning more about TinyRenderer, it has nice documentation.https://github.com/ssloy/tinyrenderer/wiki
(we use it for our software CPU rendering: 
https://github.com/bulletphysics/bullet3/blob/master/examples/TinyRenderer/our_gl.cpp#L82)

**Comment by neha191091** [comment]
Hi @msieb1,
Were you able to find a solution to the issue you were having? I am currently facing a similar issue, where I am not getting the normalized pixel values to lie in [-1, 1] even when the corresponding 3d coordinate shows up in my image.
