### ISSUE TITLE
Pybullet robot simulation go crazy!!!!!

### ISSUE THREAD

**Issue by Frank-Li-Code** [bulletphysics/bullet3#1958]
I use official examples: [https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/tensorflow](url)
Every time when robot velocity is little fast or it collision on it self, then it go crazy like this:
![20181027_225552](https://user-images.githubusercontent.com/43923352/47605665-fef20680-da3b-11e8-809a-7b7252f83798.gif)
When have this issues, there just no way to training agent to do anything at all!!! : (

**Comment by erwincoumans** [comment]
The demo settings weren't tweaked to deal with additional energy of mouse picking etc. It would be good to make it a bit more robust though, here is a PR to improve it:
https://github.com/bulletphysics/bullet3/pull/1959
Thanks for the report!

**Comment by erwincoumans** [comment]
Another issue is that the resetDebugVisualizerCamera call will interfere with mouse picking, adding even more energy into the system. If you want to pick, best to disable the call to resetDebugVisualizerCamera in that demo. I'll see if we can either disable picking in that demo, or remove the follow cam.
