### ISSUE TITLE
Bullet Physics -> App_RobotSimulator Build error!

### ISSUE THREAD

**Issue by Frank-Li-Code** [bulletphysics/bullet3#1964]
I generate the VS projects in bulletphysics/bulid3/vs2010 folder by run build_visual_studio_without_pybullet_vr.bat
and when I try to build project "App_RobotSimulator" the error appear
I'm kind new to C++, please help : )
![wrong](https://user-images.githubusercontent.com/43923352/47694452-9fad1580-dc38-11e8-8cff-4419d90055d0.PNG)

**Comment by erwincoumans** [comment]
Cannot reproduce it, please become more familiar with MSVC and C++.
