### ISSUE TITLE
Wireframe drawing for btConvexHullShape is incorrect.

### ISSUE THREAD

**Issue by stolk** [bulletphysics/bullet3#1970]
Start up "convex stack" Benchmark Demo.

Press W.

The "Taru" shape shows up incorrectly when in wireframe, but correctly when it draws the full faces.

![screenshot from 2018-10-31 12-02-33](https://user-images.githubusercontent.com/455280/47812261-29c2b000-dd05-11e8-90cc-2f02a8704529.png)

![screenshot from 2018-10-31 12-02-29](https://user-images.githubusercontent.com/455280/47812265-2d563700-dd05-11e8-81d6-5af78d5e5480.png)

If I had to guess: it seems to be drawing indexed-vertex data as if it was not indexed?

**Comment by erwincoumans** [comment]
This is not a bug but expected. The convex doesn't have indices, so there is nothing to draw. You can force to generate faces for prettier wireframe if you like.

~~~~~~~~~
convexHull->initializePolyhedralFeatures();
~~~~~~~~~

**Comment by erwincoumans** [comment]
Will be fixed soon anyway: https://github.com/bulletphysics/bullet3/commit/9e58a217324d555bb11eb5194825906f977c82e6
