### ISSUE TITLE
question about DIRECT model

### ISSUE THREAD

**Issue by lyz22233** [bulletphysics/bullet3#1973]
I set p.connect(p.DIRECT), and I use changeConstraint to change Obj's position, then I use  getBasePositionAndOrientation to get the obj's position and print it , but it has no change.

when I set p.connect(p.GUI), other code remains unchanged，then it's position can change.

**Comment by erwincoumans** [comment]
changeConstraint doesn't change the position. You need to step the simulation (stepSimulation). Did you do that?

**Comment by lyz22233** [comment]
Problem solved，thank you!

**Comment by lyz22233** [comment]
> changeConstraint doesn't change the position. You need to step the simulation (stepSimulation). Did you do that?

Problem solved，thank you!

**Comment by erwincoumans** [comment]
realTimeSimulation gets update from a separate thread, hance not DIRECT.
