### ISSUE TITLE
Question about setTimeStep

### ISSUE THREAD

**Issue by lyz22233** [bulletphysics/bullet3#1974]
I want to use bullet in DIRECT model, but setRealTimeSimulation has no effect in DIRECT mode.
So if I want to achieve the effect of setRealTimeSimulation(1), What parameter of setTimeStep should I set?

**Comment by erwincoumans** [comment]
setRealTimeSimulation just periodically calls the 'stepSimulation' at regular intervals from a separate thread. In DIRECT mode there is no other thread, so you need to call stepSimulation. No need to change 'setTimeStep'.

Please stop filing issues with questions.
Thanks!
