### ISSUE TITLE
EGL + changeVisualShape segfault

### ISSUE THREAD

**Issue by BlGene** [bulletphysics/bullet3#1976]
If I delete an object A, create a replacement B and try to call `changeVisualShape` for B it causes a segfault.

see: https://gist.github.com/BlGene/afa726e7364db6701e1793c3a85ebcd2 <-- search `#TODO():`

**Comment by erwincoumans** [comment]
Well, the eglPlugin is your contribution. Can you help fixing the issue?

**Comment by BlGene** [comment]
Yes, I can have a look. I'm a bit surprised it works for the debug viewer though.

**Comment by BlGene** [comment]
closing with #2176
