### ISSUE TITLE
Pybullet Cassie Robot Joint Constraint

### ISSUE THREAD

**Issue by ZhaomingXie** [bulletphysics/bullet3#1977]
I cannot find a place to create an issue for https://github.com/bulletphysics/pybullet_robots, so I just create one here. For the Cassie robot, a realistic model will have "knee_to_shin" a near fixed joint due to the very stiff spring, and "ankle_joint" will have a relationship with knee joint due to the kinematic chain on the physical robot. I wonder if there is an easy way to incorporate these types of constraints in the simulation?

**Comment by erwincoumans** [comment]
Yes, you can add a gear constraint, relating two joints (angle_joint and knee joint).
See https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/racecar_differential.py for an example of gear constraint. 

In addition, you can 'setJointMotorControl2' on the knee_to_shin joint, and configure the maxForce and other parameters.

**Comment by erwincoumans** [comment]
we don't have volunteers working on this URDF. If someone shares an improvement, we will accept pull requests. Thanks!
