### ISSUE TITLE
Can't install pybullet on ubuntu！

### ISSUE THREAD

**Issue by JobSmith** [bulletphysics/bullet3#1988]
This is pip install:
![image](https://user-images.githubusercontent.com/15700681/48309735-00ced480-e5bb-11e8-8260-e88a5b3d2434.png)

And this is easy_install
![image](https://user-images.githubusercontent.com/15700681/48320810-6d4be100-e658-11e8-96c1-a97f89f7cbc8.png)

**Comment by JobSmith** [comment]
I find it can be installed with conda venv, but can not with virtualenv!

**Comment by erwincoumans** [comment]
We use Ubuntu all the time (14.04, 16.04 and 18.04) and never seen any of those issues. Odd, but we cannot support all possible combinations. Never tried virtualenv.
You may want to just download/checkout Bullet source code and in the root run 
~~~~~~~~~~
sudo python setup.py install
python3 setup.py install --user
~~~~~~~~~~
