### ISSUE TITLE
Build bullet3 without building examples?

### ISSUE THREAD

**Issue by Centribo** [bulletphysics/bullet3#1989]
Currently I'm building bullet3 by running:
```
cd build3
./premake4_linux64 --double gmake
cd gmake
make
```
Which makes the bullet3 libraries (all the *.a files) and also builds all the examples. I don't need the examples in the project I am building. Is there a way to not build the examples?

**Comment by erwincoumans** [comment]
You can try using
~~~~~~~~~~~~~~~~
premake4 --no-demos --no-test
~~~~~~~~~~~~~~~~
otherwise, just manually update the premake4 files, see also build3/premake4.lua
