### ISSUE TITLE
[Multithreading] btCollisionDispatcherMt doesn't work with Compound vs Compound

### ISSUE THREAD

**Issue by mburetorp** [bulletphysics/bullet3#2002]
When trying to get multithreading up and running I found that compound vs compound don't collide at all if you use btCollisionDispatcherMt.

The problem appears to be that `algo->getAllContactManifolds(m_manifoldsPtr);` in `btCollisionDispatcherMt::dispatchAllCollisionPairs` never returns any manifolds. Also when I shutdown bullet during this penetration phase I get a crash in `btCollisionDispatcherMt::releaseManifold` since there are no manifolds in the array at that point.

My test scene is a static compound heightfield shape vs a dynamic compound sphere shape. If I remove the wrapper compound from the dynamic sphere it collides just fine.

**Comment by erwincoumans** [comment]
Thanks for the report. Probably best to enable the AABB tree, since there are no volunteers working on this. Or fix it and consider a pull request. Thanks!
