### ISSUE TITLE
Crash In Running App_BulletExampleBrowser_vs2010_debug.exe

### ISSUE THREAD

**Issue by yangxiaopo** [bulletphysics/bullet3#2003]
In File bullet3\examples\OpenGLWindow\GLRenderToTexture.cpp
void GLRenderToTexture::init(int width, int height, GLuint textureId, int renderTextureType)
glFramebufferTexture(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, textureId, 0);

![image](https://user-images.githubusercontent.com/16287565/48927176-f7c0fa00-ef0e-11e8-9184-3dce3ee46613.png)
![image](https://user-images.githubusercontent.com/16287565/48927187-03acbc00-ef0f-11e8-8508-4f573cd57810.png)
thank you, please ;)

**Comment by yangxiaopo** [comment]
may be my opengl error?

**Comment by yangxiaopo** [comment]
![image](https://user-images.githubusercontent.com/16287565/48927279-8d5c8980-ef0f-11e8-8267-491777430d73.png)

**Comment by erwincoumans** [comment]
Upgrade your GPU drivers, or add a proper discrete GPU in your machine.

**Comment by yangxiaopo** [comment]
ok
