### ISSUE TITLE
Textures for non-mesh surfaces

### ISSUE THREAD

**Issue by abefetterman** [bulletphysics/bullet3#2012]
I'm trying to load a texture onto a URDF file that isn't visually defined as a mesh (the visual element is a Box tag), using loadTexture and changeVisualShape. However, the texture never seems to render in the debug window. Is this the expected behavior? I see the texture if I add it to plane_transparent.

I have also tried adding it to SDF files, with mesh elements, to no avail.

If this is expected behavior, is there an easy way to make simple shapes in URDF with mesh visual elements, so I can get the texture rendered?

Thanks!

Edit: here's an example URDF file:

```
<?xml version="1.0"?>
<robot name="room">
  <link name="floor_link">
    <visual>
      <geometry>
        <box size="6 6 0.5"/>
      </geometry>
      <origin xyz="0 0 -0.25" rpy="0 0 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="6 6 0.5"/>
      </geometry>
      <origin xyz="0 0 -0.25" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="48600"/>
      <inertia ixx="146812.5" ixy="0" ixz="0" iyy="146812.5" iyz="0" izz="291600"/>
      <origin xyz="0 0 -0.25" rpy="0 0 0"/>
    </inertial>
    <contact>
      <lateral_friction value="1"/>
    </contact>
  </link>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
</robot>
```

**Comment by erwincoumans** [comment]
See https://github.com/bulletphysics/bullet3/blob/master/data/cube.urdf
The visual shape has a Wavefront obj with textures, while the collision shape is a non-mesh box.

**Comment by abefetterman** [comment]
@erwincoumans Creating the cube.obj and cube.mtl are significant extra steps, but I guess there is no way to anchor the texture without using an obj mesh, so this is expected behavior? It would just be nice to have a simpler single file format.

**Comment by erwincoumans** [comment]
I'll add support for textured cube, sphere and capsule.

**Comment by erwincoumans** [comment]
See https://github.com/bulletphysics/bullet3/pull/2013

**Comment by abefetterman** [comment]
Amazing, I'll be watching for the merge to come through, thanks so much!

**Comment by erwincoumans** [comment]
I just noticed your effort here, adding PyBullet to spinning up.
https://github.com/openai/spinningup
Let me know how that goes, and if I can help :-)

**Comment by erwincoumans** [comment]
Merged. Also, pip install pybullet at version 2.4.0 has the improvement.
