### ISSUE TITLE
btHeightFieldTerrainShape and flipQuadEdges

### ISSUE THREAD

**Issue by christophebeaudet** [bulletphysics/bullet3#2015]
Hi all,
My raycast doesn't succeed to hit my heightfield because all triangles are considered backface (and i do not want my rays to hit backfaces, so this is logic). It seems that flipQuadEdges on the heightfield constructor doesn't really do the job of inverting normals since commit ed42e217b54b1047d9fe47de0bc214ed494dee4e, because the winding order is the same no matter flipQuadEdges is true or false. Am i wrong somewhere ?, or perhaps this is not the purpose of that parameter ? Note that before that commit, the behaviour is "as expected" (at least in my mind) => my raycast will find the heightfield if i construct that heightfield with flipQuadEdges at true, and will not if it's false (backface)
Thx !

**Comment by erwincoumans** [comment]
If you care, add an option for either way and submit a pull request. Or just make a local change in the source code.
