### ISSUE TITLE
globalScaling not available in loadMJCF

### ISSUE THREAD

**Issue by teristam** [bulletphysics/bullet3#2019]
Hi,

In the pybullet quick start guide, it seems to suggest that `globalScaling` is also available for loadMJCF, however it is actually not available. I would suggest to either implement `globalScaling` for loadMJCF or to correct the quickstart guide to avoid confusion.

Thanks!

**Comment by erwincoumans** [comment]
Thanks for the report.
Updated the [PyBullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#). 
~~~~~~~~~~~
globalScaling is supported for SDF and URDF, not for MJCF.
~~~~~~~~~~~
It should be easy to add, in case someone wants to give it a try (MJCF shares the same code path as SDF, URDF).
