### ISSUE TITLE
btGjkEpaPenetrationDepthSolver::calcPenDepth does try to normalize zero length vector

### ISSUE THREAD

**Issue by fredUmlaut** [bulletphysics/bullet3#2021]
In the file NarrowPhaseCollision\btGjkEpaPenetrationDepthSolver.cpp
function btGjkEpaPenetrationDepthSolver::calcPenDepth
a division by zero will occur in the guess vector part when the origin of both object is the same
(for instance this could happen when one of the object has no collision response).

btVector3 guessVectors[] = {
		btVector3(transformB.getOrigin() - transformA.getOrigin()).normalized(), //division by zero!
		btVector3(transformA.getOrigin() - transformB.getOrigin()).normalized(), //division by zero!

**Comment by erwincoumans** [comment]
Thanks for the report. Let's use safeNormalize instead:
https://github.com/bulletphysics/bullet3/commit/7ce9ad23fb1dc3468c9ed3c443660e652f28326d
