### ISSUE TITLE
Pybullet Env gym update

### ISSUE THREAD

**Issue by araffin** [bulletphysics/bullet3#2025]
Hello,

I have started using pybullet envs to complete the [rl baselines zoo](https://github.com/araffin/rl-baselines-zoo) (a collection of pretrained agents), however the envs seems to follow the *old* gym interface and yields deprecation warnings.
Also, for some environments, it is not possible to render them.
Are you interested in a PR that solve those two issues ?

EDIT: I can also add an example of how to train an agent using [stable-baselines](https://github.com/hill-a/stable-baselines) which is much easier than original openai baselines.

**Comment by araffin** [comment]
Ok, i'll work on that at the beginning of next year ;)

**Comment by erwincoumans** [comment]
Thanks! I haven't tested it, since the Gym API seems not stable...
