### ISSUE TITLE
Resetting joint velocity as well as joint positions using resetJointState()

### ISSUE THREAD

**Issue by aravindsiv** [bulletphysics/bullet3#2027]
I'm using the `b3RobotSimulatorClientAPI` to simulate my robot. I noticed that while pybullet's `resetJointState` allows for the user to specify both the target position and target velocity for the joint, `b3RobotSimulatorClientAPI::resetJointState` allows for only specifying the target position, despite the availability of `b3CreatePoseCommandSetJointVelocity` inside `PhysicsClientC_API.cpp`. 

My question is: is there a reason for `b3RobotSimulatorClientAPI` not exposing this functionality? If not, how would I go about providing a set of target velocities for all my joints?

**Comment by erwincoumans** [comment]
The b3RobotSimulatorClientAPI is some example code that isn't kept up-to-date with all features of the underlying C API. It should be easy to add the missing functionality, if you know some C/C++. The project relies on volunteers/contributors, so if you add it, please consider filing a pull request.
