### ISSUE TITLE
EGL renderer plus urdfs with multiple visual elements in a single link render incorrectly

### ISSUE THREAD

**Issue by trevorablett** [bulletphysics/bullet3#2029]
When running the egl renderer with a urdf that has multiple visual elements in a single link (e.g. table/table.urdf in the pybullet_data folder), the object doesn't render properly. According to the [urdf spec](http://wiki.ros.org/urdf/XML/link), this should be supported. Using the testrender_egl.py file with pybullet.loadURDF("table/table.urdf") added, this is what I get with the egl renderer:

![selection_233](https://user-images.githubusercontent.com/11758028/50253903-07224e80-03ba-11e9-93c7-7950619a0a86.png)

And this is what I get when I comment out the egl renderer lines:

![selection_232](https://user-images.githubusercontent.com/11758028/50253924-186b5b00-03ba-11e9-843a-982753c96b5e.png)

A temporary workaround is modifying the urdf so that every link has just a single visual element like so:

```
<link name="leg1">
    <visual>
      <origin rpy="0 0 0" xyz="-0.65 -0.4 0.29"/>
      <geometry>
      <mesh filename="table.obj" scale="0.1 0.1 0.58"/>
      </geometry>
    <material name="framemat0"/>   
    </visual>
  </link>

<joint name="table_to_l1" type="fixed">
    <parent link="baseLink"/>
    <child link="leg1"/>
    <origin xyz="0 0 0"/>
  </joint>
```

After doing that, you get what you expect:
![selection_234](https://user-images.githubusercontent.com/11758028/50254201-3a191200-03bb-11e9-98d0-c20964860988.png)

**Comment by erwincoumans** [comment]
Odd, this doesn't happen with the CPU renderer (TinyRenderer) and the OpenGL renderer. The EGL renderer is based on the OpenGL renderer, but some conversion code is different, which may cause this.

**Comment by erwincoumans** [comment]
The EGL renderer is low priority and since there aren't volunteers to improve it, let's stick with your suggested workaround for now. It could be due to the scaling of different visual shapes as well.
Thanks for the report!
