### ISSUE TITLE
A strange problem

### ISSUE THREAD

**Issue by pyni** [bulletphysics/bullet3#2035]
Hi, i am working on a grasping problem with pybullet.
However, we the object is grasped by the gripper, the object will rotate itself and fall down. This is very strange:
![image](https://user-images.githubusercontent.com/18031767/50499455-c6df6200-0a84-11e9-86f6-c39a3788800c.png)
 ![image](https://user-images.githubusercontent.com/18031767/50499493-f7270080-0a84-11e9-892a-3dfe4c49ab36.png)
![image](https://user-images.githubusercontent.com/18031767/50499506-1756bf80-0a85-11e9-8ee7-eb31ac09c081.png)
![image](https://user-images.githubusercontent.com/18031767/50499517-276e9f00-0a85-11e9-89e7-adf01fc0f920.png)
![image](https://user-images.githubusercontent.com/18031767/50499537-453c0400-0a85-11e9-80b1-d4fea69811bb.png)

Why???
I have set the friction. Any suggestions please?

**Comment by erwincoumans** [comment]
Some tips: try using box collision shapes (in case you are using meshes/convex hulls)
use a much higher number of solver iterations
use a smaller time step
What are the friction coefficients for gripper and box? lateral friction, rolling friction and spinning friction?
What are the masses of the gripper and box?
How is the gripper actuated? position control, velocity control or force/torque control?
Try using smaller forces (position and velocity control has a maximum force field)

**Comment by pyni** [comment]
OK，thanks a lot.
I will try it.
