### ISSUE TITLE
[pybullet] numpy array not accepted in createMultiBody; missing input parameters in createVisualShapeArray

### ISSUE THREAD

**Issue by lauamos1116** [bulletphysics/bullet3#2045]
**_Numpy_** array are generally accepted as inputs of function _createMultiBody_, even for _linkOrientations_.
Except _linkInertialFrameOrientations_, for examples:

```
linkInertialFrameOrientations = [[0., 0., 0., 1.], [0., 0., 0., 1.]] # OK
linkInertialFrameOrientations = np.array([[0., 0., 0., 1.], [0., 0., 0., 1.]]) # exit code -1073741819 (0xC0000005)
linkInertialFrameOrientations = (np.repeat([[0., 0., 0., 1.]], 2, 0)).tolist() # OK
linkInertialFrameOrientations = (np.repeat([[0., 0., 0., 1.]], 2, 0)) # exit code -1073741819 (0xC0000005)
```

------------------------
on the other hand,
input parameters _specularColors_ is missing for function _createVisualShapeArray_
`TypeError: 'specularColors' is an invalid keyword argument for this function`
while keyword exists in function _createVisualShape_ (specularColor)

Please let me know if i make any mistake. Thanks

**Comment by erwincoumans** [comment]
Indeed, we don't support numpy for all APIs. Only pybullet.getCameraImage optionally returns the output as numpy, to avoid copying millions of pixels between C and Python. Adding numpy support doesn't likely happen anytime soon, so the user has to perform the conversion.
