### ISSUE TITLE
Strange collision issue

### ISSUE THREAD

**Issue by DSysdev** [bulletphysics/bullet3#2056]
Hi,

I encountered a problem with collision detection when applying translation after scaling to the object center of mass. Applying the translation only after setting the initial box shape dimensions to the scaling I want works correctly.

Case1: Box shape size 1 -> apply scaling -> apply translation -> update aabb -> contact test = negative
Case2: Box shape scale size -> apply translation -> update aabb -> contact test = positive

What is strange is that the final vertices are the same in both cases.

Any idea what might be the issue?

Many Thanks!

**Comment by erwincoumans** [comment]
A simple reproduction case is needed, preferably in example browser. Before you modify an object, remove it from the world. Please reopen with repro case.
