### ISSUE TITLE
How to do simulation of flexible object in pybullet

### ISSUE THREAD

**Issue by houliwei** [bulletphysics/bullet3#2057]

**Comment by houliwei** [comment]
Can pybullet model a flexible object with certain stiffness ？

**Comment by erwincoumans** [comment]
Some people used the deformable simulation in PyBullet, see https://sites.google.com/view/sim-to-real-deformable
We don't have many resources for this, so we focus on the rigid/multibody/collision detection parts.

**Comment by erwincoumans** [comment]
You can also use createConstraint with a fixed constraint using limited force to mimic soft constraints.
See the constraint.zip example here: https://github.com/bulletphysics/bullet3/issues/2100#issuecomment-461621661

**Comment by DanielTakeshi** [comment]
@houliwei  We have been able to use deformables in PyBullet in this recent work: https://berkeleyautomation.github.io/bags/
