### ISSUE TITLE
Building bullet for android ndk

### ISSUE THREAD

**Issue by soyCaptain** [bulletphysics/bullet3#2060]
Hello,
I've been trying to build bullet as a static library on android for the past couple of days. But I've had a lot of difficulty in finding a way to compile it with the ndk. 
I successfully compiled it into libs for windows. Used cmake to create a solution for visual studio and that worked flawlessly.

But for android I'm a bit lost on how it should work as there are few to no documents on how to do it, either on the repository or online. I'm also trying as much as possible to avoid just including the sources into my project.

The premake tools don't seem to target android so I'm at a loss.

Any tips?
Many Thanks

**Comment by erwincoumans** [comment]
"I'm also trying as much as possible to avoid just including the sources into my project."

This is the easiest and recommended way.
