### ISSUE TITLE
The packaging of the bulletRobotics lacks the installation of headers

### ISSUE THREAD

**Issue by MaximilienNaveau** [bulletphysics/bullet3#2061]
The packaging of the bulletRobotics lacks the installation of headers.
This prevent the use of the bulletRobotics and its urdf parsers from C++.

I will create a pull request in order to modify this.

**Comment by MaximilienNaveau** [comment]
I created a pull request that fix the issue. This is not the perfect solution. The ideal solution being to move the bullet robotics in the src folder.
https://github.com/bulletphysics/bullet3/pull/2063

**Comment by erwincoumans** [comment]
Thanks for the help!
