### ISSUE TITLE
btAssert-macro is broken, as it accidentally specifies a user-defined literal

### ISSUE THREAD

**Issue by haikarainen** [bulletphysics/bullet3#2066]
This breaks static code generation in my project (using libclang with the -cl driver)

**Comment by haikarainen** [comment]
My PR seems to fix the issues in my use-case, but could definitely use some review either way

**Comment by haikarainen** [comment]
@erwincoumans ""_ is syntax for userdefined literals. Clang errors out on it.

**Comment by erwincoumans** [comment]
Thanks, we never ran into this before.
