### ISSUE TITLE
Start a TCPServer

### ISSUE THREAD

**Issue by proboticks** [bulletphysics/bullet3#2069]
Hi, I am currently using pybullet for my research work. It's been amazing so far. I have been trying to start a TCP server so that I can connect to it from another computer. However, I am kind of stuck on this for the past few days. I see the C++ example at bullet3/examples/SharedMemory/tcp/main.cpp. 

Is it possible to start a TCP server from pybullet?

Thank you for any help on this matter.

**Comment by erwincoumans** [comment]
One way:
~~~~~~~~~~
python3
import pybullet as p
p.connect(p.GUI_SERVER) #or SHARED_MEMORY_SERVER)

In a different terminal on same machine, compile and run
App_PhysicsServerSharedMemoryBridgeTCP_gmake_x64_release
~~~~~~~~~~~~~

Then on another machine, but first for testing on same machine, use:
~~~~~~~~~~~~~
python3
import pybullet as p
p.connect(p.TCP)
p.loadURDF("plane.urdf")
~~~~~~~~~~~~~

Then on the original server, you can use 'p.syncBodyInfo' and 'getNumBodies' should report 1.

You cannot start TCP_SERVER from pybullet at the moment. Would be a nice simplication indeed.
Good luck,

**Comment by proboticks** [comment]
Thank you for the quick reply Erwin.
Cheers.
