### ISSUE TITLE
Licensing questions

### ISSUE THREAD

**Issue by DAP-DarkneSS** [bulletphysics/bullet3#207]
Hello.
Bullet has been recently promoted to the official openSUSE distribution and some questions were asked:

> Ciaran Farrell 2014-08-01 10:25:21 EEST 
> These files: 
> bullet-2.82-r2704/Extras/CUDA/cutil_gl_error.h 
> bullet-2.82-r2704/Extras/CUDA/radixsort.cu 
> bullet-2.82-r2704/Extras/CUDA/radixsort.cuh 
> bullet-2.82-r2704/Extras/CUDA/radixsort_kernel.cu 
> bullet-2.82-r2704/Extras/sph/fluids/radixsort.cu 
> bullet-2.82-r2704/Extras/sph/fluids/radixsort.cuh 
> bullet-2.82-r2704/Extras/sph/fluids/radixsort_kernel.cu 
> bullet-2.82-r2704/src/vectormath/sse/mat_aos.h // here seems  that Ciaran is wrong
> bullet-2.82-r2704/src/vectormath/sse/mat_aos.h // the same as the previous one

are licensed under this proprietary NVIDIA license: 
/\* 
- Copyright 1993-2006 NVIDIA Corporation. All rights reserved. 
- 
- NOTICE TO USER: 
- 
- This source code is subject to NVIDIA ownership rights under U.S. and 
- international Copyright laws. 
- 
- NVIDIA MAKES NO REPRESENTATION ABOUT THE SUITABILITY OF THIS SOURCE 
- CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" WITHOUT EXPRESS OR 
- IMPLIED WARRANTY OF ANY KIND. NVIDIA DISCLAIMS ALL WARRANTIES WITH 
- REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED WARRANTIES OF 
- MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE. 
- IN NO EVENT SHALL NVIDIA BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, 
- OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS 
- OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE 
- OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE 
- OR PERFORMANCE OF THIS SOURCE CODE. 
- 
- U.S. Government End Users. This source code is a "commercial item" as 
- that term is defined at 48 C.F.R. 2.101 (OCT 1995), consisting of 
- "commercial computer software" and "commercial computer software 
- documentation" as such terms are used in 48 C.F.R. 12.212 (SEPT 1995) 
- and is provided to the U.S. Government only as a commercial end item. 
- Consistent with 48 C.F.R.12.212 and 48 C.F.R. 227.7202-1 through 
- 227.7202-4 (JUNE 1995), all U.S. Government End Users acquire the 
- source code with only those rights set forth herein. 
  */

These files: 
bullet-2.82-r2704/Extras/sph/common/glext.h 
bullet-2.82-r2704/Glut/GL/glext.h 
bullet-2.82-r2704/Glut/GL/glxext.h 
bullet-2.82-r2704/Glut/GL/wglext.h

are SGI FreeB 1.1 licensed (not OSI)

This file: 
bullet-2.82-r2704/Extras/CUDA/cutil_math.h

does not allow modification: 
 This source code is subject to NVIDIA ownership rights under U.S. and 
- international Copyright laws. Users and possessors of this source code 
- are hereby granted a nonexclusive, royalty-free license to use this code 
- in individual and commercial software.

Finally, bullet-2.82-r2704/Extras/Serialize/makesdna/makesdna.cpp appears to 
have a GPL license, which is completely incompatible with the licenses above.

Perhaps it makes sense to contact upstream to sort this out.

> End of quote.

So I purged Extras & Glut dirs from the tarball but another question was why I hadn't reported this issue to upstream so I do it now.
External links:
[1] https://bugzilla.novell.com/show_bug.cgi?id=889897 // seems to be hidden =(
[2] https://build.opensuse.org/request/show/243407

**Comment by benelot** [comment]
So it can be closed, 2.83 is out!

**Comment by erwincoumans** [comment]
closing out-of-date issues.
