### ISSUE TITLE
rayTestBatch not in local coordinates

### ISSUE THREAD

**Issue by GerardMaggiolino** [bulletphysics/bullet3#2078]
The documentation of rayTestBatch states: 

| Parameters | ... | ... | ... |
| --- | --- | --- | ---| 
| optional | parentObjectUniqueId | int | ray from/to is in local space of a parent object |
| optional | parentLinkIndex | int | ray from/to is in local space of a parent object |

However, when using rayTestBatch, it appears that rayFromPositions and rayToPositions are in absolute world coordinates rather than the coordinates of parentObjectUniqueId and parentLinkIndex. This is not the case with addUserDebugLine, which properly renders ray casts by the parentObjectUniqueId coordinates. 

Segments of my code are below: 

```python
        # Initialize start and end of rays given params
        self.num_rays = math.ceil(int(self.view_range / 5) / self.num_seg) * \ 
            self.num_seg
        starting_degree = -(self.view_range - self.view_range / 2) + 90
        change_degree = self.view_range / self.num_rays
        self.start_rays = [ 
            [self.min_lidar_range
             * math.sin(math.radians(starting_degree + i * change_degree)),
             self.min_lidar_range
             * math.cos(math.radians(starting_degree + i * change_degree)),
             0.05] for i in range(self.num_rays)]
        self.end_rays = [ 
            [self.lidar_range * 
             math.sin(math.radians(starting_degree + i * change_degree)),
             self.lidar_range * 
             math.cos(math.radians(starting_degree + i * change_degree)),
             0.05] for i in range(self.num_rays)]
```
The above code properly sets a number of ray start and end points in an arc around the origin. 

```python 
        for s, e in zip(self.start_rays, self.end_rays):
            p.addUserDebugLine(s, e, [1, 0, 0], parentObjectUniqueId=self.car, 
                parentLinkIndex=9, lifeTime=0.3)
```

The above code successfully creates that arc of ray casts, which moves when the car they're attached to with parentObjectUniqueID moves. 

```python
        batch = p.rayTestBatch(self.start_rays, self.end_rays, self.car, 
            9, self.client)
```

The above code creates rays that are glued to the origin, even if the car with parentObjectUniqueID moves. Is this intended behavior? This could be alleviated by adding the position of the parent link to each ray start and end, but that operation seems costly for a large number of rays and constant movement. Additionally, the documentation is a bit misleading. 

Please let me know if I'm making a mistake with this! Thank you :). I would be happy to add working code that can be run demonstrating the problem if this would be helpful.

**Comment by erwincoumans** [comment]
It should work fine, make sure to name your arguments, since the 3rd argument is the number of threads.
~~~~~~~~~~~~~
results = p.rayTestBatch(rayFrom,rayTo,numThreads, parentObjectUniqueId=car, parentLinkIndex=hokuyo_joint)
~~~~~~~~~~~~~~

See a working example in [f10_racecar.py](https://github.com/bulletphysics/pybullet_robots/blob/master/f10_racecar.py)
