### ISSUE TITLE
Device error compiling mprKernelsCL program on MacPro with D500 

### ISSUE THREAD

**Issue by gryphun** [bulletphysics/bullet3#208]
After getting this error in my own code, I build the demos and get the same error.  It is non-intermittent and happens every time.

This is a a hex-core mac pro with a pair of AMD D500s

  Model Name:   Mac Pro
  Model Identifier: MacPro6,1
  Processor Name:   6-Core Intel Xeon E5
  Processor Speed:  3.5 GHz
  Number of Processors: 1
  Total Number of Cores:    6
  L2 Cache (per Core):  256 KB
  L3 Cache: 12 MB
  Memory:   16 GB

  Chipset Model:    AMD FirePro D500
  Type: GPU
  Bus:  PCIe
  Slot: Slot-2
  PCIe Lane Width:  x16
  VRAM (Total): 3072 MB
  Vendor:   ATI (0x1002)
  Device ID:    0x679e
  Revision ID:  0x0000
  ROM Revision: 113-C3861J-687
  gMux Version: 4.0.11 [3.2.8]
  EFI Driver Version:   01.00.687

/App_Bullet3_OpenCL_Demos_clew_gmake 
main startVendor: ATI Technologies Inc.
Renderer: AMD Radeon HD - FirePro D500 OpenGL Engine
Version: 4.1 ATI-1.24.35
## GLSL: 4.10

started GwenUserInterfaceinit fontsclewInit succesfull using /System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL
compiling kernel copyTransformsToVBOKernel ready. 
b3Warning[../../src/Bullet3OpenCL/Initialize/b3OpenCLUtils.cpp,816]:
Cannot open cached binary: cache/mpr.cl.AMD Radeon HD - FirePro D500 Compute Engine.1.2 (Jun 10 2014 22:41:23).bin
b3Error[../../src/Bullet3OpenCL/Initialize/b3OpenCLUtils.cpp,92]:
Error: [CL_DEVICE_NOT_AVAILABLE] : OpenCL Error : Error: Build Program driver returned (517)
Assertion failed: (0), function MyFatalBreakAPPLE, file ../../src/Bullet3OpenCL/Initialize/b3OpenCLUtils.cpp, line 93.
Abort trap: 6

If I check CL_DEVICE_AVAILABLE, the device comes back as being available.

**Comment by davidbuzz** [comment]
I got the same error today.   :-)

**Comment by erwincoumans** [comment]
closing out-of-date issues. OpenCL is not supported.
