### ISSUE TITLE
SSE Bit masks can fail on GCC 7

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [bulletphysics/bullet3#2080]
https://pybullet.org/Bullet/BulletFull/btVector3_8h_source.html

You use `btvMzeroMask` to flip sign bits in floats.

GCC 7 aggressively optimizes, and can actually turn that mask into (0.f,0.f,0.f,0.f) together with `ffast-math`.

I've had this problem myself in my engine so I used `castps_si128` etc. and an integer mask to make sure that never happens.
https://github.com/buildaworldnet/IrrlichtBAW/commit/32cb056ea52653c594c398b6da16932490f30a9a#diff-97ab97f938d7c387fc5c203a6c9078a8R495

**Comment by erwincoumans** [comment]
Thanks for the report. Do you have some patch for this?

**Comment by devshgraphicsprogramming** [comment]
I think one would have to trawl through the source very carefully for any usage of `_mm_BITWISEOPNAME_ps`

**Comment by erwincoumans** [comment]
Well, if gcc messes SSE, just disable SSE. The gains are not that big anyway.

**Comment by devshgraphicsprogramming** [comment]
We'll try to provide you with a fix and a Pull Request.
