### ISSUE TITLE
possible memory leak in removeBody

### ISSUE THREAD

**Issue by zi-w** [bulletphysics/bullet3#2086]
[Code to reproduce the problem](https://github.com/zi-w/zi-w.github.io/blob/master/scripts/pybullet_memory_test.zip)

Issue description: The memory usage gradually increases if we use removeBody to remove the bodies that are generated (see test_pybullet_mem.py). This problem gets alleviated when using resetSimulation, but in test_pr2_mem.py, even if we call resetSimulation, the memory usage still piles up quite quickly.

**Comment by erwincoumans** [comment]
In test_pybullet_mem.py, this is expected: the memory of createVisualShape and p.createCollisionShape is not released by a 'removeBody'. We don't have a removeVisualShape/removeCollisionShape, only resetSimulation will release that memory.

I'll have to check what is happening with the second case, thanks for the report!
