### ISSUE TITLE
Building with PhysX 4.0

### ISSUE THREAD

**Issue by makarl** [bulletphysics/bullet3#2090]
When building with PhysX support enabled using the following command:

```./premake4_linux64 --double --enable_physx gmake```

It fails while searching for `bullet3/src/physx/premake4.lua`.

The PhysX repository from https://github.com/NVIDIAGameWorks/PhysX/tree/4.0/physx was cloned into the directory `bullet3/src/physx`

**Comment by erwincoumans** [comment]
You can also copy this zipfile in the Bullet/src folder, it has both premake4.lua and all PhysX source code.
[PhysX.zip](https://github.com/bulletphysics/bullet3/files/2861420/PhysX.zip)

**Comment by erwincoumans** [comment]
Here is a branch with also PhysX support in setup.py setuptools
https://github.com/erwincoumans/bullet3/tree/physx

**Comment by frk2** [comment]
Yay the setup.py worked! Many thanks

**Comment by makarl** [comment]
Also worked for me, but I had to add the "-std=c++11" option when compiling under Linux (https://github.com/makarl/bullet3/commit/4c05f3844da03d6d871a437d373e89a8c651f129)

**Comment by floodsung** [comment]
it is unable to get jointinfo under this physx 4.1 version, how to solve this problem?

**Comment by floodsung** [comment]
What I get from getJointInfo() method is "not available"

**Comment by syslot** [comment]
> What I get from getJointInfo() method is "not available"

Do you ever test the api with PhysX4.0  backend?

**Comment by erwincoumans** [comment]
PhysX backend is very preliminary and only a few methods are hooked up. Either contribute or ignore, no support provided.

**Comment by syslot** [comment]
> What I get from getJointInfo() method is "not available"

Hi, floodsung. 

I fixed some problems when I try to use the PhysX as the backend of pybullet and you can try build from by repo if you are interested in another engine. :)
