### ISSUE TITLE
URDF Passive Object Collision Support

### ISSUE THREAD

**Issue by josiahls** [bulletphysics/bullet3#2094]
I am currently making Mujoco style environments to test and want visual targets, that have detectable collisions, but allow objects to pass through:

I am currently making an edit of the cube.urdf's for this, but do not have a solution. Below is an example. The red cube is a "target" and I am just checking if the other objects explode if they are inside it (which they do) I tried setting concave="yes", but above still happens.

An easy fix is simply removing the collision box I think, but then that means I lose collision detection, which for a target knowing when a collision happens to it is pretty important.

![image](https://user-images.githubusercontent.com/19930483/52170131-a4d7a000-2712-11e9-89dc-5400571ba5f0.png)

**Comment by erwincoumans** [comment]
You can disable collision detection and still perform a 'getClosestPoints' query.

~~~~~~~~~~
import pybullet as p
import time
p.connect(p.GUI)
planeId = p.loadURDF("plane.urdf", useMaximalCoordinates=False)
cubeId = p.loadURDF("cube_collisionfilter.urdf", [0,0,3], useMaximalCoordinates=False)

collisionFilterGroup = 0
collisionFilterMask = 0
p.setCollisionFilterGroupMask(cubeId,-1,collisionFilterGroup,collisionFilterMask)

#enableCollision = 1
#p.setCollisionFilterPair(planeId, cubeId,-1,-1,enableCollision )

p.setRealTimeSimulation(1)
p.setGravity(0,0,0)
while (p.isConnected()):
	time.sleep(1./240.)
	pts = p.getClosestPoints(planeId, cubeId, distance=100)
	print("distance=",pts[0][8])

~~~~~~~~~~
