### ISSUE TITLE
get base URDF link frame position problem

### ISSUE THREAD

**Issue by xinsongyan** [bulletphysics/bullet3#2096]
In pybullet,  getBasePositionAndOrientation() gives back the position of CoM of base link, when the URDF base link frame is needed, I have to do local transformation by myself. 

The getLinkState() could be another way to get the URDF base link frame information, but it seems that link index -1 is not accepted (for some other function it stands for base link), What is the consideration behind this?

**Comment by rubdub** [comment]
I had this issue as well. getLinkState(robotId, -1, 1) gives an error

**Comment by erwincoumans** [comment]
Yes, getLinkState only works for child links that are connected by a joint to the parent.

For the base, you need to call getBasePositionAndOrientation, which provides the position and orientation of the center of mass. You can use getDynamicsInfo(bodyUniqueId,-1) to get more information about the base, such as the localInertialFrame. Then use pybullet.multiplyTransforms to get the link transform of the base.
