### ISSUE TITLE
GUI Client connected to a TCP Server

### ISSUE THREAD

**Issue by proboticks** [bulletphysics/bullet3#2108]
I have a TCP Server running on a remote machine and I can connect to it from a local machine using:

`p.connect(p.TCP, "ip_address", "port").`

However, I couldn't quite figure out how to start a GUI Client that is connected to my remote TCP server.

Any help on this would be much appreciated.

**Comment by erwincoumans** [comment]
At the moment, the GUI always happens at the server side. It is not clear if/when this is going to change, so let's close this issue.
