### ISSUE TITLE
Batched Raycasting on the GPU in bullet to avoid RTX / walled gardens

### ISSUE THREAD

**Issue by BluePrintRandom** [bulletphysics/bullet3#2109]
Is it possible to do a batched raycast on the GPU and leave the data in a buffer to overlay in realime?

this would allow real time raytracing that is hardware agnostic ?
 
rayhitUV -> plot ?

**Comment by erwincoumans** [comment]
If you want OpenCL accelerated ray intersections, use Radeon Rays:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK
