### ISSUE TITLE
Bullet3 messing around with embedded python.

### ISSUE THREAD

**Issue by TomerZeitune** [bulletphysics/bullet3#2112]
For some reason bullet3 is messing around with embedded python in cpp. I added bullet to my game engine and after doing this 
`
	btDefaultCollisionConfiguration * collisionConfiguration = new
		btDefaultCollisionConfiguration();
	btCollisionDispatcher * dispatcher = new btCollisionDispatcher(collisionConfiguration);
	btBroadphaseInterface * overlappingPairCache = new btDbvtBroadphase();
	btSequentialImpulseConstraintSolver * solver = new btSequentialImpulseConstraintSolver;
	btDiscreteDynamicsWorld * dynamicsWorld = new btDiscreteDynamicsWorld(dispatcher,
		overlappingPairCache, solver, collisionConfiguration);`
Simple startup code I can no longer import my cpp python module and run embedded python with boost::python. Any symbol I can define to tell bullet not to mess around with python ? 
when I delete this piece of code or write only
`	btCollisionDispatcher * dispatcher = new btCollisionDispatcher(collisionConfiguration);` 
everything is working perfectly.

**Comment by erwincoumans** [comment]
There must be some other issue, Bullet is just plain C++ with barely any dependencies. Good luck tracking it down.
