### ISSUE TITLE
Camera info doesn't match simulation

### ISSUE THREAD

**Issue by lpdon** [bulletphysics/bullet3#2119]
Hello!

While trying some simulations and capturing frames using the humanoid_fixed model ("mjcf/humanoid_fixed.xml") I am having the problem that the image captured by the virtual camera doesn't match what I am simulating. Is this some rendering problem related to MCJF? The URDF and SDF models I tested look perfectly fine (for example the KUKA arm in the picture).

![image](https://user-images.githubusercontent.com/7738765/53047838-9e2b8580-3493-11e9-972e-5273b47cf41a.png)

**Comment by erwincoumans** [comment]
MJCF support is rudimentary, but its code path is shared with URDF.
Can you provide a simple reproduction case, PyBullet file?

**Comment by lpdon** [comment]
```
import pybullet as p
import time
import pybullet_data

physicsClient = p.connect(p.GUI)
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.setGravity(0,0,-10)
planeId = p.loadURDF("plane.urdf")

kuka = p.loadSDF("kuka_iiwa/kuka_with_gripper.sdf")[0]
p.resetBasePositionAndOrientation(kuka, [1.0, 0, 0], p.getQuaternionFromEuler([0,0,0]))

human = p.loadMJCF("mjcf/humanoid_fixed.xml",flags = p.URDF_USE_SELF_COLLISION_EXCLUDE_ALL_PARENTS)[0]

for i in range (10000):
    try:
      image = p.getCameraImage(200, 200)
      p.stepSimulation()
      time.sleep(1./240.)
    except KeyboardInterrupt:
      break

p.disconnect()
```

This code is already enough to reproduce it. Using the hardware accelerated camera image does however solve the problem and the camera captures the simulation correctly. Thanks a lot!

**Comment by erwincoumans** [comment]
Thanks, the regression is fixed now. Still, better to use the OpenGL hardware accelerated camera if possible (or EGL plugin)
