### ISSUE TITLE
Function to get pixels information in C++

### ISSUE THREAD

**Issue by shbang91** [bulletphysics/bullet3#2123]
Hello, I am a newbie in Bullet.
I apologize in advance if this would be a dumb question.

I would like to use Bullet simulator for a RGB-D multisensor. I kind of noticed that there are functions written in python getting pixel information, but I don't see any of those functions or related examples written in c++. If you don't mind letting me know about this, could you please give me a reference or examples to look over?

Thank you.

**Comment by erwincoumans** [comment]
This is all written in the example directory.
One way is using BulletRobotics API, which is C++.
If you use premake or cmake to generate your projects, there are some examples under Bullet/examples/RobotSimulator, see App_RobotSimulator. The C++ API uses the same underlying code as PyBullet, based on the C API. Some helper projects are in Extras/BulletRobotics as well.
