### ISSUE TITLE
Cannot load SDF file

### ISSUE THREAD

**Issue by Prakhar005** [bulletphysics/bullet3#2124]
Hello 

I am trying to load an SDF file into the pybullet environment. However, it comes up with the 
"**error: Cannot load SDF file.**"
My code is as follows:

**import pybullet as p
import time
import pybullet_data
physicsClient = p.connect(p.GUI)
p.setAdditionalSearchPath(pybullet_data.getDataPath()) 
p.setGravity(0,0,-10)
planeId = p.loadSDF("plane_stadium.sdf")
boxId = p.loadSDF("free_loop.sdf")

for i in range (3000):
    p.stepSimulation()
    time.sleep(1./240.)    
p.disconnect()**

I have made sure that the files are in the correct directory. 
The **free_loop.sdf file has a closed loop structure** ( wherein the links are connected in a loop)
I wonder, if it is not possible to load an SDF file into pybullet which has a closed structure (unlike the tree structure of URDF format)?
Thank you!

**Comment by erwincoumans** [comment]
You cannot load models with loops indeed. You manually have to close the loop using a constraint, such as point2point constraint or fixed constraint.
