### ISSUE TITLE
[pybullet] rayTestBatch hit with parentObjectUniqueId and debugLine but don't hit without debugline

### ISSUE THREAD

**Issue by mcaniot** [bulletphysics/bullet3#2131]
I get an issue with rayTestBatch. I attached my ray to my robot id and use addUserDebugLine for debugging. The ray found a hit whith this configuration. But when I don't use the function addUserDebugLine, the ray don't hit in the same configuration.

I found a workaround : I create a user debugline attached to my robot and I remove it just after. The ray hit in the same configuration as before.

**Comment by erwincoumans** [comment]
Thanks a lot for the report. The PR with a fix has been applied.
