### ISSUE TITLE
calculateInverseKinematics inaccurate when time step small

### ISSUE THREAD

**Issue by duyhungbkhn** [bulletphysics/bullet3#2140]

**Comment by erwincoumans** [comment]
Please provide a small reproduction case.

**Comment by duyhungbkhn** [comment]
When I use function "calculateInverseKinematics" to keep end effector follow circle trajectory in while loop with time.sleep(0.001), it seem inaccurate than I use bigger time.sleep(0.1). Is that for my computer configuration, is not strong enough to execute this function in high speed?

**Comment by erwincoumans** [comment]
I tried reproducing this with the inverse_kinematics.py example, setting the timestep to 0.001, but it track just fine. Can you look at the attached example, and share your version that shows the issue?

[inverse_kinematics.zip](https://github.com/bulletphysics/bullet3/files/2927544/inverse_kinematics.zip)

**Comment by duyhungbkhn** [comment]
I have used 'setRealTimeSimulation(1)'. This is my case I have problem:
[NadRobot.tar.gz](https://github.com/bulletphysics/bullet3/files/2928822/NadRobot.tar.gz)

**Comment by erwincoumans** [comment]
Use setRealTimeSimulation(0) instead.
