### ISSUE TITLE
How  to know the size of the whole scene？

### ISSUE THREAD

**Issue by zhaoguangyuan123** [bulletphysics/bullet3#2143]
How to know the real scale of the scene from pybullet?
In other words, how can we find the per-pixel size of images from getCameraImage?
Thanks,

**Comment by erwincoumans** [comment]
See [pointCloudFromCameraImage.py](https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/pointCloudFromCameraImage.py)

There is some information that relates pixels to world coordinates
~~~~~~~~~~~~~~
	w = cornersX[i]
	h = cornersY[i]
	rayFrom,rayTo, _= getRayFromTo(w,h)
~~~~~~~~~~~~~~
