### ISSUE TITLE
Peg in hole - collision issue

### ISSUE THREAD

**Issue by AndreaIncertiDelmonte** [bulletphysics/bullet3#2148]
I'm trying to simulate a peg in hole setup with a shaft inserted into a gear but the gear doesn't slide along the shaft and also the system seems unstable regarding collisions.
Here some videos that show current status:
- Expected behavior https://youtu.be/SZ0F8cXkXto 
- Shaft into gear https://youtu.be/xeKfoBjanrs
- Static shaft into gear https://youtu.be/Fc7JTHJMsAc
- Shaft into static gear https://youtu.be/N1-9Notjbm0

I used V-HACD to decompose the meshes, MeshLab to estimate the center of mass and PyBullet for the inertia tensor. In the video above, I used the decomposed mesh for both collision and visual and the shaft ones have also being slightly down scaled.

**Comment by erwincoumans** [comment]
PyBullet uses a small [collision margin of 0.001](https://github.com/bulletphysics/bullet3/blob/master/examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp#L36) (1mm) in all directions, your meshes need to take it into account. Try shrinking the peg a by 2mm on each side.
