### ISSUE TITLE
Units of joint position and velocity

### ISSUE THREAD

**Issue by Prakhar005** [bulletphysics/bullet3#2150]
Hello
I am trying to understand the units of the values returned by the **getJointState()** function. Specifically what are the units of the joint position and joint velocity? Since the documentation says that these are float values, does it mean that these are the magnitudes of the position and velocity vectors of the joint?
Thanks!

**Comment by erwincoumans** [comment]
For revolute joints, joint position is the angle in radians, joint velocity is angular velocity in radians per second. For prismatic joints, it is the joint position in meters, and joint velocity in meters per second.
