### ISSUE TITLE
delete saved states in PyBullet

### ISSUE THREAD

**Issue by zeshiYang** [bulletphysics/bullet3#2163]
Hi,
I use p.saveStates() function to save some states in simulation and I want to delete some of them, however I didn't find any functions can do that, it seems that resetsimulation() will delete all the states saved in the physics engine... How should I cope with that?(I don't want to save states in Disk...) Thank you!

**Comment by erwincoumans** [comment]
Sure, we can add a removeState. If it is urgent for you and you are familiar with C++, you could try adding it yourself. It will touch a few files, pybullet.c for python binding, PhysicsServerCommandProcessor.cpp for the remove and the BulletClientC_Api.h/cpp.

**Comment by erwincoumans** [comment]
Implemented here: https://github.com/bulletphysics/bullet3/pull/2182
