### ISSUE TITLE
dynamic objects shaking issue

### ISSUE THREAD

**Issue by hangoon18** [bulletphysics/bullet3#2165]
Hello My name is Kim.

I'm using Bullet 2.83 version.

before I explain about my issue, watching video is more faster to understand.
https://www.youtube.com/watch?v=e2_DkZp0wt0&feature=youtu.be

as you can see, I stack up several blocks.
but they shaking itself and eventually the block tower falls down....(no interaction forces)

I can't catch the problem.
it would be helpful if you give some help.

Thank you for reading

**Comment by erwincoumans** [comment]
Don't duplicate issues, here you go: https://pybullet.org/Bullet/phpBB3/viewtopic.php?f=9&t=12635&p=41951#p41951
