### ISSUE TITLE
How to get impulse while collision test?

### ISSUE THREAD

**Issue by cgoxopx** [bulletphysics/bullet3#2168]

**Comment by erwincoumansepic** [comment]
After stepSimulation, you can query for all contact points and the impulse is store in the contact points.

**Comment by erwincoumans** [comment]
After stepSimulation, you can query for all contact points and the impulse is store in the contact points.
See an example snippet here:
https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/PhysicsServerCommandProcessor.cpp#L6730

**Comment by shivani1494** [comment]
Hi, can you please expand more?
