### ISSUE TITLE
Lack of Friction between the floor and a Quadruped Robot's legs Simulation

### ISSUE THREAD

**Issue by rubencg195** [bulletphysics/bullet3#2179]
**How can I increase the contact friction between the legs of my robot and the surface of the floor?**

The code for the URDF robot can be seen here:

https://github.com/rubencg195/WalkingSpider_OpenAI_PyBullet/blob/master/src/spider.xml

The code for the controller can be seen here:

https://github.com/rubencg195/WalkingSpider_OpenAI_PyBullet/blob/master/environment/walking-spider/walking_spider/envs/walking_spider_env.py

The results can be seen in the following video link: 

https://www.youtube.com/watch?v=OEox2vI5qN8

![spider](https://raw.githubusercontent.com/rubencg195/WalkingSpider_OpenAI_PyBullet/master/images/spider.gif)

**Comment by erwincoumans** [comment]
Friction is likely fine (you can increase it using p.changeDynamics, the the quickstart guide).
You are using setJointMotorControl2 in POSITION control mode, with a very large force. Try reducing the max force. Alternatively, use PD_CONTROL mode.
