### ISSUE TITLE
Has anything chaged w.r.t. memory management between 2.86 and 2.88?

### ISSUE THREAD

**Issue by spencerkohan** [bulletphysics/bullet3#2181]
I've just updated a project from using 2.86 to 2.88, and suddenly I'm getting `EXEC_BAD_ACCESS` exceptions when using a `btDynamicWorld` instance.  Would there be any reason for this to be the case?

**Comment by erwincoumans** [comment]
I don't recall changes. It could be due to SIMD/SSE usage. Can you build a double-precision build and see if that fixes it? Add #define BT_USE_DOUBLE_PRECISION at the top of src/LinearMath/btScalar.h

**Comment by erwincoumans** [comment]
(closing, please use forums instead and cross the fingers someone helps, or do more digging on your end.)
