### ISSUE TITLE
Premake5 executable doesn't work

### ISSUE THREAD

**Issue by L4ZZA** [bulletphysics/bullet3#2183]
- Download latest bullet3 relese
- Edit "build_visual_studio_without_pybullet_vr.bat" to be like the following
```
cd build3
premake5     --targetdir="../bin" vs2017
start vs2017
PAUSE
```

These fixes still won't work
#1222 
#1223 

Please all premake*.lua scripts to premake5 even if it's  still alpha release it's pretty stable

See attachment with for logs:
[bullet_premake5_log.txt](https://github.com/bulletphysics/bullet3/files/3044309/bullet_premake5_log.txt)

**Comment by erwincoumans** [comment]
Thanks for the note.
We don't have resources for this and premake4 works fine for all our platforms and compilers (Visual Studio 2017 and 2019 convert from older project files just fine, even from 2010 projects).
Unless someone spends the time to convert all projects and options, this is not going to happen.
