### ISSUE TITLE
Is it possible to load a sdf with actor and trajectories like in gazebo? 

### ISSUE THREAD

**Issue by alessiabertugli** [bulletphysics/bullet3#2187]
Hi! I would like to load an animated mesh from gazebo with actor (walk.dae) with a simple sdf file like this:
http://sdformat.org/spec?ver=1.6&elem=actor
http://gazebosim.org/tutorials?tut=actor&cat=build_robot
I was able to load the mesh converting it in obj and collada without polyline (without any movements), but when I put the mesh in actor tag it seems that it can't be loaded.
Is it possible to load a sdf with actor and trajectories like in gazebo?

**Comment by erwincoumans** [comment]
No, we only parse the strict necessary data such as kinematics (joint position), joint limits, mass, collision and visual shape information. PyBullet is usually used to compute animation trajectories using RL.
