### ISSUE TITLE
Problems about getDebugVisualizerCamera()

### ISSUE THREAD

**Issue by pyni** [bulletphysics/bullet3#2194]
Hi, i want to reset the return parameters (width, height, viewMat, projMat, cameraUp, camForward, horizon,vertical, _,_,dist, camTarget) of **p.getDebugVisualizerCamera()** in order to change the view direction of point clouds in file: **pointCloudFromCameraImage.py**.
when I run these codes:
    **base_pos,orn = p.getBasePositionAndOrientation(trayID)
    view_matrix = p.computeViewMatrixFromYawPitchRoll(cameraTargetPosition=base_pos,distance=1.3,yaw=180,pitch=-90,roll=0,upAxisIndex=2)
    proj_matrix =  p.computeProjectionMatrixFOV(fov=60, aspect=float(960)/720,nearVal=0.1, farVal=100.0)
    (_, _, px, _, _) =  p.getCameraImage(
        width=960, height=720, viewMatrix=view_matrix,
        projectionMatrix=proj_matrix, renderer= p.ER_BULLET_HARDWARE_OPENGL)**
it shows:
![image](https://user-images.githubusercontent.com/18031767/55784226-b490ad80-5ae2-11e9-8ab4-c56704e64e94.png)
Then i run **p.getDebugVisualizerCamera()**, it shows:
**(1024, 768, (0.642787516117096, -0.4393851161003113, 0.6275069713592529, 0.0, 0.766044557094574, 0.36868777871131897, -0.5265407562255859, 0.0, -0.0, 0.8191521167755127, 0.5735764503479004, 0.0, 2.384185791015625e-07, 2.384185791015625e-07, -5.000000476837158, 1.0), (0.7499999403953552, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -1.0000200271606445, -1.0, 0.0, 0.0, -0.02000020071864128, 0.0), (0.0, 0.0, 1.0), (-0.6275069713592529, 0.5265407562255859, -0.5735764503479004), (17141.001953125, 20427.853515625, -0.0), (-8787.701171875, 7373.75537109375, 16383.041015625), 50.0, -35.0, 5.0, (0.0, 0.0, 0.0))**

Then i run following order to reset the parameters:
**p.resetDebugVisualizerCamera(1.3,180,-90,base_pos)**
Then i run **p.getDebugVisualizerCamera()**, it returns:
**(1024, 768, (nan, nan, -0.0, 0.0, nan, nan, -0.0, 0.0, nan, nan, 1.0, 0.0, nan, nan, -1.2999999523162842, 1.0), (0.7499999403953552, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -1.0000200271606445, -1.0, 0.0, 0.0, -0.02000020071864128, 0.0), (0.0, 0.0, 1.0), (0.0, 0.0, -1.0), (nan, nan, nan), (nan, nan, nan), 180.0, -90.0, 1.2999999523162842, (0.0, 0.0, 0.0))**

I wonder why there are so many **nan** here.
Am i wrong about the settings?

**Comment by pyni** [comment]
Actually , i do not know how to change **horizon** and **vertical** of function **getDebugVisualizerCamera** in file **pointCloudFromCameraImage.py**:
![image](https://user-images.githubusercontent.com/18031767/55787173-4f3fbb00-5ae8-11e9-8205-9ddf98363ffd.png)
![image](https://user-images.githubusercontent.com/18031767/55787206-5b2b7d00-5ae8-11e9-9ec3-1cb086fdc7d4.png)
I think it is important for point cloud generation

**Comment by pyni** [comment]
Hi, I find if i set **p.resetDebugVisualizerCamera(1.3,180,-89,base_pos)**,
the parameters seem right:
**(1024, 768, (-0.9999999403953552, 8.740908441495776e-08, -1.5257376473343243e-09, 0.0, -8.74223999858259e-08, -0.9998475909233093, 0.017452478408813477, 0.0, 0.0, 0.017452476546168327, 0.9998476505279541, 0.0, -0.0, 1.862645149230957e-09, -1.2999999523162842, 1.0), (0.7499999403953552, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -1.0000200271606445, -1.0, 0.0, 0.0, -0.02000020071864128, 0.0), (0.0, 0.0, 1.0), (1.5257376473343243e-09, -0.017452478408813477, -0.9998476505279541), (-26666.66796875, -0.002331264317035675, 0.0), (0.0017481818795204163, -19996.953125, 349.049560546875), 180.0, -89.0, 1.2999999523162842, (0.0, 0.0, 0.0))**

**Comment by erwincoumans** [comment]
The debug visualizer camera cannot be set to look straight down at a pitch of -90, due to Euler angle singularity.

**Comment by Flymek** [comment]
Hi, could you then explain the horizon and vertical variables? How can I calculate them myself to be able to take a point cloud looking straight down? I sadly cannot find that information anywhere, but I know all the other variables debug visualizer camera is supposed to give me.
