### ISSUE TITLE
A problem about point cloud

### ISSUE THREAD

**Issue by pyni** [bulletphysics/bullet3#2196]
HI, i use **pointCloudFromCameraImage.py** to generate point clouds. 
However, i find some points are under the object!! This is very strange:
![2019-04-09 22-11-25屏幕截图](https://user-images.githubusercontent.com/18031767/55807366-b2dfdd80-5b14-11e9-9939-1fcf48ba5b15.png)
![2019-04-09 22-11-04屏幕截图](https://user-images.githubusercontent.com/18031767/55807376-b5423780-5b14-11e9-86eb-76771dba5afc.png)

Could you please provide with some suggestions?

**Comment by pyni** [comment]
![image](https://user-images.githubusercontent.com/18031767/55850145-c70ff300-5b85-11e9-9876-51e275803bc4.png)
![image](https://user-images.githubusercontent.com/18031767/55850157-d2fbb500-5b85-11e9-8f4e-937c2e6db19b.png)
Actually,  i can hardly understand why the depth data of these two yellow objects are total different.

**Comment by erwincoumans** [comment]
Please share a small reproduction case, otherwise no-one can help you (attach a zipfile or link to some github repo etc).

**Comment by pyni** [comment]
Hi, i have found the problem.

It seems that pybullet can not support 'stl' file which normals are pointing inside of the surface.
