### ISSUE TITLE
Question how to disable(or enable) the collision detection of a particular object

### ISSUE THREAD

**Issue by KohMat** [bulletphysics/bullet3#2201]
Hello

Is there C++ API to disable(or enable) the collision detection of a particular object to other objects and keep the object rigid body dynamics calculation? 

 I can call setIgnoreCollisionCheck repeatably in btCollisionObject and disable collision detection but it will be a problem when there are a lot of objects.

**Comment by erwincoumans** [comment]
There are several ways, ranging from collision filter groups to overriding the narrowphase callback.
