### ISSUE TITLE
pybullet renders wrong color

### ISSUE THREAD

**Issue by OhmySallyGarden** [bulletphysics/bullet3#2213]
I load the URDF model of kinova jaco, and I find that the color of the robot in the simulation is not corresponding to the camera image. 
![wrong_color](https://user-images.githubusercontent.com/37887274/56413379-e57a9a80-62b9-11e9-9cf3-c69f0a64fd3e.png)
upper left of the image and the environment are not same.
The urdf description is : 

[urdf.txt](https://github.com/bulletphysics/bullet3/files/3097432/urdf.txt)

**Comment by OhmySallyGarden** [comment]
`
<?xml version="1.0" ?>





<robot name="j2n6s300" xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body" xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz" xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom" xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint" xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model" xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics" xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable" xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering" xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" xmlns:xacro="http://ros.org/wiki/xacro" xmlns:xi="http://www.w3.org/2001/XInclude">
  
  
  <link name="root">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
    </collision>
  </link>
  
  <link name="world"/>
  <joint name="connect_root_and_world" type="fixed">
    <child link="root"/>
    <parent link="world"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>
  
  <gazebo>
    <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control">
      <robotNamespace>j2n6s300</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>
  <link name="j2n6s300_link_base">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/base.dae"/>
      </geometry>
      <material name="carbon_fiber">
        <color rgba="0.1788232 0.1788232 0.1788232 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/base.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.46784"/>
      <origin rpy="0 0 0" xyz="0 0 0.1255"/>
      <inertia ixx="0.000951270861568" ixy="0" ixz="0" iyy="0.000951270861568" iyz="0" izz="0.000374272"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_base" type="fixed">
    <parent link="root"/>
    <child link="j2n6s300_link_base"/>
    <axis xyz="0 0 0"/>
    <limit effort="2000" lower="0" upper="0" velocity="1"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="j2n6s300_link_1">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/shoulder.dae"/>
      </geometry>
      <material name="carbon_fiber">
        <color rgba="0.1788232 0.1788232 0.1788232 1"/>
      </material>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/ring_big.STL"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/shoulder.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.7477"/>
      <origin xyz="0 -0.002 -0.0605"/>
      <inertia ixx="0.00152031725204" ixy="0" ixz="0" iyy="0.00152031725204" iyz="0" izz="0.00059816"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_1" type="continuous">
    <parent link="j2n6s300_link_base"/>
    <child link="j2n6s300_link_1"/>
    <axis xyz="0 0 1"/>
    <limit effort="2000" lower="-6.28318530718" upper="6.28318530718" velocity="1"/>
    <origin rpy="0 3.14159265359 0" xyz="0 0 0.15675"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <transmission name="j2n6s300_joint_1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2n6s300_joint_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="j2n6s300_joint_1_actuator">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>160</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="j2n6s300_link_2">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/arm.dae"/>
      </geometry>
      <material name="carbon_fiber">
        <color rgba="0.1788232 0.1788232 0.1788232 1"/>
      </material>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/ring_big.STL"/>
      </geometry>
      <material name="carbon_fiber1">
        <color rgba="0.5960783 0.5960783 0.5960783 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/arm.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.99"/>
      <origin xyz="0 -0.2065 -0.01"/>
      <inertia ixx="0.010502207991" ixy="0" ixz="0" iyy="0.000792" iyz="0" izz="0.010502207991"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_2" type="revolute">
    <parent link="j2n6s300_link_1"/>
    <child link="j2n6s300_link_2"/>
    <axis xyz="0 0 1"/>
    <limit effort="2000" lower="0.820304748437" upper="5.46288055874" velocity="1"/>
    <origin rpy="-1.57079632679 0 3.14159265359" xyz="0 0.0016 -0.11875"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <transmission name="j2n6s300_joint_2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2n6s300_joint_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="j2n6s300_joint_2_actuator">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>160</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="j2n6s300_link_3">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/forearm.dae"/>
      </geometry>
      <material name="carbon_fiber">
        <color rgba="0.1788232 0.1788232 0.1788232 1"/>
      </material>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/ring_big.STL"/>
      </geometry>
      <material name="carbon_fiber1">
        <color rgba="0.5960783 0.5960783 0.5960783 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/forearm.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.6763"/>
      <origin xyz="0 0.081 -0.0086"/>
      <inertia ixx="0.00142022431908" ixy="0" ixz="0" iyy="0.000304335" iyz="0" izz="0.00142022431908"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_3" type="revolute">
    <parent link="j2n6s300_link_2"/>
    <child link="j2n6s300_link_3"/>
    <axis xyz="0 0 1"/>
    <limit effort="2000" lower="0.331612557879" upper="5.9515727493" velocity="1"/>
    <origin rpy="0 3.14159265359 0" xyz="0 -0.410 0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <transmission name="j2n6s300_joint_3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2n6s300_joint_3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="j2n6s300_joint_3_actuator">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>160</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="j2n6s300_link_4">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/wrist.dae"/>
      </geometry>
      <material name="carbon_fiber">
        <color rgba="0.1788232 0.1788232 0.1788232 1"/>
      </material>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/ring_small.STL"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/wrist.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.426367"/>
      <origin xyz="0 -0.037 -0.0642"/>
      <inertia ixx="7.73496906e-05" ixy="0" ixz="0" iyy="7.73496906e-05" iyz="0" izz="0.0001428"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_4" type="continuous">
    <parent link="j2n6s300_link_3"/>
    <child link="j2n6s300_link_4"/>
    <axis xyz="0 0 1"/>
    <limit effort="2000" lower="-6.28318530718" upper="6.28318530718" velocity="1"/>
    <origin rpy="-1.57079632679 0 3.14159265359" xyz="0 0.2073 -0.0114"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <transmission name="j2n6s300_joint_4_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2n6s300_joint_4">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="j2n6s300_joint_4_actuator">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>160</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="j2n6s300_link_5">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/wrist.dae"/>
      </geometry>
      <material name="carbon_fiber">
        <color rgba="0.1788232 0.1788232 0.1788232 1"/>
      </material>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/ring_small.STL"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/wrist.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.426367"/>
      <origin xyz="0 -0.037 -0.0642"/>
      <inertia ixx="7.73496906e-05" ixy="0" ixz="0" iyy="7.73496906e-05" iyz="0" izz="0.0001428"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_5" type="continuous">
    <parent link="j2n6s300_link_4"/>
    <child link="j2n6s300_link_5"/>
    <axis xyz="0 0 1"/>
    <limit effort="2000" lower="-6.28318530718" upper="6.28318530718" velocity="1"/>
    <origin rpy="1.0471975512 0 3.14159265359" xyz="0 -0.03703 -0.06414"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <transmission name="j2n6s300_joint_5_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2n6s300_joint_5">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="j2n6s300_joint_5_actuator">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>160</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="j2n6s300_link_6">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/hand_3finger.dae"/>
      </geometry>
      <material name="carbon_fiber">
        <color rgba="0.1788232 0.1788232 0.1788232 1"/>
      </material>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/ring_small.STL"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/hand_3finger.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.99"/>
      <origin xyz="0 0 -0.06"/>
      <inertia ixx="0.0003453236187" ixy="0" ixz="0" iyy="0.0003453236187" iyz="0" izz="0.0005816"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_6" type="continuous">
    <parent link="j2n6s300_link_5"/>
    <child link="j2n6s300_link_6"/>
    <axis xyz="0 0 1"/>
    <limit effort="2000" lower="-6.28318530718" upper="6.28318530718" velocity="1"/>
    <origin rpy="1.0471975512 0 3.14159265359" xyz="0 -0.03703 -0.06414"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <transmission name="j2n6s300_joint_6_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2n6s300_joint_6">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="j2n6s300_joint_6_actuator">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>160</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="j2n6s300_end_effector">
    <visual>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
    </collision>
  </link>
  <joint name="j2n6s300_joint_end_effector" type="fixed">
    <parent link="j2n6s300_link_6"/>
    <child link="j2n6s300_end_effector"/>
    <axis xyz="0 0 0"/>
    <limit effort="2000" lower="0" upper="0" velocity="1"/>
    <origin rpy="3.14159265359 0 1.57079632679" xyz="0 0 -0.1600"/>
  </joint>
  <link name="j2n6s300_link_finger_1">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_proximal.dae"/>
      </geometry>
      <material name="carbon_fiber1">
        <color rgba="0.5960783 0.5960783 0.5960783 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_proximal.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0.022 0 0"/>
      <inertia ixx="7.8999684e-07" ixy="0" ixz="0" iyy="7.8999684e-07" iyz="0" izz="8e-08"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_finger_1" type="revolute">
    <parent link="j2n6s300_link_6"/>
    <child link="j2n6s300_link_finger_1"/>
    <axis xyz="0 0 1"/>
    <origin rpy="-1.570796327 .649262481663582 1.35961148639407" xyz="0.00279 0.03126 -0.11467"/>
    <limit effort="2000" lower="0" upper="2" velocity="1"/>
  </joint>
  <transmission name="j2n6s300_joint_finger_1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2n6s300_joint_finger_1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="j2n6s300_joint_finger_1_actuator">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="j2n6s300_link_finger_tip_1">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_distal.dae"/>
      </geometry>
      <material name="carbon_fiber1">
        <color rgba="0.5960783 0.5960783 0.5960783 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_distal.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0.022 0 0"/>
      <inertia ixx="7.8999684e-07" ixy="0" ixz="0" iyy="7.8999684e-07" iyz="0" izz="8e-08"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_finger_tip_1" type="fixed">
    <parent link="j2n6s300_link_finger_1"/>
    <child link="j2n6s300_link_finger_tip_1"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0.044 -0.003 0"/>
    <limit effort="2000" lower="0" upper="2" velocity="1"/>
  </joint>
  <link name="j2n6s300_link_finger_2">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_proximal.dae"/>
      </geometry>
      <material name="carbon_fiber1">
        <color rgba="0.5960783 0.5960783 0.5960783 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_proximal.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0.022 0 0"/>
      <inertia ixx="7.8999684e-07" ixy="0" ixz="0" iyy="7.8999684e-07" iyz="0" izz="8e-08"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_finger_2" type="revolute">
    <parent link="j2n6s300_link_6"/>
    <child link="j2n6s300_link_finger_2"/>
    <axis xyz="0 0 1"/>
    <origin rpy="-1.570796327 .649262481663582 -1.38614049188413" xyz="0.02226 -0.02707 -0.11482"/>
    <limit effort="2000" lower="0" upper="2" velocity="1"/>
  </joint>
  <transmission name="j2n6s300_joint_finger_2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2n6s300_joint_finger_2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="j2n6s300_joint_finger_2_actuator">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="j2n6s300_link_finger_tip_2">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_distal.dae"/>
      </geometry>
      <material name="carbon_fiber1">
        <color rgba="0.5960783 0.5960783 0.5960783 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_distal.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0.022 0 0"/>
      <inertia ixx="7.8999684e-07" ixy="0" ixz="0" iyy="7.8999684e-07" iyz="0" izz="8e-08"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_finger_tip_2" type="fixed">
    <parent link="j2n6s300_link_finger_2"/>
    <child link="j2n6s300_link_finger_tip_2"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0.044 -0.003 0"/>
    <limit effort="2000" lower="0" upper="2" velocity="1"/>
  </joint>
  <link name="j2n6s300_link_finger_3">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_proximal.dae"/>
      </geometry>
      <material name="carbon_fiber1">
        <color rgba="0.5960783 0.5960783 0.5960783 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_proximal.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0.022 0 0"/>
      <inertia ixx="7.8999684e-07" ixy="0" ixz="0" iyy="7.8999684e-07" iyz="0" izz="8e-08"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_finger_3" type="revolute">
    <parent link="j2n6s300_link_6"/>
    <child link="j2n6s300_link_finger_3"/>
    <axis xyz="0 0 1"/>
    <origin rpy="-1.570796327 .649262481663582 -1.75545216211587" xyz="-0.02226 -0.02707 -0.11482"/>
    <limit effort="2000" lower="0" upper="2" velocity="1"/>
  </joint>
  <transmission name="j2n6s300_joint_finger_3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2n6s300_joint_finger_3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="j2n6s300_joint_finger_3_actuator">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <link name="j2n6s300_link_finger_tip_3">
    <visual>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_distal.dae"/>
      </geometry>
      <material name="carbon_fiber1">
        <color rgba="0.5960783 0.5960783 0.5960783 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package:///home/hiter/Git/DDPG/j2n6s300_model/meshes/finger_distal.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0.022 0 0"/>
      <inertia ixx="7.8999684e-07" ixy="0" ixz="0" iyy="7.8999684e-07" iyz="0" izz="8e-08"/>
    </inertial>
  </link>
  <joint name="j2n6s300_joint_finger_tip_3" type="fixed">
    <parent link="j2n6s300_link_finger_3"/>
    <child link="j2n6s300_link_finger_tip_3"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0.044 -0.003 0"/>
    <limit effort="2000" lower="0" upper="2" velocity="1"/>
  </joint>
</robot>
`

**Comment by OhmySallyGarden** [comment]
The upper left of the image is what I want the physics engine to render. And I do not know how  to use  getVisualShapeData() and changeVisualShape() to only chage the ring of the arm rather than the whole link.

**Comment by maedmaex** [comment]
Hey, could you share any code to be able to help you
