### ISSUE TITLE
Stretching a link

### ISSUE THREAD

**Issue by Prakhar005** [bulletphysics/bullet3#2220]
Hello,

I am trying to simulate a setup where I define a rectangular link with a certain elastic modulus. I use an SDF format for this since URDF does not provide me this capability. I was wondering if it is possible to permanently attach one end of the link to the ground and apply a stretching force to the other end? I want to see the link stretch under an applied force. Thanks!

**Comment by erwincoumans** [comment]
This is rigid body dynamics, links don't deform. You could try to use soft body dynamics or deformables instead. Or explicitly add prismatic joints with motors that allow to stretch.
