### ISSUE TITLE
btPersistentManifold::sortCachedPoint returns -1, causing a crash

### ISSUE THREAD

**Issue by samapico** [bulletphysics/bullet3#2227]
In [``btPersistentManifold::addManifoldPoint``](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp#L212), I have some cases where ``newPoint`` contains NaN's for some reason, and this sometimes causes ``sortCachedPoint`` to return -1.

The following line then crashes because we are accessing out of bounds memory: [``clearUserCache(m_pointCache[insertIndex]);``](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp#L228)

I can patch this by moving the ``if (insertIndex < 0) insertIndex = 0;`` lines between ``sortCachedPoints(...)`` and ``clearUserCache(...)``, but I feel like I'm just bypassing an underlying problem.

I don't use the dynamics world, I just use ``performDiscreteCollisionDetection`` with a bunch of positions. My world contains mostly triangle meshes. Out of ~3000 positions, 2 or 3 of them encounter this issue. The issue only appears in Release, not in Debug (which made debugging this quite an adventure!). It might be hard for me to provide reproduction steps.

Here's what my [``addManifoldPoint``](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp#L212) method looks like now:

```
int btPersistentManifold::addManifoldPoint(const btManifoldPoint& newPoint)
{
	btAssert(validContactDistance(newPoint));

	int insertIndex = getNumContacts();
	if (insertIndex == MANIFOLD_CACHE_SIZE)
	{
#if MANIFOLD_CACHE_SIZE >= 4
		//sort cache so best points come first, based on area
		insertIndex = sortCachedPoints(newPoint);
#else
		insertIndex = 0;
#endif
		//sortCachedPoints can give -1 if newPoint has IND values
		if (insertIndex < 0)
			insertIndex = 0;

		clearUserCache(m_pointCache[insertIndex]);
		
	} else
	{
		m_cachedPoints++;

		
	}

	btAssert(m_pointCache[insertIndex].m_userPersistentData==0);
	m_pointCache[insertIndex] = newPoint;
	return insertIndex;
}
```

Am I missing something? Does my patch make any sense or could it break something else?

I'm using Bullet 2.80-rev2531 (compiled with msvc2010, in 32-bit) with Windows 10 x64.

**Comment by erwincoumans** [comment]
The real issue is a NaN. Is it due to invalid input? If you can reproduce it, please re-open/share a reproduction case.
