### ISSUE TITLE
Problem with camera projections

### ISSUE THREAD

**Issue by alessiabertugli** [bulletphysics/bullet3#2255]
Hi,
I want to project some objects on images given by p.getCameraImage. I used p.computeViewMatrixFromYawPitchRoll and p.computeProjectionMatrixFOV to compute view and projection matrix, then I projected my object on camera images following openGL convention of matrices multiplication. When I compute the display matrix, I get pixels outside the image view, despite the object being inside the camera view. Strangely, if I divided f_x and f_y by 20 instead of 2 everything seems to be fine (I get my object projected without distortion). What am I doing wrong?

This is my code:

    def get_view_matrix_from_yaw_pitch_roll(self):
        robot_pos, _ = p.getBasePositionAndOrientation(self.robot_tracking_id)
        view_matrix = p.computeViewMatrixFromYawPitchRoll(
            cameraTargetPosition=robot_pos,
            distance=self.tracking_camera["distance"],
            yaw=self.tracking_camera["yaw"],
            pitch=self.tracking_camera["pitch"],
            roll=0,
            upAxisIndex=2)
        return view_matrix

    def get_projection_matrix(self):
        proj_matrix = p.computeProjectionMatrixFOV(
            fov=60, aspect=float(self._render_width) / self._render_height,
            nearVal=0.1, farVal=100.0)
        return proj_matrix

    def get_view_to_display_matrix(self):
        f_x = f_y = float(self.image_height) / 2. # 20.
        view_to_disp_mat = np.array([[f_x, 0., 0., float(self.image_width) / 2.0],
                                     [0., -f_y, 0., float(self.image_height) / 2.0],
                                     [0., 0., 1., 0.],
                                     [0., 0., 0., 1.]])
        return view_to_disp_mat

    def apply_transformations(self, coords_3d):
        hmgns_world_coords = np.array([coords_3d[0], coords_3d[1], coords_3d[2], 1.])
        view_mat_reshaped = np.linalg.inv(np.reshape(np.array(self.view_matrix), (4, 4)))
        proj_mat_reshaped = np.reshape(np.array(self.projection_matrix), (4, 4))
        view_proj_matrix = np.matmul(proj_mat_reshaped, view_mat_reshaped)
        f_view_coords = np.dot(view_proj_matrix, hmgns_world_coords.T).T
        norm_coords = f_view_coords / f_view_coords[3]
        display_matrix = self.get_view_to_display_matrix()
        disp_coords = np.dot(display_matrix, norm_coords.T).T
        coords = (abs(int(disp_coords[0])), abs(int(disp_coords[1])))

        return coords

**Comment by erwincoumans** [comment]
I've not seen a difference, for example see this old issue:https://github.com/bulletphysics/bullet3/pull/1439
If you figure it out, please re-open/let us know.
