### ISSUE TITLE
Setting multiple URDF flags

### ISSUE THREAD

**Issue by wxmerkt** [bulletphysics/bullet3#2260]
Hi,
I haven't found an answer to this in the PyBullet guide - is it possible to pass more than one flag to the `loadURDF` method, e.g., to use self-collision _and_ use inertias from the URDF? 
I saw the experimental `setPhysicsEngineParameter` method - not sure whether it would work for this use case?

Thank you very much,
Wolfgang

**Comment by erwincoumans** [comment]
Yes, you can use a logical OR to combine flags in loadURDF. Added it to the PyBullet quickstart guide in the loadURDF flags section.
https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA

**Comment by wxmerkt** [comment]
Thank you!
