### ISSUE TITLE
pybullet installation in conda env for 3.6

### ISSUE THREAD

**Issue by priyashkla** [bulletphysics/bullet3#2267]
creating build/temp.linux-x86_64-3.6/examples/ThirdPartyLibs/Gwen/Controls/Dialog
    creating build/temp.linux-x86_64-3.6/examples/ThirdPartyLibs/Gwen/Platforms
    creating build/temp.linux-x86_64-3.6/examples/ThirdPartyLibs/Gwen/Renderers
    creating build/temp.linux-x86_64-3.6/examples/ThirdPartyLibs/glad
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/pybullet/pybullet.c -o build/temp.linux-x86_64-3.6/examples/pybullet/pybullet.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c src/btLinearMathAll.cpp -o build/temp.linux-x86_64-3.6/src/btLinearMathAll.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c src/btBulletCollisionAll.cpp -o build/temp.linux-x86_64-3.6/src/btBulletCollisionAll.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c src/btBulletDynamicsAll.cpp -o build/temp.linux-x86_64-3.6/src/btBulletDynamicsAll.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/ExampleBrowser/InProcessExampleBrowser.cpp -o build/temp.linux-x86_64-3.6/examples/ExampleBrowser/InProcessExampleBrowser.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/TinyRenderer/geometry.cpp -o build/temp.linux-x86_64-3.6/examples/TinyRenderer/geometry.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/TinyRenderer/model.cpp -o build/temp.linux-x86_64-3.6/examples/TinyRenderer/model.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/TinyRenderer/tgaimage.cpp -o build/temp.linux-x86_64-3.6/examples/TinyRenderer/tgaimage.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/TinyRenderer/our_gl.cpp -o build/temp.linux-x86_64-3.6/examples/TinyRenderer/our_gl.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/TinyRenderer/TinyRenderer.cpp -o build/temp.linux-x86_64-3.6/examples/TinyRenderer/TinyRenderer.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/SharedMemory/plugins/pdControlPlugin/pdControlPlugin.cpp -o build/temp.linux-x86_64-3.6/examples/SharedMemory/plugins/pdControlPlugin/pdControlPlugin.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/SharedMemory/plugins/collisionFilterPlugin/collisionFilterPlugin.cpp -o build/temp.linux-x86_64-3.6/examples/SharedMemory/plugins/collisionFilterPlugin/collisionFilterPlugin.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/SharedMemory/plugins/fileIOPlugin/fileIOPlugin.cpp -o build/temp.linux-x86_64-3.6/examples/SharedMemory/plugins/fileIOPlugin/fileIOPlugin.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/priya/.conda/envs/deepq/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/priya/.conda/envs/deepq/lib/python3.6/site-packages/numpy/core/include -Iexamples/ThirdPartyLibs/optionalX11 -Isrc -Iexamples/ThirdPartyLibs -Iexamples/ThirdPartyLibs/glad -Iexamples/ThirdPartyLibs/enet/include -Iexamples/ThirdPartyLibs/clsocket/src -I/home/priya/.conda/envs/deepq/include/python3.6m -c examples/SharedMemory/b3RobotSimulatorClientAPI_NoDirect.cpp -o build/temp.linux-x86_64-3.6/examples/SharedMemory/b3RobotSimulatorClientAPI_NoDirect.o -DGWEN_COMPILE_STATIC -DBT_USE_DOUBLE_PRECISION -DBT_ENABLE_ENET -DBT_ENABLE_CLSOCKET -DB3_DUMP_PYTHON_VERSION -DEGL_ADD_PYTHON_INIT -DB3_ENABLE_FILEIO_PLUGIN -DB3_USE_ZIPFILE_FILEIO -DBT_THREADSAFE=1 -DSTATIC_LINK_SPD_PLUGIN -DPYBULLET_USE_NUMPY -D_LINUX -DGLEW_STATIC -DGLEW_INIT_OPENGL11_FUNCTIONS=1 -DGLEW_DYNAMIC_LOAD_ALL_GLX_FUNCTIONS=1 -DDYNAMIC_LOAD_X11_FUNCTIONS -DHAS_SOCKLEN_T -fno-inline-functions-called-once -fvisibility=hidden -fvisibility-inlines-hidden
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    unable to execute 'gcc': No such file or directory
    ----------------------------------------
ERROR: Command "/home/priya/.conda/envs/deepq/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-d67bmd4g/pybullet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k920j4rq/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-d67bmd4g/pybullet/

ubuntu:16.04 LTS
anaconda3: 3.6.8 env

**Comment by erwincoumans** [comment]
gcc seems missing.
