### ISSUE TITLE
Inconsistency argument naming render/renders

### ISSUE THREAD

**Issue by Atine** [bulletphysics/bullet3#2272]
Specifically in this line inside [minitaur_duck_gym_env.py, L73:](https://github.com/bulletphysics/bullet3/blob/78e1baede85026dea5eb43fbcda4bf8a08033031/examples/pybullet/gym/pybullet_envs/bullet/minitaur_duck_gym_env.py#L73)
In other envs examples, the argument is 'renders' and only here it is 'render'.

Moreover, as most already know, in OpenAI gym, 'render' is used, where as in most of envs here, 'renders' is used. Just curious if the naming should be consistent with gym as well.

**Comment by erwincoumans** [comment]
It happened indeed, not going to change the existing old environments but will keep it in mind for the upcoming new environments.
