### ISSUE TITLE
Factoring projectionMatrix into intrinsic and extrinsic matrices 

### ISSUE THREAD

**Issue by Nematollahi** [bulletphysics/bullet3#2281]
Hey! I am interested in getting the intrinsic and extrinsic matrices of the simulated camera in pybullet. I assume that it should be possible by only decomposing the projectionMatrix. 

I follow the "Factoring the Camera Matrix" section of [this link](https://www.oreilly.com/library/view/programming-computer-vision/9781449341916/ch04.html) which uses RQ-factorization. The projectionMatrix of the pybullet is a 4x4 matrix, but as [this link](http://ksimek.github.io/2012/08/14/decompose/) says the third row of the projectionMatrix is there only to preserve the z-coordinate and should be removed for the factorization. Now by factorization of this 3x4 matrix I get the following intrinsic matrix:

K = [[ 0.74999994  0.          0.                ]
       [ 0.                  -1.         0.                ]
       [ 0.                  0.          0.0200002 ]]

which is not inline with the format of an intrinsic matrix which is:

K = [[fx           0.          cx        ]
       [ 0.         fy           cy        ]
       [ 0.          0.          1         ]]

**The value of K(3,3)  should be 1, but it is not the case in the pybullet simulated camera.**

Could you please help me how with this issue? 

I appreciate your support.

**Comment by NotAnyMike** [comment]
Any update here?

**Comment by erwincoumans** [comment]
No. You are free to bring your own view and projection matrix, as well as intrinsic and extrinsic matrices. PyBullet uses OpenGL conventions by default, but you are free to use any other perspective matrix.

**Comment by NotAnyMike** [comment]
Do you know any good resource to understand how the projection matrix from openGL is calculated and  the link to the intrinsic and extrinsic?

**Comment by erwincoumans** [comment]
No, I am not familiar with intrinsic and extrinsic matrices.

**Comment by erwincoumans** [comment]
Google?

**Comment by domef** [comment]
In the function `computeProjectionMatrixFOV` the FOV is horizontal, vertical or diagonal?

**Comment by domef** [comment]
@nematoli did you solve the problem? I'm also using the RQ-factorization but the result seems wrong.
