### ISSUE TITLE
No display in VR for HTC Vive Pro

### ISSUE THREAD

**Issue by asit2898** [bulletphysics/bullet3#2285]
Hi,
![issue](https://user-images.githubusercontent.com/51470339/59081784-ebd8da80-892a-11e9-8525-a79f04746427.png)
I was trying out the vr_kuka_setup.py example on a HTC Vive Pro device. I could get the code running, and was able to get HMD and controller feedback. However, within the VR HMD's screen, I can only see standard loading screen(screenshot attached). What is causing this issue?

**Comment by hzyjerry** [comment]
Hi @asit2898 I'm running into the exact same issue. Have you fixed this by any chance?
