### ISSUE TITLE
Example Browser freezes the system on Ubuntu 18.04

### ISSUE THREAD

**Issue by przecze** [bulletphysics/bullet3#2288]
Hi,
I tried to build bullet on fresh Ubuntu 18.04 installation. After successful build when I open the examples browser I see a window with the 3d grid and some graphical artifact instead of the objects and than the whole system freezes immediately.

I did:
```
$ apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
```
after the build failed reporting missing opengl, so I have:
```
OpenGL version string: 3.1 Mesa 18.2.2
```
and the next build was successful, but the ExampleBrowser is not working.

additional info about my GPU:
```
$ sudo lshw -C display
  *-display                 
       description: VGA compatible controller
       product: G98 [Quadro NVS 295]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nouveau latency=0
       resources: irq:25 memory:fa000000-faffffff memory:f0000000-f3ffffff memory:f8000000-f9ffffff ioport:ec00(size=128) memory:c0000-dffff
```

**Comment by erwincoumans** [comment]
The GPU is likely not supported, can't help with that.
