### ISSUE TITLE
Unable to load color for OBJ files

### ISSUE THREAD

**Issue by chrisdxie** [bulletphysics/bullet3#2292]
I'm trying to load ShapeNet models into PyBullet, but for many of these models, I can't seem to load the correct colors/textures for them. According to [here](https://github.com/bulletphysics/bullet3/issues/1813): it seems that .obj files can only have at most one texture (I have many .obj files from ShapeNet). Will this be updated any time soon?

**Comment by erwincoumans** [comment]
The workaround in the answer in that issue is still current: use obj2sdf. No resources/plans to refactor the graphics pipeline to support multiple textures per mesh, you need to break up the meshes (using obj2sdf for example).
