### ISSUE TITLE
More instructions on how to train DeepMimic?

### ISSUE THREAD

**Issue by KaizhaoLiang** [bulletphysics/bullet3#2304]
I was able to run the backflip demo. But when I tried to run the mpi_run.py or DeepMimic_Optimizer.py, it gives me "System cann't find file" error, which seems to come from the subprocess? Any idea how to resolve this problem? Thanks.

**Comment by ZhengyiLuo** [comment]
in this repo the arg file is in a different folder. Specifically remove the "args/" part in the command: 

python3 mpi_run.py --arg_file args/train_humanoid3d_spinkick_args.txt --num_workers 4

so just: 

python3 mpi_run.py --arg_file train_humanoid3d_spinkick_args.txt --num_workers 4

Training is really slow though.... submitting an issue for that.

**Comment by KaizhaoLiang** [comment]
Hi, I don't think it's not finding the arg_file. The error prompt is 
cmd: mpiexec -n 4 python3 DeepMimic_Optimizer.py --arg_file train_humanoid3d_spinkick_args.txt --num_workers 4
ERROR: Error reported: failed to launch 'python3 DeepMimic_Optimizer.py --arg_file train_humanoid3d_spinkick_args.txt --num_workers 4' on DESKTOP
Error (2) The system cannot find the file specified.

I also tried "python -m pybullet_envs.deep_mimic.mpi_run --arg_file run_humanoid3d_backflip_args.txt". It gives the same error. 

But this doesn't happen when I run testrl in both ways.

Any help is appreciated, thank you.

**Comment by ZhengyiLuo** [comment]
I think there is some problem with the DeepMimic_Optimizer.py path. Try run the command at the directory where DeepMimic_Optimizer.py is. 

Specifically: pybullet3/examples/pybullet/pybullet_envs/deep_mimic/

**Comment by erwincoumans** [comment]
The training speed has been fixed long ago, and things should work fine at several million samples per hour dependent on the machine/number of threads. Here is the command for a machine with 12 hardware cores:
~~~~~~~~~~~~~~~~~
python3 mpi_run.py --arg_file train_humanoid3d_spinkick_args.txt --num_workers 12
~~~~~~~~~~~~~~~~~
