### ISSUE TITLE
open with a GUI and then stop rendering

### ISSUE THREAD

**Issue by manuel-delverme** [bulletphysics/bullet3#2306]
Hello,
I noticed my (RL) enviroment goes at 160 FPS when render('human') is active and drops to 60FPS when mode is set to None

Is there a way to open a client with gui but then close the GUI to avoid the useless overhead?

self._p = bullet_client.BulletClient(connection_mode=pybullet.GUI)

even better would be to render on GPU with no GUI but i understand it's not possible at the moment?

**Comment by erwincoumans** [comment]
It depends on your environment. Are you using 'getCameraImage'? If so, the non-gui version uses a slower CPU renderer (TinyRenderer) by default. In GUI mode, it may use the OpenGL hardware rendering.
We have EGL offline rendering, which is available. See the egl examples in Bullet/examples/pybullet/examples.

**Comment by manuel-delverme** [comment]
Thanks for the prompt reply,

I'm already using the opengl rendering as such:
```
        (_, _, px, _, _) = bullet_client.getCameraImage(
            width=self.render_width, height=self.render_height,
            viewMatrix=view_matrix,
            projectionMatrix=proj_matrix,
            renderer=pybullet.ER_BULLET_HARDWARE_OPENGL
        )
```

getCameraImage
