### ISSUE TITLE
Dinnerware license

### ISSUE THREAD

**Issue by makarany** [bulletphysics/bullet3#2344]
@olegklimov 
Can you please help me out with the dinnerware licensing?
File: bullet3/data/dinnerware/license.txt
You have the following reference:  LICENSE: CC-SA

Can you tell me which CC-SA license it's applicable here?

Thank you,
Arany

**Comment by erwincoumans** [comment]
This one: https://creativecommons.org/licenses/by-sa/2.0/

**Comment by makarany** [comment]
thank you
