### ISSUE TITLE
How to change the color of the robots?

### ISSUE THREAD

**Issue by GPaolo** [bulletphysics/bullet3#2345]
Hi, is there a way to change the colors of the robot? I tried changing the xml file rgba parameters, but they do not appear to do anything.

**Comment by erwincoumans** [comment]
pybullet.changeVisualShape(objectUniqueId, linkIndex, ..., rgbaColor=[r,g,b,a])
If using an .obj file, the MTL allows adjusting the color, that may override the urdf setting.
