### ISSUE TITLE
TerrainDemo uses unrecommended uchar as heightfieldData type

### ISSUE THREAD

**Issue by MarcosAlfonso** [bulletphysics/bullet3#235]
Not a major issue, but I found it odd that the terrainDemo example uses unsigned chars to define the heightfieldData, which the documentation specifically recommends against using.

**Comment by benelot** [comment]
Would you want to make a pull request? If it is already fixed, we could close the issue to clean up the tracker.

**Comment by erwincoumans** [comment]
closing out-of-date issues.
