### ISSUE TITLE
Getting all solutions for calculateInverseKinematic

### ISSUE THREAD

**Issue by nicolasCheron** [bulletphysics/bullet3#2358]
Hello, As I understand, the calculateInverseKinematics function returned the closest articular solution for a desired cartesian position (and optionnaly orientation) from the current  articular position.
 Is there a way to get all the articular solutions that lead to the cartesian position and not only the closest ?

**Comment by jrz371** [comment]
No.
For a redundant manipulator (more degrees of freedom than required) there are an infinite number of solutions.

**Comment by nicolasCheron** [comment]
Actually I am using an holonomic robot (6 joints (rotations) for 6DOF). So the number of solution is not infinite. Do you know a (python) IK solver that returns all configurations using a URDF or a DH modelisation? 
Thanks for your answer.

**Comment by erwincoumans** [comment]
Even with 6 joints and 6DOF you can have infinite many solutions.
PyBullet allows you to tune the solution, using various parameters, in particular using a null space. This can be used to generate many solutions.
