### ISSUE TITLE
Program runs but does not display anything 

### ISSUE THREAD

**Issue by kaanap** [bulletphysics/bullet3#2360]
Hi when I try to run the minitaur.py file under examples/pybullet/gym/pybullet_env/bullet
It does not give any error but It does not display anything and the program works for like a second and than stops I can t figure out whats wrong could please help me 
Thanks

**Comment by erwincoumans** [comment]
This is expected, it is an internal file. Try running minitaur_raibert_controller_example.py instead, located in pybullet_envs.minitaur.envs
If you installed pybullet using pip/pip3, you can run:
~~~~~~~~~~
python3 -m pybullet_envs.minitaur.envs.minitaur_raibert_controller_example
~~~~~~~~~~
