### ISSUE TITLE
Resume training from deepmimic

### ISSUE THREAD

**Issue by ked19** [bulletphysics/bullet3#2368]
When I terminate the training and get the results in out/ directory.
Is there any method to resume the training?
I put the result to pybullet_data/data/policies/humanoid3d/ and used mpi_run.py to restart it, but the iteration number always counted from 0.

**Comment by AAInsanity** [comment]
I am having the same question. It seems like the episode return always gets a big drop when I save and reload a model for retraining. I wonder if that's what's supposed to happen.

**Comment by erwincoumans** [comment]
I guess you'll have to restart from scratch.
Eventually I'll turn this into a proper Gym environment, so you can use your favorite training algorithm that has a working save/restore.
