### ISSUE TITLE
Scaling an object by loadURDF() method

### ISSUE THREAD

**Issue by gktg1514** [bulletphysics/bullet3#2379]
When loading an object or a robot into physics server simulation, we can specify its size by using "globalScaling" parameter of the method loadURDF(). When we scale an object with the value 2 what happens ?

Is only its size gets multiplied by 2 ?
Or, both size and mass get multiplied by 2 ?
Is it possible to get mass of an object ?

Thanks in advance.

**Comment by erwincoumans** [comment]
Only the size gets multiplied. You can use getDynamicsInfo / changeDynamicsInfo to read / write the mass. Check out the [PyBullet Quickstart Guide.](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.d6og8ua34um1)
