### ISSUE TITLE
Possible to modify mass of loaded URDF file?

### ISSUE THREAD

**Issue by e-dub** [bulletphysics/bullet3#2380]
I am using bullet via the pyBullet package and I would like to vary the link of mass of a robot that I loaded into Python from a urdf file. 

```
robot = pybullet.loadURDF("robotFile.urdf")
# change mass of link 2
...
# simulate
...
```
Would something along these lines be possible with pyBullet?

**Comment by erwincoumans** [comment]
You can use the pybullet.changeDynamics to change the mass of a link.
See https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3
