### ISSUE TITLE
Motor Control By Position Control Mode

### ISSUE THREAD

**Issue by gktg1514** [bulletphysics/bullet3#2381]
I intend to control the motors of the robot in POSITION CONTROL mode. While I am doing this, what happens if I do not pass an argument for targetVelocity and force parameters ?

What I am actually wondering is what are the default values for these parameters in POSITION CONTROL mode ?

Thanks in advance.

**Comment by erwincoumans** [comment]
Default values are here:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/pybullet.c#L3285
----------------------------
double targetVelocity  = 0.f
double force = 100000.0;
double kp = 0.1;
double kd = 1.0;
----------------------------
