### ISSUE TITLE
Inactive physics objects jittering

### ISSUE THREAD

**Issue by 1vanK** [bulletphysics/bullet3#2382]
src\BulletDynamics\Dynamics\btDiscreteDynamicsWorld.cpp

```
void	btDiscreteDynamicsWorld::synchronizeSingleMotionState(btRigidBody* body)
{
    ...
    //we need to call the update at least once, even for sleeping objects
    //otherwise the 'graphics' transform never updates properly
    ///@todo: add 'dirty' flag
    //if (body->getActivationState() != ISLAND_SLEEPING)
        ...
        body->getMotionState()->setWorldTransform(interpolatedTransform);
    ...
```

this cause jittering for motionless objects
https://youtu.be/GQ9AtuScj7A

**Comment by erwincoumans** [comment]
Yes, the ISLAND_SLEEPING check should be re-enabled, or an isActive check somewhere else (as you suggested). Alternatively, just don't use the motion state and read the world transform directly.
