### ISSUE TITLE
Bullet3 as an External Library

### ISSUE THREAD

**Issue by shbang91** [bulletphysics/bullet3#2384]
I would like to use Bullet3 as an external library in my C++ project and I am trying to use cmake as a build tool. I found ```FindBullet.cmake``` has saved only Dyanmics, Collision, Linear Math, and Softbody libraries in ``` ${BULLET_LIBRARIES}```. But, when I copied and pasted ```TwoJointMain.cpp``` in my project and tried to compile it by target linking the libraries, it failed because of the need for other libraries such as ```BussIK```, ```BulletFileLoader```, and so on. So, I edited the ```FindBullet.cmake``` adding those needed libraries but it still failed to compile ```TwoJointMain.cpp```. From close investigations on ```CMakeLists.txt``` on ```TwoJointMain.cpp```, it appeared that it also needed internal source files in the bullet3 repository like ```example/SharedMemory/PhysicsClient.cpp``` and so on. In this case, do you have any idea to include these internal sources via ```CMake``` in other project?

Thank you in advance.

**Comment by erwincoumans** [comment]
For TwoJointMain.cpp you could try using Bullet/Extras/BulletRobotics.
