### ISSUE TITLE
“No matching distribution found for pybullet" when pip install

### ISSUE THREAD

**Issue by TerenceCYJ** [bulletphysics/bullet3#2385]
Collecting pybullet
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5c863ab6d8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pybullet/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5c863ab9b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pybullet/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5c863ab978>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pybullet/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5c863abb38>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pybullet/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5c863ab588>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pybullet/
  ERROR: Could not find a version that satisfies the requirement pybullet (from versions: none)
ERROR: No matching distribution found for pybullet

**Comment by jwatson-CO-edu** [comment]
May be a bad connection.  Re-running the `pip3` command worked for me.
