### ISSUE TITLE
Soft body in pybullet

### ISSUE THREAD

**Issue by alifahsanul** [bulletphysics/bullet3#2388]
I know it is possible to load soft body using pybullet.loadSoftBody()
How to specify damping and stiffness of an object?
I checked https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit# but there are no explanation of loadSoftBody
Thanks

**Comment by erwincoumans** [comment]
Soft body and deformables are experimental not fully exposed yet and still under active development. We will document them when the API is more stable.
