### ISSUE TITLE
eglRenderer camera is static

### ISSUE THREAD

**Issue by initmaks** [bulletphysics/bullet3#2390]
Hello,

I'm having a strange issue with the `eglRenderer` plugin. The image is rendered from the same perspective every time no matter what camera position and angle settings are used. The scene is not static and has moving objects. This problem doesn't exist if eglRendered is not used.
For example, if I run **examples/testrenderer_np.py** the camera is revolving around r2d2 and images are rendered properly from different angles at every step, however, if I use **examples/testrenderer_egl.py** the camera is static.

Any ideas why it could be happening?

Thanks!

**Comment by initmaks** [comment]
The latest version of `pybullet` where the issue doesn't exist is `2.4.6`.

**Comment by muupan** [comment]
I have the same problem with the latest master 66fc3a9ce94cbf9793898d9ebb11dec587670ada.

**Comment by muupan** [comment]
I have confirmed that reverting https://github.com/bulletphysics/bullet3/pull/2134 solves the issue.

**Comment by erwincoumans** [comment]
It looks like the line 
~~~~~~~~~~~~~~~~~
m_data->m_camera.disableVRCamera();
~~~~~~~~~~~~~~~~~
causes it.
For now, let's remove it.

**Comment by erwincoumans** [comment]
fixed here: https://github.com/bulletphysics/bullet3/pull/2419
