### ISSUE TITLE
Got different rendered images with/without eglRendererPlugin

### ISSUE THREAD

**Issue by taochenshh** [bulletphysics/bullet3#2410]
Hi,

I am trying out the eglRendererPlugin. But I got different RGB images when eglRendererPlugin is used and when eglRendererPlugin is not used.

Here is the simple script to recreate the problem:
```python
import pybullet as p
import pybullet_data
import numpy as np
import matplotlib.pyplot as plt
import pkgutil

physicsClient = p.connect(p.DIRECT)  # or p.DIRECT for non-graphical version
# using the eglRendererPlugin (hardware OpenGL acceleration)
egl = pkgutil.get_loader('eglRenderer')
if egl:
    p.loadPlugin(egl.get_filename(), "_eglRendererPlugin")
else:
    p.loadPlugin("eglRendererPlugin")
p.setAdditionalSearchPath(pybullet_data.getDataPath())  # optionally
p.setGravity(0, 0, -10)

planeStartPos = [0, 0, 0]
planeStartOrientation = p.getQuaternionFromEuler([0, 0, 0])
planeId = p.loadURDF("plane.urdf", planeStartPos, planeStartOrientation)

startOri = p.getQuaternionFromEuler([0, 0, 0])
startPos = [0, 0, 1]
urId = p.loadURDF("r2d2.urdf", startPos, startOri)

width = 640
height = 480

fov = 60
aspect = width / float(height)
near = 0.01
far = 10

view_matrix = p.computeViewMatrixFromYawPitchRoll([0, 0, 1], 3, 0, 0,
                                                  0, 2)
projection_matrix = p.computeProjectionMatrixFOV(fov, aspect, near, far)
images = p.getCameraImage(width,
                          height,
                          view_matrix,
                          projection_matrix,
                          shadow=True,
                          renderer=p.ER_BULLET_HARDWARE_OPENGL)
rgb_opengl = np.reshape(images[2], (height, width, 4)) * 1. / 255.

plt.imshow(rgb_opengl)
plt.show()
```

I got the following image when the EGL is not used:

![normal](https://user-images.githubusercontent.com/15166943/65171725-89a76f80-da19-11e9-8df4-ceaaf05e1d65.png)

But I got the image below when EGL is used:
![innormal](https://user-images.githubusercontent.com/15166943/65171753-9c21a900-da19-11e9-8cfc-6056e2fb1ded.png)

I am using Python 2.7 and ubuntu 18.04.

**Comment by taochenshh** [comment]
Does anyone have the same issue?

**Comment by erwincoumans** [comment]
I get a similar image for both Tiny and EGL. Could you update to latest pybullet? I think something related to egl/camera was fixed recently. It may not yet be in pypi, but I think it is.

Tiny: 
![tiny](https://user-images.githubusercontent.com/725468/67253821-99f2a600-f42e-11e9-862f-e38ef0836617.png)

EGL:
![egl](https://user-images.githubusercontent.com/725468/67253815-8fd0a780-f42e-11e9-8c2c-d0d2a94a910c.png)

**Comment by taochenshh** [comment]
Thanks for your reply. And I tried to install the latest pybullet from source. But I still got different images if I comment out the following lines:
```python
egl = pkgutil.get_loader('eglRenderer')
if egl:
    p.loadPlugin(egl.get_filename(), "_eglRendererPlugin")
else:
    p.loadPlugin("eglRendererPlugin")
```
I tried python 2.7 and python 3.7 on ubuntu 16.04 and ubuntu 18.04 and got the same issue.

**Comment by erwincoumans** [comment]
Does the camera rotate if you run the testrender_egl.py, located in bullet/examples/pybullet/examples?

**Comment by taochenshh** [comment]
Yes, I just uninstalled pybullet and built it again. Here is the output. Also, when I ran testrender_egl.py, the camera view doesn't change.

```bash
pybullet build time: Sep 23 2019 17:07:23
Loaded EGL 1.4 after reload.
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce GTX 1060/PCIe/SSE2
GL_VERSION=4.6.0 NVIDIA 396.37
GL_SHADING_LANGUAGE_VERSION=4.60 NVIDIA
Version = 4.6.0 NVIDIA 396.37
Vendor = NVIDIA Corporation
Renderer = GeForce GTX 1060/PCIe/SSE2
ven = NVIDIA Corporation
```

**Comment by erwincoumans** [comment]
>> pybullet build time: Sep 23 2019 17:07:23
That date is over a month ago. Can you get a fresh clone from 
git clone  https://github.com/bulletphysics/bullet3 and try again?

**Comment by taochenshh** [comment]
The repo on my machine was indeed old, sorry for this. Installing the latest PyBullet did solve the issue. Thank you very much!
