### ISSUE TITLE
Best Practices for PyBullet on a Cluster

### ISSUE THREAD

**Issue by MichaelLutter** [bulletphysics/bullet3#2414]
I want to parallelize my environments to speed up my reinforcement learning using different nodes within a cluster. Therefore, I use OpenMPI to parallelize across nodes and I wonder if some best practices exist for running Pybullet instances in a cluster setup to achieve optimal performance?

More concretely, how many cores / memory should one reserve within a single node for each simulator running within its own python process? From my understanding, a single PyBullet instance is parallelized across cores. Should one run multiple PyBullet instances on a single node or does this parallelization within a node slow down each PyBullet instance too much?

Thanks.

**Comment by erwincoumans** [comment]
So in a nutshell, yes it is best to run as many DIRECT pybullet instances as you have cores/threads/processes.
There are some examples using MPI and PyBullet, for example pybullet version of DeepMimic:
https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/gym/pybullet_envs/deep_mimic
Here is also a simple multiprocessing example:
https://github.com/erwincoumans/pybullet_robots/blob/master/batchsim3.py
Good luck.
