### ISSUE TITLE
Relative paths in includes

### ISSUE THREAD

**Issue by chrisaverage** [bulletphysics/bullet3#2416]
Bullet files assume bullet top include directory is added to compiler's include path and so they do includes like `#include "Bullet3Common/b3Vector3.h"`. This is a problem with package managers like vcpkg that place bullet in a subdirectory (e.g. `"bullet/Bullet3Common/b3Vector3.h"`), because then you either have to fiddle with the package manager, which is a pain, or manually add that subdirectory to your project, which kinda defeats the purpose of a package manager.

It would work a lot better if bullet used relative paths, e.g. `#include "../../Bullet3Common/b3Vector3.h"`. It wouldn't matter then in what subtree the library was placed in.

I'd be willing to do the work, but since it's a lot of files I'd like to know first if such a pull request would at all be accepted?

**Comment by erwincoumans** [comment]
Not going to refactor this code now. Will consider the comments for a future project.
