### ISSUE TITLE
How to change the elasticity of an object in pybullet?

### ISSUE THREAD

**Issue by ktlichkid** [bulletphysics/bullet3#2422]
Hi guys.
I am trying to build a simulator from pybullet. I have one issue that whenever my end-effector touches the rigid objects on the desk, it will collide with the object and bounce up a little bit. I am wondering if it is possible to change the elasticity of the object and end-effector so that I could make the collision less significant. How should I change my urdf files?

By searching the PyBullet Quickstart Guide I didn't find anything useful. I really appreciate your help! Thank you!

**Comment by erwincoumans** [comment]
There is contact damping/stiffness for this. You could use pybullet.changeDynamics, check the [pybullet quickstart guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.d6og8ua34um1).
