### ISSUE TITLE
Importing ShapeNet Objects

### ISSUE THREAD

**Issue by JonathanYang0127** [bulletphysics/bullet3#2433]
When trying to import ShapeNet objects into pybullet, I found out that pybullet doesn't support objects with more than one texture in the .mtl file. I tried the following workarounds:

1. obj2sdf
I used the obj2sdf application to convert the obj files into sdf files. However, I ran into a couple of problems. For one object, not all textures were loaded. For another I couldn't interact with the object in the simulation (it wasn't affected by gravity either).

This file contains the object for which not all textures were loaded:
[5982f083a4a939607eee615e75bc3b77(1).zip](https://github.com/bulletphysics/bullet3/files/3705664/5982f083a4a939607eee615e75bc3b77.1.zip)

What the model should look like:
![canonical](https://user-images.githubusercontent.com/14262458/66454171-dc25eb80-ea1b-11e9-99a3-dcf49ea5cf4b.png)

What it looks like inside pybullet:
![Screenshot from 2019-10-08 22-33-54](https://user-images.githubusercontent.com/14262458/66454213-08416c80-ea1c-11e9-9257-bdb66ce1ab3e.png)

This file contains the object I couldn't interact with:
[1eccbbbf1503c888f691355a196da5f.zip](https://github.com/bulletphysics/bullet3/files/3705668/1eccbbbf1503c888f691355a196da5f.zip)

2. Solidworks
I imported the object into solidworks, then exported into a urdf file. However, when I loaded the urdf into pybullet, the object did not appear.

[model.zip](https://github.com/bulletphysics/bullet3/files/3705670/model.zip)

I am wondering why I am running into these errors. Also, I am wondering if anyone else tried to/succeeded in importing ShapeNet objects, and what they did to get around the texture limit. Thanks in advance!

**Comment by erwincoumans** [comment]
Compare with various existing URDF files in PyBullet to understand its limitations. A single link can only have 1 material/texture. So you have to break up the link into multiple links (attached with fixed joints) each with their own material. Another approach is to use a texture atlas and different UV coordinates, so it is a single material for the entire robot.
