### ISSUE TITLE
Importance of Damping Coefficients

### ISSUE THREAD

**Issue by gktg1514** [bulletphysics/bullet3#2439]
When I was examining your [baxter inverse kinematics demo code](https://github.com/erwincoumans/pybullet_robots/blob/master/baxter_ik_demo.py) I realized that you did not provide any damping coefficients for "calculateInverseKinematics" function. However, you provided them for kinematics function in your [general inverse kinematics code](https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/inverse_kinematics.py). 

I am confused in this point. Are these coefficients important or not on accuracy of inverse kinematics ?

**Comment by erwincoumans** [comment]
Those damping parameters can help convergence, as described in the damped least square paper.
You can measure the residual to determine accuracy of the inverse kinematics. You can increase the number of IK iterations if needed.
