### ISSUE TITLE
.h and .cpp File Separation

### ISSUE THREAD

**Issue by kklouzal** [bulletphysics/bullet3#244]
Is there any specific reason behind the `.h` and `.cpp` files being bundled together? If not I would like to make a request to have the `.h` files separated out into an `include` folder leaving all the `.cpp` files behind in the `src` folder.

This would make bullet much more organized and easier to integrate into other user created libraries that extend bullet without wanting to fork the project, such as wrappers, let alone projects generated by the Premake scripts would also be much more clean and concise.

**Comment by erwincoumans** [comment]
closing out-of-date issues (we are not refactoring files/folders anymore)
