### ISSUE TITLE
shadow variable

### ISSUE THREAD

**Issue by maddin200** [bulletphysics/bullet3#2443]
bullet3-master/src/LinearMath/btQuickprof.cpp) (line 665):  same variable i (as well line 657).

**Comment by wduminy** [comment]
There is likely to be many places in the code that uses `i` in the way that [line 665](https://github.com/bulletphysics/bullet3/blob/master/src/LinearMath/btQuickprof.cpp#L665) uses it. 
How would one motivate fixing all of them? Is it worth the effort?
