### ISSUE TITLE
Automatic Bullet precision detection

### ISSUE THREAD

**Issue by akortunov** [bulletphysics/bullet3#2451]
A related thread: https://github.com/OpenMW/openmw/pull/2049

Is there a reliable way to detect if Bullet library was built with the USE_DOUBLE_PRECISION flag during client code compilation, especially on Windows?

We need to use different code branches for physics with single precision and with double precision.

**Comment by erwincoumans** [comment]
This is not possible. You can create a small program compile/link and use the btIsDoublePrecision API.
