### ISSUE TITLE
Has the document of pybullet been updated？

### ISSUE THREAD

**Issue by Megatron2032** [bulletphysics/bullet3#2453]
what does URDF_MAINTAIN_LINK_ORDER mean？
Some APIs for deepmimic are not in the document.

**Comment by erwincoumans** [comment]
Indeed, doc is missing some api's, please mention them here.
PyBullet link index can be different from their order in the urdf file without that flag:

urdf: parentlink0, link1, link2
pybullet: parentlink0, link2, link1 (without that flag)

**Comment by Megatron2032** [comment]
getDifferenceQuaternion
getAxisAngleFromQuaternion

URDF_MAINTAIN_LINK_ORDER

changeDynamics(activationState):
ACTIVATION_STATE_SLEEP
ACTIVATION_STATE_ENABLE_SLEEPING
ACTIVATION_STATE_DISABLE_WAKEUP

setJointMotorControlMultiDof
setJointMotorControlMultiDofArray
STABLE_PD_CONTROL

some missing APIs in deepmimic files.

**Comment by Megatron2032** [comment]
some functions used in stablePD：
calculateMassMatrix
calculateInverseDynamics

@erwincoumans

**Comment by erwincoumans** [comment]
Add arguments and outputs of getJointStateMultiDof

**Comment by erwincoumans** [comment]
Did another pass on updating the quickstart guide. Note that some of those APIs are experimental/obscure and not well documented.
