### ISSUE TITLE
Obtain forward kinematic equation

### ISSUE THREAD

**Issue by hksBRT** [bulletphysics/bullet3#2455]
If we have a URDF defining our robot, and are able to obtain the right end effector link position by feeding joint values, is there a way to obtain the underlying kinematic equation from pybullet? The relation from the base to the end effector?

**Comment by erwincoumans** [comment]
The forward kinematics are simply a multiplication of matrices. Those matrices are not exposed at the moment.
With "kinematic equation", do you mean exposing those matrices?

**Comment by hksBRT** [comment]
yes
