### ISSUE TITLE
Building in Android Studio?

### ISSUE THREAD

**Issue by dacobi** [bulletphysics/bullet3#2469]
How do you build Bullet Physics for an Android app?

I've tried importing the Android folder in build3, but this doesn't create a project that can be compiled.

Btw I need the C++ libraries, not python.

**Comment by erwincoumans** [comment]
I have not, but building Bullet is trivial. Just include the Bullet/src folder in the include directories, and add all files of Bullet/src/BulletCollision, Bullet/src/BulletDynamics and Bullet/src/LinearMath and you are done.
