### ISSUE TITLE
USE_DOUBLE_PRECISION flag not working (Bullet 2.88 release - CMake 3.15.5)

### ISSUE THREAD

**Issue by danibix95** [bulletphysics/bullet3#2479]
**Issue**
Bullet library is not built with double precision support when `USE_DOUBLE_PRECISION` variable is set to `ON`.

In particular, I encountered this issue while I was building another library that requires Bullet Physics with double precision support. That building process returned me an error of `undefined references` to a function where some of the parameters expected a `float` type, whereas in the source code they are set to `btScalar`.

Here is reported one of the obtained errors:

    in function `btDantzigSolver::solveMLCP(btMatrixX<float> const&, btVectorX<float> const&, btVectorX<float>&, btVectorX<float> const&, btVectorX<float> const&, btAlignedObjectArray<int> const&, int, bool)':
    include/bullet/BulletDynamics/MLCPSolvers/btDantzigSolver.h:75: undefined reference to `btSolveDantzigLCP(int, float*, float*, float*, float*, int, float*, float*, int*, btDantzigScratchMemory&)'

and [here](https://github.com/bulletphysics/bullet3/blob/master/src/BulletDynamics/MLCPSolvers/btDantzigLCP.h#L70) is the source code line where the function is declared.

To further investigate, I wrote a simple program to check which is the type `btScalar` alias (which typedef in [`btScalar.h`](https://github.com/bulletphysics/bullet3/blob/master/src/LinearMath/btScalar.h#L304-L312) file has been performed):

    #include <iostream>
    #include "LinearMath/btScalar.h"
    #include <typeinfo>

	int main() {
		btScalar num = 2.0;
		std::cout << "btScalar is a: ";
		if (typeid(num) == typeid(double)) {
			std::cout << typeid(num).name() << " - double" << std::endl;
		}
		else {
			std::cout << typeid(num).name() << " - float" << std::endl;
		}

		return 0;
	}

Then I compiled it including and linking the proper library:

    g++ check_type.cpp -lLinearMath -L<path_Bullet_libs> -I<path_Bullet_header_files>

Unfortunately, once it is executed, it returns the latter message, meaning that `btScalar` is defined as `float`.

**Potential Causes**
One possible cause of this issue might be the fact that I am using a recently released version of CMake, which might not treat properly the `add_definitions` directive (which has been superseded by `add_compile_definitions` directive since CMake 3.12) [employed to enable the double precision support](https://github.com/bulletphysics/bullet3/blob/master/CMakeLists.txt#L216).

**Building System**
 + Ubuntu 19.10 (Docker Image)
 + cmake 3.15.5
 + g++ 9.2.1

**Steps to reproduce the issue**
 + create a new `Ubuntu:19.10` Docker image
 + install on it basic packages for building Bullet

       build-essential python3 python3-pip libglib2.0-dev freeglut3 freeglut3-dev build-essential unzip wget curl libgl1-mesa-glx libgl1-mesa-dri mesa-utils libglu1-mesa-dev mesa-common-dev
 + install `numpy`
 + install [cmake](https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5.tar.gz) from sources
 + download [Bullet Physics](https://github.com/bulletphysics/bullet3/archive/2.88.tar.gz) and decompress it (2.88 release)
 + build the library with `build_cmake_pybullet_double.sh` script
 + execute the program provided above and check whether its output is double or float

**Workaround**
For the moment it is possible to bypass this problem by temporarily defining (before compiling) the pre-processor constant `BT_USE_DOUBLE_PRECISION` directly in the file `LinearMath/btScalar.h`, just above its usage for selecting whether to define `btScalar` as `double` or `float`.

    #ifndef BT_USE_DOUBLE_PRECISION
        #define BT_USE_DOUBLE_PRECISION
    #endif
    #if defined(BT_USE_DOUBLE_PRECISION)

**Comment by erwincoumans** [comment]
Both the Bullet library and the client program need to gave the BT_USE_DOUBLE_PRECISION preprocessor define set. cmake will do this for the library. Your test program needs the flag to (-D BT_USE_DOUBLE_PRECISION) . Your workaround is fine too.
