### ISSUE TITLE
quick start guide doesn't have definations of all the available functions. Where can we get them?

### ISSUE THREAD

**Issue by asawaswapnil** [bulletphysics/bullet3#2485]
quick start guide doesn't have definitions of all the available functions. Where can we get them? For example arguments and outputs of getJointStateMultiDof are not explained in the quick starter guide.

**Comment by erwincoumans** [comment]
There is some lag between adding functions in pybullet.c and in adding them to the quickstart guide.
So the ultimate source is the source of [pybullet.c](https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/pybullet.c).

**Comment by asawaswapnil** [comment]
Thank you!
