### ISSUE TITLE
Slippery ground

### ISSUE THREAD

**Issue by davhak** [bulletphysics/bullet3#2490]
Hi,
My modelled bipedal robot in PyBullet has flat rubber surface under the feet making it tightly bound to the ground. I played around with changeDynamics to set the 'lateralFriction' together with 'spinningFriction' to 1 but this has, basically, no effect, and the robot has still a very slippery behaviour when moving the legs. The reason of this might be that when making a step (by moving any of the revolut joints on the knee or on the hip) the foot, actually, does not slide but slightly rolls (by lifting one of its sides while the opposite side is still on the ground) and this i guess is not qualified as either 'lateralFriction' or 'spinningFriction'? Setting the 'rollingFriction' above 0 on both feet does have a strong effect on the robot's rolling (as the feet hard-bound to the robot) i.e. slowing its rolling movement down, but this is not the effect I want. Rather I want to see the feet not sliding on the ground but because of the high friction making its upper part tilting during joints movements (unless the feet is lifted above the ground).
I have tried to increase the gravity which helps a bit but not much. Also tried changing the feet from flat shape to spheres but the effect is the same.

Is there a way to achieve a stronger friction with the ground? Or in other words constraint the (x,y) positions of feet as long as they contact with the ground?
Thanks a lot for any suggestion.

**Comment by erwincoumans** [comment]
Without a very small PyBullet reproduction case we cannot do anything. Best to discuss in the Bullet forums or in StackOverflow.
