### ISSUE TITLE
Inverse Kinematics for multiple end effectors

### ISSUE THREAD

**Issue by soshishimada** [bulletphysics/bullet3#2492]
Is it possible to compute Inverse Kinematics for multiple end effectors?

**Comment by erwincoumans** [comment]
Yes, you can use pybullet.calculateInverseKinematics2 and pass a list of endeffector indices and list of target positions. See also the [PyBullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#).
