### ISSUE TITLE
How to calculate Center of Mass Jacobian

### ISSUE THREAD

**Issue by soshishimada** [bulletphysics/bullet3#2504]
Is it possible to compute a center of mass Jacobian on pybullet?
If so, it would be great if you could provide a brief instruction.

**Comment by erwincoumans** [comment]
There is an example to calculate a Jacobian here:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/jacobian.py

**Comment by soshishimada** [comment]
Thank you for the comment, and sorry for my unclear question.
By center of mass jacobian, I meant the center of mass of a whole skeleton, not CoM of each link. Is it possible?

**Comment by junhyeokahn** [comment]
Any updates on this?
