### ISSUE TITLE
Extras/Serialize/BulletFileLoader/bDNA.cpp:179: possible bad assert ?

### ISSUE THREAD

**Issue by dcb314** [bulletphysics/bullet3#251]
Extras/Serialize/BulletFileLoader/bDNA.cpp:179:17: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]

```
assert(!m_Names.size() == 0 && "SDNA empty!");
```

Maybe

```
assert(m_Names.size() == 0 && "SDNA empty!");
```

was intended.

**Comment by erwincoumans** [comment]
m_Names.size() should not be zero. The second part is just a readable string.
