### ISSUE TITLE
I would like to speed up my dqn code.

### ISSUE THREAD

**Issue by Alchemist77** [bulletphysics/bullet3#2512]
Hi,

Thank you for supporting this simulation. 

I made a dqn code that picks and places an object using pybullet.
I did not use openai env, so I prepared my own env_reset. Also I added this lines (to increase speed performance)
```     
p.configureDebugVisualizer(p.COV_ENABLE_RENDERING,0)
p.configureDebugVisualizer(p.COV_ENABLE_GUI,0)
p.configureDebugVisualizer(p.COV_ENABLE_SEGMENTATION_MARK_PREVIEW,0)
p.configureDebugVisualizer(p.COV_ENABLE_DEPTH_BUFFER_PREVIEW,0)
p.configureDebugVisualizer(p.COV_ENABLE_RGB_BUFFER_PREVIEW,0)
``` 

In addition, I checked this code to add my code
https://github.com/bulletphysics/bullet3/blob/aec9968e281faca7bc56bc05ccaf0ef29d82d062/examples/pybullet/examples/saveRestoreState.py
But it is not working in my code.

In my understanding of saveRestoreState.py, after resetsimulation(),  it loads all objects and robots and save and restore.

Is it possible to use the file (txt file) that saved the environment of all objects, robot and gripper after resetsimulation() using restore function? I did it, but i cannot restore the txt file after resetsimulation().

Another issues that i removed p.loadURDF ("plane.urdf") (because of many consumption of memories). Is it useful?

Final question, getCameraImage, this function need a lot of time consuming. Is there any way to get input image like more light using the funtion?

It is my code you can check,
https://github.com/Alchemist77/DQN_PYTORCH/blob/master/ur5_robotiq140_dqn.py
https://github.com/Alchemist77/DQN_PYTORCH/blob/master/Screenshot%20from%202019-11-30%2019-25-53.png

my computer specification
Intel® Core™ i7-9700K CPU @ 3.60GHz × 8 
GeForce RTX 2080 Ti/PCIe/SSE2
31,3 GiB

Thank you.

**Comment by erwincoumans** [comment]
You should try to avoid resetSimulation in the loop, so you can avoid doing loadURDF (or createMultiBody). saveState and restoreState is made for this: at program startup, you create the scene once, and then saveState. At reset, you only 'restoreState'.
There is an example of save/restoreState in PyBullet here:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/saveRestoreState.py
