### ISSUE TITLE
Missing Function Implementations in Bullet3Collision Narrowphase

### ISSUE THREAD

**Issue by Levi-Armstrong** [bulletphysics/bullet3#2514]
I have been working on a collision detection implementation using Bullet3Collision and cannot seem to find implementation of some functions like [this](https://github.com/bulletphysics/bullet3/blob/c4300dc2999b37ac0f689a54df422434a6cf5ddd/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h#L44) one. There also seem to be other function related to GPU also missing. Am I missing something somewhere?

**Comment by erwincoumans** [comment]
Bullet3Collision and all of the OpenCL parts are not actively developed anymore for many years, and unsupported. You are free to use it for your own research.
