### ISSUE TITLE
(PyBullet Documentation) Combining flags in loadURDF 

### ISSUE THREAD

**Issue by shrutij01** [bulletphysics/bullet3#2518]
Hi, just a suggestion for a minor correction in the documentation.

In the PyBullet Quickstart Guide, it is mentioned that the optional flags for loadURDF can be combined using a logical OR. But shouldn't they be combined using bitwise OR?

**Comment by erwincoumans** [comment]
Fixed, it is a bitwise OR of course. Thanks for the report!
