### ISSUE TITLE
addUserDebugParameter

### ISSUE THREAD

**Issue by sun-te** [bulletphysics/bullet3#2519]
If too many Debug Parameters are added by `pybullet.addUserDebugParameter`,  there will be too many debug sliders (at most 28 sliders can be shown at one time, however 83 parameters I need to debug in my case) that can not be all shown in the GUI mode.Wouldn't it be nicer to enable more debugParameter to appear on the GUI interface? Thanks!

**Comment by erwincoumans** [comment]
This commit increases the max to about 300:
https://github.com/bulletphysics/bullet3/commit/7f3059c7a97f9b9a898902ce12b8ea0ea62a746a
Thanks for the feedback!
