### ISSUE TITLE
Does calculateInverseDynamics consider external force?

### ISSUE THREAD

**Issue by soshishimada** [bulletphysics/bullet3#2520]
Does "calculateInverseDynamics" consider external force e.g. ground reaction force when applied on a floating base robot?
So, when zero acceleration is given to this function, the returned value is:

centripetal + Coriolis + gravity forces ?

or

centripetal + Coriolis + gravity forces + external force ?

**Comment by erwincoumans** [comment]
External force is not taken into account, you'll have to add this manually.
