### ISSUE TITLE
calculateInverseDynamics not working for floating base xml file

### ISSUE THREAD

**Issue by soshishimada** [bulletphysics/bullet3#2521]
Hello.
"calculateInverseDynamics" works for floating base urdf file e.g. humanoid/humanoid.urdf.
However, for xml file e.g. mjcf/humanoid.xml,
it always returns a list of zero.

Is there any way to avoid this?
Thanks in advance.

**Comment by erwincoumans** [comment]
use the loadURDF function instead.
