### ISSUE TITLE
proper way to get friction force in btMultibody

### ISSUE THREAD

**Issue by Rullec** [bulletphysics/bullet3#2525]
Hi All,

  Thanks for your time in this issue. 

  I am truly a beginner in bullet and have less knowledge for it.Currently I am using **btMultibody** to construct a robot with a floating base. At this moment I can get the the global pos & contact force (a force perpendiculared to the contact microfacet) applied in these contact points from class btPersistentManifold and btCollisionObject.
  
  But now I still **wonder the friction force in these contact points**, what I got now is now a vertical contact force looks like (0, 250, 0), with no x and z axis components if this contact force is between my object and the ground. I have also finished both of the Quick start and the User Manual and the classic RigidBodyDynamic book by featherstone(2008), but It seems no answer can I found.

  How can I get these friction force applied between collision objects from bullet? I got trapped in this questions for couple of days. 

  Thanks all tips and help in any degree!

**-----------------------update 1------------------------**
After my insisting research, I got something looks like that:
```
btMultibodyLink test_link = btmultibody_ptr->getLink(id);
std::cout << "---------bullet test link " << id << ", frame " << mCurInfoId << "---------" << std::endl;
std::cout << "constraint torque = ";
b3printf(test_link.m_appliedConstraintTorque);
std::cout << "constraint force = ";
b3printf(test_link.m_appliedConstraintForce);
// Before that I collect the contact force and make them in an array so-called total_contact_force.
std::cout << "sum of contact forces = " << total_contact_force[id].transpose() << std::endl;
```

And what shows up is these logs:
---------bullet test link 4, frame 275-------------
constraint torque = 131.215 -35.1404 -6.0525
constraint force = 52.1674 269.433 -433.353
sum of contact forces =       0 269.433       0      20

And the sum of contact forces in y axis is exactly the same as "constraint force" accordly. Can I say the constraint force derived from btMultibodyLink::m_applidedConstraintForce is the collision force? And maybe **the constraint torque is the sum of torsional friction and the torque generated by the collision force to the COM of this link in world frame?** 

P.S. There is only a btMultibody robot and a ground in my scene, quite simple. I have never set up any CONSTRAINTS except for the joint lims... I guess the m_appliedConstraintTorque is generated by the constraint solver for modeling the contact constraint in bullet, But I can not have any evidence in the manual as well...If any of you know where they are or any explanation about them, please let me know, It would be very helpful!

Thanks you again!

**Comment by Steven89Liu** [comment]
the friction related constraints are processed by these functions, addMultiBodyTorsionalFrictionConstraint() and addMultiBodyFrictionConstraint().  Could you attach your simple test? then we can work together to figure out what happened there. thanks.

**Comment by erwincoumans** [comment]
PyBullet reports the contact normal force and also lateral friction forces/directions, you can use it as sample code:

https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/PhysicsServerCommandProcessor.cpp#L7479

~~~~~~~~~~~~~~~~
for (int p = 0; p < manifold->getNumContacts(); p++)
					{
						b3ContactPointData pt;
						pt.m_bodyUniqueIdA = objectIndexA;
						pt.m_bodyUniqueIdB = objectIndexB;
						const btManifoldPoint& srcPt = manifold->getContactPoint(p);
						pt.m_contactDistance = srcPt.getDistance();
						pt.m_contactFlags = 0;
						pt.m_linkIndexA = linkIndexA;
						pt.m_linkIndexB = linkIndexB;
						for (int j = 0; j < 3; j++)
						{
							pt.m_contactNormalOnBInWS[j] = srcPt.m_normalWorldOnB[j];
							pt.m_positionOnAInWS[j] = srcPt.getPositionWorldOnA()[j];
							pt.m_positionOnBInWS[j] = srcPt.getPositionWorldOnB()[j];
						}
						pt.m_normalForce = srcPt.getAppliedImpulse() / m_data->m_physicsDeltaTime;
						pt.m_linearFrictionForce1 = srcPt.m_appliedImpulseLateral1 / m_data->m_physicsDeltaTime;
						pt.m_linearFrictionForce2 = srcPt.m_appliedImpulseLateral2 / m_data->m_physicsDeltaTime;
						for (int j = 0; j < 3; j++)
						{
							pt.m_linearFrictionDirection1[j] = srcPt.m_lateralFrictionDir1[j];
							pt.m_linearFrictionDirection2[j] = srcPt.m_lateralFrictionDir2[j];
						}
						m_data->m_cachedContactPoints.push_back(pt);
					}
~~~~~~~~~~~~~~~~

**Comment by Rullec** [comment]
thanks all of you a lot! Sorry for my late reponse, I will do these tests at once:)

**Comment by erwincoumans** [comment]
The friction and normal forces of contacts are stored in the contact points. Check my previous reply.
