### ISSUE TITLE
PointCloud Data Discrepancy

### ISSUE THREAD

**Issue by krish-dx** [bulletphysics/bullet3#2538]
Following the [PointCloudFromCamera](https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/pointCloudFromCameraImage.py) script I am able to get the point cloud data correctly.

The above approach works when the `view_matrix` parameters of the `getCameraImage` is not modified.  The [`getRayFromTo`](https://github.com/bulletphysics/bullet3/blob/08321b96ba43b9825274c96d0d550feaaf85ae91/examples/pybullet/examples/pointCloudFromCameraImage.py#L10) uses the parameters of  obtained from the `getDebugVisualizerCamera` to compute the projection and when the `viewMatrix` is set in `getCameraImage` the resulting point cloud is not as it should be. 

In the point cloud example script there are few hardcoded variables that would be hard for beginners to get on with.

- `[farPlane=10000]`(https://github.com/bulletphysics/bullet3/blob/08321b96ba43b9825274c96d0d550feaaf85ae91/examples/pybullet/examples/pointCloudFromCameraImage.py#L17)
How is this value set? 
- If `far=1000` then `farPlane` should be same?
- When the value of far is changed `far=20.0` the corners of the cube are not aligned as shown in the picture. See the red ball.

 
<img width="958" alt="Screen Shot 2019-12-12 at 12 53 09" src="https://user-images.githubusercontent.com/58452843/70681317-615ca380-1cde-11ea-9831-e22cdc32bd4c.png">

**Following feature would be great.**
1. Can there be any additional helper function that automatically returns the point cloud data based on the set camera parameters?
2. In addition to the point cloud, a helper function to compute surface normals of a given object_id?

**Comment by erwincoumans** [comment]
This was just an example to encourage you to explore further. We don't intend to support or improve this at the moment (no man power for this).

>> How is this value set?

The view frustum is defined by various planes, including a near plane and far plane. 

far should be equal to farPlane.

You can use resetDebugVisualizerCamera to assign a view and projection matrix.

I would use an OpenGL or graphics tutorial to compute the point cloud by yourself.
Good luck!
