### ISSUE TITLE
Cannot load SDF format file

### ISSUE THREAD

**Issue by freetown113** [bulletphysics/bullet3#2539]
Hi, 
  I have a problem while loading this model in pybullet. The file is in SDF format. Can you give me some hints about it?

 Thank you!
 
[model.txt](https://github.com/bulletphysics/bullet3/files/3948987/model.txt)

**Comment by erwincoumans** [comment]
revolute joints need limits. Use continuous instead. The parser reports errors, watch and fix them. Also, there are working sdf files in Bullet/data folder, compare them with yours. Good luck!

**Comment by freetown113** [comment]
Thanks a lot!
