### ISSUE TITLE
script got killed after a certain amount of time

### ISSUE THREAD

**Issue by qiuyuchen14** [bulletphysics/bullet3#2547]
I'm using pybullet to load some models and textures, and save them in each iteration. However my script got killed after I saved ~2000 images. I think it might because it reaches the limit of opened files the system permits. My script has something like: "p.createVisualShape()", "p.createMultiBody()", "p.loadTexture()", "p.loadURDF()", and after each iteration, I use p.resetSimulation(). Is there anything in pybullet to close the loaded image files or obj files? Or there might be other issues? Thanks!!

**Comment by erwincoumans** [comment]
It could be some memory leak and if so, we will fix it. It is hard to tell without a reproduction case. Can you try to re-create it in a simple small pybullet script and share it (attach a zip file)?
