### ISSUE TITLE
addUserDebugText changes robot performance

### ISSUE THREAD

**Issue by soshishimada** [bulletphysics/bullet3#2557]
Hello.
I am simulating a bipedal robot that does squat.
The robot performance changes with and without "addUserDebugText" function in the simulation loop.

I have no idea why this is happening...
Are there any calculations inside  "addUserDebugText" that changes dynamics parameters?

Thanks in advance!

**Comment by erwincoumans** [comment]
There should be no difference, as long as you call 'stepSimulation'.

You are not making any calls to 'setRealTImeSimulation(...)', are you?

**Comment by erwincoumans** [comment]
Without a simple reproduction case there is nothing we can do. Please re-open if you can tell us how to reproduce the issue.
