### ISSUE TITLE
I Can't Run Reinforcement Learning Training Example

### ISSUE THREAD

**Issue by knkrgz** [bulletphysics/bullet3#2568]
Hi all,

I am trying to follow pybullet quickstart guide and run an example. I want to train minitaur and visualize minitaur robot for academic purposes.  I am actually newbie in python environment and rf learning. I am using anaconda navigator/promt. I created a conda environment with python 3.5 and also 3.6. Installed these python packages: pip install gym, tensorflow, agents, pybullet, ruamel.yaml
I believe there is a version problem but i am not sure. 

I tried to run this line  first and result is below.
python -m pybullet_envs.agents.train_ppo --config=pybullet_minitaur --logdir=pybullet_minitaur
![image](https://user-images.githubusercontent.com/50485779/71765994-e452d180-2f0b-11ea-9b86-844f4d867208.png)

I think it should create a log file which is 20200104T155451-pybullet_minitaur then ı should use it with this line:

python -m pybullet_envs.agents.visualize_ppo --logdir=pybullet_minitaur/20200104T155451-pybullet_minitaur --outdir=pybullet_minitaur

I also tried with pendulum if I write something wrong. Shouldn't it start pybullet automatically?
![image](https://user-images.githubusercontent.com/50485779/71766076-19abef00-2f0d-11ea-945d-872c2964e6c3.png)

How do ı resume run? How is the 'magic' happens and it walks in pybullet with these training outputs?
INFO:tensorflow:Resume run and write summaries and checkpoints to pendulum\20200104T161024-pybullet_pendulum.

my pip list in case you wonder
![image](https://user-images.githubusercontent.com/50485779/71766149-e1f17700-2f0d-11ea-8d5e-a01627d1866b.png)

I can only look into rl learning at weekends because of my work. I just need a little bit pushing, thank you for your time.

**Comment by erwincoumans** [comment]
You could use colab instead, check this:
https://twitter.com/erwincoumans/status/1212962029939478533
or use stable_baselines, it has clear description how to train and enjoy PyBullet environments:
https://github.com/hill-a/stable-baselines and
https://github.com/araffin/rl-baselines-zoo
