### ISSUE TITLE
Monitoring contact forces?

### ISSUE THREAD

**Issue by alda30** [bulletphysics/bullet3#257]
Is there any prameter in Bullet to monitor the "contact forces" between rigid bodies?

The forces between rigid bodies normally can contain the terms:
1) Dynamic force (impulse/time)
2) Network forces (forces imposed to the contact of interest due to other contacts which neighbouring rigid object may have)
3) External forces (gravity, etc)

Or can you address the "rigid body solver" in Bullet, which is responsible for updating forces in each iterative step?

Thanks

**Comment by erwincoumans** [comment]
closing out-of-date issues.
