### ISSUE TITLE
changeVisualShape does not work with eglRenderer in Direct Mode

### ISSUE THREAD

**Issue by liruiw** [bulletphysics/bullet3#2571]
Hello,

I'm having an issue with changeVisualShape with loaded texture in Direct Mode. The images returned by getCameraImage seems not changing, while it's updated in GUI mode and TinyRenderer. Any ideas why it could be happening? 

Also, is there APIs to change ambient light intensities in Direct Mode? 

Thanks!

**Comment by bibbygoodwin** [comment]
Hi @liruiw, did you resolve this at any point? I'm not using loaded textures, just standard geoms from an .mjcf file, but believed that calling changeVisualShape would work. For me, this method appears to have no effect no matter which renderer I use (ER_BULLET_HARDWARE_OPENGL or ER_TINY_RENDERER)

**Comment by ycheng517** [comment]
This is still an issue, see possibly related ticket: https://github.com/bulletphysics/bullet3/issues/2777
