### ISSUE TITLE
The btGjkPairDetector fails to detect collision between primitive sphere and primitive box.

### ISSUE THREAD

**Issue by Levi-Armstrong** [bulletphysics/bullet3#2579]
I have been using Bullet as a collision checker for robotic motion planning and I have noticed that sometime it fails to detect a collision between objects. Below is one case that can be used to confirm it fails. Is this a result of the size of the objects?

Sphere:
Radius: 0.01
Position:  0.019576, -1.03115, 0.398155

Box:
Side length: 0.005
Position: 0.0275, -1.0275, 0.3925

Box:
Side length: 0.005
Position: 0.0275, -1.0275, 0.3975

Box:
Side length: 0.005
Position: 0.0275, -1.0275, 0.4025

Update: I added a few more test cases. I also tested it again but I scaled everything by a factor of 10 and it was then able to detect collision between the sphere and all of the boxes. Is there something I can tune so at the original scale Bullet detects the collision?

**Comment by Levi-Armstrong** [comment]
I rebuilt bullet with double precision turn on and now everything works. Are there known issues with using double precision?

**Comment by erwincoumans** [comment]
Double precision is preferred. For our robotics and machine learning research we exclusively use double precision version of PyBullet (using Bullet under the hood), since it is more precise.

Also, What collision margins do you use? The relative sizes (-1.03115 and 0.005) could be a challenge for single precision.

**Comment by erwincoumans** [comment]
If you have a small reproduction case for double, let us know and re-open. Thanks!

**Comment by Levi-Armstrong** [comment]
Thank you for the feedback, I will create test only using Bullet components and post here.
