### ISSUE TITLE
BT_USE_DOUBLE_PRECISION is not added to BulletConfig.cmake.in

### ISSUE THREAD

**Issue by Levi-Armstrong** [bulletphysics/bullet3#2582]
It looks like this is exported to bullet.pc.in but is not done for BulletConfig.cmake.in. Should BULLET_DEFINITIONS in BulletConfig.cmake.in be changed to the argument used in bullet.pc.in?

**Comment by erwincoumans** [comment]
There is no maintainer for those files, so if you have an improvement suggestion, please submit a PR. Thanks!

**Comment by Levi-Armstrong** [comment]
Ah, I will create a PR. Is there any objections to upgrading to use modern cmake functionality?

**Comment by schornakj** [comment]
@Levi-Armstrong Were you able to get anywhere with this?
