### ISSUE TITLE
Option for collision distance or margin ?

### ISSUE THREAD

**Issue by v-wewei** [bulletphysics/bullet3#2584]
Hi, 
Dose pybullet share the feature for collision margin or collision distance? since i see my gripper often give the distance which is larger than the actual radius of the cylinder. for example cylinder with radius of 0.04 m, but the two finger gripper distance of 0.0439 m, also actually with position control i can grasp the cylinder .
So, would it be able to adjust the collision margin for my grasping task ?
the visual shape is same as the collision shape in the picture.

![image](https://user-images.githubusercontent.com/46891883/72417122-2c4ae180-37b3-11ea-8556-aa1d0e81c6d6.png)

Thanks very much .

**Comment by erwincoumans** [comment]
See https://github.com/bulletphysics/bullet3/pull/2626
