### ISSUE TITLE
Changing the masses of links of the model loaded from an URDF file

### ISSUE THREAD

**Issue by kniranjankumar** [bulletphysics/bullet3#2585]
I have a reinforcement learning problem where I want to change the masses of the links of a model I load from URDF file. I wan to be able to do instantiate different masses for each episode of my training process. Is there a way to accommodate this requirement with pybullet as it is right now? I have tried using createMultiBody but I run into the problem of not being able to limit joint angles. Any help would be appreciated. Thanks!

**Comment by erwincoumans** [comment]
Yes, you can use pybullet.changeDynamics to change masses, after you load a URDF file.
