### ISSUE TITLE
Saving robot positions as new urdf 

### ISSUE THREAD

**Issue by EdwardSmith1884** [bulletphysics/bullet3#2587]
Is there a way to save the current position of a robot as a new .urdf file? I am looking to export its current state after some updates have occurred to a graphics engine for rendering, and I thought this might be the best way to do it. If not, would you mind telling me how you would recommend doing this? Thank you !

**Comment by erwincoumans** [comment]
URDF doesn't store state.
You can use pybullet.saveWorld or come up with some custom solution (getJointState(s))
