### ISSUE TITLE
loadurdf baseposition change

### ISSUE THREAD

**Issue by Hayleymol** [bulletphysics/bullet3#2591]
Hi, I am trying to train laikago to walk in openai gym environment by fixing codes provided by pybullet.
While I am loading laikago.urdf using loadURDF function, I got an issue. 

When I assign basePosition and baseOrientation using optional inputs like,

self._p.loadURDF(os.path.join("/personal path/", self.model_urdf),
                                     basePosition=self.basePosition,
                                     baseOrientation=self.baseOrientation,
                                     useFixedBase=self.fixed_base,
                                     flags=pybullet.URDF_USE_SELF_COLLISION))

My laikago does appear in the environment. 
However, when I start training the laikago, it seems like basePosition and baseOrientation is fixed to the world coordinate that it's body won't move even though legs are moving. 
As result,  laikago looks like it is walking in the air.

Loading script that I brought in above is under robot_bases.py script
MJCFBasedRobot class does not have input of basePosition and baseOrientation when loading character. and I guess that is why other xml based characters such as ant baseposition is not fixed during simulation.

I need to fix position and orientation just once when first loading the model.
I try function such as resetBasePositionAndOrientation and tried placing functions in different places but I am having no luck.

Is there way that I can first fix the position and orientation just once when loading?
Where should I place the code in order to initiate only once? 

All helps will be greatly appreciated. 

----------------------------------------
additional trial + question

It seems like position and orientation fixing issue seems to come from some revised codes.
Since original URDFBasedRobot class seems to load model twice when reset, I changed inside of the URDFBasedRobot class code like MJCFBasedRobot class method.
( I mean, I introduced self.doneloading flag into URDFBasedRobot as well) 
As a result, twice loading issue is fixed but now base position and rotation is fixed.

It would be great if anyone could give me some advice!

**Comment by felixxfu** [comment]
What actions are you applying to the Laikago robot, when you said that "laikago looks like it is walking in the air"?

Maybe try applying random actions and see if it would move?

**Comment by Hayleymol** [comment]
I found the issue, turned out that the alive bonus I set was wrong
