### ISSUE TITLE
Control Penalty for Laikago?

### ISSUE THREAD

**Issue by felixxfu** [bulletphysics/bullet3#2592]
It seems to me the control penalties require some tuning for Laikago to make good walking movement...
Does anyone have experience and is willing to share the setting for control penalties, namely,

```
electricity_cost 
foot_collision_cost
joints_at_limit_cost
```
?

Any help is much appreciated!

Thanks,
Felix

**Comment by erwincoumans** [comment]
We plan to share some Laikago env in the future, but don't commit to a schedule.
