### ISSUE TITLE
use case : using wind for sound waves

### ISSUE THREAD

**Issue by agentdavo** [bulletphysics/bullet3#2593]
Hi,

Would it be feasable to create a soft body and alter the internal pressure with a constant amplitude  sinusoidal wave (1khz sine) and monitor the propagation of the pressure wave away from the body as it hits other bodies?  Can we use wind here or can you offer an alternative method?

**Comment by erwincoumans** [comment]
This is a research topic on its own, I doubt Bullet is suitable for this. Good luck!
