### ISSUE TITLE
pybullet: AntBulletEnv-v0 gives different rewards per episode for same seed and actions

### ISSUE THREAD

**Issue by pdeubel** [bulletphysics/bullet3#2596]
Hi,

I trained the `AntBulletEnv-v0` environment. Afterwards I loaded a trained model and it occured to me that when I set the same seed on the environment, I get different rewards for one episode. The model can be excluded as the source of error, I attached an array of actions which I extracted from the model for which I could reproduce this behavior using this sample code:

```
import gym, pybullet_envs
import numpy as np

actions = np.genfromtxt("actions.txt")
all_rewards = []
for j, _ in enumerate(range(100)):
    env = gym.make("AntBulletEnv-v0")
    env.seed(123)
    env.reset()

    rews = []
    for i, _ in enumerate(range(13)):
        _, rew, _, _ = env.step(actions[i])
        rews.append(rew)
    rews = np.array(rews).sum()

    all_rewards.append(rews)
    # print(rews)

assert all(x == all_rewards[0] for x in all_rewards)
```
[actions.txt](https://github.com/bulletphysics/bullet3/files/4106011/actions.txt)

I used a new conda environment to test this:
- Python 3.6
- numpy 1.18.1
- pybullet 2.6.4
- gym 0.15.4

When I create the environment outside the loop, every reward but the first one is equal for me. Is this expected or is this a bug?

I tried to track down the issue:
In `gym_locomotion_envs.py` in line 68 in method `step()`, `self.robot.calc_state()` is called, this refers to `robot_locomotors.py`, where in line 36 `current_relative_position()` is called which will in turn call `get_state()` in `robot_bases.py` in line 348. And in line 353 the `getJointState()` is called which will, on some episodes, give me different `x` and `vx` values on the 12th step. There I stopped debugging because this then goes into the C code and bullet and I could not setup the debugging right now.

Thanks in advance!

**Comment by erwincoumans** [comment]
The very first reset cycle will be different than all next ones, since it creates the urdf/model etc, so random seeds are different. There is a discussion and a patch that fixes it. Not going to break envs v0, perhaps a future revision will apply the patch.
https://github.com/bulletphysics/bullet3/issues/2639
