### ISSUE TITLE
inverseDynamics external forces question

### ISSUE THREAD

**Issue by mklvcm** [bulletphysics/bullet3#2598]
(possibly newbie) question: inveseDynamics does not have external forces parameter.
Does this mean those are automatically calculated from collisions?
I'm trying to simulate walking robot and it needs to take into account contact forces, right?
-Thank you :)

**Comment by mklvcm** [comment]
Can anyone comment on this please?

**Comment by erwincoumans** [comment]
Please use forums instead for such discussion: https://pybullet.org
