### ISSUE TITLE
Premake 5 Unicode Flag Fix

### ISSUE THREAD

**Issue by geohan98** [bulletphysics/bullet3#2600]
Fixed error with 'GwenOpenGLTest' premake file, `flags{"Unicode"}` is no longer supported in premake5, swapped it out for `characterset ("Unicode")`. Seems to work, might be worth swapping out in the main branch.

**Comment by erwincoumans** [comment]
We have to refactor all the scripts to support premake5, since I don't have time for that I stick with premake4.
