### ISSUE TITLE
obj2sdf weird rendering

### ISSUE THREAD

**Issue by Pandhariix** [bulletphysics/bullet3#2601]
Hi,

I recently rebased my fork of bullet3 on master and recompiled everything. I used obj2sdf to decompose existing obj files (torso and base of the robot, see pictures), and I get the following result:
![image](https://user-images.githubusercontent.com/11226450/73489470-edb84800-43aa-11ea-8c31-f517ef4049e2.png)

The shapes of the meshes are accurate, but the textures are wrong. I eventually managed to have accurate textures, but at the cost of the meshes' smoothness (by exporting the meshes from blender as objs, without the normals).

I noticed that obj2sdf was updated in PR #2366, so I checked out an older version of master (c7fa8bfc58ac9cb0e7881c880ede86d3ef333bc4), recompiled everything and re-used obj2sdf on my obj files:
![image](https://user-images.githubusercontent.com/11226450/73489672-4687e080-43ab-11ea-8615-0e7743375796.png)

With the older version, everything seems to work

**Comment by erwincoumans** [comment]
Thanks for the report. It must have happened when we updated the tiny obj loader.
Do you have a link to obj file + mtl + textures to test?

**Comment by fuchuyuan** [comment]
@Pandhariix Can you try to patch [this](https://github.com/bulletphysics/bullet3/pull/2602) and see if this fixes? If not can you send a link for the obj files and texture files for me to test?

**Comment by Pandhariix** [comment]
@erwincoumans, unfortunately I cannot yet share those meshes (due to licensing issues), I'll try @fuchuyuan 's fix locally and report the result here though

**Comment by Pandhariix** [comment]
@fuchuyuan: it works :+1: 
![image](https://user-images.githubusercontent.com/11226450/73538338-1b44d600-442b-11ea-9dc8-43c372bb9689.png)
