### ISSUE TITLE
Missing mesh file in minitaur_terrain_randomizer

### ISSUE THREAD

**Issue by Visgean** [bulletphysics/bullet3#2615]
Hi, this file 
https://github.com/bulletphysics/bullet3/blob/aec9968e281faca7bc56bc05ccaf0ef29d82d062/examples/pybullet/gym/pybullet_envs/minitaur/envs/env_randomizers/minitaur_terrain_randomizer.py#L215

references mesh file "robotics/reinforcement_learning/minitaur/envs/testdata/triangle_mesh_terrain/terrain9735.obj"
but this is nowhere to be found...

**Comment by erwincoumans** [comment]
Here is the file, it isn't very interesting:
[terrain9735.obj.zip](https://github.com/bulletphysics/bullet3/files/4189723/terrain9735.obj.zip)

**Comment by Visgean** [comment]
Thanks! Do you happen to have the code that generated the mesh? I was planning to write something similar myself but if it has already been written.... I am planning to use this sort of randomized environment for my dissertation.
