### ISSUE TITLE
freeze rigidbody until hit

### ISSUE THREAD

**Issue by ghiboz** [bulletphysics/bullet3#2616]
hi all! it's possible freeze a rigidbody and when it's hit for the first time awake it to make its behaviour 'standard'
thanks

**Comment by erwincoumans** [comment]
Yes, you can create a rigid body that starts in sleeping mode. It will activate when something hits it.

**Comment by ghiboz** [comment]
thanks @erwincoumans , but how can I do this?

**Comment by ChaseCarlson** [comment]
@ghiboz If you're still stuck on this, you can start a btRigidBody off as sleeping like this:
`bBody->setActivationState(ISLAND_SLEEPING);`

When it is acted upon by another object it will become active.
