### ISSUE TITLE
Feature request: simple tutorial how to replace mujoco with pybullet in a project

### ISSUE THREAD

**Issue by christofer-f** [bulletphysics/bullet3#2629]
Hi,

I am completely new to this project and I have a question.
Is there a simple way to replace mujoco with pybullet in a project?

Like a wrapper file so that I can write:

`from pybullet_wrapper_of_mujoco_py import load_model_from_path, MjSim, MjViewer`

instead of the current line:

`from mujoco_py import load_model_from_path, MjSim, MjViewer`

Br,
Christofer

**Comment by erwincoumans** [comment]
That would be great. If you or someone else works on this, please share and re-open this issue.
