### ISSUE TITLE
How to detect collision without breakdown the scenario

### ISSUE THREAD

**Issue by ghx0x0** [bulletphysics/bullet3#2631]
I have use some  meshes to build a cluttered objects scenario, then I want to test if a gripper in some pose is collision with the scenario.

However, when I add the mesh of the gripper in a 'collision' pose, the objects around this pose is pushed by the gripper, so the scenario is broken.

Does pybullet support collision detection without breaking the scenario?
Thanks a lot!

**Comment by erwincoumans** [comment]
It is easiest to keep a second simulation (in DIRECT mode) and perform queries there, using PyBullet.getClosestPoints.
