### ISSUE TITLE
Render vs Renders inconsistency 

### ISSUE THREAD

**Issue by tmulc18** [bulletphysics/bullet3#2633]
For some environments, like `HumanoidBulletEnv-v0`, you can create an environment that renders with `gym.make('env-name',render=True)`, while for other environments, like `KukaBulletEnv-v0`, you do `gym.make('env-name',renders=True)`.  It seems like there should be a convention (i.e., either `render` or `renders`, but not both), and all environments should follow it.

I'm suggesting `render`, because that is the name of the method OpenAI gym uses.  I'm opening the issue because I'm willing to submit a PR that either changes the old environments to accept both or fix the environments that don't follow the convention.

Check [here](https://github.com/bulletphysics/bullet3/issues/2272) for old version of this issue.

**Comment by erwincoumans** [comment]
Thanks for the report. Not going to break the API. Will consider it for future new Gym envs.
