### ISSUE TITLE
Issue with btGeneric6DofSpring2Constraint and axis 4

### ISSUE THREAD

**Issue by MikelAyani** [bulletphysics/bullet3#2638]
This issue can be reproduced with just some modifications, for example, to the TestHingeTorque example. 
What needs to be done:
- Create a btGeneric6DofSpring2Constraint constraint between two bodies, one static, and the other dynamic.
- Limit all axis but not axis 4 (rotation on the y-axis)
- Set the joint motor to true with any speed != 0
The result is that the joint will rotate and get blocked/stopped at pi/2. The same test with axis 3 or 5 will make the joint keep rotating around those axes unlimited, as expected. 
I haven't noticed any issue with the translational axis.
I can provide some code if needed.

**Comment by erwincoumans** [comment]
From the class source documentation
- Rotation order for the Euler system can be set. (One axis' freedom is still limited to pi/2)
So your axis 4 is limited. You could change to a different rotation order, then another axis will be limited.
https://github.com/bulletphysics/bullet3/blob/5dfcbe9a331df3c0393ee68d88d0e6983ad0a260/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.cpp#L23
