### ISSUE TITLE
Root actuated control

### ISSUE THREAD

**Issue by soshishimada** [bulletphysics/bullet3#2642]
Hello. Is it possible to actuate root (3 translations by prismatic and 3 orientations by revolute)?
I've created a urdf that has 3 translations on its root as below:

`<robot name="dumpUrdf">
	<link name = "base">
		<inertial>
			<origin rpy = "0 0 0"  xyz = "0 0 0" />
			<mass value =  "0.0001" />
			<inertia ixx = "0.0001" ixy = "0" ixz = "0" iyy = "0.0001" iyz = "0" izz = "0.0001" />
		</inertial>
	</link>
	<link name = "root_z">
		<inertial>
			<origin rpy = "0 0 0"  xyz = "0 0 0" />
			<mass value =  "15" />
			<inertia ixx = "0.1" ixy = "0" ixz = "0" iyy = "0.1" iyz = "0" izz = "0.1" />
		</inertial>
		<collision>
			<origin rpy = "0 0 0"  xyz = "0 0 0" />
			<geometry>
				<sphere radius="0.04" />
			</geometry>
		</collision>
	</link>
	<joint name="root_z" type="prismatic">
		<parent link = "base" />
		<child link = "root_z" />
		<origin rpy = "0 0 0" xyz ="0 0 0"  />
		<limit effort="10000.0"  lower="-10.1" upper="10.2"   velocity="1.5" />
		<axis xyz = "0.0 0.0 1.0" />
	</joint>
	<link name = "root_x">
		<inertial>
			<origin rpy = "0 0 0"  xyz = "0 0 0" />
			<mass value =  "0.0001" />
			<inertia ixx = "0.1" ixy = "0" ixz = "0" iyy = "0.1" iyz = "0" izz = "0.1" />
		</inertial>
		<collision>
			<origin rpy = "0 0 0"  xyz = "0 0 0" />
			<geometry>
				<sphere radius="0.0001" />
			</geometry>
		</collision>
	</link>
	<joint name="root_x" type="prismatic">
		<parent link = "root_z" />
		<child link = "root_x" />
		<origin rpy = "0 0 0" xyz ="0 0 0"  />
		<limit effort="10000.0"  lower="-10.1" upper="10.2"    velocity="1.5" />
		<axis xyz = "1.0 0.0 0.0" />
	</joint>
	<link name = "root_y">
		<inertial>
			<origin rpy = "0 0 0"  xyz = "0 0 0" />
			<mass value =  "0.0001" />
			<inertia ixx = "0.1" ixy = "0" ixz = "0" iyy = "0.1" iyz = "0" izz = "0.1" />
		</inertial>
		<collision>
			<origin rpy = "0 0 0"  xyz = "0 0 0" />
			<geometry>
				<sphere radius="0.0001" />
			</geometry>
		</collision>
	</link>
	<joint name="root_y" type="prismatic">
		<parent link = "root_x" />
		<child link = "root_y" />
		<origin rpy = "0 0 0" xyz ="0 0 0"  />
		<limit effort="10000.0"  lower="-10.1" upper="10.2"    velocity="1.5" />
		<axis xyz = "0.0 1.0 0.0" />
	</joint>
</robot>`

Only the joint 'root_z' is working after setting useFixedBase=True in  p.loadURDF( ). However, 'root_y' and 'root_x' do not create any translation.

**Comment by erwincoumans** [comment]
There is a 2d biped that is related. Please use the forums to discuss further.
https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/gym/pybullet_data/biped
