### ISSUE TITLE
PyBullet URDF_USE_SELF_COLLISION doesn't work

### ISSUE THREAD

**Issue by meken** [bulletphysics/bullet3#2644]
I'm struggling to get pybullet to detect self collisions, I've tried enabling self collision detection through flags when loading the URDF
```python
import pybullet as p

modelId = p.loadURDF("urdf/sims.urdf", flags=p.URDF_USE_SELF_COLLISION)
```
as well as through `setCollisionFilterPair` method
```python
parentLink, legALink, legBLink = -1, 0, 1
enableCollision = 1
p.setCollisionFilterPair(modelId, modelId, parentLink, legALink, enableCollision)
p.setCollisionFilterPair(modelId, modelId, parentLink, legBLink, enableCollision)
```
In all cases the legs seem to go through the main body (parent):
<img width="145" alt="collision" src="https://user-images.githubusercontent.com/829368/75345443-07ab5480-589d-11ea-9a6a-f06f33ed8d4c.png">

See the attached sample setup for reproducing the issue
[collision.zip](https://github.com/bulletphysics/bullet3/files/4255717/collision.zip)

Note that collision detection with the plane works just fine, it's the self collision between the main body (parent) and the legs that seems to be an issue. When the flag is turned on, the legs go through the parent, but don't go through each other. However, the method setCollisionFilterPair doesn't seem to make any difference at all, as legs go through parent as well as through each other.

I'm pretty new to pybullet, so I might be doing something wrong, but any help is appreciated.

**Comment by erwincoumans** [comment]
By default, collisions between parent and child are disabled, since they are usually overlapping/contacting. You could add the flag URDF_USE_SELF_COLLISION_INCLUDE_PARENT in addition to the other flag.
