### ISSUE TITLE
How to use the C API

### ISSUE THREAD

**Issue by AlexApps99** [bulletphysics/bullet3#2647]
It says in the README:
> A new physics-engine agnostic C-API is created, see examples/SharedMemory/PhysicsClientC_API.h

How can I use this? I'm currently working on a Rust binding of Bullet (Rust bindings only really work with C), but it's unclear how to actually use Bullet from C as there are a lot of different physics clients in the examples folder and no clear, simple examples, or guides.

If somebody could give me some guidance on this that'd be awesome.
Thanks

**Comment by erwincoumans** [comment]
There are two examples:
Python bindings here:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/pybullet.c

C++ wrapper around this C API:
https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/b3RobotSimulatorClientAPI_NoDirect.cpp

**Comment by AlexApps99** [comment]
Thanks

**Comment by AlexApps99** [comment]
How would I build and link a project using the C API with CMake? Trying to compile the examples folder needs OpenGL among other things and it takes too long, all I need is the SharedMemory folder

**Comment by erwincoumans** [comment]
premake and cmake have a BulletRobotics project in the Extras folder. It doesn't require OpenGL.

**Comment by AlexApps99** [comment]
I keep getting linkage errors while trying to disable parts of Bullet that are unneeded, what do I need to compile BulletRobotics?
I currently have enabled:
- `BUILD_BULLET3`
- `BUILD_EXTRAS`
Every other `BUILD_*` is disabled, I am getting the error `/usr/bin/ld: cannot find -lBussIK`.

What else do I need to enable to get this to work?

**Comment by AlexApps99** [comment]
@erwincoumans please could you help me? Thanks :)
