### ISSUE TITLE
PyBullet: Big STLs are not totally loaded

### ISSUE THREAD

**Issue by Gregwar** [bulletphysics/bullet3#2654]
If an URDF contains too much facets in its STLs, it is only partially loaded
Again, this issue can be closed with some leads on how to fix this in the source

## Example of failing model
![](https://gregwar.com/sigmaban/ko.png)
URDF & STLs:
https://gregwar.com/sigmaban/sigmaban_big.tgz

##  The exact same model with meshes simplification works
![](https://gregwar.com/sigmaban/ok.png)
URDF & STLs:
https://gregwar.com/sigmaban/sigmaban_light.tgz

**Comment by erwincoumans** [comment]
You need to reduce the number of vertices first, there are hardcoded limits.

**Comment by Nuofan-SUSTech** [comment]
> You need to reduce the number of vertices first, there are hardcoded limits.

Is there any way to improve the hardcoded limits?
