### ISSUE TITLE
Control the car to the target position

### ISSUE THREAD

**Issue by Jingjinganhao** [bulletphysics/bullet3#2664]
Hi， how to control the car to the target position? Is there any API can control the car to the target position like
    p.setJointMotorControl2(bodyUniqueId=kukaUid,
                            jointIndex=6,
                            controlMode=p.POSITION_CONTROL,
                            targetPosition=-angle,
                            force=20)

**Comment by erwincoumans** [comment]
what car?

**Comment by Jingjinganhao** [comment]
> what car?

racecar in racecar.py 
I want to control it to the target position
