### ISSUE TITLE
Can't install pybullet on Windows 10

### ISSUE THREAD

**Issue by aadevmobile** [bulletphysics/bullet3#2666]
Hello,
I'm trying to install qiBullet but it keeps failing when to installing pybullet.

This is what I get:
![pibullet_error](https://user-images.githubusercontent.com/60118936/76563313-88617780-647d-11ea-99cf-23a881b73906.png)
![pibullet_error2](https://user-images.githubusercontent.com/60118936/76563522-f5750d00-647d-11ea-9966-797487267c72.png)

Did you see this before? Any suggestions? I'm struggling with this..

I've read 1708. Mine doesnt say anything about stdint.h, i've tried it tho, no luck.

**Comment by KevinJune** [comment]
![1](https://user-images.githubusercontent.com/31851657/76602541-186af400-6546-11ea-84c5-3bfec51c2124.png)
![2](https://user-images.githubusercontent.com/31851657/76602485-f70a0800-6545-11ea-8210-3c2a862529fb.png)
![3](https://user-images.githubusercontent.com/31851657/76602488-f7a29e80-6545-11ea-8084-fc7884213507.png)

**Comment by KevinJune** [comment]
I have similar problem with you, and I solve it by deleteing the vs2015 completely(both softwares about vs and the environment variable)
Then I only install the Build tool box which erwin said.
[https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe?fixForIE=.exe.](url)
Finally you can use a program to test whether you install the tool box correctly.
Hope my answer can help you.

**Comment by erwincoumans** [comment]
Please use the forums instead: https://pybullet.org

**Comment by aadevmobile** [comment]
Hi Erwin,

https://pybullet.org/Bullet/phpBB3/viewtopic.php?f=9&t=12890
Could you please help me? I've tried so many things, it's not working...

**Comment by erwincoumans** [comment]
I fixed the issues, can you please try again with pybullet-2.6.9 and report back.
Also uploaded a precompiled wheel for Python 2.7 Windows 64bit.

Thanks!
Erwin

**Comment by aadevmobile** [comment]
Thank you! Thank you! Thank you!
It works now!!

**Comment by aadevmobile** [comment]
I was too happy too fast...
I need to have it working for Python 2.7 Windows 32bits now :/
I've updated the info in the forum... It seems to be a different error now.
Or it's something I'm doing very wrong and I don't know how to do right...

Could you please take a look at again?
