### ISSUE TITLE
Gravity setting for accurate force/torque data

### ISSUE THREAD

**Issue by Todibo99** [bulletphysics/bullet3#2676]
Hello, I am trying to do robot grasping and collect joint force/torque data in pybullet.

I found that the joint force/torque measurements could be affected by the gravity setting. For example, if I set gravity (0,0,0), the forces will be close to zero. I found many examples use gravity (0,0,-9.8) and If I set gravity (0,0,-9.8), the forces will be larger.

So is (0,0,-9.8) the correct value of gravity to get accurate force/torque reading?

Thanks !

**Comment by erwincoumans** [comment]
Please use the forums for discussion, and always provide a small fully working Python script reproduction case (with URDF etc). https://pybullet.org
