### ISSUE TITLE
How to integrate Pybullet with VTK

### ISSUE THREAD

**Issue by Nibba2018** [bulletphysics/bullet3#2680]
Hello everyone, I had a question, actually, I wanted to apply Pybullet's physics onto VTK models but I am unable to find the required documentation to do so. Can someone help me out here?

**Comment by erwincoumans** [comment]
Better use the forums for this. No idea what VTK models are, but PyBullet loads URDF, SDF and MJCF, and also obj, stl etc. See the examples.
