### ISSUE TITLE
Grasp Deformable Cloth Example freezes ExampleBrowser program

### ISSUE THREAD

**Issue by javadan** [bulletphysics/bullet3#2681]
I just clicked through the App_ExampleBrowser program, and got to 'Grasp Deformable Cloth' example, and then if I try to load another example, it crashes and I need to kill the process. 

ven = Intel Open Source Technology Center
Workaround for some crash in the Intel OpenGL driver on Linux/Ubuntu
ven = Intel Open Source Technology Center
Workaround for some crash in the Intel OpenGL driver on Linux/Ubuntu
^Cb3Printf: Aborting and deleting SharedMemoryCommon object
^Cb3Printf: Aborting and deleting SharedMemoryCommon object
^C^C^C^C^C^CKilled

I don't mind that example not working, but I seem to be stuck on that example now.

Where is the config / settings file that remembers the last example that was run?  I saw "progress.marks" in the CMakeFiles dir, and tried changing the number in that file, but that didn't work.

**Comment by erwincoumans** [comment]
Better use the forums for this.
