### ISSUE TITLE
Question about the parameters of btMultiBody::fillConstraintJacobianMultiDof()?

### ISSUE THREAD

**Issue by Steven89Liu** [bulletphysics/bullet3#2684]
i'm confused about this part of code as below. do the normal_lin_world and normal_ang_world can be the zero at the same time? thanks.
``` 
       btVector3 omega_coeffs_world;
	omega_coeffs_world = p_minus_com_world.cross(normal_lin_world);
	jac[0] = omega_coeffs_world[0] + normal_ang_world[0];
	jac[1] = omega_coeffs_world[1] + normal_ang_world[1];
	jac[2] = omega_coeffs_world[2] + normal_ang_world[2];
```

**Comment by erwincoumans** [comment]
if they are both zero it would be a useless jacobian

**Comment by Steven89Liu** [comment]
sorry, i made a mistake, i was thinking to ask if they can be non-zero at the same time. thanks.

**Comment by Steven89Liu** [comment]
update. hope you can see my last comment that is important for me. thanks.
