### ISSUE TITLE
will we able to use triangle-mesh for collision ?

### ISSUE THREAD

**Issue by v-wewei** [bulletphysics/bullet3#2692]
hi, @erikogenvik 
since pybullet will convert the triangle-mesh into convex-hull in default, though there are several method like v-hacd to create a convex decomposition first to ensure high performance and stability. 
But i just want to use other mesh decomposion mehtod , since some of the part do not seems smooth  enough especially for the depart region if we use v-hacd. 
Since we can smooth and decomposition the triangle mesh with other method but not to depart the mesh and then perform decomposition just like v-hacd, is there any other problem for stability and performance if we do not convert the mesh to convex hull by default ?
could you help to provide an method for disable the default setting that converting triangle mesh to convex hull in pybullet ? 
thanks advance.

**Comment by erwincoumans** [comment]
pybullet has vhacd built-in now.

>> other mesh decomposion method

You can use any method, store the convex decomposition as vertex/face object grouis in the Wavefront obj file

>> for disable the default setting 

Add concave="yes" in the URDF works fir non-moving objects
