### ISSUE TITLE
Collisions randomly not working in RELEASE mode

### ISSUE THREAD

**Issue by penumbra23** [bulletphysics/bullet3#2701]
Hello Bullet Github community!

Working on my project (using OpenGL and Bullet Physics) I've spotted some weird behavior with collisions. My sample app includes several boxes falling from some distance and colliding with a plane (floor) and with each other.

In **Debug** mode, it works perfectly. In **Release** mode it acts undefined: sometimes the collisions are totally "turned-off", sometimes one or two cubes hit the plane but other cubes fail, sometimes one or two cubes hit each other but nothing else and with each run it's completely random.

My first guess was something with optimizations, which turned out to be true regarding some post on [pybullet.org](https://pybullet.org) forum, but even with all optimizations switched off, the error persists.

Someone had similar problems? Solutions?

**OS**: Windows 10
**IDE & Compiler**: Visual Studio 2019 MSVC v142
**C++ standard**: C++17
**Bullet version**: 2.89 installed via vcpkg (commit [e2c671d](https://github.com/microsoft/vcpkg/tree/e2c671d4bdccc023a7e0d78ca5d658057543c443/ports/bullet3))

**Comment by erwincoumans** [comment]
There must be a compile setting difference between library and your app. Please use the forums to dicsuss.
