### ISSUE TITLE
6DoF Spring constraint changes.

### ISSUE THREAD

**Issue by stolk** [bulletphysics/bullet3#2705]
It's been 2 yrs or so, since I updated my bullet copy, which caused my sim to break down.

It now looks like this:

https://www.youtube.com/watch?v=O1DZOjExAL0&feature=youtu.be

Whereas with the old code, it was working just fine:

https://twitter.com/BramStolk/status/1245207361075253249?s=20

Could this have been caused by this change?

https://github.com/bulletphysics/bullet3/commit/9160d0aee15cf35d7d4a9f9e3a792e1dd8b39a19#diff-c53746af2548b996e47b349dbdab59d2

**Comment by stolk** [comment]
Sorry, I had the wrong commit link originally.

**Comment by stolk** [comment]
So yeah, after reverting `btGeneric6DofSpring2Constraint.cpp` and `btGeneric6DofSpring2Constraint.h` to the old versions of 2 yrs ago, it works again, so infinite error can cause some serious stability issues.

**Comment by erwincoumans** [comment]
Thanks for the update. Could you help by re-introducing some flag that toggles between the old (for you working version) and the current version?

By the way, I think such tank would work nice with btMultiBody, but that would require much more change. If I ever find time to prototype such tank in PyBullet I'll reply here.

**Comment by stolk** [comment]
I put the flag back, before I create another pull rq, there is still a pull rq from this morning pending, maybe keep them separate, and I create a new rq tomorrow?

**Comment by stolk** [comment]
never mind, github already merged those changes into a single rq. I guess there is always just 1 pull rq active.

**Comment by erwincoumans** [comment]
Thanks, I suppose it is fixed.
