### ISSUE TITLE
Segfault when using multiple threads to read state of one physics server

### ISSUE THREAD

**Issue by richardrl** [bulletphysics/bullet3#2713]
In pyBullet when we setRealTimeSimulation == True, we often want to have multiple threads either reading or manipulating the state.

For example,
1. Two threads simultaneously closing the two fingers of a parallel jaw gripper so they close as the same velocity and end up mirroring each other's trajectories.
2. Setting debug text that updates as the user uses the mouse to pick up objects in the GUI.

The naive implementation using thread.Thread segfaults. See below:

```
def update_debug(robot, pos_text_id):
    while True:
        robot.pb_client.addUserDebugText(str(robot.arm.get_ee_pose()[0]),
                                        robot.arm.get_ee_pose()[0] + [0, 0, .02],
        replaceItemUniqueId=pos_text_id,
                                         physicsClientId=0)


thread = threading.Thread(target=update_debug, args=(robot, pos_text_id))
thread.start()


... main program code ...
```

Operating system: MacOSX 10.12, Python2.7

**Comment by erwincoumans** [comment]
>> we often want to

No, you can only connect to each shared memory connection from 1 single thread. Internally the physics server will serialize the commands anyway.

Note there are 2 shared memory sections, so you can have at most 2 threads (aside from the server) sending commands. Use the p.connect(p.SHARED_MEMORY, key=SHARED_MEMORY_KEY2 for the second connection.
