### ISSUE TITLE
btSoftBody::Node understanding struct members

### ISSUE THREAD

**Issue by Bicyclette** [bulletphysics/bullet3#2715]
Hi !
I'm looking at the **btSoftBody::Node** struct and there are those variables:

btVector3 m_x
btVector3 m_q
btVector3 m_v
btVector3 m_f
btVector3 m_n
btScalar m_im
btScalar m_area
btDbvtNode* m_leaf
int m_battach:1

This struct is a member of the btSoftBody::Face data type, my goal is to update my meshe's VBO to do a visual update of the soft body.

I can guess that the m_area field is the area of the face, but about the those m_q, m_x etc. ?
All I need are the vertex normal and position.

**Comment by erwincoumans** [comment]
Please use the forums or check the code instead. From btSoftBody.h:

~~~~~~~~~~~~~~~~~~~~~
/* Node			*/
	struct Node : Feature
	{
		btVector3 m_x;       // Position
		btVector3 m_q;       // Previous step position/Test position
		btVector3 m_v;       // Velocity
        btVector3 m_vsplit;  // Temporary Velocity in addintion to velocity used in split impulse
        btVector3 m_vn;      // Previous step velocity
		btVector3 m_f;       // Force accumulator
		btVector3 m_n;       // Normal
		btScalar m_im;       // 1/mass
		btScalar m_area;     // Area
		btDbvtNode* m_leaf;  // Leaf data
		int m_battach : 1;   // Attached
        int index;
	};
~~~~~~~~~~~~~~~~~~~~~
