### ISSUE TITLE
SPD controller seems only support 3D model

### ISSUE THREAD

**Issue by zeshiYang** [bulletphysics/bullet3#2716]
I tried to add spd controller into 2d biped environment.
Firstly I used spd controller implemented by python and it works.
Then I use the function p.setJointMotorControlMultiDofArray with p.STABLE_PD_CONTROL, but the simulation crashes and the biped model flies to the sky.
Since the C++ spd controller are only tested in DeepMimic environment, where the character's root joint are fixed with base. However in biped's urdf file, the base is fixed and the torso are connected with two prismatic joint and a revolute joint. So I delete these joints and use a fixed joint to connect base with torso like DeepMimic, then I use the p.setJointMotorControlMultiDofArray with spd controller and it works again...
I think may be there are somthings wrong with C++ spd controller implementation in bullet's source code, so the 2D biped models are not supported...
[codes.zip](https://github.com/bulletphysics/bullet3/files/4433152/codes.zip)

**Comment by erwincoumans** [comment]
Yes, the stable PD was only implemented for DeepMimic and has some assumptions (floating base for example). There are no resources or plans to work on this anytime soon though. If someone has time to fix it, please reopen. Otherwise try explicit PD instead with a small timestep.
