### ISSUE TITLE
How to create constraints

### ISSUE THREAD

**Issue by Jingjinganhao** [bulletphysics/bullet3#2719]
Hi I want to build a revolute joint by using createConstraint 
I did as [this](https://github.com/bulletphysics/pybullet_robots/blob/master/dobot.py) but it didn't work
my urdf is :
[urdf.txt](https://github.com/bulletphysics/bullet3/files/4442319/urdf.txt)

I did as follow:
c = p.createConstraint(uarmId,3,uarmId,2,jointType=p.JOINT_POINT2POINT,jointAxis =[0,1,0],
parentFramePosition=[0.0274502,0.0165272,0.02698],
childFramePosition=[-0.1587598,0.0165272,-0.00006])

parentFramePosition =the coordinates of  joint1- the coordinates of joint3
childFramePosition = the coordinates of joint1-the coordinates of joint2
Is this wrong?
What does p.JOINT_POINT2POINT mean? it means revolute?

**Comment by erwincoumans** [comment]
Please use other forums.
