### ISSUE TITLE
ERROR: 0:1: '' :  version '150' is not supported

### ISSUE THREAD

**Issue by 1234shel** [bulletphysics/bullet3#2720]
Hi,
I am trying to run pybullet on ubuntu 18.04 running as a parallels VM on a macbook. I am getting the following error: ERROR: 0:1: '' :  version '150' is not supported

I am not sure how to go about fixing this. As soon as the compiler reaches the connect to GUI line I get that error:
import pybullet as p
p.connect(p.GUI)

I am beginner with pybullet so any and all help will be very much appreciated.

**Comment by erwincoumans** [comment]
VM's often don't support OpenGL3. Use direct mode and create images / videos using getCameraImage or avoid parallels. Use other forums to discuss this.
