### ISSUE TITLE
How to build for ios and macos using modern Xcode?

### ISSUE THREAD

**Issue by KTRosenberg** [bulletphysics/bullet3#2727]
I would like to build bullet3 to use in an ios 13 project in xcode 11. I realize it's unrealistic to expect all build systems to be available since there are so many platforms and there have been many changes over the years. However, it looks like there is no documentation indicating how I would build for ios. The current build scripts are for macos using xcode 4, and we're currently on 11.

May I have guidance in building for ios and xcode using the modern toolchain? I am pretty stumped since there doesn't seem to be any information on this.
I somehow doubt it is as simple as dropping the entire source folder into xcode, and adding all .c files as build targets. Furthermore, it would be much easier to have a static library.

Thank you for your time.

**Comment by erwincoumans** [comment]
Please use the forums to discuss. Easiest is to just add the Bullet/src folder as includes and all files under Bullet/src/LinearMath, Bullet/src/BulletCollision and Bullet/src/BulletDynamics.
