### ISSUE TITLE
get_orientation() wrong in pybullet Joint

### ISSUE THREAD

**Issue by benureau** [bulletphysics/bullet3#2733]
https://github.com/bulletphysics/bullet3/blob/628524dd6c8927d323c203aee19c4cb2fd0ae639/examples/pybullet/gym/pybullet_envs/robot_bases.py#L360-L366

As per the lines above, the get_orientation() function does not seem properly implemented.

**Comment by erwincoumans** [comment]
I wasted too much time in that cluttered gym env code, looking forward to delete and replace it at some stage. If you have a patch, please create a pull request.
