### ISSUE TITLE
pybullet execeeding joint limits specified in urdf

### ISSUE THREAD

**Issue by goodnamegood** [bulletphysics/bullet3#2735]
I created a robot myself with a customized URDF file. I also specified the joint limits in terms of its lower and upper bound. However, when I execute an action through velocity control for example, the joint angles exceed their physical limit. How do I cope with this issue?

**Comment by erwincoumans** [comment]
>> How do I cope with this issue?

Use the forums to discuss such topics. See https://pybullet.org
