### ISSUE TITLE
No velocity control with multi dof joint

### ISSUE THREAD

**Issue by LeeChunHei** [bulletphysics/bullet3#2740]
I noticed that in the [Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#)
setJointMotorControlMultiDof and setJointMotorControlMultiDofArray's control mode can be selected as velocity control, however this will lead to illegal control mode error, which is caused by [this](https://github.com/bulletphysics/bullet3/blob/628524dd6c8927d323c203aee19c4cb2fd0ae639/examples/pybullet/pybullet.c#L2790) and [this](https://github.com/bulletphysics/bullet3/blob/628524dd6c8927d323c203aee19c4cb2fd0ae639/examples/pybullet/pybullet.c#L3248).
But when I try to archive velocity mode in an alternate way, using position control with velocity gain as 1 and position gain as 0, it did nothing to the multi dof joint (spherical joint). And somehow this position control method works with the revolute joint.
Is the velocity control to multi dof joint never be coded with the c++ backend?
And if this control method will not be implemented, can you update the quickstart guide mentioning this?

**Comment by erwincoumans** [comment]
There is no velocity control for the spherical joint indeed, hence the 'illegal control mode error'. There are no resources to work on this.
