### ISSUE TITLE
No stable pd control for urdf with mesh

### ISSUE THREAD

**Issue by LeeChunHei** [bulletphysics/bullet3#2742]
@erwincoumans , I'm sorry for opening a new issue for this problem #2739.
I found that the missing stable PD control is not just caused by not making the base floating.
It shows that stable PD control could not be applied to the robot when its urdf involves meshes like stl, obj.
So I had tested with [laikago](https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_data/laikago/laikago.urdf) and found that stable PD control cannot control its joint as well, it behaves just like what I mentioned in #2739.
I'm pretty sure the setting is correct which the urdf is imported with useFixedBase=False. However, with the unknown reason, this control won't work when stl or obj meshes are involved in the urdf files.
Is that the assumption @erwincoumans mentioned in #2716 includes stable PD control needs model built with box and sphere only?

**Comment by erwincoumans** [comment]
Unfortunately stable pd is not supported aside from the deepmimic env with its character.
