### ISSUE TITLE
PPO train kuka_grasping didn't perform well

### ISSUE THREAD

**Issue by LINGYUNFDU** [bulletphysics/bullet3#2747]
I have tried:
python3 -m pybullet_envs.agents.train_ppo --config=pybullet_kuka_grasping --logdir=kuka
Then i evaluate the environment:
python3 -m pybullet_envs.agents.visualize_ppo  --logdir=kuka/<timestampname> --outdir=kuka_video1

However, from the "kuka_video1", we find it the robot can still not grasp the object.

_Originally posted by @pyni in https://github.com/bulletphysics/bullet3/issues/1386#issuecomment-384849069_

**Comment by 52Hz-Kun** [comment]
Hello, I'd like to ask you if you have successfully used dqn algorithm experiment?

**Comment by LINGYUNFDU** [comment]
> Hello, I'd like to ask you if you have successfully used dqn algorithm experiment?

No, neither the DQN on discrete grasping task nor this PPO on continus task perform well... sigh

**Comment by erwincoumans** [comment]
It is not supported. Please find a forum to discuss it.
