### ISSUE TITLE
PyBullet: ER_TINY_RENDERER issue with box geoms in MJCF files

### ISSUE THREAD

**Issue by jgehring** [bulletphysics/bullet3#2751]
It appears that the connection mode modifies how bodies are loaded from MJCF -- the symptom is that their camera image rendering is affected. See [this script](https://gist.github.com/jgehring/95d42638454b016cc9cf434b552a1952) for reproducing this (tested with PyBullet 2.7.2 on macOS and 2.7.3 on Ubuntu). The script creates 3 bodies: a box and a sphere from a MCJF file, and a equal-sized box via `createMultiBody()`. Colors defined in MCJF descriptions don't seem to be recognized, but box geoms are rendered at a significantly smaller size when connecting in `DIRECT` mode; in `GUI` mode, shapes are rendered as expected. Interestingly, the mass and extent of the MCJF box when queried via the API is the same in both connection modes.

Here are the images produced by the script:

`p.connect(p.GUI)` | `p.connect(p.DIRECT)`
------------ | -------------
![render_gui_1](https://user-images.githubusercontent.com/88510/79620475-52648280-8110-11ea-90cb-dcc105d10481.png) | ![render_direct_1](https://user-images.githubusercontent.com/88510/79620485-5abcbd80-8110-11ea-811a-cd7b5c23b189.png)
![render_gui_2](https://user-images.githubusercontent.com/88510/79620482-58f2fa00-8110-11ea-8281-10da993afa2a.png) | ![render_direct_2](https://user-images.githubusercontent.com/88510/79620488-5c868100-8110-11ea-8580-539dcc6b78c7.png)

**Comment by jgehring** [comment]
Update: in the example script above, I used `ER_BULLET_HARDWARE_OPENGL` to obtain the camera image since I copy-pasted the rendering code. When I use `ER_TINY_RENDERER`, I obtain the right-hand column from above (i.e. center box rendered too small) for both connection modes. Apparently, it's the rendering back-end rather than the connection mode that results in invalid box sizes.

**Comment by erwincoumans** [comment]
Yes, tinyrenderer converted from urdf convention (urdf size is actual size, while mjcf size is half-size)
fixed here. Most of the standard mjcf benchmarks (ant, hopper, half-cheetah, humanoid only uses sphere and capsules, so it went undetected).
Thanks for the report!
