### ISSUE TITLE
Copy object for trajectory visualization

### ISSUE THREAD

**Issue by LemonPi** [bulletphysics/bullet3#2752]
I have an object loaded from URDF whose position changes along a trajectory X. I'd like to visualize this with a single image by creating a trail of this object with increasing alpha the closer it is to the end of the trajectory. There doesn't seem to be a way to copy an object or a visual-only copy of an object. I'm planning to do this via `loadURDF` and `changeVisualShape`; is there a better way of doing this?

**Comment by erwincoumans** [comment]
You can use addUserDebugLine for a trajectory. See the inverse kinematics example.
Or use instancing, see the batch usage in https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/createMultiBodyBatch.py#L114
