### ISSUE TITLE
Calculate Center of Mass of Multibody

### ISSUE THREAD

**Issue by 6etacat** [bulletphysics/bullet3#2754]
Hi. I'm new to robotics and physical simulations. 

I'm trying to load an obj file of the YCB dataset into the and have it behave like a normal object under gravity. I realized that I would need to set the `baseInertialFramePosition` in the multibody to the center of mass. I'm wondering if I'm able to do so in PyBullet. It would be best if I can get both the center of mass assuming the mass is evenly distributed on the mesh and the center of mass assuming mass is evenly distributed inside the mesh. 

Thank you!

**Comment by erwincoumans** [comment]
It is not available, best to find a different solution.
