### ISSUE TITLE
Can pybullet simulate sensors such as  laser radar, IMU,  GPS, haptics etc?

### ISSUE THREAD

**Issue by Jingjinganhao** [bulletphysics/bullet3#2759]
Hi, I want to use pybullet to build a robot simulation environment, the robot has some sensors such as laser radar, IMU,  GPS. Can pybullet simulate these? Any examples can help me.\
Thank you very much!

**Comment by erwincoumans** [comment]
You could use 'rayTestBatch' to simulate laser/radar and lidar.
For IMU, you can start with the actual world position and orientation and linear/angular velocity etc, and add some noise model. Similar for GPS. There is no GPS triangulation model.
For camera image sensor you can use getCameraImage.

**Comment by Jingjinganhao** [comment]
Thank you very much！

**Comment by Privilger** [comment]
> You could use 'rayTestBatch' to simulate laser/radar and lidar. For IMU, you can start with the actual world position and orientation and linear/angular velocity etc, and add some noise model. Similar for GPS. There is no GPS triangulation model. For camera image sensor you can use getCameraImage.

Hi, for IMU,
How can I get the acceleration?

**Comment by kwang-12** [comment]
> 



> > You could use 'rayTestBatch' to simulate laser/radar and lidar. For IMU, you can start with the actual world position and orientation and linear/angular velocity etc, and add some noise model. Similar for GPS. There is no GPS triangulation model. For camera image sensor you can use getCameraImage.
> 
> Hi, for IMU, How can I get the acceleration?

Maybe this is late but you can use `getBaseVelocity` to get the linear velocity and calculate the acceleration by taking its derivative.

**Comment by superyeevi** [comment]
how about tactile sensors，like  Tekscan？
