### ISSUE TITLE
Get realtimesimulation performance by setting stepSimulation parameters.

### ISSUE THREAD

**Issue by TneitaP** [bulletphysics/bullet3#2761]
Hi,
I've been using the Pybullet in my own project, which use calculated angle data to control the vrhand just like this [youtube demos](https://www.youtube.com/watch?v=0JC-yukK-jo). I also referenced the deployment in `examples/pybullet/examples/vrhand.py` , which use `p.setRealTimeSimulation(1)` to get a pretty elegant hand controlled results with `p.POSITION_CONTROL` .
After getting smooth control, what I really need is to obtain the torque loaded on each joints at every moment of the control process . But I can't find a proper function in current API to fetch these data back in the `realtimesimulation` . There is a related option called `p.getJointState(objId, jointId)` and its 3rd returned value seems to meet my needs (called `appliedJointMotorTorque`) ,  but it's only valid under `stepSimulation` condition.

Nevertheless, I still tried to call `p.getJointState (objId, jointId) [3]` under `realtimesimulation`,  and save this torque sequence as a pkl file. Then in another program, it is loaded on the same hand urdf model by the `p.TORQUE_CONTROL` control mode under `stepSimulation` ( retargeting of the control process ). 

Experimental results prove that such operations are problematic (hand movement is completely different in the two programs, the latter has a lot of strange behavior).

<img width="523" alt="demo" src="https://user-images.githubusercontent.com/26382832/80058087-e8f2d280-855a-11ea-9d9c-d074f4c01f0a.png">

Therefore, I wonder if it is possible to adjust the parameters of `StepSimulation` to obtain a simulation effect similar to `RealTimeSimulation` without high-frequency jitter?

In addition, I also doubt whether it is reasonable to use the above `appliedJointMotorTorque`(3rd returned value of `p.getJointState(objId, jointId)` ) as the force input parameter of function `setJointMotorControl2` under `p.TORQUE_CONTROL` afterwards ?

**Comment by erwincoumans** [comment]
It has been a few year since I looked into that. Recording the torques during VR should happen in a plugin, so it happens exactly after each internal stepSimulation (in realTime mode). If you call 'getJointState' from python in realTime mode, you may skip simulation steps etc, so that won't work.
Writing such plugin requires a bit of C coding, see the VR sync plugin.
Closing now, since I get too many open topics of discussion. Happy to reply though, even if it is closed.
