### ISSUE TITLE
GCC Error - LIB\bullet3-2.89\btgui No such file or directory

### ISSUE THREAD

**Issue by loopahnoob** [bulletphysics/bullet3#2786]
I'm honestly so confused as to how to install this. I've tried using the python method, however that needs the VC compiler, which I don't have. I'm thinking that maybe MinGW isn't compatible with Bullet. Anyways, here's the log:

(This is built by CMake by the way, MinGW Makefiles)

[1_5-7-2020.log](https://github.com/bulletphysics/bullet3/files/4590384/1_5-7-2020.log)

**Comment by erwincoumans** [comment]
Bullet should compile out-of-the-box on Linux, Mac OSX and Windows using a recent free Visual Studio version.
If you prefer a custom compiler, it is up to you to make the build work.
btw, the log file is partial and shows no error.

**Comment by loopahnoob** [comment]
Is it possible to use MinGW though? I don't have Visual Studio or any IDE installed, I only use a text editor and the MinGW compiler. If this is not possible, then I will consider installing VS.
