### ISSUE TITLE
Parallel Gripper implementation in pybullet

### ISSUE THREAD

**Issue by 1seck** [bulletphysics/bullet3#2791]
Hi there,

I have stl-files of a robot with parallel grippers, I put the 8 parts together with createMultiBody in pybullet and it works fine so far for all DOFs except the grippers. 

How can I add a constraint for the grippers, so they cannot move independently from each other? As I am informed, using resetJointState is not advisable, but it would need to be something like joint_state_gripper_2 = - joint_state_gripper_1 in the JOINT_PRISMATIC axis?
Also would it be better to put everything into an urdf-file instead, does urdf have such a constraint definition? Or do I have to code something in C++?

The actual mechanics of the coupling of the gripper is too complicated to map here I suppose, it basically looks like two half moons attached to the servo motor.

What would be the common way of doing this in pybullet?

**Comment by erwincoumans** [comment]
There is a gear constraint for this, which couples 2 joints (prismatic or revolute).
You can use the gear ratio of 1 or -1 or other values.
See the [mimicJointConstraint](https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/mimicJointConstraint.py).
Note that by default the constraint is purely on the velocity level, so there can be drift. You can enable erp (error reduction parameter) to remove positional drift.

**Comment by 1seck** [comment]
Thank you.
