### ISSUE TITLE
How to use function resetJointStatesMultiDof()?

### ISSUE THREAD

**Issue by GiZumRyue** [bulletphysics/bullet3#2803]
Hi, i am a pybullet starter. And i dont know how to use the function resetJointStatesMultiDof()

it's my code:
`actions = np.zeros(6)
pybullet.resetJointStatesMultiDof(self.robot, range(6), targetValues=actions.tolist())`

The error:
`pybullet.error: Expected an position and/or velocity list.`

That means the format of targetValues is wrong? I already check in PyBullet Quickstart Guide or the examples and cannot find any related information.
Any suggested usage of resetJointStatesMultiDof()? Thx

**Comment by erwincoumans** [comment]
Please see https://github.com/bulletphysics/bullet3/blob/ef08e9b415f05d4fed60f3846730d9579962b61f/examples/pybullet/gym/pybullet_envs/deep_mimic/env/humanoid_stable_pd.py

**Comment by GiZumRyue** [comment]
> Please see https://github.com/bulletphysics/bullet3/blob/ef08e9b415f05d4fed60f3846730d9579962b61f/examples/pybullet/gym/pybullet_envs/deep_mimic/env/humanoid_stable_pd.py

Thx! I have found out the solution!

**Comment by wagenaartje** [comment]
To others that want to know what the actual reason is you get this error: a joint can have multiple states. So let's say you have an object with 3 hinge joints, which you want to assign the angles `[-pi,+pi,-pi]`. Then don't do:

```
pybullet.resetJointStatesMultiDof(objectId, [0, 1,2], [-np.pi, np.pi, -np.pi])
```

But do

```
pybullet.resetJointStatesMultiDof(objectId, [0, 1,2], [[-np.pi], [np.pi], [-np.pi]])
```

In other words, add an extra dimension.
