### ISSUE TITLE
Difference in getJointState angle and getLinkState

### ISSUE THREAD

**Issue by ShravanTata** [bulletphysics/bullet3#2806]
Hi,

I have been using getJointState to query the angle of a joint and been using getLinkState to do some coordinate transforms of a link. But I saw that there is some difference in getting the angle from getJointState and computing the angle of the same link from getLinkState and converting using getEulerFromQuaternion. Any thoughts on where this difference might be coming from? I have added an example to reproduce my observations. Thank you

Shravan

[test_joint_state_error.zip](https://github.com/bulletphysics/bullet3/files/4637176/test_joint_state_error.zip)

**Comment by erwincoumans** [comment]
Thanks for the report.
By default, PyBullet doesn't recompute forward kinematics in getLinkState. Please use this:
~~~~~~~~~~~~~~~~~~
link_state = p.getLinkState(model_id, 0, computeForwardKinematics=True)[5]
~~~~~~~~~~~~~~~~~~
