### ISSUE TITLE
TINY_RENDERER: Color Issue

### ISSUE THREAD

**Issue by chris0914** [bulletphysics/bullet3#2828]
I was unable to reopen the issue #2770. I provided a MWE for the C++ API. Please let me know if this helps.

Cheers Chris

**Comment by erwincoumans** [comment]
You shouldn't use the shape index from 'createVisualShape' (which is a shape unique id) in changeVisualShape: that takes a object unique id, link index, and optionally a local shape index starting from 0, best not to provide it.
