### ISSUE TITLE
contact tests don't detect soft bodies

### ISSUE THREAD

**Issue by stephengold** [bulletphysics/bullet3#2829]
In my application, I discovered that soft bodies are not detected by contact tests. Based on code inspection, I suspect the same is true for convex sweep tests.

`btSoftRigidDynamicsWorld` overrides the `rayTest()` method of `btCollisionWorld` to handle soft bodies, but it doesn't override `convexSweepTest()` nor `contactTest()`.

**Comment by erwincoumans** [comment]
Most features are indeed not implemented at the moment. Closing, since there is no active development happening.
