### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by jimbok8** [bulletphysics/bullet3#283]
I have cloned bullet3 and am trying to run it in Visual Studio Express 2013.
It seems to compile OK
I have picked a demo at random: "App_Bullet3_OpenCL_Demos_clew" but when I try to run it I get an 'out of memory' error.

Manufacturer Hewlett-Packard  Model HP ZBook 17
Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
Total amount of system memory 32.0 GB RAM 
System type 64-bit operating system 
Number of processor cores 4
NVIDIA Quadro K4100M
Total available graphics memory 8192 MB 
        Dedicated graphics memory 4096 MB 
        Dedicated system memory 0 MB 
        Shared system memory 4096 MB 
Display adapter driver version 9.18.13.3265 
Secondary monitor resolution 1920x1080 
Primary monitor resolution 1600x1200 
DirectX version DirectX 10 

The command line has this info:

main startVersion = 4.4.0
Vendor = NVIDIA Corporation
## Renderer = Quadro K4100M/PCIe/SSE2

started GwenUserInterfaceinit fontsclewInit succesfull using OpenCL.dll
numDevices=1
compiling kernel copyTransformsToVBOKernel ready.
clBuildProgram successfully compiled cached binary: cache/mpr.cl.Intel(R) HD Gra
phics 4600.9.18.10.3324.bin
compiling kernel mprPenetrationKernel ready.
compiling kernel findSeparatingAxisUnitSphereKernel ready.
clBuildProgram successfully compiled cached binary: cache/sat.cl.Intel(R) HD Gra
phics 4600.9.18.10.3324.bin
clBuildProgram successfully compiled cached binary: cache/satConcave.cl.Intel(R)
 HD Graphics 4600.9.18.10.3324.bin
compiling kernel findSeparatingAxisKernel ready.
compiling kernel findSeparatingAxisVertexFaceKernel ready.
compiling kernel findSeparatingAxisEdgeEdgeKernel ready.
compiling kernel findConcaveSeparatingAxisKernel ready.
compiling kernel findConcaveSeparatingAxisVertexFaceKernel ready.
compiling kernel findConcaveSeparatingAxisEdgeEdgeKernel ready.
compiling kernel findCompoundPairsKernel ready.
compiling kernel processCompoundPairsKernel ready.
clBuildProgram successfully compiled cached binary: cache/satClipHullContacts.cl
.Intel(R) HD Graphics 4600.9.18.10.3324.bin
compiling kernel clipHullHullKernel ready.
compiling kernel clipCompoundsHullHullKernel ready.
compiling kernel findClippingFacesKernel ready.
compiling kernel clipFacesAndFindContactsKernel ready.
compiling kernel clipHullHullConcaveConvexKernel ready.
compiling kernel newContactReductionKernel ready.
clBuildProgram successfully compiled cached binary: cache/bvhTraversal.cl.Intel(
R) HD Graphics 4600.9.18.10.3324.bin
compiling kernel bvhTraversalKernel ready.
b3Warning[....\src\Bullet3OpenCL\Initialize\b3OpenCLUtils.cpp,651]:

Cached file not found cache/primitiveContacts.cl.Intel(R) HD Graphics 4600.9.18.
10.3324.bin
b3Error[....\src\Bullet3OpenCL\Initialize\b3OpenCLUtils.cpp,914]:
Error in clBuildProgram, Line 914 in file ....\src\Bullet3OpenCL\Initialize\b3O
penCLUtils.cpp, Log:
fcl build 1 succeeded.
fcl build 2 succeeded.
Error: out of memory.

 !!!

b3Error[....\src\Bullet3OpenCL\NarrowphaseCollision\b3ConvexHullContact.cpp,263
]:
Assert ....\src\Bullet3OpenCL\NarrowphaseCollision\b3ConvexHullContact.cpp:263
(errNum==CL_SUCCESS)

---

Why is it making reference to Intel(R) HD Graphics 4600.9.18.?

Note for VS2013 I had to add:
# include  (LT)algorithm(GT) to fem_add_plasticity_force.h

to get rid of errors complaining about  std::min

**Comment by benelot** [comment]
You could make a pull request to add this to the readme. Otherwise it would be good to close this issue to clean up the tracker.

**Comment by erwincoumans** [comment]
closing out-of-date issues (OpenCL is not supported)
