### ISSUE TITLE
1. The difference between Pybullet and Bullet. 2. Buliding error

### ISSUE THREAD

**Issue by Steven-ZY** [bulletphysics/bullet3#2834]
I'm new to Bullet. I have two questions. No.1, what's the difference between Pybullet and Bullet. Do they have the same functions? I have installed Pybullet through conda command, do I need to install Bullet through vcpkg？No.2，after installing vcpkg，when I follow the [instruction](https://github.com/bulletphysics/bullet3#build-instructions-for-bullet-using-premake-you-can-also-use-cmake-instead) to open build3/vs2010/0_Bullet3Solution.sln, I can't build solutions. And how to modify the batch file about Python location? just as said in the picture
![image](https://user-images.githubusercontent.com/59967141/83373252-43a10900-a3fa-11ea-8343-9034be36b7c6.png)
![image](https://user-images.githubusercontent.com/59967141/83373356-97135700-a3fa-11ea-8083-e511dffa505d.png)

I'm looking forward to your answer. Thanks in advance!

**Comment by erwincoumans** [comment]
PyBullet is a python module for sim, robotics and machine learning, it has rendering, inverse kinematics etc. Install is just pip install pybullet, it will do all, no need to manually install Bullet c++.

Bullet C++ is the underlying physics library, you don't need to compile or install it, pip does that.
