### ISSUE TITLE
include file with uppercase letter

### ISSUE THREAD

**Issue by angus-tsile** [bulletphysics/bullet3#2859]
In "BulletCollision\BroadphaseCollision\btDbvt.cpp", there's an include file "LinearMath/btQuickProf.h".
This include file is btQuickprof.h with letter 'p' in lowercase, does not compile under Linux.

**Comment by erwincoumans** [comment]
Indeed, it is dead code (DBVT_ENABLE_BENCHMARK is never defined). Will fix anyway.
Thanks for the report!
