### ISSUE TITLE
Create an example how to perform deformable tetrahedral mesh collision with Bullet

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#286]
It is a frequently asked feature to show how to perform collision detection using tetrahedral meshes (popular in finite element method simulations). This is possible using btCompoundShape in Bullet 2.x, or using the composite shape in Bullet 3.x (experimental).

Create some examples how to use it.

**Comment by benjones** [comment]
I did implement this in my project (easier than I expected).  The collision response looked maybe a little bit better than using triangle meshes, but it runs about 10x slower than the GImpact version, so for most cases I switched back.  I can share a little code after the Siggraph deadline.

**Comment by erwincoumans** [comment]
thanks for the update. I haven't had the time to get back to this, but it will happen eventually. Hope to see you again at SIGGRAPH!

**Comment by erwincoumans** [comment]
closing out-of-date issues. We have new experimental deformables tetrahedral meshes with fem.
