### ISSUE TITLE
How to set a projector in pybullet env?

### ISSUE THREAD

**Issue by baoyufuyou** [bulletphysics/bullet3#2860]
Is it possible to setup a spotlight projector in pybullet like this example? If possible, how? Thanks a lot!
example: 
https://www.youtube.com/watch?v=4pXfKjlC4BU
and 
https://www.google.com/search?q=UE4+PROJECTOR&client=ubuntu&hs=8cX&channel=fs&sxsrf=ALeKk01VujLzSp_axgmSwLxzBy0x3JUrgQ:1592306126299&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjCiqDImobqAhXBwsQBHRj1A4AQ_AUoAXoECAsQAw&biw=1080&bih=1789#imgrc=0zv6XGvDeo05KM

**Comment by erwincoumans** [comment]
There is a projective texture feature here: https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/projective_texture.py

It may not be what you want, so it is best to use another renderer/solution.
