### ISSUE TITLE
Where found <include> to building library ?????????? 

### ISSUE THREAD

**Issue by kaizer1** [bulletphysics/bullet3#2861]
Everything went well, but just add in <include>???? What  include folders? Folders include no? Where to find folders <include>or add it <src> ? I have this folders after build (success build library ( windows 10 )) : 
 CMakeFiles
 data
 examples
Extras
lib
src
test
Testing

**Comment by erwincoumans** [comment]
You can use make install, it installs the include headers, or just include Bullet/src as include path).
Best to discuss in the forums, https://pybullet.org/Bullet/phpBB3/
