### ISSUE TITLE
Problem about slow rendering time

### ISSUE THREAD

**Issue by baoyufuyou** [bulletphysics/bullet3#2880]
Hi guys, I faced also problem of low rendering time. I tested the speed in my computer. Then, the getscreenpixels20423 will take about 17 ms.
with GPU 0: GeForce RTX 2070. Is that normal????? I'm a little bit confused.
Thanks a lot. Guys.

![image](https://user-images.githubusercontent.com/39621208/85417366-cdfb0980-b56f-11ea-9b67-8b5a86eedb53.png)

![image](https://user-images.githubusercontent.com/39621208/85417383-d2272700-b56f-11ea-9dbf-d34f3f359fa3.png)
![image](https://user-images.githubusercontent.com/39621208/85417393-d5221780-b56f-11ea-9292-131c3af1e8fc.png)

**Comment by erwincoumans** [comment]
It depends on resolution etc. Did you try to use EGL? Also, make sure to disable v-sync (rendering may stall on it).

It was closed, did you find a solution?

**Comment by baoyufuyou** [comment]
Thank you very much.  ;) I found I used models with high quality and wrong projection matrix. I simlified the model and fix the projection matrix.   Then, the rendering looks fine. 
I will try to use EGL and test the v-sync. See will it be faster.
