### ISSUE TITLE
Sim-to-real gap for Dynamixel motors?

### ISSUE THREAD

**Issue by jackwilkinson255** [bulletphysics/bullet3#2885]
Is there an example somewhere similar to this: 

[https://www.youtube.com/watch?v=WTMPrv4OJi0](url)

Where the sim-to-real differences between hardware and sim can be seen? I am using Dynamixel XM430-W210 (same in the video) with ROS.

Thanks,

Jack

**Comment by erwincoumans** [comment]
The code for the demo isn't public, and it just used the Dynamixel SDK directly, not ROS.
Good luck!
Erwin
