### ISSUE TITLE
`GetTickCount64` breaks running on Windows < 6.0 (i.e. XP)

### ISSUE THREAD

**Issue by ghost** [bulletphysics/bullet3#289]
Since `GetTickCount64` is unavailable in `WINVER < _WIN32_WINNT_VISTA`, `LinearMath/btQuickprof.cpp` should probably use

```
#if WINVER < 0x0600
#define GetTickCount64 GetTickCount
#endif
```

NB after changing this everything seems to work without slightest problem.

**Comment by iSLC** [comment]
@vaxquis If you have a C++11 compiler available then you could make use of [this patch](https://github.com/bulletphysics/bullet3/pull/305).

**Comment by erwincoumans** [comment]
I applied a compile time check. This still means that an executable build with a newer compiler doesn't run on XP. Would a runtime check be possible?

**Comment by vaxquis** [comment]
in theory we could use something like
```c++
#if WINVER < 0x0600
ULONGLONG GetTickCountLocal() {
  return GetTickCount();
}
#else
ULONGLONG GetTickCountLocal() {
  OSVERSIONINFO vi;
  memset(&vi, 0, sizeof(vi));
  vi.dwOSVersionInfoSize = sizeof(vi);
  GetVersionEx(&vi);
  return (vi.dwMajorVersion >= 6) ? GetTickCount64() : GetTickCount();
}
#endif
```
... and replacing the 3 `GetTickCount64()` calls with `GetTickCountLocal()` calls - but that'd solve nothing, as the very fact that `GetTickCount64` symbol was included in the import table of the DLL will prevent the library from loading on OSes without it. IMO the only options are either to stay with compile check or to use a replacement/wrapper for `GetTickCount64()`, along the lines iSLC proposed (maybe GetTickCount() with manual overflow check? AFAIR that's the only difference between them) - pity there's no C++11 support in the old MSVC compilers.

**Comment by lunkhound** [comment]
The original motivation for the change from GetTickCount to GetTickCount64 was for compatibility with Windows Phone/Windows Store apps (see commit aaaf8dc4e27eb4a48224b7fa265ef3c0b7b664a1).  You could probably do a compile-time check for that (i.e. only use GetTickCount64 when compiling for Windows Phone or Windows Store).

Though I have to wonder how necessary these GetTickCount calls really are.  There is no mention of the issue they are trying to work around (KB274323) on Microsoft's site anymore.  Most PCs these days don't even have an ISA bus.  I have a vague memory of encountering that issue with the windows performance counter jumping back in the late 90's with Windows NT4.
And these timers are only for the profiler from what I can tell.

**Comment by pabloxid** [comment]
I'm a Windows XP user, and I had to change that line by this one to make it really work:

#if WINVER <0x0602
// ULONGLONG GetTickCount64 () {return GetTickCount (); }
#define GetTickCount64 GetTickCount
#endif

**Comment by erwincoumans** [comment]
#if WINVER <0x0602 is applied in master, thanks for the report!

**Comment by pabloxid** [comment]
Sorry, it's not only this line, but also the remain block. For a reason, function wrapper didn't work (it throws an error, don't remember which) but macro version works indeed.

**Comment by erwincoumans** [comment]
ah, ok. updated master again.
