### ISSUE TITLE
Half Cheetah Falls Through Heightfield

### ISSUE THREAD

**Issue by oisinturbitt** [bulletphysics/bullet3#2893]
Hi There,

I am attempting to use the GEOM_HEIGHTFIELD collision shape to generate a random heightfield using Perlin noise. This heightfield is then used to train a half cheetah walker. However, it occurs occasionally that when the half cheetah spawns, a limb will either penetrate the heightfield mesh causing the half cheetah to get stuck or fall through the heightfield entirely.

I have tried using different mesh sizings along changing the numSolverIterations and contactERP parameters but this behaviour still occurs. There is some images of this happening below.

The build I am using is on Ubuntu 18.04, using Python 3.7.4 and pyBullet 2.8.0.

![Selection_039](https://user-images.githubusercontent.com/31827333/86117688-61c85a80-bac7-11ea-8315-2f8bc9fe39c6.png)
![Selection_040](https://user-images.githubusercontent.com/31827333/86117693-62f98780-bac7-11ea-81fe-8f80a50519f3.png)

**Comment by erwincoumans** [comment]
Spawn the half-cheeta above the heightfield, not inside. You can perform a collision query and move the robot down (spawn at a safe height).

**Comment by oisinturbitt** [comment]
Hi Erwin, 

Thanks for taking the time to get back. We are spawning the half cheetah well above the heightfield and it is falling down on to it. Still, the half-cheetah will either get stuck in the heightfield or fall right through it.

**Comment by erwincoumans** [comment]
Can you provide a small reproduction case, preferably no other dependencies?

**Comment by oisinturbitt** [comment]
I was able to find the bug and it was as you said. Due to the random terrain generation, if we had generated terrain with a large incline that the half-cheetah was reset far too high which then lead to the cheetah falling through. Seems to be fixed now and is working perfectly. Thanks a million for the help and for putting the library together!
