### ISSUE TITLE
Lateralfriction is equal to coefficient of sliding friction?

### ISSUE THREAD

**Issue by zhangzhongwd** [bulletphysics/bullet3#2899]
I want to set objects' friction. I found changeDynamics() had three parameters about friction, including lateral friction, spinning friction and rolling friction. How to set object's sliding friction and static friction, is lateralfriction is coefficient of sliding friction? I am confused about this. I saw some examples often set lateralfriction larger than 1, but in fact the coefficient of sliding friction is always less than 1.

**Comment by erwincoumans** [comment]
Yes, lateral friction is sliding friction. Why would the coefficient need to be smaller than 1?
