### ISSUE TITLE
DeepMimic run pretrained policy opens multiple windows

### ISSUE THREAD

**Issue by tchemaly** [bulletphysics/bullet3#2901]
I am executing the following command: 
mpiexec -n 6 python3 testrl.py --arg_file run_humanoid3d_walk_args.txt

Multiple windows open, and the humanoid performs only a part of the action in each window. Can you please help on what the issue could be?

![Screenshot from 2020-07-01 13-48-21](https://user-images.githubusercontent.com/47718813/86235797-ac1e0a00-bba1-11ea-83ff-7fd8c7e16570.png)

**Comment by erwincoumans** [comment]
Remove the mpiexec when enjoying/running the script:
python3 testrl.py --arg_file run_humanoid3d_walk_args.txt
