### ISSUE TITLE
Target position given to setJointMotorControl2 not always met

### ISSUE THREAD

**Issue by seann999** [bulletphysics/bullet3#2906]
I am controlling a mobile manipulator in Pybullet.
Setting the joint positions (calculated with IK) with resetJointState results in a desired pose, but setting them with setJointMotorControl2 and running the simulation for N (>100) steps yields in a pose that is off (and thus the end effector is not in the target pose). I initially thought that it might be because of some collision, but that doesn't seem to be the cause. What could be it?

**Comment by seann999** [comment]
Upon further investigation, it seems like setJointMotorControl2 does not guarantee that the final position will be at the target position.
What can I do to deal with this?

**Comment by seann999** [comment]
Orange lines are target values, blue ones are actual positions
![joints](https://user-images.githubusercontent.com/6847529/86362184-d827b100-bcaf-11ea-810c-2b2807efb3cc.png)

**Comment by erwincoumans** [comment]
small self-contained repro case and I'll re-open the issue :)

**Comment by seann999** [comment]
I've created a gist to reproduce the behavior:
https://gist.github.com/seann999/9f43f493cdce56ed87e662682e3660c4
These are the joint states produced (the last 2 plots for gripper states can be ignored):
![joints](https://user-images.githubusercontent.com/6847529/86935709-19203980-c178-11ea-8305-cdaf2b68d2bf.png)

**Comment by erwincoumans** [comment]
I ran the script but there are no graphs.
It usually takes a couple of simulation steps (not just 1) for the motors to reach a target pose, how many steps did you allow? In addition, the gains/forces need to be tuned well.

**Comment by erwincoumans** [comment]
I had a quick look, the robot doesn't have a fixed base and it penetrating the plane. Please remove the plane and check again. Also, you may want to use a few simulation steps to allow the control to reach the target.

**Comment by seann999** [comment]
I hadn't noticed the penetration; removing the plane worked.
Thank you!
