### ISSUE TITLE
IK support for spherical/MultiDof joints

### ISSUE THREAD

**Issue by ManifoldFR** [bulletphysics/bullet3#2907]
Hello,

I'm trying to retarget motion to a custom robot hand URDF I made that has 10 revolute and 5 spherical (3 DoF) joints. I have a list of Numpy arrays `targets` where each entry is a vec3 
```python
joint_poses = pb.calculateInverseKinematics2(
    objUid,
    end_effector_idx,
    targetPositions=targets,
    maxNumIterations=10,
    solver=pb.IK_DLS
)
```
I get a tuple of length 25, which I guess is the number of DoFs (25 = 3 x 5 + 1 x 10) obtained from `btMultiBody::getNumDofs()`. I expected that number to be 30 = 4 x 5 + 1 x 10 (the value of `btMultiBody::getNumPosVar()`, presumably), because the 5 spherical joints usually have their positions described by quaternions. I think I am mistaken and the output is actually the Euler angles? I am also getting a few segmentation faults.

I guess there is no official support for this right now, then? I started looking at the source code, but I'm not sure if the actual base IK code supports 3 DoF joints.

**Comment by erwincoumans** [comment]
IK for multidof joints is currently not supported indeed. Closing for now, if someone wants to implement it we can re-open/create a PR.

**Comment by ManifoldFR** [comment]
Thanks ! I'll take a look at it if I have time later on.
