### ISSUE TITLE
Saving frame(s) as image and mp4?

### ISSUE THREAD

**Issue by keto33** [bulletphysics/bullet3#2929]
I'm using pybullet and have three questions regarding **video_sync_mp4.py**

1. How can I set the size of the output video size?

2. How can I save the scene only without dialogue windows?

3. Is it possible to save each frame as a single image?

**Comment by erwincoumans** [comment]
Add the --width and --height to the connection options, and use COV_ENABLE_GUI,0 as follows:
~~~~~~~~~~~~~
p.connect(p.GUI, options="--width=320 --height=240 --mp4=\"test.mp4\" --mp4fps=240")
p.configureDebugVisualizer(p.COV_ENABLE_GUI,0)
p.configureDebugVisualizer(p.COV_ENABLE_SINGLE_STEP_RENDERING,1)
~~~~~~~~~~~~~
You can use ffmpeg to extract all frames from the video:
~~~~~~~~~~~~~
ffmpeg -i test.mp4 "frames/out-%03d.jpg"
~~~~~~~~~~~~~
