### ISSUE TITLE
btDbvtBroadphase very slow on sweep/ray testing

### ISSUE THREAD

**Issue by LordOfDragons** [bulletphysics/bullet3#293]
See http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=10266 for discussion. Allow implementors of btHeightTerrain (or convex shape in general) derived classes to optimize long raycast/convexcast calls using cast-aware processAllTriangles variants.

**Comment by erwincoumans** [comment]
closing out-of-date issues. height terrain has its own ray test now.
