### ISSUE TITLE
setGravity named keywords incoherent with quickstart

### ISSUE THREAD

**Issue by LJKS** [bulletphysics/bullet3#2936]
[Walkthrough](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/preview?pru=AAABc3c3e4M*HnpzQG5l9n-II30kZgL8fQ#) states: 
required | gravityX | float | gravity force along the X world axis

but:
self.client = p.connect(p.DIRECT)
p.setGravity(gravityX=0,gravityY=0,gravityZ=9.8, physicsClientId=self.client)

results in TypeError: 
TypeError: Required argument 'gravX' (pos 1) not found

Edit1: Wrong Quickstart Walkthrough, but same issue

**Comment by aravindsiv** [comment]
You can just use:
```
p.setGravity(0,0,-9.8,self.client)
```
and it should work as expected.

**Comment by erwincoumans** [comment]
renamed the gravityX-> gravX etc. Thanks for the report. Indeed, leaving out the args works as well.
