### ISSUE TITLE
Keyword args different than in Quickstart

### ISSUE THREAD

**Issue by LJKS** [bulletphysics/bullet3#2941]
I found some more differences between the Quickstart and actual implementation in : 
resetBasePositionAndOrientation
getBasePositionAndOrientation

According to the Quickstart they expect Keyword "objectUniqueId" which actually is "bodyUniqueId"

Please let me know if Quickstart related Issues are not wished for.
(And if erwincoumans is reading this: Congrats to the RSS best paper award, love your work!)

**Comment by erwincoumans** [comment]
Heh, thanks. Yes, the naming object and body is indeed mixed up, not consistent. We can update the quickstart guide, not worth breaking the API.
