### ISSUE TITLE
Ensure joint limits when using torque control

### ISSUE THREAD

**Issue by ma-rv** [bulletphysics/bullet3#2944]
Hi @erwincoumans, 

Is there a way to ensure joint limits when using torque control with the panda robot? Already in this simple example, the velocity constraint of the joint (2.1750) will be violated. Furthermore is the actual torque limit with 87 even higher, compared to the applied torque of 50. Do I miss something? 

Same when randomly moving all 7 joints via torque control in their assigned max torque range. Constraints on joint positions and velocities will be violated frequently.

I would like to use torque control for reinforcement learning, though I need to guarantee the constraints. I am thankful for any advice!

```
p.connect(p.DIRECT)
p.setGravity(0, 0, -9.81)
p.setTimestep = 1 / 240

p.loadURDF(os.path.join(pybullet_data.getDataPath(), "franka_panda/panda.urdf"), flags=p.URDF_USE_SELF_COLLISION, useFixedBase=True, basePosition=[0, 0, 0])

p.setJointMotorControl2(bodyIndex=0, jointIndex=1, controlMode=p.VELOCITY_CONTROL, force=0)

for _ in range(150):
    
    p.setJointMotorControl2(bodyIndex=0, jointIndex=1, controlMode=p.TORQUE_CONTROL, force=50)
    print(p.getJointState(0, 1))
    p.stepSimulation()
            
```

**Comment by erwincoumans** [comment]
PyBullet only reads a subset of information from the URDF, SDF or MJCF, and that doesn't include joint limit forces. You can use changeDynamics to set the jointLimitForce. See also the Pybullet Quickstart Guide:

https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3

In general, applying random large forces is going to cause instable simulations. It is best to compute them using feedback, for example using PD or PyBullet inverse dynamics, or use the built-in position or velocity control.
