### ISSUE TITLE
Question about Bullet constraint solver

### ISSUE THREAD

**Issue by arpspoof** [bulletphysics/bullet3#2957]
Hello,

I am new to bullet physics simulation. I'm not sure if this is the correct place to ask this question.. What is the default constraint solver used for Featherstone's articulations? Is that sequential impulse? Thank you in advance for any information!

**Comment by Steven89Liu** [comment]
you can refer to this function PhysicsServerCommandProcessor::createEmptyDynamicsWorld(),  by default it will use the  btMultiBodyConstraintSolver as the constriant solver which is the subclass of the btSequentialImpulseConstraintSolver.
hope this can help you.

**Comment by arpspoof** [comment]
Thank you, that's very helpful
