### ISSUE TITLE
Attaching one urdf to other urdf inside pybullet environment

### ISSUE THREAD

**Issue by omi9y** [bulletphysics/bullet3#2960]
Hi,

I've loaded two UR10 robots inside pybullet environment and want them to carry any object(take for eg a rectangular shape bar whose one side will be held by one ur10 and another side by other ur10) from one position to other to perform a collaborative task.

Is there any way to attach that rectangular shape bar to the robot's end-effector inside the pybullet environment while executing the code?

**Comment by erwincoumans** [comment]
You can use the pybullet_utils.urdfEditor for this. See the example attaching a Kuka robot on top of a Husky vehicle:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_utils/examples/combineUrdf.py
https://www.youtube.com/watch?v=5rbRlhT41YI
