### ISSUE TITLE
Configure GPU for EGL Rendering

### ISSUE THREAD

**Issue by chanb** [bulletphysics/bullet3#2962]
Is there a way to specify which GPU to do the rendering? Currently it defaults to a GPU that is significantly weaker than my other GPU. Thanks!

**Comment by erwincoumans** [comment]
It is hardcoded at the moment.
See around line 219 in ci.m_renderDevice = -1;
https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/plugins/eglPlugin/eglRendererVisualShapeConverter.cpp#L219

You could change the code and install it again (python3 setup.py install in the root)
