### ISSUE TITLE
Pybullet URDF Issue

### ISSUE THREAD

**Issue by 1234shel** [bulletphysics/bullet3#3001]
My previous post was closed off so I had to post again. I am loading my URDF file into pybullet. After loading, when I use getJointInfo to retrieve link name and parent id, they do match the parent-child combinations in the Joints within the URDF file.

I have attached the files. It would be great if you could have a look. I just want to know why the parent and child links are not the same as they are defined in the Urdf file.

On a related note, I had to turn off p.URDF_MAINTAIN_LINK_ORDER. This was causing some elements of the Urdf file to go through the floor. I think I have seen other posts reporting this same issue as well.

[robo_files.zip](https://github.com/bulletphysics/bullet3/files/5106777/robo_files.zip)

**Comment by erwincoumans** [comment]
We don't provide such assistance. Please check the Bullet/data urdf files, they should work fine. As long as yours are similar, you should be fine.
