### ISSUE TITLE
[question] Questions about how pybullet is called and where it is installed

### ISSUE THREAD

**Issue by borninfreedom** [bulletphysics/bullet3#3016]
**Environment**
* OS: win10
* virtual env: anaconda3
* IDE: pycharm pro

I am confused about where the pybullet is installed. When I write the ```import pybullet as p```, and press Ctrl + B (this means jump to file) at the 'pybullet'. In the ```pybullet.py``` file at the location ```C:\Users\born_\AppData\Local\JetBrains\PyCharm2020.2\python_stubs\-520983747```, there is one line written like this: 
```python
# from C:\Users\born_\AppData\Roaming\Python\Python36\site-packages\pybullet.cp36-win_amd64.pyd
```

**Why are pybullet.pyd and pybullet.py not installed in the site-package of anaconda's env?**
**How the pybullet.py connects to pybullet.pyd?**

**Comment by erwincoumans** [comment]
Those are setuptools issues, no specific to PyBullet.
