### ISSUE TITLE
MJCF multibody base returns zeros for getBase* operations

### ISSUE THREAD

**Issue by leed04** [bulletphysics/bullet3#3017]
Robots loaded from MJCF files appear not to update the base position, quaternion and velocity if the body is moved by an external force (joint movements, mouse grab from debug visualizer, another object, etc.).  Pybullet always report zeros / identity quaternion in this case.  However, it will report the correct position / velocity if I use resetBaseXXX to move the body.  

In other words, if I reset the base velocity to some value, the MJCF body will move and report the correct position.  But if I locomate the body using forces applied to joints, it will report the base position as zero even though you can clearly see the body move on the GUI.  Note that if I get the linkstate data, it will report the correct position for the link.  

No issue for URDF bodies - they work as expected.

I tried both the pip version and pulling from the repo.

The following will output something like if I use the MJCF:
`base pos (0.0, 0.0, 0.0) (0.0, 0.0, 0.0, 1.0) link0 (1.115901393048976, 0.0, 0.3638164458140663) vel ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))`
and if I use the URDF model:
`base pos (1.6452943032137872, 0.006704730930358081, 0.2939349839712138) (-0.42019997079663385, 0.5999982177735182, -0.24064578037533352, 0.6368074525307131) link0 (1.3457160150449214, -0.2589152467190768, 0.1956358661625387) vel ((0.047596055493145696, -0.6208701263417843, 0.40143882039282924), (-1.0956299125964344, -2.0889457666345432, -3.2329384927868903))`
Simple example:
```
import pybullet as p
import pybullet_data
import numpy as np
physicsClient = p.connect(p.GUI)#or p.DIRECT for non-graphical version
p.setAdditionalSearchPath(pybullet_data.getDataPath()) #optionally
p.setGravity(0,0,-10)
planeId = p.loadURDF("plane.urdf")

test_reset = False
use_mjcf = True

if use_mjcf:
  bodies = p.loadMJCF('mjcf/hopper.xml')
  boxId = bodies[0]
else:
  boxId = p.loadURDF("r2d2.urdf",basePosition=[0,0,1])

numJoints = p.getNumJoints(boxId)
while True:
  if test_reset:
    p.resetBaseVelocity(boxId,[0,0,1])
  else:
    for j in range(numJoints):
      jointInfo = p.getJointInfo(boxId, j)
    
      if jointInfo[2] == p.JOINT_FIXED:
        continue      
      torque = np.random.uniform(-1.0,1.0) * 500
      p.setJointMotorControl2(boxId, j, p.TORQUE_CONTROL, force=torque) 

  p.stepSimulation()
  cubePos, cubeOrn = p.getBasePositionAndOrientation(boxId)
  linkstate = p.getLinkState(boxId,1)
  print ("base pos",cubePos,cubeOrn,"link0",linkstate[0],"vel",p.getBaseVelocity(boxId))
```

**Comment by erwincoumans** [comment]
This is expected: those 2D robots have their base fixed to the world, and add a few degrees of freedom to allow only motion in a 2d plane. So you need to use getLinkState (using computeForwardKinematics=True) to get the world-space information of particular links (see PyBullet quickstart guide for more info).
