### ISSUE TITLE
Update version in pypi

### ISSUE THREAD

**Issue by wmmc88** [bulletphysics/bullet3#3019]
It seems like when I pip install bullet, it installs an outdated version. pip install version 2.8.7 and according to https://pypi.org/project/pybullet/#history it looks like that's the most up to date version available. But looking at the github releases, the latest version should be 2.8.9. Is there plans to update the python repo?

It also seems like the release history in pypi vs in github are completely different. Do they use different versioning schemes?

**Comment by erwincoumans** [comment]
The PyBullet version happens to be similar to the Bullet C++ SDK version, it is up-to-date though.
