### ISSUE TITLE
Inverse Kinematics for a floating Base Example?

### ISSUE THREAD

**Issue by tsgtdss583** [bulletphysics/bullet3#3029]

**Comment by erwincoumans** [comment]
Here is a nice example:
https://github.com/google-research/motion_imitation/blob/master/mpc_controller/laikago_sim.py#L373

IK is used to compute the swing foot trajectory.
Video (using MPC) here: https://www.youtube.com/watch?v=2Qh9r210z_w

**Comment by tsgtdss583** [comment]
thank you so much
