### ISSUE TITLE
Can I load human as soft body in pybullet ?

### ISSUE THREAD

**Issue by deepakraina99** [bulletphysics/bullet3#3054]
I do have solid model of human (.stl and .obj files). How can load it as soft body in PyBullet ? Any suggestions.
Thanks

**Comment by deepakraina99** [comment]
I request someone to anwser my query. Thanks

**Comment by erwincoumans** [comment]
This would be a lot of work, and part of this would be looking at the existing deformable examples etc.
It is best to discuss this on the Bullet forums or elsewhere (stackoverflow).

**Comment by deepakraina99** [comment]
@erwincoumans. Thanks.
