### ISSUE TITLE
setActivationState(0)?

### ISSUE THREAD

**Issue by velkyel** [bulletphysics/bullet3#306]
in btRigidBody::updateDeactivation(btScalar) is line: setActivationState(0)

i have not found what is 0 state.. I think it's wrong call because world updateActivationState() this fix to ACTIVE_TAG.  right?

btw: bullet sources are full of strange and performance penalty code like this. no offense please.

**Comment by ezraanderson** [comment]
~
just for reference purposes
```C
#define ACTIVE_TAG 1
#define ISLAND_SLEEPING 2
#define WANTS_DEACTIVATION 3
#define DISABLE_DEACTIVATION 4
#define DISABLE_SIMULATION 5
```

https://github.com/erwincoumans/experiments/blob/master/bullet2/BulletCollision/CollisionDispatch/btCollisionObject.h

**Comment by erwincoumans** [comment]
The value '0' is overwritten in btDiscreteDynamicsWorld::updateActivationState, but it is not right indeed, is should be ACTIVE_TAG (likely some bug in a refactoring long time ago, I would need to check the history of the project to track it down).

>>btw: bullet sources are full of strange and performance penalty code like this
Please report them so we can address it. Thanks!

**Comment by erwincoumans** [comment]
Closing out-of-date issues.
