### ISSUE TITLE
Meaning of kpOrg and kdOrg in humanoid_stable_pd

### ISSUE THREAD

**Issue by tfederico** [bulletphysics/bullet3#3062]
Hi,

I am trying to adapt deepmimic in pybullet so that it trains the upper part of the body (chest + arms).

I encountered the `_kpOrg` and `_kdOrg` variables in `humanoid_stable_pd` and I have some questions 

1. What do they represent?
2. How did you pick their values? If I were to remove any joint, would the values for the remaining joints change?
3. Is it intentional the fact that the values of `_kdOrg` are the same values of `_kpOrg` divided by 10?

**Comment by tfederico** [comment]
@erwincoumans I have the same question for `build_action_offset`, `build_action_scale`, `build_action_bound_min` and `build_action_bound_max` in `pybullet_deepmimic_env`

**Comment by tfederico** [comment]
I figured the meaning of the proportional and derivative term for the PD controller. Could you tell me how you obtained those values?

**Comment by erwincoumans** [comment]
All those values are from the original deep mimic repository, so that policies created with deep mimic are compatible.
