### ISSUE TITLE
Recording the acceleration at each time stamp

### ISSUE THREAD

**Issue by omi9y** [bulletphysics/bullet3#3067]
Hi,

I want to record position, velocity & acceleration to use it for later purpose. However, I'm able to record position and velocity data but I failing to record acceleration data as there is no direct function to do so. Therefore, I thought of recording velocity, and thereby derivating it get acceleration but now the biggest issue at present is a sampling time. 

Will you please provide the sampling time as I haven't found or if possible directly the function to record the acceleration.

P.S. Here, I'm recording data in the cartesian frame.

Thanks,
Omprakash

**Comment by erwincoumans** [comment]
The default delta time in PyBullet is 1./240.
You can set the delta time using pybullet.setTimeStep(dt), best to keep the dt small, such as in the range of 240 to 2000 Hz
