### ISSUE TITLE
About pybullet torque tracking problem

### ISSUE THREAD

**Issue by ddliu365** [bulletphysics/bullet3#3069]
Hi, folks,

I am using pybullet for simulation via position control for a humanoid.

I found some joint torque information is missing while inquire by `getJointState`.

See the picture below
![image](https://user-images.githubusercontent.com/38701021/93632309-1d0fd980-f9bb-11ea-99a0-21e77595f45a.png)

Can anyone help to fix this issue?

**Comment by erwincoumans** [comment]
We need a small reproduction case. Did your model have fixed joints in the URDF? Did you skip those? Also, did you enable force-torque sensor for the right joints (skipping the fixed joints)?

**Comment by ddliu365** [comment]
Yes,  I have fixed joints in URDF, however, those are not listed in the figure. Would that matter?

while I inquire the jointID, I basically match the name with the joint id. What do you mean by skipping?

I didn't enable force-torque sensor for any joint.

**Comment by erwincoumans** [comment]
Closing for now. If you can share a small pybullet reproduction case, we can re-open.
