### ISSUE TITLE
Gazebo sensors and plugins in pybullet (loadURDF)

### ISSUE THREAD

**Issue by ojasjoshi** [bulletphysics/bullet3#3077]
The quickstart guide says, " PyBullet doesn't process all information from a URDF file.  See the examples and URDF files to get an idea what features are supported." 

In some of the examples, such as data/racecar/racecar.urdf I see gazebo sensors and gazebo plugins. I could not find any official documentation stating what URDF specifications/ fields are processed or not processed by loadURDF. 

Hence, my question is, are gazebo plugins and sensors loaded into pybullet via loadURDF? If not, is there a pybullet recommended way to create custom sensors?

**Comment by erwincoumans** [comment]
gazebo plugins/sensors are not processed. You should be able to implement all sensors using the available data in PyBullet. For example, a radar sensor can be implemented using ray tests. IMU using getBasePositionAndOrientation and getBaseVelocity in addition with some noise model.
