### ISSUE TITLE
pybullet compatibility for specific Ubuntu releases

### ISSUE THREAD

**Issue by ojasjoshi** [bulletphysics/bullet3#3080]
The documentation mentions that Linux distrbutions are supported but does not mention info on the compatibility for Ubuntu 18.04, 16.04 and 14.04 specifically. My question:
- Is pybullet officially supported on all three(18,16,14) Ubuntu releases?
- Are some features not available on certain Ubuntu releases?
- Are there any plans to deprecate compatibility for certain Ubuntu releases in future pybullet releases?

**Comment by erwincoumans** [comment]
PyBullet should work on all Ubuntu versions, it is plain C++ code, nothing fancy.

**Comment by ojasjoshi** [comment]
thanks for the quick response @erikogenvik.. the same logic would work on MacOS and Windows but clarifying to check if there are any constraints for compatibility for certain MacOS and Windows releases?

**Comment by erwincoumans** [comment]
I'm not aware of incompatibilties.
