### ISSUE TITLE
Is the physics parameter maxSolverIterations equivalent to real time update rate? 

### ISSUE THREAD

**Issue by ojasjoshi** [bulletphysics/bullet3#3081]
I am confused as I see that delta stepTime is frequently reported in Hz in the quickguide as well as some other responses. Hence my questions,

- Shouldn't the stepTime be reported in sec?
- I observed that change maxSolverIterations does not make the simulation run faster. Is the maxSolverIterations analogous to real time update rate and configurable via maxSolverIterations parameter?
- Is the (real-time-factor)RTF=1 by default in pybullet?

**Comment by erwincoumans** [comment]
delta time is in seconds, you can also use 1/frequency instead (100Hz == 0.01sec)
maxSolverIterations is a constraint solver setting, and it is best left default (50 iterations). Increase the maxSolverIterations if you need higher accuracy, for example if your simulation has large mass ratios.
In the PyBullet we assume that the simulation delta time is fixed at initialization, and not related to a real wall-clock. Only if you use 'setRealTimeSimulation(true) the simulation is synchronized with the wall-clock, so you can enjoy the simulation, for example using VR.
