### ISSUE TITLE
Why model can go through the table  ？

### ISSUE THREAD

**Issue by poisonwine** [bulletphysics/bullet3#3085]
I load the table of pybullet, whose path is data/table/table.urdf. Then I load a ycb_model, which should be put on the table. However, after simulating for seconds ,  I find the model goes through the table as the picture shows. Why would this happen?
<img src='https://github.com/poisonwine/hw5/blob/master/picture/poke%20into%20the%20desk.png'>

**Comment by erwincoumans** [comment]
No idea what an 'ybc_model' is, but I would recommend looking at the plenty of examples that work fine, in Bullet/data and Bullet/examples/pybullet/examples for example.
