### ISSUE TITLE
Cmake Error Windows 10

### ISSUE THREAD

**Issue by Maximilian-Winter** [bulletphysics/bullet3#3092]
When I try to configure the project in cmake, i get the following error :
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeCompilerIdDetection.cmake:112 (message):
  No preprocessor test for "PathScale"

**Comment by erwincoumans** [comment]
It is probably an error in the cmake installation, it works fine here with cmake-3.18.
~~~~~~~
mkdir build
cd build
cmake ..
~~~~~~~
