### ISSUE TITLE
Planar snake starts flying

### ISSUE THREAD

**Issue by MatthiasKohler** [bulletphysics/bullet3#3101]
I want to simulate a snake. The snake should consist of a few segments, where each joint consists of a spring and a damper. The snake is moved by applying a torque at each joint. I therefore adapted the snake example by switching from position control to torque control and adding constraints at each joint. If I now apply forces at joints, the snake curls up, as expected but then I flies off.

What am I doing wrong here?
[snake.zip](https://github.com/bulletphysics/bullet3/files/5340552/snake.zip)

**Comment by erwincoumans** [comment]
The forces are likely too high. Also this is a forum question, not an issue.
