### ISSUE TITLE
Put a Photo into simulation

### ISSUE THREAD

**Issue by E666GT** [bulletphysics/bullet3#3108]
Hello. May I know if there is a way to put a TV (or GEM_BOX) displaying photos or videos. 

Any methods?

I'm trying to load the texture, but it seems the photo gets a random cropped and resolution. I want the photo to be loaded with its original size and scale.

Thanks

**Comment by erwincoumans** [comment]
set the uv coordinates in an obj file of programmatic created visual shape. you can modify textures on the fly, see the examples/pybullet/examples folder
