### ISSUE TITLE
Bullet User Manual

### ISSUE THREAD

**Issue by britalmeida** [bulletphysics/bullet3#311]
Could you add the User Manual pdf to the git repository? Maybe in docs? next to the already very useful one from Siggraph.
It always takes me a while to find the pdf in it's latest version (which I believe is this one:
http://code.google.com/p/bullet/source/browse/trunk/Bullet_User_Manual.pdf ).

This page could also benefit from a direct link to the pdf:
http://bulletphysics.org/mediawiki-1.5.8/index.php/Bullet_User_Manual_and_API_documentation

Thanks

**Comment by benelot** [comment]
This issue could be closed as the manual is there and the link is added as well.

**Comment by erwincoumans** [comment]
closing out-of-date issues.
