### ISSUE TITLE
I installed tensor flow and baseline under python3.6 environment, but still can't install Pybullet

### ISSUE THREAD

**Issue by Tianrun2** [bulletphysics/bullet3#3113]
Hi,

As mentioned in the topic, I installed python 3.6 environment and installed Tensorflow and Baseline under python 3.6, but I still cannot install pybullet. 

I used pip install pybullet

The specific detail are shown in the follwoing screen shot:

![9cbb29bb7efca4b439767598e1deda2](https://user-images.githubusercontent.com/73015095/96331609-375bd680-1091-11eb-900d-7a508dd6cb10.png)
![d06906c0e3be2aece11c452bd99c4a3](https://user-images.githubusercontent.com/73015095/96331632-607c6700-1091-11eb-9999-92f6f97422f4.png)
![8d736a1b95ca98123504b5d42ef87c6](https://user-images.githubusercontent.com/73015095/96331663-9d485e00-1091-11eb-95d6-20f67dd077d8.png)

**Comment by erwincoumans** [comment]
You need to install the recent visual studio 2019 on Windows, and use pip in a command-prompt with msvc installed.
