### ISSUE TITLE
urdf object Behaving abnormally， Stay vertical instead of falling

### ISSUE THREAD

**Issue by chao0716** [bulletphysics/bullet3#3114]
I tried to drop 10 flat objects at once, but when they fell, they stayed upright instead of inverted. Even if I controlled them with the mouse, they would eventually return to upright. Attached is an example and the mesh file I used was obtained through VHACD. Anyone have an idea about this？Thanks. zip file has the URDF model and .obj and test code
[base_cube.zip](https://github.com/bulletphysics/bullet3/files/5395786/base_cube.zip)

![1](https://user-images.githubusercontent.com/32490390/96338697-7e15f480-10c2-11eb-88f7-ac11bc17ef72.PNG)
![2](https://user-images.githubusercontent.com/32490390/96338698-7f472180-10c2-11eb-8b85-dc8eb5d55154.PNG)

**Comment by erwincoumans** [comment]
An object needs to be centered around its center if mass. Check out the urdf files in the  Bullet data folder, use obj files.
