### ISSUE TITLE
Set an random object for each episode

### ISSUE THREAD

**Issue by Gloriabhsfer** [bulletphysics/bullet3#3144]
Hi All:

I am doing reinforcement learning training with pybullet and my goal is to let the robot reach a random object inside its workspace. But inside my workspace, the object that my robot aiming to reach is keeping moving and will generate more than one inside each episode(I want to train 1 target at 1 epi). I was following the example for kuka robot to add my object.[https://github.com/Gloriabhsfer/bullet3/blob/master/examples/pybullet/gym/pybullet_envs/bullet/kuka_diverse_object_gym_env.py](url)
Here is the related part of my code to generate object:

```
 def reset(self):
        flags = pybullet.URDF_USE_SELF_COLLISION
        pybullet.resetSimulation()
        pybullet.loadURDF(TABLE_URDF_PATH, [0.5, 0, -0.6300], [0, 0, 0, 1])
        pybullet.loadURDF(ROBOT_URDF_PATH, [0, 0, 0], [0, 0, 0, 1], flags=flags)
        pybullet.stepSimulation()
        urdfList=BALL_URDF_PATH
        self._objectID=self.target_generate(urdfList)
        linkstate = pybullet.getLinkState(self.ur5, self.end_effector_index, computeForwardKinematics=True)
        current_pose=linkstate[0]
        self.state=current_pose
        return self.state
def target_generate(self,urdfList):
        flags = pybullet.URDF_USE_SELF_COLLISION
        objectID= urdfList
        pos = np.random.uniform(POS_MIN, POS_MAX)

        objectID=pybullet.loadURDF(BALL_URDF_PATH, pos, [0, 0, 0, 1],flags=flags)
        for _ in range(500):
            pybullet.stepSimulation()
        return objectID
def step(self, action):
        urdfList=BALL_URDF_PATH
        objectID=self.target_generate(urdfList)
###other parts for change robot pos, vel and get rewardm done###
```
But my simulation will have multiple objects inside one episode, and it will not disappear when 1 training is finished.
![Screenshot from 2020-11-11 14-32-24](https://user-images.githubusercontent.com/13515137/98855977-e1c5e000-242a-11eb-9685-9142bfdb7a92.png)
Does someone have any ideas about this?
Best,
Gloria

**Comment by erwincoumans** [comment]
The target_generate is generating objects each step, so it is expected.
