### ISSUE TITLE
Programmatically create new links and joints?

### ISSUE THREAD

**Issue by seann999** [bulletphysics/bullet3#3155]
Is this possible? This is to procedurally generate a robot.
Otherwise I guess this would involve writing to a urdf/sdf file then reading it, which is a little cumbersome.

**Comment by erwincoumans** [comment]
You can use pybullet.createMultiBody,
see also https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_utils/examples/combineUrdf.py or
createMultiBody* examples in
https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/examples
