### ISSUE TITLE
stable pd  controller does not work for atlas model

### ISSUE THREAD

**Issue by zeshiYang** [bulletphysics/bullet3#3170]
I tried to use the stable PD
[test_spd.txt](https://github.com/bulletphysics/bullet3/files/5610066/test_spd.txt)

 controller in "setJointMotorControlMultiDofArray" to drive atlas robot provided in pybullet robot repo. However, it seems the simulation is not stable and crashed.
I checked the stable PD controller implementation and found that the mass matrix is singular.
Besides the singular mass matrix, the centrifugal force computed by calculateInverseDynamic function contains Nan values. 

Could please tell me why the stable PD controller does not work for the atlas model?
Attached is my python script. Thank you for your help.

**Comment by erwincoumans** [comment]
It likely requires more work, no time to help fixing. Good luck!
