### ISSUE TITLE
Pybullet from pip does not install on 10.15.7

### ISSUE THREAD

**Issue by themightyoarfish** [bulletphysics/bullet3#3175]
I'm using Python 3.8.6 in a venv, and `python setup.py install` yields a bunch of errors, starting with
```
examples/ThirdPartyLibs/zlib/gzlib.c:264:18: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
```

Clang version is 12.0.0

The full output is here (too long for github): https://pastebin.com/yLEE1Gzc

What could this be caused by?

The master branch installs successfully.

**Comment by erwincoumans** [comment]
Where is -Werror defined?

**Comment by erwincoumans** [comment]
I tried pip3 install pybullet on various new machines (Mac OSX 10.16 Big Sur etc), no issue. Cannot reproduce, lets close

**Comment by themightyoarfish** [comment]
Here' how I can reproduce this problem:

- MacOS Catalina 10.15.7 
- Python 3.8.7 (from homebrew)
- A `requirements.txt` with only `pybullet~=2.8.7` in it

```
python3 -m venv test_venv
source test_venv/bin/activate
pip install -r requirements.txt --no-cache-dir
```

Maybe the problem exists only in this specific verions

**Comment by erwincoumans** [comment]
> Here' how I can reproduce this problem:
> 
> * MacOS Catalina 10.15.7
> * Python 3.8.7 (from homebrew)
> * A `requirements.txt` with only `pybullet~=2.8.7` in it
> 
> ```
> python3 -m venv test_venv
> source test_venv/bin/activate
> pip install -r requirements.txt --no-cache-dir
> ```
> 
> Maybe the problem exists only in this specific verions

please try using the latest version

**Comment by themightyoarfish** [comment]
Yeah it works with the latest one, but I'd be curious what the problem is, as that version used to work. Anyhow, might be useful for others seeing this issue.
