### ISSUE TITLE
Where is the deformable_torus.py example?

### ISSUE THREAD

**Issue by eflopez1** [bulletphysics/bullet3#3178]
Hello,

I am interested in using PyBullet for some simulation work with my research and saw this video of a deformable torus:
https://www.youtube.com/watch?v=_EOvLbEEZHk

When downloading PyBullet using pip, I could not find the example. In order to use this example, is it necessary to build the code from source?

Sorry of this is a simple question, and thank you for the help!

**Comment by erwincoumans** [comment]
Good question. See the examples folder under https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet
