### ISSUE TITLE
premake4 executables

### ISSUE THREAD

**Issue by xriss** [bulletphysics/bullet3#3180]
I notice you have a bunch of premake4 executable files in the build3 directory, which is exactly the situation I used to be in with one of my projects until a little while ago when I decided to take a hard look at the premake4 source code and see if I could convince premake4 to run inside a standard lua environment.

The result was this fork of premake4 ( with vs2015 patch )

https://github.com/xriss/puremake

The upside is less binary blobs in the repo, the downside is you have a luajit system dependency when building.

It should be a simple drop in replacement for all of the binary files and some slight changes to the build documentation.

Would you be interested in a pull request to do that?

**Comment by erwincoumans** [comment]
That's interesting, thanks for sharing. At this stage, it is nicer to be self-contained, instead of an additional system dependency. It maybe useful for new platforms though (where we don't ship a premake4 exe). Will keep an eye on your link if needed, but a pull request is not needed. Thanks!
