### ISSUE TITLE
Inverse Dynamics 

### ISSUE THREAD

**Issue by aravind-3105** [bulletphysics/bullet3#3187]
Following the implementation part of the controller.

![issue](https://user-images.githubusercontent.com/54389263/101263277-1f313b00-3755-11eb-9a52-1625bfe9adc6.png)

The deviation between the desired and actual position is higher than expected. The error doesn't tend to converge to 0 even after sufficient time given for the controller. What could be the possible reasons for this discrepancy?

**Comment by erwincoumans** [comment]
See here for a working case: https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/inverse_dynamics.py
Otherwise please create a new issue with a small full reproduction case.
