### ISSUE TITLE
stepSimulation incorrectly declared in examples

### ISSUE THREAD

**Issue by cga-cmu** [bulletphysics/bullet3#3200]
I tried changing the time step in stepSimulation in code copied from the examples, but it had no effect. It turns out that stepSimulation as defined and used in the examples tree ignores the 2nd and 3rd arguments:
virtual void stepSimulation(float deltaTime)
and m_dynamicsWorld->stepSimulation(deltaTime)
when it should be
virtual void stepSimulation(btScalar deltaTime, int max_n_steps, btScalar step_size )
and m_dynamicsWorld->stepSimulation(timeStep,maxSubSteps,fixedTimeStep);

There is also the issue of whether the arguments to stepSimulation should be float or btScalar. The principle in the code seems to be that only states need to be btScalar and thus possibly double, and simulation parameters like eps are declared as floats.

This is in many (all?) xxxExamples.cpp files but most importantly in
CommonInterfaces/CommonRigidBodyBase.h:	virtual void stepSimulation(float deltaTime)
CommonInterfaces/CommonRigidBodyBase.h:			m_dynamicsWorld->stepSimulation(deltaTime);
CommonInterfaces/CommonExampleInterface.h:	virtual void stepSimulation(float deltaTime) = 0;
CommonInterfaces/CommonMultiBodyBase.h:	virtual void stepSimulation(float deltaTime)
CommonInterfaces/CommonMultiBodyBase.h:			m_dynamicsWorld->stepSimulation(deltaTime);

Check out
grep -R stepSimulation examples

It took a while for me to figure this out, and it might help others who are also starting out to fix this.
Thanks very much for Bullet!
Chris

**Comment by erwincoumans** [comment]
Thanks for bringing this up. Most of the example simplify the call indeed, and assume the default internal fixed stepsize of 1./60. for most of the default examples. btScalar is preferred over straight 'float'.
In PyBullet, we use double precision for the simulation, and explicitly let the user specify the fixed internal step size, which is 1./240. for typical robotics usage (some use 1./1000. sec).
