### ISSUE TITLE
The function `createConstraint` make me confuse.

### ISSUE THREAD

**Issue by zapplelove** [bulletphysics/bullet3#3205]
I want to use this function to form loop structures in a very complex robot. In gazebo, I can just use the `<gazebo><joint /></gazebo>` label, and the position of the new joint frame is relative to the child link frame. But in pybullet, the position of new joint frame is relative to both parent and child center of mass frame, this makes me confuse, why use two link frames? And why use the mass frame? If the shape is complex, and the mass frame may have a rotating, so I think this function can have an optional choice to choose the method like gazebo.

**Comment by erwincoumans** [comment]
You can use pybullet.multiplyTransforms and pybullet.inverseTransform to convert between coordinate frames. There is no plan to change the constraint API (unless someone contributes it). Good luck!
