### ISSUE TITLE
The exact meaning of qIndex returned by  getJointInfo

### ISSUE THREAD

**Issue by borninfreedom** [bulletphysics/bullet3#3240]
* getJointInfo returns a list of information, the 3th index is qIndex, which is described as the first position index in the positional state variables for this body.
* When I run 
```python
kukaId = p.loadSDF("kuka_iiwa/kuka_with_gripper2.sdf")
kukaId=kukaId[0]
for i in range(numJoints):
    p.stepSimulation()
    jointInfo=p.getJointInfo(kukaId,i)
    qIndex = jointInfo[3]
    print(f"joint {i}={qIndex}")
```
* The output is 
```python
joint 0=7
joint 1=8
joint 2=9
joint 3=10
joint 4=11
joint 5=12
joint 6=13
joint 7=14
joint 8=15
joint 9=-1
joint 10=16
joint 11=17
joint 12=-1
joint 13=18
```
What's the exact meaning?

**Comment by erwincoumans** [comment]
q are the joint coordinates. The first 7 are for the base (3 position, 4 orientation quaternion). From 7 onward, there are the revolute joints. -1 refers to a fixed joint.
