### ISSUE TITLE
How to view the source code of pybulllet's API?

### ISSUE THREAD

**Issue by borninfreedom** [bulletphysics/bullet3#3241]
For example, I want to view the source code of calculateInverseKinematics, where can I find it?

**Comment by cadop** [comment]
Maybe this helps 

https://github.com/bulletphysics/bullet3/blob/93be7e644024e92df13b454a4a0b0fcd02b21b10/examples/SharedMemory/PhysicsServerCommandProcessor.cpp#L12749

**Comment by borninfreedom** [comment]
OK, thank you very much.

**Comment by cadop** [comment]
If the link was able to answer it, maybe you could close the issue?

**Comment by erwincoumans** [comment]
@cadop 's link is indeed the pybullet python binding, the actual C++ processing of the commands happens here:
https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/PhysicsServerCommandProcessor.cpp#L13839
