### ISSUE TITLE
Android builds, breaking because _N,_C varibles ??

### ISSUE THREAD

**Issue by ezraanderson** [bulletphysics/bullet3#325]
breaking the C++ spec, by using _N and _C as variables (which are reserved by ISO.IEC 14882 Section 18.4.3.1.2 )

https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/Gimpact/gim_basic_geometry_operations.h

Fix:
 https://github.com/ezraanderson/plugin-moai-bullet/commit/e437cc52d97a6adbe86404262b47c3e488463158

**Comment by erwincoumans** [comment]
Likely this is an issue with some standard C++ header that is included before a Bullet header, right?
Sorting the order of the header includes (first Bullet, than C++ header) should fix it too, right?
Anyway, I applied a fix.

**Comment by erwincoumans** [comment]
Fix in this pull request
