### ISSUE TITLE
[CMake] [MSVC] setting USE_MSVC_RUNTIME_LIBRARY_DLL to ON has no effect

### ISSUE THREAD

**Issue by SoapyMan** [bulletphysics/bullet3#3268]
Setting **USE_MSVC_RUNTIME_LIBRARY_DLL** has no effect - project files will still remain with *Multithreaded* runtime
Seems like **USE_MSVC_RELEASE_RUNTIME_ALWAYS** does not work either.

Expected: Multithreaded DLL

CMake version: 3.19.2
Generator: Visual Studio 16 (2019)

**Comment by erwincoumans** [comment]
The cmake files are just for convenience, we don't support them. If you have an issue, just edit the files.
