### ISSUE TITLE
_get_cpu_capabilities license matter?

### ISSUE THREAD

**Issue by cielavenir** [bulletphysics/bullet3#3272]
In https://github.com/bulletphysics/bullet3/blob/abea1a848411cf53385fb8288c89db05e5751ef7/src/Bullet3Common/b3Vector3.cpp#L848 (today's latest master), I see 0x2000 constant. It seems it checks for FMA availability. The thing is, how did you find the meanings? I found that this is defined in OSFMK source code, but it is license under APSL. So I wonder if entire bullet3 can be licensed under zlib license.

**Comment by erwincoumans** [comment]
That file was contributed by Apple under the zlib license. I have never heard of OSFMK or APSL, but there is no relationship with that project.
