### ISSUE TITLE
Unpredictable Object Kinematics

### ISSUE THREAD

**Issue by zshureih** [bulletphysics/bullet3#3277]
Been reading through the pybullet quickstart guide in order to run a simulation of two objects. The task is to determine whether or not one of the objects will land on the other, and we are given this data from a unity simulation running in parallel. The unity simulation may or may not produce an accurate or realistic result, and we are developing an agent that can determine whether or not the result was realistic.

This was working at one point, but we've now encountered an interesting problem where the dropped object ("target") flies infinitely in the negative z direction (so it can't be seen), and then when it reaches z = ~-180 it is present in the simulation.
The support object (the block resting on the plane), does not exhibit this behavior.

At first, we believed this to be an issue with objects overlapping, as the only case where target objects were behaving this way were cases like the one shown below.
![image](https://user-images.githubusercontent.com/42466551/108641731-b99c4300-7455-11eb-8ace-f76acd6dfad8.png)

However, the problem has now spread to all target objects. We utilize p.getOverlappingObjects, and p.getContactPoints to make sure that the target and supporting objects are not overlapping at the start of the simulation, and we have run tests where the supporting object isn't ever created, and we still see the same behavior in the target object.

Objects are generated by extracting their dimensions, positions, mass, and rotations from the unity simulation, and then creating mulitbodies from this data.

Will happily provide code to help solve the issue

**Comment by erwincoumans** [comment]
No idea about the request, but unless you have a small reproduction case in a small pybullet test showing a bug, it is best to discuss this in the forums (and hope someone can help).
