### ISSUE TITLE
Caculate Jacobian matrix and mass matrix with respect to part of arm joints

### ISSUE THREAD

**Issue by zhuyifengzju** [bulletphysics/bullet3#3279]
Hi,
    I would like to ask if there is a way to calculate jacobian matrix and mass matrix with respect to the arm joints only (without considering grippers). It seems that if the gripper is defined in the same urdf file with the arm, the `calculateMassMatrix` or `calculateJacobian` does not work if I only pass in positions for arm joints. Thanks!

**Comment by erwincoumans** [comment]
You could create a separate URDF files, without the gripper.
