### ISSUE TITLE
-lboost_regex needed during linking

### ISSUE THREAD

**Issue by sjneph** [bulletphysics/bullet3#329]
This is my first time building bullet3.  I'm using Fedora 20 with boost 1.54.0 installed through the package manager.

cd build3
./premake_linux64 gmake
cd gmake
make

Gives the same error in two build cases.
test_bullet_collision.make
Test_OpenCL_Bullet3.make

../../bin/libgtest_gmake_x64_release.a(gtest-all.o): In function `testing::internal::RE::~RE()':                                                                                                                   
gtest-all.cc:(.text+0x46ef): undefined reference to `regfreeA'
...

The fix was to include -lboost_regex to the LIBS variable in each of those two make files.

**Comment by erwincoumans** [comment]
Bullet has no dependency on boost, this is a bug and any boost usage should be removed. If gtest really depends on boost, then we have to remove gtest or fix that.

**Comment by sjneph** [comment]
Okay, that's a bad assumption on my part (boost dependency).  I will dig further into this.

**Comment by erwincoumans** [comment]
It would be great if you can help sorting out the mess on Fedora with gtest. Can you check out how to link against POSIX regex on Fedora?

**Comment by sjneph** [comment]
It looks like things compile fine. I was picking up boost's header for regex like a dummy.  Sorry for my confusion - I'll close this out.

**Comment by tauruswang** [comment]
😊v  
-lboost_regex needed during linking    yes, gmake use the boost regex ???

**Comment by erwincoumans** [comment]
Bullet doesn't use boost.
