### ISSUE TITLE
How to uninstall the pybullet installed with cmake?

### ISSUE THREAD

**Issue by huzheyuan740** [bulletphysics/bullet3#3299]
Hello! I have installed pybullet using CMake before, but after that, I installed pybullet using pip again and got the following error, I think it might be related to the previous CMake installation. So I would like to ask how to uninstall the CMake installation? Thanks.

`
pybullet build time: Mar  4 2021 20:16:12
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce RTX 2080 Ti/PCIe/SSE2
GL_VERSION=3.3.0 NVIDIA 410.78
GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.3.0 NVIDIA 410.78
Vendor = NVIDIA Corporation
Renderer = GeForce RTX 2080 Ti/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
!!!!: /home/huzheyuan/anaconda3/envs/bulletenv/lib/python3.6/site-packages/pybullet_data
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/UrdfFindMeshFile.h,102]:

b3Printf: plane.urdf:15: cannot find 'plane100.obj' in any directory in urdf path

Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: Could not parse visual element for Link:
Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: planeLink
Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: failed to parse link
Traceback (most recent call last):
  File "hello.py", line 8, in <module>
    planeId = p.loadURDF("plane.urdf")
pybullet.error: Cannot load URDF file.
ven = NVIDIA Corporation
numActiveThreads = 0
stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
`

**Comment by erwincoumans** [comment]
How did you install pybullet with cmake? Usually it involved some manual creation of symbolic links, just remove those.
