### ISSUE TITLE
xarm6_with_gripper doesn't work as desired.

### ISSUE THREAD

**Issue by seolhokim** [bulletphysics/bullet3#3308]
```
import pybullet as p
import time
import pybullet_data
physicsClient = p.connect(p.GUI)
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.setGravity(0, 0, -9.8)
p.setTimeStep(1/200)
planeID = p.loadURDF("plane.urdf")
cubeStartPos = [0, 0, 0.5]
cubeStartOrientation = p.getQuaternionFromEuler([0,0,3.14/2])
robotID = p.loadURDF("xarm/xarm6_with_gripper.urdf", cubeStartPos, cubeStartOrientation)
p.setRealTimeSimulation(0)


orientation = p.getQuaternionFromEuler([3.14,0,0])

gripper_idx = 7
target_position = p.calculateInverseKinematics(robotID,gripper_idx,[0.5,0.5,0.4],targetOrientation = orientation)
p.setJointMotorControlArray(robotID,range(len(target_position)),p.POSITION_CONTROL,targetPositions = target_position)
for _ in range(300):
    p.stepSimulation()
p.getLinkState(robotID, gripper_idx)[0]

```

This result shows this arm can't calculate joint state well.

**Comment by lorepieri8** [comment]
Any guesses on where the error comes from? The URDF?

**Comment by erwincoumans** [comment]
You can see a working example here: 
https://github.com/erwincoumans/xArm-Python-SDK/tree/master/example/wrapper/xarm6
run 
~~~
python loadarm_sim.py
~~~
Good luck!

**Comment by seolhokim** [comment]
What I want to ask is why gripper doesn't move to coordinates where i wanted to move correctly.

I calculated InverseKinematics and do setJointMotorControl like I did in kukagymenv.
If call kuka_iiwa/kuka_with_gripper2.sdf and do exactly same work, then It works well. but xarm6_with_gripper.urdf not.

**Comment by lorepieri8** [comment]
@seolhokim 

I think you where considering the wrong links, try:

`p.setJointMotorControlArray(robotID,range(1,len(target_position)+1),p.POSITION_CONTROL,targetPositions = target_position)`

**Comment by lorepieri8** [comment]
Also, maxNumIterations=50 helps in calculateInverseKinematics.

**Comment by seolhokim** [comment]
@lorepieri8 It works! Thank you so much. I need to analyze it more.
