### ISSUE TITLE
unable to load cube with different color for each side

### ISSUE THREAD

**Issue by shiyani21** [bulletphysics/bullet3#3316]
I have made a cube in blender and given each side a different color, I am trying to load it in the simulator and only 1 color shows up for the entire cube.
[cube_10_6_6_zip.zip](https://github.com/bulletphysics/bullet3/files/6166004/cube_10_6_6_zip.zip)
here is the image of what it looks in the simulator:
![image_0](https://user-images.githubusercontent.com/75742827/111668683-61eebe80-87ec-11eb-95ce-da4b7ffbf761.png)
and this is what it looks like in blender
![image](https://user-images.githubusercontent.com/75742827/111669883-9ca52680-87ed-11eb-9d8f-5df90f800f8f.png)

**Comment by erwincoumans** [comment]
You will need to texture-map the cube in a program such as Blender, use a texture with different colors, and assign the UV's accordingly.
