### ISSUE TITLE
MemLeak - placing/removing objects

### ISSUE THREAD

**Issue by chris0914** [bulletphysics/bullet3#3319]
When running the below code the memory usage slowly increases. I am not sure if it is caused by placing or removing. When only placing cylinders memory consumption increases, but that is not necessarily unexpected. However, I do not see a way to test removing without placing. Nevertheless, as I am doing reinforcement learning it is not unusual to repeatedly place and remove obstacles, which leads to the steady increase in memory.
Tested with python 3.8.5 under Ubuntu 18.04 and Ubuntu 20.04. Used pybullet 3.1.0.

```
import pybullet as p

p.connect(p.DIRECT)
while True:
    p.removeBody(
        p.createMultiBody(
            0,
            p.createCollisionShape(p.GEOM_CYLINDER, radius=0.1, height=1.0),
            basePosition=[0, 0, 0.5],
        )
    )
p.disconnect()
```

**Comment by erwincoumans** [comment]
The collision shape is not removed (it can be shared among multiple bodies), you will need a resetSimulation to remove the collision shape. Generally it is best to create objects up-front, and only use saveState/restoreState.
