### ISSUE TITLE
How to Add a new B3_SHARED_API b3SharedMemoryCommandHandle ?

### ISSUE THREAD

**Issue by mohammad200h** [bulletphysics/bullet3#3327]
Hi,

I am adding a functionality to pybullet that enables it two detect collision between btGhostobject and btRigidBody.

I hacked my way through the source files and I am on the last stage.

I have created a new b3SharedMemoryCommandHandle called:
B3_SHARED_API b3SharedMemoryCommandHandle b3InitRequestGhostCollisionInformation(b3PhysicsClientHandle physClient)
I have added this command to pybullet.c, PhysicsClientC_API.cpp and PhysicsClientC_API.h.

I have compiled the code and installed pybullet form source using pip3 command.

When I import pybullet I get the following error:
 import pybullet as p
ImportError: /home/mamad/hand_RL_ws/bullet3/examples/pybullet/gym/pybullet.cpython-36m-x86_64-linux-gnu.so: undefined symbol: b3InitRequestGhostCollisionInformation

So my question is how do I add a new command and avoid getting this error?

Best
Mohammad

**Comment by erwincoumans** [comment]
It should work fine, if you follow the same functions as other ones, in pybullet.c, PhysicsClientC_API.cpp and PhysicsClientC_API.h
Not sure what went wrong.
