### ISSUE TITLE
How to disable X and Y-axis movement in PyBullet

### ISSUE THREAD

**Issue by h3ct0r** [bulletphysics/bullet3#3332]
Hi guys, I am looking into simulating only rotations and gravity for a URDF object using Pybullet. In this sense, I need to disable movements in the X and Y axis: meaning that the object can drop with gravity, and the collisions will affect the roll, pitch, and yaw, but it will not produce any lateral movements.

A post on the gamedev.stackexchange shows that the C++ API has the `setLinearFactor` and `setAngularFactor` functions that should do something similar of that I'm looking for (https://gamedev.stackexchange.com/questions/22319/how-to-disable-y-axis-movement-in-the-bullet-physics-engine). Is there anything like that in the Python API?

```
body->setLinearFactor(btVector3(1,0,1));
body->setAngularFactor(btVector3(0,1,0));
```

Issue #1028 says something about "using maximal coordinate constraints or btMultiBody and adding the right degrees of freedom using a fixed base" to limit the degrees of freedom, but I haven't found any example of this. Can anyone point me into a example/documentation reference to achieve this?

A version of this question was also asked in [StackOverflow](https://stackoverflow.com/questions/66897121/how-to-disable-x-and-y-axis-movement-in-pybullet), with no answers yet.

Thanks!

**Comment by erwincoumans** [comment]
See this example:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/biped2d_pybullet.py
