### ISSUE TITLE
Pybullet rigid and multi body representation 

### ISSUE THREAD

**Issue by mostafa-hussein** [bulletphysics/bullet3#3333]
Hi all,

Does Pybullet only support the btmultibody architecture from Featherstone? 
Is there any parameter we can set that allow us to use the btrigidbody architecture? 
Another question does the MLCP equations will be different in both architectures (btrigidbody and btmultibody )

Thanks all for reviewing my question.

**Comment by erwincoumans** [comment]
PyBullet supports both. Use the useMaximalCoordinates flag in loadURDF. Not all features are supported when using useMaximalCoordinates  = True, so Featherstone is recommended.
