### ISSUE TITLE
About using VR in PyBullet

### ISSUE THREAD

**Issue by 1210652636** [bulletphysics/bullet3#3334]
I do not know how to use VR in PyBullet, I even do not know how to start. Please help me. I am very confused about it.

**Comment by cadop** [comment]
Hopefully these resources can help

1. Page 72 of the pybullet quickstart guide https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3
1. Examples folder has a few VR things https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/examples
1. This kind of sparse doc (referenced in the quickstart guide) https://docs.google.com/document/d/1I4m0Letbkw4je5uIBxuCfhBcllnwKojJAyYSTjHbrH8/edit#

**Comment by 1210652636** [comment]
Thanks a lot! I have known these three links and I even tried the examples about VR, but it didn't work, the program can not connect to my VR and I do not know why. I didn't find a very detailed tutorial to help me connect to VR.

**Comment by BluePrintRandom** [comment]
blender xr_action branch is wrapping openXR

I think window_manager.c has the relevant code to run a XR session

**Comment by 1210652636** [comment]
![image](https://user-images.githubusercontent.com/36726128/113655057-b8546c00-96cb-11eb-8a2e-33a68f2c0d43.png)
Now I can only run an empty VR world and there is nothing in this world. I can not see the robot or any other items in the world. And I run the "https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/examples/vrEvent.py", nothing happened, I even can not see any output in the output page.
![image](https://user-images.githubusercontent.com/36726128/113655458-6fe97e00-96cc-11eb-9086-fa96191dc18d.png)

**Comment by erwincoumans** [comment]
Are you running App_PhysicsServer_SharedMemory_VR?
Once that runs fine, and you see an empty world, I recommend try running vr_kuka_setup.py next:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/vr_kuka_setup.py

**Comment by 1210652636** [comment]
![image](https://user-images.githubusercontent.com/36726128/113677579-50fce300-96f0-11eb-9d04-013ad717b6c1.png)
I performed a series of operations based on what is shown in the image above.
![image](https://user-images.githubusercontent.com/36726128/113677839-96b9ab80-96f0-11eb-81d5-a7dcfb2b6eb6.png)
The script generates a series of files. Actually I did not see "App_PhysicsServer_SharedMemory_VR.exe", I saw files with the name "App_PhysicsServer_SharedMemory_VR" in other formats, which I then opened in MSVC.
I try to run the "App_PhysicsServer_SharedMemory_VR":
![image](https://user-images.githubusercontent.com/36726128/113678756-9372ef80-96f1-11eb-8d07-f44aa77f412e.png)
![image](https://user-images.githubusercontent.com/36726128/113679664-96221480-96f2-11eb-8431-fa5d43543400.png)
Right-click on "App_PhysicsServer_SharedMemory_VR" and run it. All I can see is the following image.
![image](https://user-images.githubusercontent.com/36726128/113679913-df726400-96f2-11eb-8a3b-186b8736b76b.png)
I run other codes that give the following screen, this may not have anything to do with VR.
![image](https://user-images.githubusercontent.com/36726128/113680023-016be680-96f3-11eb-9cd6-1412cf3b225f.png)

And then I try to run "https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/vr_kuka_setup.py", and nothing happened. The steps I ran were as follows: 1. Right-click on "App_PhysicsServer_SharedMemory_VR" and run it and I would see a blank screen in VR (with nothing in it but two handles). And then I run "https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/vr_kuka_setup.py" and it just runs there by himself, nothing is output, nothing happens, and nothing is visible in VR.
![image](https://user-images.githubusercontent.com/36726128/113680781-d2a24000-96f3-11eb-9086-4f3e48ddd468.png)
Am I doing the steps correctly? I know maybe I am a little stupid but I am try my best to do these things, so pls tell me about this, thanks a lot!!

**Comment by 1210652636** [comment]
> Are you running App_PhysicsServer_SharedMemory_VR?
> Once that runs fine, and you see an empty world, I recommend try running vr_kuka_setup.py next:
> https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/vr_kuka_setup.py
> 
> Best to run a plain terminal and regular python (3) version, no ipython or other versions.

image
I performed a series of operations based on what is shown in the image above.
image
The script generates a series of files. Actually I did not see "App_PhysicsServer_SharedMemory_VR.exe", I saw files with the name "App_PhysicsServer_SharedMemory_VR" in other formats, which I then opened in MSVC.
I try to run the "App_PhysicsServer_SharedMemory_VR":
image
image
Right-click on "App_PhysicsServer_SharedMemory_VR" and run it. All I can see is the following image.
image
I run other codes that give the following screen, this may not have anything to do with VR.
image

And then I try to run "https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/vr_kuka_setup.py", and nothing happened. The steps I ran were as follows: 1. Right-click on "App_PhysicsServer_SharedMemory_VR" and run it and I would see a blank screen in VR (with nothing in it but two handles). And then I run "https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/vr_kuka_setup.py" and it just runs there by himself, nothing is output, nothing happens, and nothing is visible in VR.
image
Am I doing the steps correctly? I know maybe I am a little stupid but I am try my best to do these things, so pls tell me about this, thanks a lot!!

**Comment by 1210652636** [comment]
> Are you running App_PhysicsServer_SharedMemory_VR?
> Once that runs fine, and you see an empty world, I recommend try running vr_kuka_setup.py next:
> https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/vr_kuka_setup.py
> 
> Best to run a plain terminal and regular python (3) version, no ipython or other versions.


![image](https://user-images.githubusercontent.com/36726128/113681331-6d028380-96f4-11eb-9d6e-d463b5ca3633.png)


I performed a series of operations based on what is shown in the image above.

![image](https://user-images.githubusercontent.com/36726128/113681379-7855af00-96f4-11eb-97d0-c36baeade474.png)


The script generates a series of files. Actually I did not see "App_PhysicsServer_SharedMemory_VR.exe", I saw files with the name "App_PhysicsServer_SharedMemory_VR" in other formats, which I then opened in MSVC.
I try to run the "App_PhysicsServer_SharedMemory_VR":

![image](https://user-images.githubusercontent.com/36726128/113681414-84da0780-96f4-11eb-8798-545bc2951747.png)


Right-click on "App_PhysicsServer_SharedMemory_VR" and run it. All I can see is the following image.

![image](https://user-images.githubusercontent.com/36726128/113681445-8c99ac00-96f4-11eb-9de5-e70d2ea67126.png)


I run other codes that give the following screen, this may not have anything to do with VR.

![image](https://user-images.githubusercontent.com/36726128/113681475-96231400-96f4-11eb-8779-ea3f13e6d73f.png)



And then I try to run "https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/vr_kuka_setup.py", and nothing happened. The steps I ran were as follows: 1. Right-click on "App_PhysicsServer_SharedMemory_VR" and run it and I would see a blank screen in VR (with nothing in it but two handles). And then I run "https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/vr_kuka_setup.py" and it just runs there by himself, nothing is output, nothing happens, and nothing is visible in VR.

![image](https://user-images.githubusercontent.com/36726128/113681506-9de2b880-96f4-11eb-95cc-d82e5b3f7451.png)


Am I doing the steps correctly? I know maybe I am a little stupid but I am try my best to do these things, so pls tell me about this, thanks a lot!!

**Comment by erwincoumans** [comment]
You need to leave that "App_PhysicsServer_SharedMemory_VR running of course. Also, it needs to compiled in 64bit mode.

The run that vr_kuka_setup.py from a regular Python (64bit) terminal:

python3 path/to/vr_kuka_setup.py

Note that the pybullet plugin needs to ge up-to-date.
Ot should connect using SHARED_MEMORY.

**Comment by 1210652636** [comment]
> You need to leave that "App_PhysicsServer_SharedMemory_VR running of course. Also, it needs to compiled in 64bit mode.
> 
> The run that vr_kuka_setup.py from a regular Python (64bit) terminal:
> 
> python3 path/to/vr_kuka_setup.py
> 
> Note that the pybullet plugin needs to ge up-to-date.
> Ot should connect using SHARED_MEMORY.

Thanks for your patient and I try your method but it still didn't work.

![image](https://user-images.githubusercontent.com/36726128/113825146-32abeb80-97b3-11eb-86fa-e72d9026f16f.png)

![image](https://user-images.githubusercontent.com/36726128/113825315-6850d480-97b3-11eb-9ea7-fad5b1cb6c81.png)

It seems that the program doesn't work anymore at line 7：
![image](https://user-images.githubusercontent.com/36726128/113825493-9e8e5400-97b3-11eb-9253-fa9e6ff95fa2.png)
![image](https://user-images.githubusercontent.com/36726128/113825523-abab4300-97b3-11eb-8abb-77820b419d04.png)

My python version is 3.9.4：

![image](https://user-images.githubusercontent.com/36726128/113825560-b534ab00-97b3-11eb-9d9e-3f9ede3b8ba9.png)

Again, thanks for your patient.

**Comment by erwincoumans** [comment]
It is about the version of pybullet, not of Python.
Best is to do this:
pip uninstall pybullet
then in the root of your installation run
python setup.py install
(replace with pip3 and python3 if needed)

**Comment by 1210652636** [comment]
omg, it works thanks a lot!!!

I think my mistake is that I forget to change "Win32" to "x64", so this is why it can not run the code.

![image](https://user-images.githubusercontent.com/36726128/113954634-c7165c80-984c-11eb-9d59-734f9ba40d21.png)

**Comment by 1210652636** [comment]
> Make sure the executable name on Windows for the VR server is App_PhysicsServer_SharedMemory_VR_vs2010_x64_release.exe
> ![image](https://user-images.githubusercontent.com/725468/113902709-0c6f5700-9785-11eb-9a37-52a6e30464a1.png)
> When generating the visual studio project files with premake, it expect Python installation to be located in c:\python***
> so it can find the right include and library files.
> 
> It is about the version of pybullet, not of Python.
> Best is to do this:
> pip uninstall pybullet
> then in the root of your installation run
> python setup.py install
> (replace with pip3 and python3 if needed)

omg, it works thanks a lot!!!

I think my mistake is that I forget to change "Win32" to "x64", so this is why it can not run the code.

![image](https://user-images.githubusercontent.com/36726128/113954831-2e341100-984d-11eb-97fc-fb31480366af.png)

**Comment by erwincoumans** [comment]
Great, glad it works. Closing.
