### ISSUE TITLE
intrinsic matrix

### ISSUE THREAD

**Issue by shiyani21** [bulletphysics/bullet3#3338]
I want to know what the value of H is in the intrinsic matrix, I know pybullet has px=py=0 and I know we get the FOV from projection matrix:
![image](https://user-images.githubusercontent.com/75742827/113625533-0a937f80-962f-11eb-885b-25d3311fd013.png)
and we use this eq. to get focal length:
![image](https://user-images.githubusercontent.com/75742827/113625626-24cd5d80-962f-11eb-8056-959b04d0d9eb.png)

so what is h and what is skew value?

**Comment by erwincoumans** [comment]
PyBullet uses OpenGL matrices, check somewhere else for details about OpenGL / rendering matrices.
