### ISSUE TITLE
Crashing in AppExampleBrower 

### ISSUE THREAD

**Issue by grpnpraveen** [bulletphysics/bullet3#3342]
When cloth simulation is being clicked the entire application is not working even after rebuild.
![image](https://user-images.githubusercontent.com/10905467/113827106-8bbe5400-97a0-11eb-915c-fd9c76dc35a0.png)
![image](https://user-images.githubusercontent.com/10905467/113827161-9bd63380-97a0-11eb-8de5-beedbc3d16e7.png)

**Comment by erwincoumans** [comment]
Thanks for the report. An intern has been adding FEM deformables, and may have broken PDB cloth. Will check it out.

**Comment by grpnpraveen** [comment]
Thank you for your information and support.

**Comment by erwincoumans** [comment]
Can't reproduce on MacOS, all works fine. Which OS are you on, what compiler (version etc)?

**Comment by grpnpraveen** [comment]
Windows.

**Comment by erwincoumans** [comment]
Can't reproduce.
