### ISSUE TITLE
Question about calculateMassMatrix and calculateJacobian for a floating base

### ISSUE THREAD

**Issue by Michae1Park** [bulletphysics/bullet3#3345]
I have a floating base with three child links, and I am trying to compute A = JMJ^t.

I referred to this example (https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_utils/pd_controller_stable.py) and was able to compute the mass matrix by setting the flags parameter to 1 for calculateMassMatrix(). The dimension here is (10,10) because the orientation of the floating base is represented in quaternions.

The caculateJacobian() function does not seem to support the flags=1 option but I was able to compute it anyway, but here the dimension is (9,9) because the orientation of the base is represented in Euler angles. Thus, I am having issues computing A=JMJ^t.

Is there a way to compute the mass matrix with base orientation represented in euler angles or computing the Jacobian with base orientation in quaternion?  And is the returned Jacobian with respect to the world or the base?

**Comment by erwincoumans** [comment]
If you need a mass matrix and jacobian, it is best to model a 'floating' base using a fixed base, and explicitly add the degrees of freedom for the moving base (x,y,z translational, and x,y,z rotational). There is no jacobian version of flags=1.

This this example:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/biped2d_pybullet.py

Just add one more translational dof, and 2 more rotational dofs to the URDF file.
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_data/biped/biped2d_pybullet.urdf

Here is another URDF example of a floating body using fixed base and explicit translational/rotational joints:
https://github.com/erwincoumans/tiny-differentiable-simulator/blob/master/data/humanoid_partial_xyz_xyz_fixed.urdf
