### ISSUE TITLE
collision point to closest mesh vertex 

### ISSUE THREAD

**Issue by shivanimall** [bulletphysics/bullet3#3347]
Hello @erwincoumans, 

I have to convert the collision point (on say body B) returned by `getContactPoints` to the closest mesh vertex contained in body B's .obj file or as returned by `getMeshData`

I use `getContactPoints` function to get collision points on body B (body B's model vertices are contained B.obj)
then, I have to transform these collision points from WCS in pybullet to the model's coordinate system such that the points lie in AABB of body B mesh vertices in B.obj

For this, I re-align the orientation using rotation matrix and subtract the current `base_position` returned by getBasePositionOrientation  at each timestep of collision from the collision point at that timestep.  Then translate it by values of AABB of body B.
The only concern is `getBasePositionOrientation` func returns the center of mass pos and not the geometric center of the object. So, the values I get may not accurate. Wondering if there is a more standard way to do this? or any pybullet function/support for this?

Let me know if my question is unclear, thanks!

**Comment by erwincoumans** [comment]
If there the collision geometry has an offset, relative to the center of mass, you can get the local offset (position, orientation) transform using pybullet.getCollisionShapeData (see PyBullet Quickstart Guide)
Then you can multiply the transforms using pybullet.multiplyTransforms(base_pos, base_orn, colgeom_pos, colgeom_orn)

**Comment by shivanimall** [comment]
thanks much Erwin, will try the above and update, in case I run into issues.
