### ISSUE TITLE
Fix GyroscopicDemo

### ISSUE THREAD

**Issue by benelot** [bulletphysics/bullet3#357]
It is pretty easy actually!

It sets the flag on body to:
body->setFlags(BT_ENABLE_GYROPSCOPIC_FORCE);

It seems that the flag name has changed and is now:
body->setFlags(BT_ENABLE_GYROSCOPIC_FORCE_EXPLICIT);

Can anybody that understands the meaning of the flag confirm that this is the fix?

When I set the new flag, the code compiled properly and the demo works as I would expect it.

Thanks!

**Comment by scpeters** [comment]
Pull requests #348 and #350 would fix this, but they haven't been merged yet.

**Comment by erwincoumans** [comment]
ok, I merged the pull request (somehow I thought it was already merged, but it wasn't).
Note you should not use the 'explicit' version, but the 'implicit' one, to avoid adding energy/blowing up your simulation. BT_ENABLE_GYROPSCOPIC_FORCE maps to the implicit version now.
