### ISSUE TITLE
Solving constraints becomes very slow if the number of islands is large

### ISSUE THREAD

**Issue by cameronwhite** [bulletphysics/bullet3#359]
For every island, `InplaceSolverIslandCallback::processIsland()` iterates through the entire list of constraints to find the constraints that belong to that island. Since the constraints are already sorted by island id, it would be much faster to iterate through `m_sortedConstraints` once in `InplaceSolverIslandCallback::setup()` and precompute the index into `m_sortedConstraints` where each island's constraints begin.

**Comment by erwincoumans** [comment]
sure. Do you mind preparing a patch for this?

**Comment by benelot** [comment]
Is this issue fixed? It seems to be referenced in commit. If it is done, closing it would clean up the tracker.

**Comment by cameronwhite** [comment]
https://github.com/bulletphysics/bullet3/pull/386 is the active pull request

**Comment by benelot** [comment]
Ok, perfect, I am just trying to cleanup older issues. So this one is obviously not done yet. Thank you for linking it here!

**Comment by erwincoumans** [comment]
Unfortunately I don't see the benefits, neither some good benchmark that shows the benefits. I ran the Ragdolls benchmark, with and without the patch, and performance is about the same (even slightly slower). See comment in the closed [pull request](https://github.com/bulletphysics/bullet3/pull/386). Let's close it for now.
