### ISSUE TITLE
btTranslationalLimitMotor gets stuck when beyond limits

### ISSUE THREAD

**Issue by JonathaN7Shepard** [bulletphysics/bullet3#362]
btTranslationalLimitMotor stops working when m_currentLinearDiff exceeds the limits set for the constraint. By "stops working" I mean I'm giving it a m_targetVelocity in a direction opposite of the current limit it's stuck at, but it won't move! If external forces put the bodies back within the limits, it starts working again.

**Comment by erwincoumans** [comment]
Can you try using the new btGeneric6DofSpring2Constraint instead? It should solve this issue.

**Comment by JonathaN7Shepard** [comment]
Thanks, that solved the issue!
