### ISSUE TITLE
2.83 tag changed

### ISSUE THREAD

**Issue by scpeters** [bulletphysics/bullet3#370]
The 2.83 tag was created on Sunday night, but then it was modified on Monday. It's my understanding that tags are supposed to be immutable references to specific points in the code and should not be changed. It wreaks havoc on downstream users who package the code. I would recommend using patch release numbering (2.83.1) rather than modify the original tag.

I think @sherm1 did the same thing recently with simbody, so you're not alone. But I think I complained to him too.

It's done now, probably no need to revert it, but I would recommend patch release numbering for the future.

**Comment by erwincoumans** [comment]
True, I thought no-one would notice this on a Sunday. Hey, stop working in the weekend Stephen :-)
Fair enough, I'll use patch release next time.

**Comment by scpeters** [comment]
:)

**Comment by sherm1** [comment]
> I think @sherm1 did the same thing recently with simbody, so you're not alone. But I think I complained to him too.

Guilty, but repentant and reformed!
