### ISSUE TITLE
collisionAlgorithmMaxElementSize

### ISSUE THREAD

**Issue by velkyel** [bulletphysics/bullet3#372]
variable collisionAlgorithmMaxElementSize (BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp) should count all collision algorithms, especially btCompoundCompoundCollisionAlgorithm - on x86_64 is bigger than others.

**Comment by erwincoumans** [comment]
This is an issue indeed, I'll fix it right away. Thanks for reporting!

**Comment by erwincoumans** [comment]
fix is in this pull request: https://github.com/bulletphysics/bullet3/pull/373
