### ISSUE TITLE
Fail to use pybullet in python 2.7.17 on ubuntu 18.04

### ISSUE THREAD

**Issue by GouMinghao** [bulletphysics/bullet3#3830]
I install pybullet by calling `pip install pybullet`.
Then I type `import pybullet` in python and the following error occurs. However, there is no such error using python3.

```
Python 2.7.17 (default, Feb 27 2021, 15:10:58) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybullet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python2.7/dist-packages/pybullet.so: undefined symbol: PyUnicode_AsUTF8
```

The Python is original cpython 2.7.17 installed from apt and the system is Ubuntu 18.04.
I have also tried python2.7 in Anaconda with the same error.

I want know how to solve this problem. I have to use python2 due to ROS doesn't support python3.

**Comment by erwincoumans** [comment]
Thanks for the report, fixed here:
https://github.com/bulletphysics/bullet3/pull/3832
