### ISSUE TITLE
controlling spherical joint

### ISSUE THREAD

**Issue by rshum19** [bulletphysics/bullet3#3833]
Hello, 

I'm having some trouble controlling a spherical joint in my robot. I can successfully control the spherical joint using `controlMode=POSITION_CONTROL`. However, I really want to control the spherical joint in either `VELOCITY_CONTROL` or  `TORQUE_CONTROL`. 

When trying 'TORQUE_CONTROL` using the following line of code:

```
  p.setJointMotorControlMultiDof(ballbot,
                                 1,
                                 p.TORQUE_CONTROL,
                                 force=[torqueX,torqueY,torqueZ])
```
it seems that the torque is being applied at the frame of the parent link and not at the frame of child link. Is this the expected behavior?

When trying 'VELOCITY_CONTROL' I get segfaults when running the script that is not a valid control mode. Is velocity control not implemented?

Thank you!

**Comment by erwincoumans** [comment]
You can use position control, torque control or implicit pd control.

The 3 modes are implemented in this example:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/humanoidMotionCapture.py

There is no velocity control indeed.
Torques are applied in joint frame, which is attached to the parent link.
