### ISSUE TITLE
Please publish dependency list in README

### ISSUE THREAD

**Issue by yurivict** [bulletphysics/bullet3#3852]
```setup.py``` doesn't contain dependencies, and there is no ```requirements.txt```.

```Numpy``` is one dependency, ```gym``` is another.

Please publish a complete list.

**Comment by erwincoumans** [comment]
There are zero dependencies.
Both gym and numpy are optional, you only need gym if you want to run one of the gym environments.
you can also run setup.py without numpy installed, it should work.
