### ISSUE TITLE
gripper finger joint limit violated when in contact

### ISSUE THREAD

**Issue by IanYangChina** [bulletphysics/bullet3#3883]
Hi, I have been working on a manipulation simulation using a Kuka robot and a simple parallel jaw gripper. There is a joint limit violation issue when the gripper fingers make contact with other objects. In the example figures, the gripper tries to open the door of a chest. Though it succeeded, you can see the fingers of the gripper are at the wrong place. Their joint limits are violated. Do you have any suggestions for this problem? Thanks a lot!

This is the rest state of the robot.
![Screenshot 2021-06-07 113838](https://user-images.githubusercontent.com/37257202/121003692-b9665000-c785-11eb-952b-9a4afe0ee594.png)

The following are violated states.
![Screenshot 2021-06-07 113923](https://user-images.githubusercontent.com/37257202/121003689-b79c8c80-c785-11eb-8e41-7a5c895b5255.png)
![Screenshot 2021-06-07 113821](https://user-images.githubusercontent.com/37257202/121003690-b8352300-c785-11eb-92ed-ce64d1172fef.png)

**Comment by erwincoumans** [comment]
It depends on the details of the setup. Turning this into a discussion.
