### ISSUE TITLE
Invalid cast when building with MinGW-w64

### ISSUE THREAD

**Issue by markand** [bulletphysics/bullet3#394]
I'm trying to build bullet 2.83.4 on Windows using MinGW-w64 with GCC 4.9.

I get the following error while building:

```
[ 67%] Building CXX object examples/ExampleBrowser/CMakeFiles/App_ExampleBrowser.dir/__/__/Extras/Serialize/BulletFileLoader/bFile.obj
C:\src\64\bullet3-2.83.4\Extras\Serialize\BulletFileLoader\bFile.cpp: In member function 'void bParse::bFile::swapDNA(char*)':
C:\src\64\bullet3-2.83.4\Extras\Serialize\BulletFileLoader\bFile.cpp:446:13: error: cast from 'char*' to 'long int' loses precision [-fpermissive]
   nr= (long)cp;
             ^
C:\src\64\bullet3-2.83.4\Extras\Serialize\BulletFileLoader\bFile.cpp:483:13: error: cast from 'char*' to 'long int' loses precision [-fpermissive]
   nr= (long)cp;
```

Small precision, this happens only in 64 bit (MinGW-w64). 32 bits MinGW compiles fine.

**Comment by johnfredcee** [comment]
long is not big enough to hold a pointer : one possible fix is to change these to long long ; there are only a few sites where it is a problem.

**Comment by johnfredcee** [comment]
[mingw64-fix.txt](https://github.com/bulletphysics/bullet3/files/116064/mingw64-fix.txt)

**Comment by markand** [comment]
What about using (u)intrptr_t which is designed for?

**Comment by johnfredcee** [comment]
No idea. Is C++11 specific code ok? The code base looks old and hairy, so I went for an old and hairy solution!

**Comment by erwincoumans** [comment]
Sure, I'll look into it.

intptr_t has some portability issues but it only requires C99 not C++11, see also http://stackoverflow.com/questions/9492798/using-intptr-t-instead-of-void

The Bullet code base values portability and support for older compilers and platforms, so C++11 and C++14 is not allowed just yet. I rather have the code base look old and hairy rather than getting compile errors on various platforms.

**Comment by johnfredcee** [comment]
That's *C* 99, not C++ - those were .cpp files I modified..

On 4 February 2016 at 21:38, erwincoumans <notifications@github.com> wrote:

> Sure, I'll look into it.
>
> intptr_t has some portability issues but it only requires C99 not C++11,
> see also
> http://stackoverflow.com/questions/9492798/using-intptr-t-instead-of-void
>
> The Bullet code base values portability and support for older compilers
> and platforms, so C++11 and C++14 is not allowed just yet. I rather have
> the code base look old and hairy rather than getting compile errors on
> various platforms.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bulletphysics/bullet3/issues/394#issuecomment-180063176>
> .
>



-- 
-------------------------------------------
johnfredcee@googlemail.com

**Comment by erwincoumans** [comment]
That's what I told indeed, C99. Some C++ implementations support C99, others don't. You don't need to have C++11 for that. Even in C++11 the intptr_t is optional, hence non-portable.

**Comment by markand** [comment]
Le 04/02/2016 22:38, erwincoumans a écrit :
>
> The Bullet code base values portability and support for older 
> compilers and platforms, so C++11 and C++14 is not allowed just yet. I 
> rather have the code base look old and hairy rather than getting 
> compile errors on various platforms.
>

Deprecated platforms.

Also, a check can be quickly done with CMake to see if a specific 
typedef exists :-)

     include(CheckTypeSize)
     check_type_size(uintptr_t HAVE_UINTPTR_T)

Then you can easily add your own implementation if uintptr_t is missing.

-- 
David Demelier
