### ISSUE TITLE
Collision issue in PlayCanvas

### ISSUE THREAD

**Issue by jochemgeussens** [bulletphysics/bullet3#395]
Dear community

I'm playing around with PlayCanvas, which is using a JavaScript version of Bullet (ammo.js). Recently I ran into some strange collision issues. I received quite some responses from PlayCanvas but none of them solved the issue at hand. I wrote this thread on ammo.js as well, but didn't receive an answer yet. 

To summarize the problem, there are certain patterns of faces that do not respect the physics rules (edges DO respect them). One of those faces is the following (OBJ-format exported from blender):

> \# Blender v2.71 (sub 0) OBJ File: 'dungeon entrance.blend'
> \# www.blender.org
> mtllib dungeon entrance.mtl
> o tower_entrance_Cube.007
> v 0.806374 3.510620 59.581371
> v 1.867039 3.570729 55.274376
> v 1.947178 5.084308 59.415688
> vt 9.151969 -7.611137
> vt 9.167459 -8.339106
> vt 10.832100 -8.210979
> vn -0.804300 0.563000 -0.190200
> usemtl Material.001
> s 1
> f 1/1/1 3/2/1 2/3/1

The issue could be something "stupid" that I overlooked, but my current knowledge of graphics isn't enough to figure this out by myself :/

The full conversation on PlayCanvas can be found here: http://answers.playcanvas.com/questions/1573/mesh-collision-issues
The thread on Ammo.js can be found here: https://github.com/kripken/ammo.js/issues/108

I hope someone can give me some pointers to where the problem originates from.

Thanks in advance. 

Kind regards
J.

**Comment by erwincoumans** [comment]
If you can reproduce the issue using Bullet in this repository, using C++ and modifying any of the included examples, I can have a look at it.
