### ISSUE TITLE
unnecessary print

### ISSUE THREAD

**Issue by kbys-t** [bulletphysics/bullet3#3977]
The following print disturbs the display when running the pybullet envs with tqdm. If it is only for debugging, it would be better to display it only when the verbose flag is set.
https://github.com/bulletphysics/bullet3/blob/ce26271923e48c297b623285421ac1c2ad06e623/examples/pybullet/pybullet.c#L508

**Comment by araffin** [comment]
was that issue solved?
it would be nice to have an env variable to control this print.
