### ISSUE TITLE
Cannot find pybullet_vs2010.dll

### ISSUE THREAD

**Issue by Mark799** [bulletphysics/bullet3#3984]
Hello, 

The Quickstart Guide tells me to "Rename pybullet_vs2010.dll to pybullet.pyd and start the Python.exe interpreter using bullet/bin as the current working directory." However, I cannot find the .dll file. 

Is this still up-to-date? If not, could you please tell us how to use the code with a Python interpreter?

Also, after building Bullet3, I got the following: 

(...)
">Done building project "pybullet.vcxproj" -- FAILED."
(...)
"========== Build: 66 succeeded, 1 failed, 0 up-to-date, 0 skipped =========="

As far as I know, I followed all the instructions correctly. Still one build failed. Maybe these two issues are related? 

Kind regards,
Mark

**Comment by erwincoumans** [comment]
It is best to use pip3 install pybullet or python setup.py install --develop
