### ISSUE TITLE
Loaded multiple objects not visible

### ISSUE THREAD

**Issue by RolandZhu** [bulletphysics/bullet3#3999]
Hi! Thanks for all of your support for the great simulator!

I'm working on a manipulation project that requires a robot to interact with 9 objects, one object at a time.
I choose to follow a simple pipeline: load one object, manipulate it, remove it with `removeBody`, and reload the next one.
However, the loaded object becomes invisible after 4 load-reload iterations, while they're an object ID for loaded object and I can get the body information through `getBasePositionAndOrientation`.
I can use the `resetSimulation` to remove everything, but that will require a re-load of the robot, which is not preferred.
Any idea why is this the case and how can I fix it?
I create a minimum example [here](https://www.dropbox.com/s/cp1k27mjul6behu/test.zip?dl=0) to reproduce the issue.
Please let me know if you have any ideas or suggestions!

Many thanks.

**Comment by erwincoumans** [comment]
The resolution of the STL meshes is way too high. Best to approximate them, or use mesh decimation (in Blender for example).
