### ISSUE TITLE
Several Fixes for btkinematiccharactercontroller

### ISSUE THREAD

**Issue by androidtestcsb** [bulletphysics/bullet3#40]
I'm currently having a lot of problems with the btkinematiccharactercontroller. He slides down slopes, when he walks towards a narrow corner, he starts hammering, it is possible to glitch through a wall and he can't use elevator platforms.
I hope it gets fixed soon, because I think a player character is pretty essential for a physics engine.

**Comment by erwincoumans** [comment]
There hasn't been any activity for too long, let's close the issue.
