### ISSUE TITLE
getContactPoints() not working propetly

### ISSUE THREAD

**Issue by CreaM129129** [bulletphysics/bullet3#4004]
Hello.

I am moving ur5 arm in PyBullet. My goal is to detect when arm collides with itself and than stop the simulation. 

First i was using `getOverlappingObjects` and `getAABB`. This was working, but proved to be too imprecise and simulation was stopped when there was no collision. 

Now I am using `getContactPoints` but function always returns empty tuple, even though arm is clearly colliding. I know i have to add `flags=p.URDF_USE_SELF_COLLISION | p.URDF_USE_SELF_COLLISION_EXCLUDE_ALL_PARENTS` when loading URDF. I also tried this on official _franka_panda/panda.urdf_ model, but problem is persisting.

Here is the snippet of my code:

**reseting the environment:**
```
self.ur5_id = p.loadURDF(os.path.join(urdfRootPath, "ur5/urdf/ur5.urdf"), useFixedBase=True, basePosition=[0, 0, 0], flags=p.URDF_USE_SELF_COLLISION | p.URDF_USE_SELF_COLLISION_EXCLUDE_ALL_PARENTS)
for i in range(-1, 7):
   for j in range(-1, 7):
      p.setCollisionFilterPair(self.ur5_id, self.ur5_id, i, j, 1)
```

**step:**
```
p.stepSimulation()
for i in range(-1, 7):
   for j in range(-1, 7):
      print(p.getContactPoints(self.ur5_id, self.ur5_id, i, j))
```

I have omitted most of the code like moving the arm, rendering, ect...
Thank you for any clues on how to debug this!

**Comment by erwincoumans** [comment]
What if you do getContactPoints without any arguments? Also, try not configuring the setCollisionFilterPair.

Without a small self-contained example it is not possible to figure out what is wrong.

**Comment by CreaM129129** [comment]
Not using `setCollisionFilterPair` does not seem to do anything. 
I am not sure what do you mean by getting ContactPoints without any arguments (when there is a clear collision) - is that even possible?

I 'solved' the issue by using [pybullet-planning](https://github.com/caelan/pybullet-planning) module with `get_collision_fn`. This seem to handle collisions without any trouble. To anyone having similar issues I would recommend trying out pybullet-planning and [this demo](https://github.com/yijiangh/pybullet_planning_tutorials).

As debugging this issue seems hard and time consuming, and is probably caused by some trivial mistake on my part, i will close this issue. Thanks for help though!
