### ISSUE TITLE
issue: createCollisionShapeArray: pass tuple on collisionFramePositions causes SIGSEGV

### ISSUE THREAD

**Issue by id9502** [bulletphysics/bullet3#4011]
https://github.com/bulletphysics/bullet3/blob/e4a450a53dc6eded9d16a0d1dde07fc8a25760d0/examples/pybullet/pybullet.c#L9001

Issue: passing tuple for collisionFramePositions or collisionFrameOrientations will cause SEGSEGV,
Reason: line.9001, line9002 @ pybullet.c: PyList_GET_ITEM will fail if input variable is tuple

**Comment by erwincoumans** [comment]
Thanks, do you have a minimal pybullet script that reproduces the crash?

**Comment by id9502** [comment]
Here is the code that can reproduce the crash:

`import pybullet as p`
`p.connect(p.DIRECT)`
`p.createCollisionShapeArray(shapeTypes=(pb.GEOM_SPHERE, pb.GEOM_CYLINDER), radii=(0.08, 0.08), lengths=(0., 0.1),`
`                            collisionFramePositions=((0., 0., 0.05), (0., 0., 0.)))`

And the terminal outputs:

pybullet build time: Oct 11 2021 21:00:24
[1]    4025 segmentation fault  python3 ./crash.py

**Comment by erwincoumans** [comment]
Indeed, passing in tuples voids the warranty of PyBullet, so pass in lists.
```
p.createCollisionShapeArray(shapeTypes=(p.GEOM_SPHERE, p.GEOM_CYLINDER), radii=(0.08, 0.08), lengths=(0., 0.1),
collisionFramePositions=[[0., 0., 0.05], [0., 0., 0.]])
```
