### ISSUE TITLE
[MSVC][/std:c++latest] Build error C2446 from Eigen

### ISSUE THREAD

**Issue by QuellaZhang** [bulletphysics/bullet3#4013]
Hello,

The MSVC team recently added bullet3 as part of RWC testing to detect compiler regressions. And we found some errors when building bullet3 with '/std:c++latest'. These issues come from Eigen, I upgraded Eigen to 3.4.0 and the error disappeared. Can you help upgrade Eigen version?

**Steps to reproduce**

1. open VS2019 x64 tools command
2. git clone https://github.com/bulletphysics/bullet3 F:\gitP\bulletphysics\bullet3
3. mkdir F:\gitP\bulletphysics\bullet3\build_amd64
4. cd F:\gitP\bulletphysics\bullet3\build_amd64
5. set _CL_= /std:c++latest /D_HAS_TR1_NAMESPACE=1 /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /D_HAS_DEPRECATED_NEGATORS /D_SILENCE_CXX17_NEGATORS_DEPRECATION_WARNING
6. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release .. 
7. msbuild /m /p:Platform=x64 /p:Configuration=Release BULLET_PHYSICS.sln /t:Rebuild

**Build.log:** [bullet3_build.log](https://github.com/bulletphysics/bullet3/files/7424837/bullet3_build.log)

**Error info:**
F:\gitP\bulletphysics\bullet3\examples\ThirdPartyLibs\Eigen\src/Cholesky/LDLT.h(371,1): error C2446: '==': no conversion from 'Scalar' to 'Eigen::ArrayWrapper<Derived>'
F:\gitP\bulletphysics\bullet3\examples\ThirdPartyLibs\Eigen\src/Cholesky/LDLT.h(371,1): error C2446: '==': no conversion from 'Scalar' to 'Eigen::ArrayWrapper<Derived>'

**Comment by erwincoumans** [comment]
Thanks for the report, I will look into it.

**Comment by erwincoumans** [comment]
Should be fixed here: https://github.com/bulletphysics/bullet3/pull/4010

**Comment by erwincoumans** [comment]
https://github.com/bulletphysics/bullet3/pull/4010
