### ISSUE TITLE
setMaxAngMotorForce

### ISSUE THREAD

**Issue by kzahedi** [bulletphysics/bullet3#402]
Hi,

could it be, that the value that I give to the function have a different meaning in a recent update? I would be very thankful, if someone could explain what the unit is. If I set setMaxAngMotorForce to 1, does this refer to e.g. 1Nm?

Cheers,
Keyan

**Comment by scpeters** [comment]
Yes, it changed in a165ff54c9e6ec789945a3d7c7e37cda47573efb (see justification in #328). It was incorrect before, now the units should be Nm.

**Comment by kzahedi** [comment]
Thank you very much!

**Comment by scpeters** [comment]
Great, if that answered the question, then feel free to close the issue. Glad to help.

**Comment by erwincoumans** [comment]
closing out-of-date issues.
