### ISSUE TITLE
btConeTwistConstraint constructor

### ISSUE THREAD

**Issue by Onhi** [bulletphysics/bullet3#4022]
m_rbBFrame of "getFixedBody()" is set at the origin of the world in the single body/frame constructor.

btConeTwistConstraint::btConeTwistConstraint(btRigidBody& rbA, const btTransform& rbAFrame) : btTypedConstraint(CONETWIST_CONSTRAINT_TYPE, rbA), m_rbAFrame(rbAFrame), m_angularOnly(false), m_useSolveConstraintObsolete(CONETWIST_USE_OBSOLETE_SOLVER)
{
    m_rbBFrame = m_rbAFrame;
    m_rbBFrame.setOrigin(btVector3(0., 0., 0.)); // BUG?
    m_rbBFrame.getOrigin() = m_rbA.getCenterOfMassTransform()(m_rbAFrame.getOrigin()); // FIX?
    init();
}

**Comment by erwincoumans** [comment]
Could be a bug. Best to use the constructor with two bodies.
