### ISSUE TITLE
Constraint with Base Link To Seg Fault

### ISSUE THREAD

**Issue by seanjwang** [bulletphysics/bullet3#4035]
When using the createConstraint function, whenever parentLinkIndex=1, it leads to a segfault. This issue can be reproduced using mimicJointConstraint.py and changing any parentLinkIndex to -1. As a temporary fix, I've defined a ghost body fixed to the base link and defined my constraint using it, but this seems like a hacky fix.

**Comment by erwincoumans** [comment]
The mimic contraint will syncronize the joint angles/velocity. A base (-1) doesn't have a joint or angle, so it won't work.
