### ISSUE TITLE
bullet crashes at getOpenGLSubMatrix when using NEON

### ISSUE THREAD

**Issue by lefty2** [bulletphysics/bullet3#407]
I found a "bad access" crash at the following line:
vm[0] = v0;
in btMatrix3x3::getOpenGLSubMatrix
it only happens when NEON is enabled.

**Comment by erwincoumans** [comment]
Did you make sure your destination matrix is 16-byte aligned?

**Comment by lefty2** [comment]
What? The distination matrix is 16 floats

**Comment by erwincoumans** [comment]
ATTRIBUTE_ALIGNED16(float m[16]);

**Comment by lefty2** [comment]
Isn't it already aligned without the macro?

**Comment by erwincoumans** [comment]
Apparently it is not, so you need to align your data for this API call.
Indeed, it would be great if NEON would work on un-aligned data. I don't have the time create a work-around, so please use the alignment macro.

**Comment by erwincoumans** [comment]
if alignment doesn't fix it, please provide a reproduction case and file a new issue. Thanks!
