### ISSUE TITLE
"pip install pybullet" and ""building wheel fails for bullet 3.2.1

### ISSUE THREAD

**Issue by rohit-kumar-j** [bulletphysics/bullet3#4071]
Error: building wheel fails, see also [Issues: #1864](https://github.com/bulletphysics/bullet3/issues/1864)

```
failed to build wheel for pybullet
```

**Comment by rohit-kumar-j** [comment]
Solution: update Microsoft build Tools from [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/)

**Comment by SrinjoyChoudhury** [comment]
> Solution: update Microsoft build Tools from [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/), get bullet 3.2.1 release and extract from [here](https://github.com/bulletphysics/bullet3/releases/tag/3.21), extract the files
> 
> ```shell
> cd bullet3-3.21
> python setup.py build
> python setup.py install
> ```

Followed your instructions exactly. After `python setup.py build` I get this error:
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

I already have build tools installed (Version 17.6.0):
![image](https://github.com/bulletphysics/bullet3/assets/109635064/af821e17-f243-4d05-860e-6d7bf6947e0c)

I get the same error if I continue to the next step.
