### ISSUE TITLE
calculate the inertia matrix for a floating base system

### ISSUE THREAD

**Issue by YunxiTang** [bulletphysics/bullet3#4124]
Hi,
As I am planning to do the whole body control of a floating robot and I found few examples/information about how to get the M matrix for a floating based robot. Is there any example for such issue?
Many thanks!

**Comment by erwincoumans** [comment]
We compute the mass matrix for stable PD control (used for DeepMimic), see the code here:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/pdControllerStable.py#L78
