### ISSUE TITLE
Import Soft Body with Different Resting Length for Edges in PyBullet

### ISSUE THREAD

**Issue by eflopez1** [bulletphysics/bullet3#4142]
Hello,

I am interested in importing a .obj file as a soft body in PyBullet, but with the addition that the 'resting length' of the springs can be changed when the object is created. My current understanding is that when mesh files are simulated, each edge is treated as a spring with its resting length being the original length of the edge in the .obj file. Can this be changed so that each edge is in tension (i.e. the resting length is 0) for each edge?

Apologies if my interpretation is incorrect in how soft bodies are simulated. Any help or guidance is appreciated.

**Comment by erwincoumans** [comment]
Possible, but you would have to dig into the underlying C++ code. It depends on which soft body, position based dynamics (default) or the newer 'deformable' using FEM/mass spring.
```
p.resetSimulation(p.RESET_USE_DEFORMABLE_WORLD)
```
It is somewhere under Bullet/src/BulletSoftBody. We don't have resources to work on this at the moment, so closing.

**Comment by eflopez1** [comment]
Thank you!
