### ISSUE TITLE
Quaternion convention typo in documentation 

### ISSUE THREAD

**Issue by wualbert** [bulletphysics/bullet3#4184]
On page 63 of the [Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3)
> target orientation in Cartesian world space, quaternion [x,y,w,z]. 

Should this be `[x,y,z,w]` instead?

**Comment by erwincoumans** [comment]
good find, fixed!
