### ISSUE TITLE
Poor performance with OpenGL Renderer on Apple M1 machines

### ISSUE THREAD

**Issue by ZQX323** [bulletphysics/bullet3#4185]
Recently I have changed my PC to MacBook Pro(M1 Max with 32 cores), however the performance of rendering is poor.  
Here is a link to show the performance in M1 chips.
https://forum.juce.com/t/poor-performance-with-opengl-renderer-on-apple-m1-machines/48725

I notice there is only an option to choose OpenGL2. Is there another solution to solve this problem?

**Comment by ZQX323** [comment]
I have fixed the poor performance problem by setting:
pybullet_client.configureDebugVisualizer(p.COV_ENABLE_GUI, 0)

Right now it is x25 faster than before. But I am still confused why it is so expensive to enable GUI.

**Comment by erwincoumans** [comment]
Press 'g', the Mac OpenGL drivers probably don't support certain features of the GUI renderer in hardware, and have a CPU software fallback. Indeed, press 'g' or use that line 
```
pybullet_client.configureDebugVisualizer(p.COV_ENABLE_GUI, 0)
```
to make it faster.
