### ISSUE TITLE
Feature request: btHingeConstraint::getHingeAngleUnwrapped

### ISSUE THREAD

**Issue by scpeters** [bulletphysics/bullet3#42]
The `btHingeConstraint::getHingeAngle()` function always returns values wrapped to [-PI,PI]. It would be nice to have an unwrapped angle. We patched Gazebo's internal copy of ODE to return unwrapped angles for hinge joints (see [hinge.cpp](https://bitbucket.org/osrf/gazebo/src/f5f87276c49956ee4df6902966a6fdc2ff9b7e4f/deps/opende/src/joints/hinge.cpp?at=default#cl-359)). We should try to push that back upstream to ODE and potentially here to bullet if the implementation is reasonable to you.

Migrated from [google code](http://code.google.com/p/bullet/issues/detail?id=796).

**Comment by scpeters** [comment]
Sorry for the delay, I just confirmed that the `btHingeAccumulatedAngleConstraint` class is properly storing the accumulated angle. It does not allow for unwrapped joint limits, however. Is that difficult to implement?

**Comment by erwincoumans** [comment]
It is probably not difficult to implement, so if you have time please give it a try :+1: The history of the file shows some changes related to joint limits that can likely be simplified with the change.
