### ISSUE TITLE
CMake: modernize config file with imported targets & components

### ISSUE THREAD

**Issue by SpaceIm** [bulletphysics/bullet3#4208]
`bullet3` has a quite fragile way to design a config file, and usage is old CMake.

It would be nice to properly export targets and create config file with built-in CMake functions (`configure_package_config_file`, `write_basic_package_version_file`, `install(EXPORT ...)`)

Imported targets could be:
- `Bullet::Bullet3Common`
- `Bullet::LinearMath`
- `Bullet::BulletInverseDynamics`
- `Bullet::BulletCollision`
- `Bullet::BulletDynamics`
- `Bullet::BulletSoftBody`
- etc
- and eventually an interface `Bullet::Bullet` target depending on all components.

And usage would be something like this:

```cmake
find_package(Bullet REQUIRED BulletCollision BulletSoftBody CONFIG)
target_link_libraries(myApp PRIVATE Bullet::BulletCollision Bullet::BulletSoftBody)
```

In it's simple form, modification in Bullet CMakeLists files would be:

add `cmake/BulletConfig.cmake.in`:

```cmake
@PACKAGE_INIT@

include("${CMAKE_CURRENT_LIST_DIR}/BulletTargets.cmake")
```

Somewhere in top CMakeLists:

```cmake
include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

configure_package_config_file(
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/BulletConfig.cmake.in
    BulletConfig.cmake
    INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Bullet
)

write_basic_package_version_file(
    BulletConfigVersion.cmake
    VERSION ${PROJECT_VERSION}
    COMPATIBILITY AnyNewerVersion
)

export(
    EXPORT BulletExport
    NAMESPACE Bullet::
    FILE BulletTargets.cmake
)

install(
    EXPORT BulletExport
    NAMESPACE Bullet::
    FILE BulletTargets.cmake
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Bullet
)

install(
    FILES
        ${CMAKE_CURRENT_BINARY_DIR}/BulletConfig.cmake
        ${CMAKE_CURRENT_BINARY_DIR}/BulletConfigVersion.cmake
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Bullet
)
```

All existing install commands of targets should add `EXPORT BulletExport` (it might be a better idea to factorize installation of targets in top CMakeLists by collecting targets in a variable).

Moreover, for coherency, you could add ALIAS targets.

**Comment by SpaceIm** [comment]
Actually, I see that it was added few years ago then reverted in https://github.com/bulletphysics/bullet3/pull/1303 :(

**Comment by erwincoumans** [comment]
It was reverted since the new cmake broke various things (don't remember what exactly). I agree the build system and the code base should be improved, but we lack resources to work on this and rather keep it as-is.
