### ISSUE TITLE
rayTestBatch is losing one ray on RTX3090 if MAX_RAY_INTERSECTION_BATCH_SIZE is used

### ISSUE THREAD

**Issue by bookhahn** [bulletphysics/bullet3#4215]
Hi,

I have noticed the following:

In pyBullet 3.2.1 the maximum number of rays one can test with rayTestBatch on a RTX3090 is 16384. However if I pass 16384 rays to rayTestBatch I only get 16383 back, so one is missing. If I do the same thing with half the number of rays, everything works perfectly fine.

Cheers!

**Comment by erwincoumans** [comment]
You can try modifying the constants in https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/SharedMemoryPublic.h and recompile PyBullet.  By the way, PyBullet doesn't use the GPU, it is just a CPU multithreaded implementation.
