### ISSUE TITLE
VERSION file not updated to 3.22 in 3.22 release?

### ISSUE THREAD

**Issue by traversaro** [bulletphysics/bullet3#4220]
Hi @erwincoumans, thanks a lot for your work!

I noticed that you tagged both versions `3.22a` and `3.22`, but in both cases the `VERSION` file was not updated: 
* https://github.com/bulletphysics/bullet3/blob/3.22a/VERSION
* https://github.com/bulletphysics/bullet3/blob/3.22/VERSION

Perhaps this was intentionally, but I tought it was harmeless to notify this. Thanks again!

**Comment by erwincoumans** [comment]
Fixed, thanks for the report!
https://github.com/erwincoumans/bullet3/blob/master/VERSION
