### ISSUE TITLE
Can't display correctly while using loadURDF and createMultibody simultaneously

### ISSUE THREAD

**Issue by newethan33** [bulletphysics/bullet3#4222]
Hello, I'm new to pybullet and I am trying to do some project using URDF file with different terrain.
But I faced a problem when using these two function.

I've tried to run heightfield.py in the example, and it seems good.
![Selection_050](https://user-images.githubusercontent.com/48834352/160562234-8c00919d-b799-45ae-865d-8c18b931dc70.png)

Then, I added a biped2d URDF model to this height field, but the display of the ground turn out to be wrong.
![Selection_051](https://user-images.githubusercontent.com/48834352/160564142-14d4b604-4411-496f-b1d6-932d1ed3d768.png)

I've tried to change the rgbaColor using changeVisualShape and used some other URDF files, but the problem is still there.
Please help me to solve this problem, thanks a lot!

**Comment by erwincoumans** [comment]
It seems to work fine for me:
[biped2d_pybullet.zip](https://github.com/bulletphysics/bullet3/files/8377002/biped2d_pybullet.zip)
