### ISSUE TITLE
how the POSITION_CONTROL is implemented

### ISSUE THREAD

**Issue by xibeisiber** [bulletphysics/bullet3#4230]
Hi,
I'm try to implement my own PD controller of a 7DOF arm using equation ( tau=C(q, qdot)+M(acc+Kp*qerr+kd*qderr ) but haven't got a satisfying results by adjusting the kp and kd value. I also noticed there's a pdControllerStable.py in the example folder, and tried the control law in the arm, but it didn't work.

Therefore I wonder how the POSITION_CONTROL or CONTROL_MODE_POSITION_VELOCITY_PD is implemented in the source C++ file, and how the PD gains are set. I tried to locate it in the source files but didn't find it..

Thanks for any help!

**Comment by erwincoumans** [comment]
POSITION_CONTROL uses the constraint solver (MLCP) to compute the forces/torques, so it has a full (white-box) model of the dynamics. It is implemented here: https://github.com/bulletphysics/bullet3/blob/master/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp
[jstepien-pba.pdf.zip](https://github.com/bulletphysics/bullet3/files/8486080/jstepien-pba.pdf.zip)

More background on motors and constraint solver are in attached PhD thesis by Jakub Stępień.
