### ISSUE TITLE
GetContactPoints return nan or -inf force

### ISSUE THREAD

**Issue by HaojieSHI98** [bulletphysics/bullet3#4232]
I am implementing a quadrupedal robot, when use GetContactPoints, it returns nan or -inf for normal force and friction force like the following:

(0, 1, 0, 2, -1, (-0.37404486705222156, -0.1542245874600427, -9.935898315827085e-06), (-0.37404486705222156, -0.1542245874600427, 0.0), (0.0, 0.0, 1.0), -9.935898315827085e-06, inf, -inf, (0.0, -1.0, 0.0), -inf, (1.0, -0.0, -0.0))
(0, 1, 0, 6, -1, (-0.35954553895101016, 0.157773714262279, -4.956770841890723e-06), (-0.35954553895101016, 0.157773714262279, 0.0), (0.0, 0.0, 1.0), -4.956770841890723e-06, inf, inf, (0.0, -1.0, 0.0), -inf, (1.0, -0.0, -0.0))
(0, 1, 0, 10, -1, (-0.7566197599828783, -0.16378883190543272, -7.683810614278475e-06), (-0.7566197599828783, -0.16378883190543272, 0.0), (0.0, 0.0, 1.0), -7.683810614278475e-06, inf, -inf, (0.0, -1.0, 0.0), -inf, (1.0, -0.0, -0.0))

Actually I want to get the force. I wonder what is the problem. Thanks.

**Comment by erwincoumans** [comment]
This is usually to to invalid input or divergence in control and/or simulation. Without a reproduction case we close such issues, since it is impossible to fix.
