### ISSUE TITLE
Axis changed after saving urdf via urdfEditor if inertial frame has rotation.

### ISSUE THREAD

**Issue by TexnoMann** [bulletphysics/bullet3#4240]
I found a broken axis issue after using urdfEditor (Initially I ran into a problem here: #4231). The axis for wrist_3_joint broke after that I opened urdf with urdfEditor and saved it unchanged.

I've noticed that this only happens for links that have a non-zero rotation for the child link's inertial frame. I have attached the file.
[pybullet_report.zip](https://github.com/bulletphysics/bullet3/files/8507045/pybullet_report.zip)

  _was:_
  ```xml
  <joint name="wrist_3_joint" type="revolute">
      <parent link="wrist_2_link"/>
      <child link="wrist_3_link"/>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.1"/>
      <axis xyz="0 1 0"/>
      <limit effort="28.0" lower="-3.14159265359" upper="3.14159265359" velocity="6.28"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
  ```
_became:_
```xml
  <joint name="wrist_3_joint" type="revolute">
      <parent link="wrist_2_link"/>
      <child link="wrist_3_link"/>
      <limit effort="28.00000" lower="-3.14159" upper="3.14159" velocity="6.28000"/>
      <dynamics damping="1.0" friction="0.0001"/>
      <origin rpy="0.00000 -0.00000 0.00000" xyz="0.00000 0.00000 0.10000"/>
      <axis xyz="0.00000 0.00000 -1.00000"/>
  </joint>
  ```

I also have a problem if the geometry for the collision is described as box, sphere or cylinder. The saved result will contain an unknown reference and give me an error:
```xml
<mesh filename="unknown_file" scale="1.00000 1.00000 1.00000"/>
```

**Comment by TexnoMann** [comment]
#4231

**Comment by erwincoumans** [comment]
Indeed, the urdfEditor is very limited and doesn't support all features. There isn't going to be development in this area, so closing for now. If someone has a contribution, please file a pull request.
