### ISSUE TITLE
Error occured during creating constraint to fix rope and box together.

### ISSUE THREAD

**Issue by woshizh951** [bulletphysics/bullet3#4242]
Hi,

I'm trying to fix a rope-like multibody which is consists of capsules, and a box fixed on a table together.
The box is load as urdf with useFixedBase option to make it stable.
The cable is linked like the example snake.py.
I use the following fuction to fix them together:
constraint_id = p.createConstraint(
            parentBodyUniqueId=cube2,
            parentLinkIndex=-1,
            childBodyUniqueId=sphere_id,
            childLinkIndex=-1,
            jointType=p.JOINT_POINT2POINT,
            jointAxis=(0, 0, 0),
            parentFramePosition=[0, 0, 0],
            childFramePosition=(0, 0, 0))
        p.changeConstraint(constraint_id, maxForce=2000)
The result is illustrated below:
![image](https://user-images.githubusercontent.com/19282086/164193500-4c629e7e-119f-46c6-bd5f-44b7b246087a.png)

However, when i'm dragging the cable by mouse in simulator.  The fixed end was away from linked box. It seems the link was broken.
![image](https://user-images.githubusercontent.com/19282086/164195437-0b8045ae-a9db-4d6b-9f32-ebba91885f46.png)

I wonder that is there any method to fixed two body togother to avoid pull away during manipulation?

**Comment by erwincoumans** [comment]
The mouse picking forces are very large, causing the constraint to be violated. You can make the rope root body fixed?
Other options are decreasing the time step, increasing the number of solver iterations, or decreasing the mouse picking strength. See the [PyBullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3).

You can also try changing the constraint solver to 'Dantzig LCP' but you may run into limitations, and it is not supported.
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/switchConstraintSolver.py
