### ISSUE TITLE
pybullet can not show all objects.

### ISSUE THREAD

**Issue by JiayunjieJYJ** [bulletphysics/bullet3#4260]
Either DebugVisualizer or getCameraImage, some objects don't show when I import multiple URDFs.

**Comment by JiayunjieJYJ** [comment]
![image](https://user-images.githubusercontent.com/44229958/168413453-a080bc09-1e7c-43a3-baad-fe9deb8a55c3.png)
For example, each robot is located under each green line, but only a few of them can be shown, anyone know the reason?

**Comment by JiayunjieJYJ** [comment]
I have tried using different computers, including laptop with CPU or a PC with GPU, but when I import multiple URDFs, only top 8 or 8  of them can be shown, the left is just ignored.

**Comment by erwincoumans** [comment]
The number of triangles is likely too high, please simplify the visual (and possibly collision) meshes.
