### ISSUE TITLE
Using pybullet inside casadi for dynamics computation

### ISSUE THREAD

**Issue by prakrutk** [bulletphysics/bullet3#4287]
I am trying to use pybullet inside casadi for computing the next states but it gives a segmentation fault as I try to pass optimization variable (force value and the coordinates where force is to be applied) inside pybullet.applyExternalForce. 

I am not sure but I guess it is because casadi uses a symbolic framework and I cannot pass symbols in a pybullet function. If any one has a clearer idea on why this is happening and is there any way to get this working please do let me know.

Thanks.

**Comment by YechenZhou** [comment]
Have you solved this problem yet? I have the same problem as you. @prakrutk

**Comment by prakrutk** [comment]
I guess it is mostly due to the symbolic framework while pybullet does not take in symbolic variables in the function. I did not find any solution I used another physics engine in place of this to make it work.

**Comment by jcarpent** [comment]
Depending on your applications, you may use Pinocchio for that (https://github.com/stack-of-tasks/pinocchio/).

**Comment by YechenZhou** [comment]
> I guess it is mostly due to the symbolic framework while pybullet does not take in symbolic variables in the function. I did not find any solution I used another physics engine in place of this to make it work.
Can you tell me what physics engine you used afterwards?

**Comment by prakrutk** [comment]
> > I guess it is mostly due to the symbolic framework while pybullet does not take in symbolic variables in the function. I did not find any solution I used another physics engine in place of this to make it work.
> > Can you tell me what physics engine you used afterwards? @prakrutk

I used Mujoco for my application. But it depends on what you are using it for.

**Comment by YechenZhou** [comment]
> > > I guess it is mostly due to the symbolic framework while pybullet does not take in symbolic variables in the function. I did not find any solution I used another physics engine in place of this to make it work.
> > > Can you tell me what physics engine you used afterwards? @prakrutk
> 
> I used Mujoco for my application. But it depends on what you are using it for.

 Thanks. Can Mujoco work inside casadi? @prakrutk
