### ISSUE TITLE
Zero gravity leads to stuck rendering

### ISSUE THREAD

**Issue by marcj** [bulletphysics/bullet3#4305]
I've checked out https://github.com/bulletphysics/bullet3/commit/a1d96646c8ca28b99b2581dcfc4d74cc3b4de018 and changed only in `examples/CommonInterfaces/CommonCallbacks.h` the gravity to 0 (or very low 0.1) `m_dynamicsWorld->setGravity(btVector3(0, 0, 0))` and started the example `AppBasicExampleGui`. When it starts up and I create force on some cubes with my mouse it starts moving but then suddenly stops. Please see the attached screen record:

https://user-images.githubusercontent.com/450980/178845347-169d4a76-1959-4c4e-a369-43a77f2973a9.mov

**Comment by erwincoumans** [comment]
It could be object deactivation (sleeping), can you press 'd' key and see if that helps?
