### ISSUE TITLE
PyBullet Quickstart Guide Inconsistent regarding orientation transformation order

### ISSUE THREAD

**Issue by bandjhughes** [bulletphysics/bullet3#4407]
The "Transforms: Position and Orientation" section states in part "... The orientation (or rotation) of objects can be expressed using quaternions [x,y,z,w], euler angles **[yaw, pitch, roll]** or 3x3 matrices...."  Note the euler angle order of **[yaw, pitch, roll]**.

However, in the "getQuaternionFromEuler and getEulerFromQuaternion" section the table documentation state "The X,Y,Z Euler angles are in radians, accumulating 3 rotations expressing the roll around the X, pitch around Y and yaw around the Z axis."  So that would be [roll, pitch, yaw].

Also, in the "getEulerFromQuaternion" section, the documentation states in part "...The rotation order is first roll around X, then pitch around Y and finally yaw around Z, as in the ROS URDF rpy convention."

**Comment by erwincoumans** [comment]
It is roll, pitch, yaw indeed, changed the doc. Thanks!
