### ISSUE TITLE
vectormath not part of Bullet 2.83.5

### ISSUE THREAD

**Issue by makklaski** [bulletphysics/bullet3#441]
I'm surprised that it was removed in 2.83. I think that Bullet version 3 is a better candidate for this kind of change.
So I assume that this is the official place to get it:
https://github.com/erwincoumans/sce_vectormath

**Comment by erwincoumans** [comment]
Yes, that URL is the best place to get vectormath. Vectormath was dropped because it was only used in BulletMultiThreaded, which was dropped.
