### ISSUE TITLE
btMultiBody depends on bullet3 in debug version

### ISSUE THREAD

**Issue by AndresTraks** [bulletphysics/bullet3#442]
The debug version of bullet 2.x causes a linker error unless bullet3 is also linked in. Unlike in release versions, the "if (0)" clause isn't optimized out at https://github.com/bulletphysics/bullet3/blob/8e163c984ddd0227ae8d901ea3a1a2b99ed1b2fc/src/BulletDynamics/Featherstone/btMultiBody.cpp#L850 and so b3Printf is still required.

You could use "#if 0" and "#endif" to comment out the b3Printf statement if that's the intention.

**Comment by erwincoumans** [comment]
Yes, that is a bug and I'll fix it right away. Thanks for reporting!

**Comment by AndresTraks** [comment]
It works now, thanks!
