### ISSUE TITLE
Question about createMultiBody

### ISSUE THREAD

**Issue by yangliuxin-nn** [bulletphysics/bullet3#4427]
Hello,

I want to make the items created by createMultiBody() do not bounce nor collide with other items. Could you please help me with this problem?

Many thanks for your time and help!

Best wishes,
Liuxin

**Comment by erwincoumans** [comment]
You could try to assign collision filter, see setCollisionFilterGroupMask https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#
or ask ChatGPT:

![Screenshot from 2023-04-25 17-56-16](https://user-images.githubusercontent.com/725468/234438996-541493f1-c4cb-4a67-904a-af8a123afc5c.png)
