### ISSUE TITLE
Does bullet support cloth simulation?

### ISSUE THREAD

**Issue by dandingol03** [bulletphysics/bullet3#4442]
Hi, i was trying to make human body try on clothes in my rendering engine recently., and i found `bullet` this wonderful physical engine. Is bullet suitable for cloth simulation?

**Comment by danielpmorton** [comment]
You should check out https://github.com/contactrika/dedo

**Comment by BluePrintRandom** [comment]
check the upbge fork of blender - they have 'soft body physics' you can pin to objects using 'rigid body joints'
