### ISSUE TITLE
Returns of p.getContactPoints()

### ISSUE THREAD

**Issue by onurbagoren** [bulletphysics/bullet3#4446]
Hello,

I am unsure as to what the returns from the function call `p.getContactPoints()` is, and unfortunately cannot find any documentation online for this. Is there any help that I could get with this?

Thanks!

**Comment by manas96** [comment]
It's documented [here ](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.cb0co8y2vuvc) in the quickstart guide.
