### ISSUE TITLE
Fix the Bullet Raycast sample.

### ISSUE THREAD

**Issue by benelot** [bulletphysics/bullet3#450]
The first hit example is missing a

`m_dynamicsWorld->rayTest(from,to,closestResults);`

so instead of

			btVector3 from(-30,1.2,0);
			btVector3 to(30,1.2,0);
			m_dynamicsWorld->getDebugDrawer()->drawLine(from,to,btVector4(0,0,1,1));

			btCollisionWorld::ClosestRayResultCallback	closestResults(from,to);
			closestResults.m_flags |= btTriangleRaycastCallback::kF_FilterBackfaces;
			
			if (closestResults.hasHit())
			{
				
				btVector3 p = from.lerp(to,closestResults.m_closestHitFraction);
				m_dynamicsWorld->getDebugDrawer()->drawSphere(p,0.1,blue);
				m_dynamicsWorld->getDebugDrawer()->drawLine(p,p+closestResults.m_hitNormalWorld,blue);

			}

it should be

			btVector3 from(-30,1.2,0);
			btVector3 to(30,1.2,0);
			m_dynamicsWorld->getDebugDrawer()->drawLine(from,to,btVector4(0,0,1,1));

			btCollisionWorld::ClosestRayResultCallback	closestResults(from,to);
			closestResults.m_flags |= btTriangleRaycastCallback::kF_FilterBackfaces;
			
			m_dynamicsWorld->rayTest(from,to,closestResults);

			if (closestResults.hasHit())
			{
				
				btVector3 p = from.lerp(to,closestResults.m_closestHitFraction);
				m_dynamicsWorld->getDebugDrawer()->drawSphere(p,0.1,blue);
				m_dynamicsWorld->getDebugDrawer()->drawLine(p,p+closestResults.m_hitNormalWorld,blue);

			}

**Comment by benelot** [comment]
Ok I saw that it was an issue with an old revision I had, it seems to be there already.

**Comment by benelot** [comment]
It is missing here:
https://github.com/bulletphysics/bullet3/blob/master/examples/Raycast/RaytestDemo.cpp

**Comment by erwincoumans** [comment]
thanks for the feedback, we'll fix it

**Comment by benelot** [comment]
I made you a pullrequest:
https://github.com/bulletphysics/bullet3/pull/464
