### ISSUE TITLE
How to implement sensors？

### ISSUE THREAD

**Issue by PinkFatMan** [bulletphysics/bullet3#4501]
I want to implement a mechanism, which is a sensor or trigger. How do I need to set the collider properties to implement it?

**Comment by erwincoumans** [comment]
Using PyBullet you can query any contact points (and filter them for particular objects/sensors) and check the forces (impulses) and penetration and contact locations. See getContactPoints in https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3
