### ISSUE TITLE
Implement btMultiBodyJointMotor and btMultiBodyJointLimitConstraint for Spherical Joint

### ISSUE THREAD

**Issue by benelot** [bulletphysics/bullet3#463]
I think it would also be reasonable to update the btMultiBodyJointMotor and the btMultiBodyJointLimitConstraint for both the Spherical joint already added to the btMultiBody. The Spherical joint is neither limitable nor movable via a motor. From what I see in the code, the Spherical joint is not considered in any of them.

**Comment by erwincoumans** [comment]
Closing out-of-date issues. btMultiBodyJointMotor  is implemented for spherical joints. limit not yet.
