### ISSUE TITLE
Feature Request: ways to customize raytests

### ISSUE THREAD

**Issue by kijoshua** [bulletphysics/bullet3#48]
I've been able to successfully implement my own collision algorithm for a dynamic shape, via processCollision.  But now I'm really struggling with support for raycasts, because there appears to be no similar system to customize.  Ultimately, I'd love to just have a processRaycast method that I could customize, since the structure I'm wrapping already has implementations I could use.  Rather than making a new RaycastAlgorithm system though, I'd imagine a new shape type.  I wouldn't request that such a thing be added to the core shape interface, but perhaps a new shape type interface to join the current 3 main branches (compound, convex, concave).  Just something simple that defers to a virtual method for most every interaction with default implementations just hooking back into the same old Bullet system?

**Comment by erwincoumans** [comment]
There hasn't been activity for too long on this issue, let's close it. If it is urgent and someone wants to work on this, please open a new issue with a pull request.
