### ISSUE TITLE
Raycast against arbitrary bodies?

### ISSUE THREAD

**Issue by f0rsen** [bulletphysics/bullet3#487]
How would I raycast against bodies that aren't simulated and that doesn't push other objects?

For example: a networked game where the enemies are handled by interpolation instead of by bullet.

**Comment by erwincoumans** [comment]
This is not a place for discussion and questions, please use the forums at http://bulletphysics.org

In a nutshell, a raycast is just a collision query, and it should work fine. A raycast or collision query has no impact on simulation.

**Comment by f0rsen** [comment]
Sorry, I was too set up in the GitHub mindset. Thank you for your answer.
