### ISSUE TITLE
Dynamic allocation of structs generates alignment warnings

### ISSUE THREAD

**Issue by simo-11** [bulletphysics/bullet3#537]
I allocate btJointFeedback structures from heap as number of joints can change and warnings like below are generated.

1>..\..\examples\CharpyDemo\CharpyDemo.cpp(1250): warning C4316: 'btJointFeedback' : object allocated on the heap may not be aligned 16

adding BT_DECLARE_ALIGNED_ALLOCATOR();
adds aligned new and delete operations and makes warnings and possible issues to vanish.

Would it be possible and reasonable to add them to all struct definitions?

ATTRIBUTE_ALIGNED16(struct)	btJointFeedback
{
	BT_DECLARE_ALIGNED_ALLOCATOR();
	btVector3	m_appliedForceBodyA;
	btVector3	m_appliedTorqueBodyA;
	btVector3	m_appliedForceBodyB;
	btVector3	m_appliedTorqueBodyB;
};

**Comment by erwincoumans** [comment]
Yes, done here: https://github.com/bulletphysics/bullet3/pull/538
If there are other struct definitions with the same issue, please report them in a separate issue.
Thanks for the report!
