### ISSUE TITLE
Inverse dynamics not working with a floating base

### ISSUE THREAD

**Issue by DivideByZero2** [bulletphysics/bullet3#541]
Created using btMultiBodyTreeCreator. Fixed base works correctly

**Comment by erwincoumans** [comment]
The first inverse dynamics example code didn't support floating base.
I modified the example to support floating base, by adding 6 dummy values that represent the floating base. See https://github.com/bulletphysics/bullet3/pull/542

**Comment by DivideByZero2** [comment]
Thanks for the example. It looks like I just had a bug in my code (forgot the extra 6 dummy values). I think there might be a small typo in the example. 

qdot6[6+i] = qdot6[i];
q6[6+i] = q6[i];
joint_force6[6+i] = joint_force6[i];
=>
qdot6[6 + i] = qdot[i];
q6[6 + i] = q[i];
joint_force6[6 + i] = joint_force[i];
