### ISSUE TITLE
Make use of SYCL instead of openCL ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [bulletphysics/bullet3#555]
Hello sorry if I say something of stupid but there is this New khronos specification : SYCL and it aims to be the same things than opencl but using c++, this api is highter level and more easy. 

See: https://www.khronos.org/registry/sycl/specs/sycl-1.2.pdf
And : https://github.com/amd/triSYCL

**Comment by erwincoumans** [comment]
closing out-of-date issues, OpenCL is not supported.

**Comment by LifeIsStrange** [comment]
Sorry but what happened to the openCL bullet 3.X port?

**Comment by erwincoumans** [comment]
Nothing. My focus is on PyBullet and reinforcement learning for robotics nowadays. Noone works on OpenCL.

**Comment by LifeIsStrange** [comment]
OK !
But I believe that openCL is a way to get more performance, as such it could be useful for reinforcement learning too. 

But yes nobody is working on it for now.
