### ISSUE TITLE
CCD collision problem (was googlecode Issue 792)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#58]
copied from https://code.google.com/p/bullet/issues/detail?id=792&colspec=Modified%20ID%20Type%20Stars%20Status%20Owner%20Summary

CCD collision detection seem to ignore that collision between constraint linked rigid bodies might be disabled.

Reproduction: use the attached patch (CCD_collision_problem_demo.patch ) for GenericJointDemo to get a set up with 2 capsules: one static (the upper) and the other attached to it (below) such way that it can only move along the Y axis. Moving the nonstatic rigid body with a relatively high speed into the static one using the mouse results in the two capsules getting stuck together because of the collision. The expected behavior is that the nonstatic capsule should fly over the static capsule.

What version of the product are you using? On what operating system?
Rev. 2719 32 bit on a Win7 64 bit.

Suggested fix attached in a separate patch (CCD_collision_problem_fix.patch)

**Comment by sponji** [comment]
Just noticed this issue and seems like my fix in https://github.com/bulletphysics/bullet3/pull/1662 was exactly the same as the patch behind the google code link. I think you can close this issue too.

**Comment by erwincoumans** [comment]
Thanks for the report, closing it!
