### ISSUE TITLE
btQuaternion - Slerp sometimes return error values (was googlecode Issue 786)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#64]
https://code.google.com/p/bullet/issues/detail?id=786&colspec=Modified%20ID%20Type%20Stars%20Status%20Owner%20Summary

Reported by creagamestudio, Jan 11, 2014
What steps will reproduce the problem?
Answer:
at btQuaternion.h (line 508): const btScalar d = btScalar(1.0) / btSin(theta);
"btSin(theta)" sometimes may be equal 0...

My fix is:
const btScalar sin_theta = btSin(theta);
if (sin_theta == 0)
  return q;
const btScalar d = btScalar(1.0) / sin_theta;

**Comment by T4Larson** [comment]
See #446 : Mathematically, theta and d should be larger than _epsilon for 1.0-SIMD_EPSILON (also increased precision for results near 0.0), so if the dotproduct is below the presicion threshold, theta and d would be >0, so no extra check is probably needed after that point.
