### ISSUE TITLE
Velocity/Velosity spelling inconsistency

### ISSUE THREAD

**Issue by vallentin** [bulletphysics/bullet3#686]
Both  `btHingeConstraint` and `btHinge2Constraint` has a "velocity" vs "velosity" spelling inconsistency.

Both classes has the `setMotorTargetVelocity` mutator, but the accessor is then named `getMotorTargetVelosity`.

**Comment by matpalm** [comment]
pull requests most welcome !

**Comment by vallentin** [comment]
Closing as this was fixed in 4a1c682.
