### ISSUE TITLE
setIgnoreCollisionCheck and CCD

### ISSUE THREAD

**Issue by sponji** [bulletphysics/bullet3#691]
Seems like setIgnoreCollisionCheck doesn't work with CCD. The rigid bodies move through each other when they go slower, but when there's enough motion they collide. Is this a bug or am I just doing something silly?

**Comment by benelot** [comment]
I am not sure if I am correct, but I remember having read that CCD only triggers with at a higher velocity than a certain threshold. Therefore, slowly moving objects are not handled with CDD. That is all I know, maybe it helps you already.

**Comment by sponji** [comment]
Yeah, that's what I meant with "enough motion", going over the threshold so it actually starts using CCD.

**Comment by erwincoumans** [comment]
It is probably a bug,  ccd collisions need to be filterered the same as discrete collisions. A patch is welcome, otherwise I look at it once I find some time.
