### ISSUE TITLE
Dynamica Plugin for Maya 2016 - Windows

### ISSUE THREAD

**Issue by AIExperiment** [bulletphysics/bullet3#695]
Hi,

Apologies in advance, but I have a bit of a noob question here...

I'm not entirely sure how to build the Maya 2016 dynamica plugin using the source code available. 

Can someone either point me in the direction of a tutorial to do so, or provide me with a link to the Maya 2016 Dynamica Plugin mll

Ultimately, if I knew how to build the plugin myself, I wouldn't need to pester anyone in the future. As the proverb goes.

"Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime!"

Cheers

Mike

**Comment by benelot** [comment]
Wrong place go ask, ask again on the bullet physics forum. Cheers.

**Comment by erwincoumans** [comment]
closing out-of-date issues
