### ISSUE TITLE
Parse joint dynamics in SDF

### ISSUE THREAD

**Issue by YunfeiBai** [bulletphysics/bullet3#710]
On [line 963](https://github.com/bulletphysics/bullet3/blob/260e5d2b3d2a7c715019e206e98b7c19a12815d2/examples/Importers/ImportURDFDemo/UrdfParser.cpp#L963), should use
axis_xml->FirstChildElement("dynamics");
instead of
config->FirstChildElement("dynamics");

Because dynamics is a child of axis.

**Comment by erwincoumans** [comment]
Thanks for the report, fixed here:
https://github.com/bulletphysics/bullet3/commit/e88de13cc669b77acbe12c3efe303c1c37a60dbb
