### ISSUE TITLE
Need Bulletphysics Engine in TypeScript?

### ISSUE THREAD

**Issue by lvignals** [bulletphysics/bullet3#711]
Hello, I need the Bulletphysics engine as a TypeScript library.
Is anyone aware of a project or initiative that is currently porting the Bulletphysics engine to Type Script?
Thank you.

**Comment by thegame771** [comment]
You can check ammo.js: https://github.com/kripken/ammo.js/ and/or cannon.js: http://www.cannonjs.org/

**Comment by erwincoumans** [comment]
Let's close this issue, this is mainly for the C++ Bullet Physics Engine, not for ports to other languages.
