### ISSUE TITLE
How to do distance computations between two convex hulls in the opencl mode? Is GJK_EPA deprecated?

### ISSUE THREAD

**Issue by shomedas** [bulletphysics/bullet3#729]
How to do distance computations between two convex hulls(intersecting or non intersecting) in the opencl mode? Is GJK, EPA deprecated? I am looking for some application like the one in Demos/CollisionDemo OR in Demos/ConvexHullDistance

**Comment by benelot** [comment]
Give this question an shot at bulletphysics.org forum, you receive answers
more quickly.

**Comment by erwincoumans** [comment]
The OpenCL is experimental, ignore it. Just use the Bullet 2.x API. I'll port the CollisionDemo/ConvexHullDistance to the Bullet Example Browser.
