### ISSUE TITLE
compute distance between convex hulls in GPU using opencl

### ISSUE THREAD

**Issue by shomedas** [bulletphysics/bullet3#730]
How to do distance computations between two convex hulls in the gpu? Is there a GJK_EPA for the gpu using opencl? I need to do  do the computations realtime(60fps). I have used the GJK-EPA in 2.8.3 version, but i guess it happens on the cpu

**Comment by erwincoumans** [comment]
The GPU/OpenCL version hasn't been developed for a while, and it lacks GJK-EPA. The Bullet 2.x GJK-EPA should be able to operate in real-time for many scenarios.
Also: This is not a discussion forum, please visit http://bulletphysics.org or stackoverflow etc.
