### ISSUE TITLE
Contact constraint force mixing.

### ISSUE THREAD

**Issue by kermado** [bulletphysics/bullet3#740]
I see that `btManifoldPoint::m_contactCFM1` and `btManifoldPoint::m_contactCFM1` are used for the friction constraints. However, the CFM for penetrating contact constraints is set to zero in `btSequentialImpulseConstraintSolver::setupContactConstraint()`. Is there a reason for this?

ODE allows setting the CFM for penetrating contact constraints in order to crudely simulate soft bodies.

**Comment by erwincoumans** [comment]
We also allow for 'soft' rigid body contacts, see the Example Browser. The contact stiffness and contact damping is now converted in cfm/erp.
