### ISSUE TITLE
OpenCL status

### ISSUE THREAD

**Issue by alabd14313** [bulletphysics/bullet3#785]
Hello friends!
I have a question. What is the status of openCL implementation?
and I have some happy news:

1.   OpenCL 2.2 brings the most developer-requested feature into core – the OpenCL C++ kernel language.

2.   SYCL 2.2 which leverages OpenCL 2.2 to provide the power of single source C++ programming.

3.   SPIR-V 1.1 now supports all the kernel language features of OpenCL C++ in OpenCL 2.2, including initializer and finalizer function execution modes to support constructors and destructors.

4.   POCL: Portable Computing Language (pocl) aims to become a MIT-licensed open source implementation of the OpenCL standard which can be easily adapted for new targets and devices, both for homogeneous CPU and heterogeneous GPUs/accelerators. (http://portablecl.org/)

**Comment by erwincoumans** [comment]
this is not a discussion forum, go to http://bulletphysics.org for chit-chat.
