### ISSUE TITLE
Blender 2.8 project - UPBGE team to adapt new render to BGE from 2.8 project

### ISSUE THREAD

**Issue by BluePrintRandom** [bulletphysics/bullet3#824]
The UPBGE team is already modernizing the BGE physics, rendering, control input etc, and has been doing a really nice job.

Is there anything that you think should be included in blender game bullet that is missing @erwincoumans ?

Is there a path to getting bt multibody etc into the bge?

Is your new IK solver faster than blenders? 

do you skin armatures?  

Thanks.
Jacob Merrill

**Comment by erwincoumans** [comment]
This is not a discussion forum for such topics.

**Comment by BluePrintRandom** [comment]
where is?
