### ISSUE TITLE
Bullet 2.84 pre-release doesn't match code version of 2.85

### ISSUE THREAD

**Issue by scpeters** [bulletphysics/bullet3#829]
The [software version is listed as 2.85](https://github.com/bulletphysics/bullet3/blob/2.84/CMakeLists.txt#L8) in the [2.84 pre-release](https://github.com/bulletphysics/bullet3/releases/tag/2.84). Shouldn't those match?

**Comment by erwincoumans** [comment]
Thanks for bringing up the inconsistency, somehow the 2.84 release never got tagged/released after the VERSION was bumbed up from 2.83 to 2.84 last year. This release should be tagged 2.85 indeed. I'll look into it.

**Comment by erwincoumans** [comment]
Due to serialization update, the release has to be named 2.85 indeed, so we skip 2.84.
See https://github.com/bulletphysics/bullet3/releases/tag/2.85
