### ISSUE TITLE
Version check with BT_BULLET_VERSION

### ISSUE THREAD

**Issue by JayFoxRox** [bulletphysics/bullet3#854]
Okay, so 2.84 introduced API breaking changes with https://github.com/bulletphysics/bullet3/commit/626a913866158e5956cfa2ae7f5f6350e99d783e

However, `BT_BULLET_VERSION` was already bumped up to 284 at [2.83.6](https://github.com/bulletphysics/bullet3/blob/2.83.6/src/LinearMath/btScalar.h) (see [2.83.5](https://github.com/bulletphysics/bullet3/blob/2.83.5/src/LinearMath/btScalar.h) where it still was 283)
To my surprise this meant [2.84](https://github.com/bulletphysics/bullet3/blob/2.84/src/LinearMath/btScalar.h) is actually.. *drumroll* 285

- Is that intended? (It broke our codebase because we added checks for 284 because we wanted to catch ... bullet 2.84)
- How to best check for API feature level?
- How to check for a printable version number?
- Will this go back to normal?

**Comment by erwincoumans** [comment]
The current version if Bullet 2.85, the previous one is 2.83. Ignore 2.84, that was a mistake. Next one will be Bullet 2.86.
For Bullet 2.x, you can check API version as in Bullet/src/btScalar.h:

#define BT_BULLET_VERSION 285

inline int	btGetVersion()
{
	return BT_BULLET_VERSION;
}

If there is any issue, please create new one.
