### ISSUE TITLE
Fix memory leaks in ExampleBrowser, pybullet and SharedMemoryAPI + add unit test

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#869]
There are some memory leaks in the example code (Example Browser, pybullet, Shared Memory API). This needs to be fixed, and Continuous Integration tests for memory leaks added to Travis / AppVeyor.

**Comment by DavidDeAngelo** [comment]
I noticed the GUIHelperInterface has a couple methods that create objects, but it lacks a corresponding remove function, for example createPhysicsDebugDrawer. If you create multiple CommonExampleInterfaces and delete them, you'll have some left over objects. While its doubt its likely that someone would do that, I can't think of any good reason to have create functions without remove functions.

**Comment by erwincoumans** [comment]
The one who allocates stuff is responsible to delete it properly, so creating multiple copies etc. is considered a user error.

**Comment by erwincoumans** [comment]
The leaks in Example browser etc should be fixed, reopen new issue if there are new leaks found.

**Comment by erwincoumans** [comment]
The leaks should be fixed a while ago, closing.
