### ISSUE TITLE
bug in btMultiBody::clearVelocities()

### ISSUE THREAD

**Issue by 12michi34** [bulletphysics/bullet3#878]
btMultiBody::clearVelocities() does currently 

void btMultiBody::clearVelocities()
{
	for (int i = 0; i < 6 + getNumLinks(); ++i) 
	{
		m_realBuf[i] = 0.f;
	}
}
index goes from 0 to 6 + getNumLinks().
But m_realBuf gets allocated as 
m_realBuf.resize(6 + m_dofCount + m_dofCount*m_dofCount + 6 + m_dofCount);	

No consider a situation where getNumLinks()> m_dofCount ... Then memory gets trampled.

Simple repro is a btMultiBody with only fixed constrtaints (=m_dofCount =0, and getNumLinks() > 0).

Cheers,

Michi

**Comment by erwincoumans** [comment]
thanks for the report, that looks like a bug indeed, will look into fixing it asap.

**Comment by erwincoumans** [comment]
Fixed in https://github.com/bulletphysics/bullet3/pull/886/commits/710ac09b565b7c5759c09456b3861b42ed833e24
