### ISSUE TITLE
Enable broadphase to return pairs with distance < threshold (was googlecode Issue 715)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#90]
See https://code.google.com/p/bullet/issues/detail?id=715&colspec=Modified%20ID%20Type%20Stars%20Status%20Owner%20Summary

**Comment by Levi-Armstrong** [comment]
Hello, I currently need this type of functionality. Does anyone know if is currently capable or is it still missing?

**Comment by Levi-Armstrong** [comment]
I do have availability to add this if it is not already added. It looks like from what I can tell is it is not. It seems to make it functional you would need to change for all of the shapes getABB shown below. Would this change be acceptable or is there a better solution?

`localHalfExtents += btVector3(getMargin(),getMargin(),getMargin());`

to

`localHalfExtents += btVector3(getMargin()+getContactBreakingThreshold(),getMargin()+getContactBreakingThreshold(),getMargin()+getContactBreakingThreshold());`

**Comment by Levi-Armstrong** [comment]
@erwincoumans Any thoughts on if this would be an acceptable change?

**Comment by benelot** [comment]
I think since you already have an idea and know how to implement it, just
do it in your own fork and pull-request it. Then you can use it already and
Erwin can give you advice on how to make it better or if it is suitable for
merging.

**Comment by erwincoumans** [comment]
This functionality was added a while ago, let's close it now.
