### ISSUE TITLE
possible collision response bug with internal edges and spheres (was googlecode Issue 706)

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#92]
See https://code.google.com/p/bullet/issues/detail?id=706&colspec=Modified%20ID%20Type%20Stars%20Status%20Owner%20Summary

**Comment by jazztickets** [comment]
Can you look at this issue or give some guidance on workarounds, Erwin?

**Comment by erwincoumans** [comment]
closing out-of-date issues

**Comment by jazztickets** [comment]
I mean, the issue still happens in the latest version...

**Comment by erwincoumans** [comment]
No clear reproduction case. What does this test do exactly?
https://github.com/jazztickets/btest/blob/master/src/main.cpp
Obviously the internal edge utility changes the contact normal.

**Comment by jazztickets** [comment]
It's all explained in the original bug report:
https://code.google.com/archive/p/bullet/issues/706

The btest project reproduces the environment setup in the video: https://www.youtube.com/watch?v=71jd0g6PsdE

There's a blender file attached there too. More users have had issues in the referenced issue (https://github.com/libgdx/libgdx/issues/2534#issuecomment-62255817)
