### ISSUE TITLE
Expose programmatic created collision shapes, rigid bodies to pybullet

### ISSUE THREAD

**Issue by erwincoumans** [bulletphysics/bullet3#936]
in addition to existing loadURDF/SDF/MJCF/Bullet file format. Possibly make it easy to convert shape data when running pybullet within Blender.

**Comment by BluePrintRandom** [comment]
<3 <3 <3

**Comment by erwincoumans** [comment]
We can now programmatically create both collision and visual shapes.
A few examples:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/createObstacleCourse.py#L31
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/createTexturedMeshVisualShape.py
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/createVisualShape.py#L40
