### ISSUE TITLE
Update topic on IRC @ Freenode or give OP status to somebody else

### ISSUE THREAD

**Issue by xissburg** [bulletphysics/bullet3#939]
Sorry for posting this here but I think it's the quickest way to reach @erwincoumans 

The #bulletphysics channel on Freenode needs to have the topic updated and someone who can manage it. I know @erwincoumans has OP status in this channel (since the topic was last updated by erwin_bullet on October 14, 2012 at 12:16:02 PM EST,  "Topic is Bullet Physics 2.81 is released, see http://bulletphysics.org"). We'd like to ask @erwincoumans to either update it or preferably give OP status to someone who's active in the channel.

Thanks

**Comment by erwincoumans** [comment]
Are people still using freenode? I doubt I can find a password and client to use it. Let's close this issue.
