### ISSUE TITLE
Cannot create spherical joint from URDF

### ISSUE THREAD

**Issue by benelot** [bulletphysics/bullet3#946]
I see that urdf only knows floating to create a completely free 6 dof joint. But I could find from the urdf loader source if there is nothing mapped from urdf to the multibody spherical joint. 

https://github.com/bulletphysics/bullet3/blob/b9b958ec9c4d943c56adcb497771b70c4c6e8a5e/examples/Importers/ImportURDFDemo/URDF2Bullet.cpp

Will there be in the future?

**Comment by erwincoumans** [comment]
There is a spherical joint used in pybullet_envs.deep_mimic
