### ISSUE TITLE
CMakeLists.txt still has SET(BULLET_VERSION 2.85)

### ISSUE THREAD

**Issue by starthal** [bulletphysics/bullet3#953]
Is this intentional? My installed libraries (via Homebrew) have `2.85` in their names but the package version is 2.86.

**Comment by erwincoumans** [comment]
Aaargh, missed that one: there are a few too many version tags in the code.

Hopefully this does the trick next time: FILE (STRINGS "VERSION" BULLET_VERSION)

See https://github.com/bulletphysics/bullet3/pull/954

Thanks for the report!
