### ISSUE TITLE
Lost implementation "int btCollisionWorldImporter::getNumConstraints() const"

### ISSUE THREAD

**Issue by nicolaichuk** [bulletphysics/bullet3#997]
Function [int btCollisionWorldImporter::getNumConstraints() const](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/CollisionDispatch/btCollisionWorldImporter.h#L127)
do not have implementation in [cpp-file](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/CollisionDispatch/btCollisionWorldImporter.cpp).

**Comment by nicolaichuk** [comment]
I think it is copy-past from https://github.com/bulletphysics/bullet3/blob/master/Extras/Serialize/BulletWorldImporter/btWorldImporter.h#L139

and this function may remove because collision word do not have constraints.

**Comment by erwincoumans** [comment]
Yes, we can remove the method from the header file. Thanks for the report!

**Comment by erwincoumans** [comment]
Fixed here:https://github.com/bulletphysics/bullet3/commit/644e510c83f9108f79d9ae98411e0a0f97be208b

**Comment by nicolaichuk** [comment]
@erwincoumans, thanks.
